### ISSUE TITLE
Crash on "Bomber John" when trying to iron curtain minelayer. (current release)

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#10005]
```
Red Alert Mod at Version release-20150919
on map 8bc40b22e045f5561208cdb65cd182dc607efdc6 (Bomber John by Holloweye).
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.InvalidOperationException`: Actor does not have trait of type `OpenRA.Mods.Common.Traits.RenderBuilding`
   at OpenRA.TraitDictionary.TraitContainer`1.Get(UInt32 actor)
   at OpenRA.TraitDictionary.Get[T](Actor actor)
   at OpenRA.Actor.Trait[T]()
   at OpenRA.Mods.Common.Traits.GrantUpgradePower.Activate(Actor self, Order order, SupportPowerManager manager)
   at OpenRA.Mods.Common.Traits.SupportPowerInstance.Activate(Order order)
   at OpenRA.Mods.Common.Traits.SupportPowerManager.ResolveOrder(Actor self, Order order)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by penev92** [comment]
Can you give us a replay?

**Comment by pchote** [comment]
This is pretty clear cut, so we don't need a replay.  This map gives a tree actor the Iron Curtain power.  Trees don't use `RenderBuilding`, but `GrantUpgradePower` has a hardcoded `Trait<RenderBuilding>()` without a corresponding `Requires<RenderBuildingInfo>`.

**Comment by pchote** [comment]
On bleed/prep the hardcoded `RenderBuilding` is changed to a hardcoded `WithSpriteBody`, so this will no longer crash.  That doesn't mean this bug is invalid, though: this trait shouldn't hardcode that lookup or at the very least it should declare the correct `Requires<>`.

**Comment by pchote** [comment]
This is a simple fix for something that map/modders have already hit.  I think this qualifies it for a next release fixup.

**Comment by epicelite** [comment]
It attempts to iron curtain a tree and that equals a crash? Would this work on any map?

**Comment by pchote** [comment]
Other way around. The *tree* can iron curtain other things.

**Comment by epicelite** [comment]
u w0t m8?
You know what, I'll just leave this to you. I don't need to know.

**Comment by obrakmann** [comment]
That's funny. I don't get the exception mentioned above but this instead:
```
Exception of type `System.InvalidOperationException`: Unit `t17` does not have a sequence named `active`
```

Ultimate cause will probably be the same, though.

**Comment by abcdefg30** [comment]
For me it's the same as for @obrakmann.
I only get his crash when using the chronosphere power, but the iron curtain power is fine.

**Comment by penev92** [comment]
The Iron Curtain is fine on bleed. It crashes on the old release.
