### ISSUE TITLE
Custom Map crash after about 6 seconds.

### ISSUE THREAD

**Issue by oppdelta** [OpenRA/OpenRA#10088]
Red Alert Mod at Version release-20150919
on map 8d80c75134ed716442a3981934d30876646faf25 (Opperation Turtle V0.3 by OPPDelta).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IndexOutOfRangeException`: Index was outside the bounds of the array.
   at OpenRA.CellLayer`1.get_Item(CPos cell)
   at OpenRA.Mods.Common.Traits.ResourceLayer.GetResource(CPos cell)
   at OpenRA.Mods.Common.Traits.SeedsResource.<Seed>m__0(CPos p)
   at System.Linq.Enumerable.<SkipWhileIterator>d__1`1.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__1`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at OpenRA.Mods.Common.Traits.SeedsResource.Seed(Actor self)
   at OpenRA.Mods.Common.Traits.SeedsResource.Tick(Actor self)
   at OpenRA.World.<Tick>m__3(TraitPair`1 x)
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by abcdefg30** [comment]
This should be fixed in the next version (see #10062, #10039, #9528).
Thanks for the report, though!

**Comment by oppdelta** [comment]
Oh wow. After hours of searching, still couldn't find this on here. Good job on the fix and nippy response. Thank you. Sorry for duplicate issue.

**Comment by abcdefg30** [comment]
No problem, you are welcome. :)
