### ISSUE TITLE
Invalid Operation Exception

### ISSUE THREAD

**Issue by dmmory** [OpenRA/OpenRA#10146]
I was playing a skirmish in the Tiberian Dawn mod, and it exited with a Fatal Error dialog box.

When I looked at the exception log, I saw this:

Tiberian Dawn Mod at Version release-20150919
on map 23f00dd4242754487f7f67d9198549c6a204a5ed (Rogue States by Psydev).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (mtnk 372 (not in world))
   at OpenRA.TraitDictionary.CheckDestroyed(Actor actor)
   at OpenRA.TraitDictionary.Get[T](Actor actor)
   at OpenRA.Actor.Trait[T]()
   at OpenRA.Widgets.WorldInteractionControllerWidget.<HandleKeyPress>m__1(Actor a)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at OpenRA.Widgets.WorldInteractionControllerWidget.HandleKeyPress(KeyInput e)
   at OpenRA.Widgets.Widget.HandleKeyPressOuter(KeyInput e)
   at OpenRA.Widgets.Widget.HandleKeyPressOuter(KeyInput e)
   at OpenRA.Widgets.Widget.HandleKeyPressOuter(KeyInput e)
   at OpenRA.Widgets.Widget.HandleKeyPressOuter(KeyInput e)
   at OpenRA.Widgets.Ui.HandleKeyPress(KeyInput e)
   at OpenRA.DefaultInputHandler.<OnKeyInput>c__AnonStorey0.<>m__0()
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   at OpenRA.DefaultInputHandler.OnKeyInput(KeyInput input)
   at OpenRA.Renderer.Sdl2.Sdl2Input.PumpInput(IInputHandler inputHandler)
   at OpenRA.Renderer.Sdl2.Sdl2GraphicsDevice.PumpInput(IInputHandler inputHandler)
   at OpenRA.Graphics.Renderer.EndFrame(IInputHandler inputHandler)
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

If any other information is required, please let me know.

**Comment by penev92** [comment]
Thanks for the report. This has been fixed in the new playtests.
