### ISSUE TITLE
Problem when i open OpenRA

### ISSUE THREAD

**Issue by DarkCatSpyChrono123** [OpenRA/OpenRA#10140]
Please help!
Here are the files of the crash:
Exception file
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: No suitable renderers were found. Check graphics.log for details.
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
Debug File
None
Geoip file
None
Graphics file
OpenGL Information:
Vendor: Microsoft Corporation
Note:  The default driver provided by Microsoft does not include full OpenGL support.
Please install the latest drivers from your graphics card manufacturer's website.

Renderer: GDI Generic
GL Version: 1.1.0
Shader Version: 
Available extensions:
GL_WIN_swap_hint GL_EXT_bgra GL_EXT_paletted_texture
System.InvalidProgramException: OpenGL Version Error: See graphics.log for details.
   at OpenRA.Renderer.Sdl2.ErrorHandler.CheckGlVersion()
   at OpenRA.Renderer.Sdl2.Sdl2GraphicsDevice..ctor(Size windowSize, WindowMode windowMode)
   at OpenRA.Renderer.Sdl2.DeviceFactory.Create(Size size, WindowMode windowMode)
   at OpenRA.Graphics.Renderer.CreateDevice(Assembly rendererDll, Int32 width, Int32 height, WindowMode window)
   at OpenRA.Graphics.Renderer..ctor(GraphicSettings graphicSettings, ServerSettings serverSettings)
   at OpenRA.Game.Initialize(Arguments args)
OpenRA requires OpenGL version 2.0 or greater and detected 1.1

OpenGL Information:
Vendor: Microsoft Corporation
Note:  The default driver provided by Microsoft does not include full OpenGL support.
Please install the latest drivers from your graphics card manufacturer's website.

Renderer: GDI Generic
GL Version: 1.1.0
Shader Version: 
Available extensions:
GL_WIN_swap_hint GL_EXT_bgra GL_EXT_paletted_texture
System.InvalidProgramException: OpenGL Version Error: See graphics.log for details.
   at OpenRA.Renderer.Sdl2.ErrorHandler.CheckGlVersion()
   at OpenRA.Renderer.Sdl2.Sdl2GraphicsDevice..ctor(Size windowSize, WindowMode windowMode)
   at OpenRA.Renderer.Sdl2.DeviceFactory.Create(Size size, WindowMode windowMode)
   at OpenRA.Graphics.Renderer.CreateDevice(Assembly rendererDll, Int32 width, Int32 height, WindowMode window)
   at OpenRA.Graphics.Renderer..ctor(GraphicSettings graphicSettings, ServerSettings serverSettings)
   at OpenRA.Game.Initialize(Arguments args)
Perf File
None

Server file
None

Sound file
None

Sync report file
None

Please help bye :)

**Comment by pchote** [comment]
Quote from the error log:

>Note: The default driver provided by Microsoft does not include full OpenGL support.
Please install the latest drivers from your graphics card manufacturer's website.
