### ISSUE TITLE
Another bleed sound crash (IMA ADPCM)

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#10284]
caused by #10069 probably.

```
Attacque Superior Mod at Version {DEV_VERSION}
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.InvalidDataException`: assphinx.wav is not a valid sound file!
   at OpenRA.Sound.LoadSound(String filename) in d:\OpenRA-dev\OpenRA.Game\Sound\Sound.cs:line 72
   at OpenRA.Exts.GetOrAdd[K,V](Dictionary`2 d, K k, Func`2 createFn) in d:\OpenRA-dev\OpenRA.Game\Exts.cs:line 130
   at OpenRA.Primitives.Cache`2.get_Item(T key) in d:\OpenRA-dev\OpenRA.Game\Primitives\Cache.cs:line 35
   at OpenRA.Sound.PlayMusicThen(MusicInfo m, Action then) in d:\OpenRA-dev\OpenRA.Game\Sound\Sound.cs:line 185
   at OpenRA.Mods.Common.Traits.MusicPlaylist.Play()
   at OpenRA.Mods.Common.Traits.MusicPlaylist..ctor(World world, MusicPlaylistInfo info)
   at OpenRA.Mods.Common.Traits.MusicPlaylistInfo.Create(ActorInitializer init)
   at OpenRA.Actor..ctor(World world, String name, TypeDictionary initDict) in d:\OpenRA-dev\OpenRA.Game\Actor.cs:line 92
   at OpenRA.World.CreateActor(Boolean addToWorld, String name, TypeDictionary initDict) in d:\OpenRA-dev\OpenRA.Game\World.cs:line 226
   at OpenRA.World.CreateActor(String name, TypeDictionary initDict) in d:\OpenRA-dev\OpenRA.Game\World.cs:line 221
   at OpenRA.World..ctor(Map map, OrderManager orderManager, WorldType type) in d:\OpenRA-dev\OpenRA.Game\World.cs:line 164
   at OpenRA.Game.StartGame(String mapUID, WorldType type) in d:\OpenRA-dev\OpenRA.Game\Game.cs:line 153
   at OpenRA.Game.LoadShellMap() in d:\OpenRA-dev\OpenRA.Game\Game.cs:line 398
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   at OpenRA.Game.InitializeMod(String mod, Arguments args) in d:\OpenRA-dev\OpenRA.Game\Game.cs:line 354
   at OpenRA.Game.Initialize(Arguments args) in d:\OpenRA-dev\OpenRA.Game\Game.cs:line 248
   at OpenRA.Program.Run(String[] args) in d:\OpenRA-dev\OpenRA.Game\Support\Program.cs:line 115
   at OpenRA.Program.Main(String[] args) in d:\OpenRA-dev\OpenRA.Game\Support\Program.cs:line 39
```

File is available at https://copy.com/U7Y8FzAbMxt7tQJC

This worked fine for half a year now - since I started modding OpenRA tbh - so yeah.

**Comment by GraionDilach** [comment]
PEBKAC on my end. I overlooked the additional `SoundFormats: Aud, Wav` line from `mod.yaml` - adding it fixed this one. The error message threw me a bit off though.
