### ISSUE TITLE
Crash during single player skirmish match (ArgumentOutOfRangeException)

### ISSUE THREAD

**Issue by mmmh81** [OpenRA/OpenRA#10315]
Hi,
OpenRA just crashed during a single player match with 3 AI players. The error occurred shortly after - but not at the same time - the first AI was defeated. Exception.log is attached.

Thanks for the great re-implementation!

[exception.zip](https://github.com/OpenRA/OpenRA/files/73486/exception.zip)
##

**Comment by abcdefg30** [comment]
Just posting the crash here for easier access:
```
Red Alert Mod at Version release-20151224
on map d9803d8fa385f0a6363d2ba9289ac157ea113b94 (Bad Neighbors by Nuke'm Bro.).
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.ArgumentOutOfRangeException`: Index out of bounds. It must be non-negative and less than the listing. (Der Index lag außerhalb des Bereichs. Er muss nicht negativ und kleiner als die Auflistung sein.)
Parametername: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at OpenRA.ListExts.BinarySearchMany(List`1 list, UInt32 searchFor)
   at OpenRA.TraitDictionary.TraitContainer`1.Add(Actor actor, Object trait)
   at OpenRA.TraitDictionary.AddTrait(Actor actor, Object val)
   at OpenRA.Actor..ctor(World world, String name, TypeDictionary initDict)
   at OpenRA.World.CreateActor(Boolean addToWorld, String name, TypeDictionary initDict)
   at OpenRA.Mods.RA.Traits.ParatroopersPower.SendParatroopers(Actor self, WPos target, Boolean randomize, Int32 dropFacing)
   at OpenRA.Mods.RA.Traits.ParatroopersPower.Activate(Actor self, Order order, SupportPowerManager manager)
   at OpenRA.Mods.Common.Traits.SupportPowerInstance.Activate(Order order)
   at OpenRA.Mods.Common.Traits.SupportPowerManager.ResolveOrder(Actor self, Order order)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by RoosterDragon** [comment]
@mmmh81: Do you have the replay for this match?

**Comment by mmmh81** [comment]
This should be the replay:
[OpenRA-2015-12-28T191510Z.zip](https://github.com/OpenRA/OpenRA/files/74155/OpenRA-2015-12-28T191510Z.zip)

**Comment by RoosterDragon** [comment]
This exception fails to replicate if you just run the replay (even if you force it past the disconnection, the paradrop succeeds).

I'm not sure what that implies. The error log is pretty odd. This will probably require some more thinking.

**Comment by pchote** [comment]
We haven't received any more reports of this, so closing as un unreproducable one-off.
