### ISSUE TITLE
Rare Crash when entering Lobby

### ISSUE THREAD

**Issue by Templarfreak** [OpenRA/OpenRA#10450]
This crash can only happen if you click Skirmish button fast enough. I wish I could say more, but that's how I get this crash. You can reliably recreate this if you can click on the Skirmish button fast enough. (I'd say about 4 or 5 times a second)

Here is a paste of the crash log: http://pastebin.com/6tAKpdaK

Safe to say that someone with patience will never encounter this issue, but if you're like me and like to spam the mouse button it'll happen from time to time.

**Comment by obrakmann** [comment]
```
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.18408
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Mods.Common.Widgets.Logic.LobbyLogic.UpdatePlayerList()
   at System.Action.Invoke()
   at OpenRA.Game.SyncLobbyInfo() in c:\OpenRA Testing\Bleed 20160105\OpenRA-bleed\OpenRA.Game\Game.cs:line 138
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order) in c:\OpenRA Testing\Bleed 20160105\OpenRA-bleed\OpenRA.Game\Network\UnitOrders.cs:line 199
   at OpenRA.Network.OrderManager.TickImmediate() in c:\OpenRA Testing\Bleed 20160105\OpenRA-bleed\OpenRA.Game\Network\OrderManager.cs:line 124
   at OpenRA.Sync.<>c__DisplayClass5.<CheckSyncUnchanged>b__4() in c:\OpenRA Testing\Bleed 20160105\OpenRA-bleed\OpenRA.Game\Sync.cs:line 170
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn) in c:\OpenRA Testing\Bleed 20160105\OpenRA-bleed\OpenRA.Game\Sync.cs:line 178
   at OpenRA.Sync.CheckSyncUnchanged(World world, Action fn) in c:\OpenRA Testing\Bleed 20160105\OpenRA-bleed\OpenRA.Game\Sync.cs:line 170
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in c:\OpenRA Testing\Bleed 20160105\OpenRA-bleed\OpenRA.Game\Game.cs:line 492
   at OpenRA.Game.LogicTick() in c:\OpenRA Testing\Bleed 20160105\OpenRA-bleed\OpenRA.Game\Game.cs:line 545
   at OpenRA.Game.Loop() in c:\OpenRA Testing\Bleed 20160105\OpenRA-bleed\OpenRA.Game\Game.cs:line 672
   at OpenRA.Game.Run() in c:\OpenRA Testing\Bleed 20160105\OpenRA-bleed\OpenRA.Game\Game.cs:line 712
   at OpenRA.Program.Run(String[] args) in c:\OpenRA Testing\Bleed 20160105\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 117
   at OpenRA.Program.Main(String[] args) in c:\OpenRA Testing\Bleed 20160105\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 39
```

**Comment by r34ch** [comment]
I had a similar (if not the same) issue #10338
