### ISSUE TITLE
IndexOutOfRangeException in FootprintBounds

### ISSUE THREAD

**Issue by steadyfield** [OpenRA/OpenRA#10460]
```
Tiberian Sun Mod at Version {DEV_VERSION}
on map f302316e85c754d108fc1c3d79993e90a0faf4e1 (Tiberium Garden Redux by Westwood Studios).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.IndexOutOfRangeException`:
   at OpenRA.Traits.FrozenActorLayer.FootprintBounds(FrozenActor fa) in d:\git\OpenRA-bleed-1-9\OpenRA.Game\Traits\Player\FrozenActorLayer.cs:Line 194
   at OpenRA.Traits.FrozenActorLayer.Add(FrozenActor fa) in d:\git\OpenRA-bleed-1-9\OpenRA.Game\Traits\Player\FrozenActorLayer.cs:Line 189
   at OpenRA.Mods.Common.Traits.FrozenUnderFog.<>c__DisplayClass5.<Created>b__4(Player player, Int32 playerIndex)
   at OpenRA.Primitives.PlayerDictionary`1..ctor(World world, Func`3 valueFactory) in d:\git\OpenRA-bleed-1-9\OpenRA.Game\Primitives\PlayerDictionary.cs:Line 27
   at OpenRA.Mods.Common.Traits.FrozenUnderFog.Created(Actor self)
   at OpenRA.World.CreateActor(Boolean addToWorld, String name, TypeDictionary initDict) in d:\git\OpenRA-bleed-1-9\OpenRA.Game\World.cs:Line 232
   at OpenRA.World.CreateActor(String name, TypeDictionary initDict) in d:\git\OpenRA-bleed-1-9\OpenRA.Game\World.cs:Line 225
   at OpenRA.Mods.Common.Traits.PlaceBuilding.<>c__DisplayClass6.<ResolveOrder>b__2(World w)
   at OpenRA.World.Tick() in d:\git\OpenRA-bleed-1-9\OpenRA.Game\World.cs:Line 309
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in d:\git\OpenRA-bleed-1-9\OpenRA.Game\Game.cs:Line 520
   at OpenRA.Game.LogicTick() in d:\git\OpenRA-bleed-1-9\OpenRA.Game\Game.cs:Line 545
   at OpenRA.Game.Loop() in d:\git\OpenRA-bleed-1-9\OpenRA.Game\Game.cs:Line 672
   at OpenRA.Game.Run() in d:\git\OpenRA-bleed-1-9\OpenRA.Game\Game.cs:Line 712
   at OpenRA.Program.Run(String[] args) in d:\git\OpenRA-bleed-1-9\OpenRA.Game\Support\Program.cs:Line 117
   at OpenRA.Program.Main(String[] args) in d:\git\OpenRA-bleed-1-9\OpenRA.Game\Support\Program.cs:Line 39
```

**Comment by RoosterDragon** [comment]
Do you remember what you were building and where you were trying to place it?

**Comment by steadyfield** [comment]
RoosterDragon,
I was trying to build the GDI component tower and trying to place it near the edge of cliff.

But when I restarted the game and build the tower again, it didn't crash.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/ra2/issues/85 looks like the same problem, but it gives more context.

**Comment by RoosterDragon** [comment]
This will happen if the frozen actor has no footprint - which means the new spatial partitioning causes a crash.

However - lacking a footprint in itself is indicative of a deeper problem. There may be something wrong with the isometric perspective and the shroud projection, or maybe some weird edge case with cliffs and/or the map boundary that isn't handled quite right. I've filed #10592 in hopes of rooting up a bit more info next time this happens.

**Comment by Unit158** [comment]
http://pastebin.com/T7YL8ZZF This happened again with @ABrandau when he was in a fight with the AI.

**Comment by pchote** [comment]
If people are playing TS (or other heightmap-enabled mods) on maps imported with bogus cordons then it will be possible to place structures at the very north of the map that go outside the bounds of the shroud array, triggering this.

**Comment by RoosterDragon** [comment]
I tried placing a bunch of single-cell buildings at the extreme edges on a variety of cliff heights on Tiberium Garden Redux but I didn't have any luck triggering an error.

**Comment by Mailaender** [comment]
It could also be an AI related bug. I noticed that blocked harvesters will get ordered to 0,0 to search for new resources. Something similar could happen if the AI can't place buildings anywhere. Just a guess as the AI is often a special case when giving and validating orders and it seems to crash in `PlaceBuilding`.
