### ISSUE TITLE
Opening replay from folder with a space crashes client.

### ISSUE THREAD

**Issue by Remyoman** [OpenRA/OpenRA#10572]
Opening a replay from a folder with a space in the path crashes the client.
My Downloads folder is location in a folder with a space (D:\Remy Baratte\Downloads).

```
Red Alert Mod at Version release-20151224
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.FileNotFoundException`: Could not find file 'D:\Remy'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at OpenRA.FileFormats.ReplayMetadata.Read(String path)
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by obrakmann** [comment]
Seems to work fine on Linux. Windows-only problem?

**Comment by obrakmann** [comment]
I guess [this](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.GameMonitor/GameMonitor.cs#L33) is the problem. `ProcessStartInfo` just passes all arguments as a single string so tokenizing it later is next to impossible.

**Comment by pchote** [comment]
I would hope that windows will accept arguments wrapped in quotes, so something like `string.Join(" ", args.Select(a => "\"" + a + "\""))` should fix it.
