### ISSUE TITLE
TD - GDI - Mission 3 crashes to desktop

### ISSUE THREAD

**Issue by s7jones** [OpenRA/OpenRA#10593]
**What you were doing when something broke?**
Loading Mission 3 of GDI on the Tiberium Dawn mod.

**What you expected to happen?**
The mission to load.

**What actually happened?**
Crash to desktop.

**If it's a crash, the contents of exception.log.**
```
Tiberian Dawn Mod at Version {DEV_VERSION}
on map c8adcbebb529bfbadfc2e96a634c532b9d1f9117 (Destroy The SAM Sites by Westwood Studios).
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenRA.ReadOnlyDictionary`2.get_Item(TKey key) in C:\cygwin64\home\Sam\OpenRA\OpenRA.Game\Primitives\ReadOnlyDictionary.cs:line 77
   at OpenRA.Graphics.TerrainRenderer.UpdateCell(CPos cell) in C:\cygwin64\home\Sam\OpenRA\OpenRA.Game\Graphics\TerrainRenderer.cs:line 49
   at OpenRA.Graphics.TerrainRenderer..ctor(World world, WorldRenderer wr) in C:\cygwin64\home\Sam\OpenRA\OpenRA.Game\Graphics\TerrainRenderer.cs:line 40
   at OpenRA.Graphics.WorldRenderer..ctor(World world) in C:\cygwin64\home\Sam\OpenRA\OpenRA.Game\Graphics\WorldRenderer.cs:line 54
   at OpenRA.Game.StartGame(String mapUID, WorldType type) in C:\cygwin64\home\Sam\OpenRA\OpenRA.Game\Game.cs:line 158
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order) in C:\cygwin64\home\Sam\OpenRA\OpenRA.Game\Network\UnitOrders.cs:line 109
   at OpenRA.Network.OrderManager.TickImmediate() in C:\cygwin64\home\Sam\OpenRA\OpenRA.Game\Network\OrderManager.cs:line 124
   at OpenRA.Sync.<>c__DisplayClass13_0.<CheckSyncUnchanged>b__0() in C:\cygwin64\home\Sam\OpenRA\OpenRA.Game\Sync.cs:line 170
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn) in C:\cygwin64\home\Sam\OpenRA\OpenRA.Game\Sync.cs:line 178
   at OpenRA.Sync.CheckSyncUnchanged(World world, Action fn) in C:\cygwin64\home\Sam\OpenRA\OpenRA.Game\Sync.cs:line 170
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in C:\cygwin64\home\Sam\OpenRA\OpenRA.Game\Game.cs:line 529
   at OpenRA.Game.LogicTick() in C:\cygwin64\home\Sam\OpenRA\OpenRA.Game\Game.cs:line 582
   at OpenRA.Game.Loop() in C:\cygwin64\home\Sam\OpenRA\OpenRA.Game\Game.cs:line 709
   at OpenRA.Game.Run() in C:\cygwin64\home\Sam\OpenRA\OpenRA.Game\Game.cs:line 749
   at OpenRA.Program.Run(String[] args) in C:\cygwin64\home\Sam\OpenRA\OpenRA.Game\Support\Program.cs:line 117
   at OpenRA.Program.Main(String[] args) in C:\cygwin64\home\Sam\OpenRA\OpenRA.Game\Support\Program.cs:line 39
```

**Comment by abcdefg30** [comment]
Looks like there is an invalid template on this map?
Putting
```
if (!world.TileSet.Templates.ContainsKey(tile.Type))
	return;
```
before [this line in TerrainRenderer.cs](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Graphics/TerrainRenderer.cs#L49) fixed the crash.
