### ISSUE TITLE
Can not create OpenGL context. (Error: Invalid window)

### ISSUE THREAD

**Issue by NovusMessari** [OpenRA/OpenRA#10597]
On starting up OpenRA release-20151224., I get a crash message. I've looked at the exception log and it seems to be a problem with graphical errors.

Exception Log:
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: No suitable renderers were found. Check graphics.log for details.
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

Graphical Log:
System.InvalidOperationException: Can not create OpenGL context. (Error: Invalid window)
   at OpenRA.Platforms.Default.Sdl2GraphicsDevice..ctor(Size windowSize, WindowMode windowMode)
   at OpenRA.Platforms.Default.DeviceFactory.CreateGraphics(Size size, WindowMode windowMode)
   at OpenRA.Renderer.CreateDevice(Assembly platformDll, Int32 width, Int32 height, WindowMode window)
   at OpenRA.Renderer..ctor(GraphicSettings graphicSettings, ServerSettings serverSettings)
   at OpenRA.Game.Initialize(Arguments args)
System.InvalidOperationException: Can not create OpenGL context. (Error: Invalid window)
   at OpenRA.Platforms.Default.Sdl2GraphicsDevice..ctor(Size windowSize, WindowMode windowMode)
   at OpenRA.Platforms.Default.DeviceFactory.CreateGraphics(Size size, WindowMode windowMode)
   at OpenRA.Renderer.CreateDevice(Assembly platformDll, Int32 width, Int32 height, WindowMode window)
   at OpenRA.Renderer..ctor(GraphicSettings graphicSettings, ServerSettings serverSettings)
   at OpenRA.Game.Initialize(Arguments args)
##

**Comment by pchote** [comment]
Is this still a problem with the latest playtest?

**Comment by Mailaender** [comment]
Please reopen once you have tested the latest release and it still persists.

**Comment by caaygun** [comment]
I had the same issue, setting desktop resolution to 32-bit color depth resolved it.

**Comment by abcdefg30** [comment]
No activity since a while. I don't think there is much to do here without further leads (at least we know that 32-bit color depth might resolve this issue).

**Comment by phpbg** [comment]
Duplicate of #16327

**Comment by rkj** [comment]
I run into the similar issue on Windows 10, pretty vanilla with nvidia GTX 2080. 

This is the exception from graphics.log:

```
System.InvalidOperationException: Can not create OpenGL context. (Error: Invalid window)
   at OpenRA.Platforms.Default.Sdl2GraphicsContext.InitializeOpenGL()
   at OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor(Size requestEffectiveWindowSize, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile requestProfile)
   at OpenRA.Platforms.Default.DefaultPlatform.CreateWindow(Size size, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile profile)
   at OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings)
   at OpenRA.Game.Initialize(Arguments args)
System.InvalidOperationException: No supported OpenGL profiles were found.
   at OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor(Size requestEffectiveWindowSize, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile requestProfile)
   at OpenRA.Platforms.Default.DefaultPlatform.CreateWindow(Size size, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile profile)
   at OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings)
   at OpenRA.Game.Initialize(Arguments args)
```

**Comment by Mailaender** [comment]
Do you have an internal graphics card? Does it have vendor drivers?

**Comment by rkj** [comment]
I am not sure. I managed to 'fix' this. I have display scaling turned on to 125%. After I moved back to 100% it worked fine.
