### ISSUE TITLE
[TS] `System.ArgumentException`: This frozen actor has no footprint! Please report a bug!

### ISSUE THREAD

**Issue by steadyfield** [OpenRA/OpenRA#10698]
Tiberian Sun Mod at Version {DEV_VERSION}
on map f302316e85c754d108fc1c3d79993e90a0faf4e1 (Tiberium Garden Redux by Westwood Studios).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.ArgumentException`: This frozen actor has no footprint! Please report a bug!
Actor Name: natech
Actor Location: 39,-35
Input footprint: []
Input footprint (shroud.Contains): []
Input footprint (map.Contains): []
   at OpenRA.Traits.FrozenActor..ctor(Actor self, PPos[] footprint, Shroud shroud, Boolean startsRevealed) in d:\git\OpenRA-bleed-2-6\OpenRA.Game\Traits\Player\FrozenActorLayer.cs:Line 68
   at OpenRA.Mods.Common.Traits.FrozenUnderFog.<>c__DisplayClass5.<Created>b__4(Player player, Int32 playerIndex)
   at OpenRA.Primitives.PlayerDictionary`1..ctor(World world, Func`3 valueFactory) in d:\git\OpenRA-bleed-2-6\OpenRA.Game\Primitives\PlayerDictionary.cs:Line 27
   at OpenRA.Mods.Common.Traits.FrozenUnderFog.Created(Actor self)
   at OpenRA.World.CreateActor(Boolean addToWorld, String name, TypeDictionary initDict) in d:\git\OpenRA-bleed-2-6\OpenRA.Game\World.cs:Line 232
   at OpenRA.World.CreateActor(String name, TypeDictionary initDict) in d:\git\OpenRA-bleed-2-6\OpenRA.Game\World.cs:Line 225
   at OpenRA.Mods.Common.Traits.PlaceBuilding.<>c__DisplayClass6.<ResolveOrder>b__2(World w)
   at OpenRA.World.Tick() in d:\git\OpenRA-bleed-2-6\OpenRA.Game\World.cs:Line 309
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in d:\git\OpenRA-bleed-2-6\OpenRA.Game\Game.cs:Line 557
   at OpenRA.Game.LogicTick() in d:\git\OpenRA-bleed-2-6\OpenRA.Game\Game.cs:Line 582
   at OpenRA.Game.Loop() in d:\git\OpenRA-bleed-2-6\OpenRA.Game\Game.cs:Line 709
   at OpenRA.Game.Run() in d:\git\OpenRA-bleed-2-6\OpenRA.Game\Game.cs:Line 749
   at OpenRA.Program.Run(String[] args) in d:\git\OpenRA-bleed-2-6\OpenRA.Game\Support\Program.cs:Line 117
   at OpenRA.Program.Main(String[] args) in d:\git\OpenRA-bleed-2-6\OpenRA.Game\Support\Program.cs:Line 39

**Comment by obrakmann** [comment]
@RoosterDragon: your mouse trap caught something.

**Comment by pchote** [comment]
Just like I thought, the AI is trying (and almost succeeding!) to place an actor above the north cordon of the map, where the cell projection has no valid solution.

![screen shot 2016-02-06 at 17 02 02](https://cloud.githubusercontent.com/assets/167819/12867975/940217fa-ccf3-11e5-841f-236da866e83b.png)
