### ISSUE TITLE
Player color remap crash

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#10776]
I'm getting

```
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type 'System.ArgumentException': The value -1697 is invalid for red. red must be >= 0 and <= 255.
   at System.Drawing.Color.CheckByte(Int32 value, String name)
   at System.Drawing.Color.FromArgb(Int32 alpha, Int32 red, Int32 green, Int32 blue)
   at OpenRA.Exts.ColorLerp(Single t, Color c1, Color c2) in e:\OpenRA_work2\OpenRA.Game\Exts.cs:line 411.
   at OpenRA.Graphics.PlayerColorRemap.<>c__DisplayClassb.<.ctor>b__2(Int32 x, Int32 i) in e:\OpenRA_work2\OpenRA.Game\Graphics\PlayerColorRemap.cs:line 46.
   at System.Linq.Enumerable.<SelectIterator>d__7'2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable'1 source, Func'2 keySelector, Func'2 elementSelector, IEqualityComparer'1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable'1 source, Func'2 keySelector, Func'2 elementSelector)
   at OpenRA.Graphics.PlayerColorRemap..ctor(Int32[] ramp, HSLColor c, Single rampFraction) in e:\OpenRA_work2\OpenRA.Game\Graphics\PlayerColorRemap.cs:line 46.
   at OpenRA.Traits.PlayerColorPalette.LoadPlayerPalettes(WorldRenderer wr, String playerName, HSLColor color, Boolean replaceExisting) in e:\OpenRA_work2\OpenRA.Game\Traits\Player
\PlayerColorPalette.cs:line 47.
   at OpenRA.Graphics.WorldRenderer.UpdatePalettesForPlayer(String internalName, HSLColor color, Boolean replaceExisting) in e:\OpenRA_work2\OpenRA.Game\Graphics\WorldRenderer.cs:line 62.
   at OpenRA.Graphics.WorldRenderer..ctor(World world) in e:\OpenRA_work2\OpenRA.Game\Graphics\WorldRenderer.cs:line 49.
   at OpenRA.Game.StartGame(String mapUID, WorldType type) in e:\OpenRA_work2\OpenRA.Game\Game.cs:line 158.
   at OpenRA.Game.LoadShellMap() in e:\OpenRA_work2\OpenRA.Game\Game.cs:line 443.
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   at OpenRA.Game.InitializeMod(String mod, Arguments args) in e:\OpenRA_work2\OpenRA.Game\Game.cs:line 399.
   at OpenRA.Game.Initialize(Arguments args) in e:\OpenRA_work2\OpenRA.Game\Game.cs:line 288.
   at OpenRA.Program.Run(String[] args) in e:\OpenRA_work2\OpenRA.Game\Support\Program.cs:line 115.
   at OpenRA.Program.Main(String[] args) in e:\OpenRA_work2\OpenRA.Game\Support\Program.cs:line 39.
```

from

```
	PlayerColorPalette@BLDGREMAP:
		BasePalette: mc
		BaseName: bldgremap
		RemapIndex: 177, 178, 69, 180, 181, 205, 67, 58, 66, 57, 203, 65, 72, 41, 64, 40
```

And yes, the colors are ordered correctly from brightest to darkest in terms of both total luminosity as well as `red` value.

**Comment by reaperrr** [comment]
According to my own testing, it seems that the lowest and highest palette index listed must not be further apart than the total count of indices listed. In other words, I can reorder indices from 16-31 arbitrarily just fine, but I cannot replace index 30 with 200 or add 200 somewhere to that list. Looks like the code cannot handle 'gaps'.

**Comment by reaperrr** [comment]
Bogus issue, I was just using the wrong palette trait.
