### ISSUE TITLE
RangeMultiplier only affects maximum range.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#10908]
Which can lead to crashes if the `RangeMultiplier`*`Range` value ends up being smaller than `MinRange`. Example case scenario, artillery with a relatively big minimum range under an effect which halves it's range or more.

Example stackdump of such a crash:

```
Attacque Superior Mod at Version {DEV_VERSION}
on map 27a37711fa56b77091e0be5689faaae7455e9973 (DEFCON 6 (2-6) by Westwood Studios).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.ArgumentOutOfRangeException`: Maximum range is less than the minimum range.
Parameter name: maxRange
   at OpenRA.Map.<FindTilesInAnnulus>d__25.MoveNext() in d:\OpenRA-AS-dev\OpenRA.Game\Map\Map.cs:line 1131
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at OpenRA.Mods.Common.Activities.MoveAdjacentTo.CalculatePathToTarget(Actor self)
   at OpenRA.Mods.Common.Activities.MoveAdjacentTo.<>c__DisplayClass2.<Tick>b__0()
   at OpenRA.Mods.Common.Activities.Move.EvalPath()
   at OpenRA.Mods.Common.Activities.Move.Tick(Actor self)
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in d:\OpenRA-AS-dev\OpenRA.Game\Traits\ActivityUtils.cs:line 37
   at OpenRA.Mods.Common.Activities.MoveAdjacentTo.Tick(Actor self)
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in d:\OpenRA-AS-dev\OpenRA.Game\Traits\ActivityUtils.cs:line 37
   at OpenRA.Actor.Tick() in d:\OpenRA-AS-dev\OpenRA.Game\Actor.cs:line 164
   at OpenRA.World.Tick() in d:\OpenRA-AS-dev\OpenRA.Game\World.cs:line 331
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in d:\OpenRA-AS-dev\OpenRA.Game\Game.cs:line 556
   at OpenRA.Game.LogicTick() in d:\OpenRA-AS-dev\OpenRA.Game\Game.cs:line 581
   at OpenRA.Game.Loop() in d:\OpenRA-AS-dev\OpenRA.Game\Game.cs:line 708
   at OpenRA.Game.Run() in d:\OpenRA-AS-dev\OpenRA.Game\Game.cs:line 748
   at OpenRA.Program.Run(String[] args) in d:\OpenRA-AS-dev\OpenRA.Game\Support\Program.cs:line 118
   at OpenRA.Program.Main(String[] args) in d:\OpenRA-AS-dev\OpenRA.Game\Support\Program.cs:line 40
```

**Comment by GraionDilach** [comment]
On a second thought, not affecting minimum range should be preferred probably and in the above case the actor shouldn't try to even fire the weapon at all.
