### ISSUE TITLE
Crash after leaving RA mod paused for an extended time mid skirmish

### ISSUE THREAD

**Issue by Jon310** [OpenRA/OpenRA#11189]
I left the game running overnight so I could finish the skirmish game in the RA mod in the morning. When I turned my monitor back on the game crashed. 
[exception.zip](https://github.com/OpenRA/OpenRA/files/234780/exception.zip)

**Comment by LipkeGu** [comment]
```
Red Alert Mod at Version release-20151224
on map 48e2abda20b2648dbbca733cea960595e192412f (The Bridge by Jon310).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.OutOfMemoryException`: Exception of type 'System.OutOfMemoryException' was thrown.
   at OpenRA.Mods.Common.Traits.WithMuzzleOverlay.Render(Actor self, WorldRenderer wr)
   at OpenRA.Actor.<Renderables>c__Iterator0.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OpenRA.Graphics.WorldRenderer.GenerateRenderables()
   at OpenRA.Graphics.WorldRenderer.Draw()
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

```

**Comment by pchote** [comment]
It looks like we're leaking memory somewhere.  It should be easy for @RoosterDragon or someone else to leave the game paused in their memory profiler for a couple of hours to find the culprit.

**Comment by LipkeGu** [comment]
I had run the Playtest at least for at least 6 hours in pause state but nothing crashed... maybe it is release-specific

**Comment by GraionDilach** [comment]
It also can be hardware specific. In this case I assume I'm more likely to reproduce this compared to most of you with my 2 GB RAM. :P

**Comment by pchote** [comment]
@GraionDilach has a very good point.  How much RAM does your machine have @Jon310?

@LipkeGu the game would not need to be run until it crashes a for memory analyzer to detect a leak, nor would a single stacktrace tell you anything useful for debugging.

**Comment by LipkeGu** [comment]
@pchote yes i tested it on windows 7 Embedded with 32bit at 3,25 GB RAM.

**Comment by Jon310** [comment]
I have 16g RAM. I very much doubt it came anywhere near using it all. I have the play test paused at the moment looking to reproduce it there. The PC was not in standby or hibernation., just monitors off while I slept. When 12 or so hours pass I will post again.

**Comment by LipkeGu** [comment]
@Jon310 and how much vram (Video memory) ?

**Comment by Jon310** [comment]
8gigs

**Comment by Jon310** [comment]
No crash so far. Looking like its not happening on the play test. Leaving it on overnight to be sure.

**Comment by Jon310** [comment]
All night with the playtest and everything is looking good. No crash and no unusual ram usage.

**Comment by StexoO** [comment]
@Jon310 Maybe another application filled your RAM so OpenRA couldn't allocate anything ?

**Comment by obrakmann** [comment]
@Jon310, thanks for investigating. Glad it's not happening on the playtest anymore, so I think we're done here. Feel free to re-open if it happens again.
