### ISSUE TITLE
TD crash: maps which contain farmer's field husks

### ISSUE THREAD

**Issue by psydev** [OpenRA/OpenRA#11247]
When I start a map which contains a destroyed celery field (v17.husk), it throws an exception and crashes.

It doesn't seem that this issue affects any maps which are included with the game, but it does affect a couple maps I've made. (Including Understanding Power and Media Control).

EDIT: Seems to also apply to all the other field husks: v14 -> v18

```
Tiberian Dawn Mod at Version release-20160508
on map 98edd263db7c925ca19465f5c908c3f80711df70 (Understanding Power by Psydev).
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.17929
Exception of type `System.ArgumentException`: This frozen actor has no footprint.
Actor Name: v17.husk
Actor Location: 30,1
Input footprint: []
Input footprint (after shroud.Contains): []
   at OpenRA.Traits.FrozenActor..ctor(Actor self, PPos[] footprint, Shroud shroud, Boolean startsRevealed)
   at OpenRA.Mods.Common.Traits.FrozenUnderFog.<Created>c__AnonStorey1.<>m__0(Player player, Int32 playerIndex)
   at OpenRA.Primitives.PlayerDictionary`1..ctor(World world, Func`3 valueFactory)
   at OpenRA.Mods.Common.Traits.FrozenUnderFog.Created(Actor self)
   at OpenRA.World.CreateActor(Boolean addToWorld, String name, TypeDictionary initDict)
   at OpenRA.Mods.Common.Traits.SpawnMapActors.WorldLoaded(World world, WorldRenderer wr)
   at OpenRA.World.LoadComplete(WorldRenderer wr)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.TickImmediate()
   at OpenRA.Sync.<CheckSyncUnchanged>c__AnonStorey0.<>m__0()
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   at OpenRA.Sync.CheckSyncUnchanged(World world, Action fn)
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by reaperrr** [comment]
Looks like the current `FrozenUnderFog` code can't handle buildings with only `_` in the footprint.
