### ISSUE TITLE
Trying to create a unique version of a unit (Flamethrower):

### ISSUE THREAD

**Issue by sajwang** [OpenRA/OpenRA#11273]
So I am trying to create a flamethrower unit much in the way of the British Spy; I tried to modify its HP first, then lower its cost, etc. I had done this before (I think it was a Spring 2015 release of OpenRA?) without too many problems, but I repeatedly encounter an error (see Exception log): 
I basically copied the British Spy Example to create this unit: 
Original Unit:
E4:
	Inherits: ^Soldier
	Buildable:
		Queue: Infantry
		BuildAtProductionType: Soldier
		BuildPaletteOrder: 70
		Prerequisites: ~!infantry.china, ~barr, ftur, ~techlevel.low
	Valued:
		Cost: 300
	Tooltip:
		Name: Flamethrower
		Description: Advanced anti-structure unit.\n  Strong vs Infantry, Buildings\n  Weak vs Vehicles, Aircraft
	Health:
		HP: 40
	Armament@PRIMARY:
		Weapon: Flamer
		LocalOffset: 427,0,341
		FireDelay: 8
	Armament@GARRISONED:
		Name: garrisoned
		Weapon: Flamer
	AttackFrontal:
	WithInfantryBody:
		AttackSequence: shoot
	ProducibleWithLevel:
		Prerequisites: barracks.upgraded

Country's Unit:
E4.China:
	Inherits: E4
	Buildable:
		Prerequisites: ~infantry.china, ~barr, ftur, ~techlevel.low
	Valued:
		Cost: 300
	ToolTip:
		Name: Chinese Flamethrower
                Description: Stronger than typical flamethrowers. .\n  Strong vs Infantry, Buildings\n  Weak vs Vehicles, Aircraft
        Health:
		HP: 60
	RenderSprites:
		Image: e4

Exception log:
Red Alert- World at War Mod at Version V1
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.AggregateException`: One or more errors occurred.
Inner Exception of type `System.InvalidOperationException`: Cannot locate type: ToolTipInfo
     at OpenRA.ObjectCreator.<MissingTypeAction>m__7(String s)
   at OpenRA.ObjectCreator.CreateObject[T](String className, Dictionary`2 args)
   at OpenRA.ObjectCreator.CreateObject[T](String className)
   at OpenRA.ActorInfo.LoadTraitInfo(ObjectCreator creator, String traitName, MiniYaml my)
   at OpenRA.ActorInfo..ctor(ObjectCreator creator, String name, MiniYaml node)
   at OpenRA.Ruleset.<LoadDefaults>c__AnonStorey0.<>m__1(MiniYamlNode k)
   at OpenRA.Exts.ToDictionaryWithConflictLog[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, String debugName, Func`2 logKey, Func`2 logValue)
   at OpenRA.Ruleset.MergeOrDefault[T](String name, IReadOnlyFileSystem fileSystem, IEnumerable`1 files, MiniYaml additional, IReadOnlyDictionary`2 defaults, Func`2 makeObject)
   at OpenRA.Ruleset.<LoadDefaults>c__AnonStorey0.<>m__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at OpenRA.Ruleset.LoadDefaults(ModData modData)
   at OpenRA.ModData.<ModData>m__2()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at OpenRA.ModData.get_DefaultRules()
   at OpenRA.Ruleset.LoadDefaultsForTileSet(ModData modData, String tileSet)
   at OpenRA.Map.PostInit()
   at OpenRA.Map..ctor(ModData modData, IReadOnlyPackage package)
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Game.LoadShellMap()
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

Any help is appreciated, thanks!

**Comment by ScottNZ** [comment]
You've got a typo. E4 uses `Tooltip`, and you're using `ToolTip`.

**Comment by obrakmann** [comment]
well, ninja'd.

It's `Tooltip:`, not `ToolTip:`. The trait names are case-sensitive.

If you get an error such as this ("Cannot locate type"), it means that either
1. you have a typo somewhere, such as in this case, or
2. You're running a too old (the trait doesn't exist yet) or too new version of the game (the trait has been removed/renamed/replaced).

**Comment by GraionDilach** [comment]
There's a third case: you forgot to include the trait-container dll in your mod.yaml.

**Comment by sajwang** [comment]
Yep, looks like that did the trick. Gotta be more observant next time.

Thanks
