### ISSUE TITLE
Getting constant exception, file not named

### ISSUE THREAD

**Issue by sajwang** [OpenRA/OpenRA#11282]
I started encountering an exception (bad indent). Through some trial and error (making a dummy mod and adding back each yaml file until I encountered the exception again), I think it might be in my structures yaml. (It didn't specify which, see exceptions log below).

However, I tracked to line 1176 and the indentation seems fine to me. Could it be something else?
[structures.txt](https://github.com/OpenRA/OpenRA/files/264824/structures.txt)

Red Alert- World at War Mod at Version V1
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.AggregateException`: One or more errors occurred.
Inner Exception of type `OpenRA.YamlException`: Bad indent in miniyaml at <no filename available>:1176
     at OpenRA.MiniYaml.FromLines(IEnumerable`1 lines, String filename)
   at OpenRA.MiniYaml.FromString(String text, String fileName)
   at OpenRA.MiniYaml.FromStream(Stream s, String fileName)
   at OpenRA.MiniYaml.<Load>c__AnonStorey3.<>m__0(String s)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at OpenRA.MiniYaml.Merge(IEnumerable`1 sources)
   at OpenRA.MiniYaml.Load(IReadOnlyFileSystem fileSystem, IEnumerable`1 files, MiniYaml mapRules)
   at OpenRA.Ruleset.MergeOrDefault[T](String name, IReadOnlyFileSystem fileSystem, IEnumerable`1 files, MiniYaml additional, IReadOnlyDictionary`2 defaults, Func`2 makeObject)
   at OpenRA.Ruleset.<LoadDefaults>c__AnonStorey0.<>m__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at OpenRA.Ruleset.LoadDefaults(ModData modData)
   at OpenRA.ModData.<ModData>m__2()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at OpenRA.ModData.get_DefaultRules()
   at OpenRA.Ruleset.LoadDefaultsForTileSet(ModData modData, String tileSet)
   at OpenRA.Map.PostInit()
   at OpenRA.Map..ctor(ModData modData, IReadOnlyPackage package)
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Game.LoadShellMap()
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by sajwang** [comment]
oops, it looks like some text was cut out: 

"Inner Exception of type `OpenRA.YamlException`: Bad indent in miniyaml at <no filename available>:1176"

**Comment by cjshmyr** [comment]
Looks like line 1176 is indented with spaces instead of tabs, which will result in this error

![image](https://cloud.githubusercontent.com/assets/566742/15271895/8477e4b0-1a1c-11e6-8285-b194b9f445d2.png)

**Comment by sajwang** [comment]
This is going to sound very ignorant, but is there anything i can use to check whether i used spaces or indents?

I'm using wordpad/turbo pad at the moment and to my knowledge I can't track them on either.

**Comment by cjshmyr** [comment]
For sure, give notepad++ a shot, I used it just now to check

**Comment by sajwang** [comment]
looks good so far (still getting errors, but my code is a mess, it seems).

Thanks! I'll open this again if I'm still hitting trouble.

**Comment by sajwang** [comment]
Ok, yep, got rid of the indentation problem. Totally new one arose.

I scanned through to try and kill as many duplicates and correct as many typos as I can find. Still getting the following:
Red Alert- World at War Mod at Version V1
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.AggregateException`: One or more errors occurred.
Inner Exception of type `System.IO.InvalidDataException`: Duplicate key 'RequiresPrerequisites' in :0
  Inner Exception of type `System.ArgumentException`: An item with the same key has already been added.
       at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OpenRA.MiniYaml.ToDictionary[TKey,TElement](Func`2 keySelector, Func`2 elementSelector)
     at OpenRA.MiniYaml.ToDictionary[TKey,TElement](Func`2 keySelector, Func`2 elementSelector)
   at OpenRA.MiniYaml.ToDictionary[TElement](Func`2 elementSelector)
   at OpenRA.MiniYaml.ToDictionary()
   at OpenRA.FieldLoader.Load(Object self, MiniYaml my)
   at OpenRA.ActorInfo.LoadTraitInfo(ObjectCreator creator, String traitName, MiniYaml my)
   at OpenRA.ActorInfo..ctor(ObjectCreator creator, String name, MiniYaml node)
   at OpenRA.Ruleset.<LoadDefaults>c__AnonStorey0.<>m__1(MiniYamlNode k)
   at OpenRA.Exts.ToDictionaryWithConflictLog[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, String debugName, Func`2 logKey, Func`2 logValue)
   at OpenRA.Ruleset.MergeOrDefault[T](String name, IReadOnlyFileSystem fileSystem, IEnumerable`1 files, MiniYaml additional, IReadOnlyDictionary`2 defaults, Func`2 makeObject)
   at OpenRA.Ruleset.<LoadDefaults>c__AnonStorey0.<>m__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at OpenRA.Ruleset.LoadDefaults(ModData modData)
   at OpenRA.ModData.<ModData>m__2()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at OpenRA.ModData.get_DefaultRules()
   at OpenRA.Ruleset.LoadDefaultsForTileSet(ModData modData, String tileSet)
   at OpenRA.Map.PostInit()
   at OpenRA.Map..ctor(ModData modData, IReadOnlyPackage package)
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Game.LoadShellMap()
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)


For the life of me I can't figure out why.

Updated yaml:
[structures.txt](https://github.com/OpenRA/OpenRA/files/264844/structures.txt)

**Comment by cjshmyr** [comment]
Under `HPAD`'s definition, the line `ProvidesPrerequisite@greekstructure:` has an extra indent.

If you are interested how to figure this one out, based on the error message ("duplicate key..."), do a quick find for any `RequiresPrerequisites`. One was indented an once extra, resulting in two `RequiresPrerequisites` living under one node, hence the duplicate error.

You may find our [IRC channel](http://webchat.freenode.net/?channels=openra) helpful for troubleshooting these types of problems too, there might be more eyes to look at it.

**Comment by sajwang** [comment]
There we go; that helped. Managed to get my mod back :)

I'll check out the IRC next time around. Thanks again
