### ISSUE TITLE
Upgrading map yamls with the --upgrade-mod command throws out a lot of stream errors.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#11312]
```
Failed to upgrade map aggressivetendencies.oramap
Error was: System.IO.FileNotFoundException: Could not find file 'D:\OpenRA-AS-dev\mods\cnc\maps\aggressivetendencies.oramap.451.tmp'.
File name: 'D:\OpenRA-AS-dev\mods\cnc\maps\aggressivetendencies.oramap.451.tmp'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at ICSharpCode.SharpZipLib.Zip.DiskArchiveStorage.ConvertTemporaryToFinal()
   at ICSharpCode.SharpZipLib.Zip.ZipFile.RunUpdates()
   at ICSharpCode.SharpZipLib.Zip.ZipFile.CommitUpdate()
   at OpenRA.FileSystem.ZipFile.Update(String filename, Byte[] contents) in d:\OpenRA-AS-dev\OpenRA.Game\FileSystem\ZipFile.cs:line 83
   at OpenRA.Mods.Common.UtilityCommands.UpgradeRules.UpgradeMapFormat(ModData modData, IReadWritePackage package)
   at OpenRA.Mods.Common.UtilityCommands.UpgradeMapCommand.UpgradeMap(ModData modData, IReadWritePackage package, Int32 engineDate)
   at OpenRA.Mods.Common.UtilityCommands.UpgradeModCommand.Run(ModData modData, String[] args)
[...]
Failed to upgrade map gdi01
Error was: System.ArgumentNullException: Value cannot be null.
Parameter name: stream
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream)
   at OpenRA.MiniYaml.FromStream(Stream s, String fileName) in d:\OpenRA-AS-dev\OpenRA.Game\MiniYaml.cs:line 251
   at OpenRA.Mods.Common.UtilityCommands.UpgradeMapCommand.ProcessYaml(Map map, MiniYaml yaml, Int32 engineDate, UpgradeAction processYaml)
   at OpenRA.Mods.Common.UtilityCommands.UpgradeMapCommand.UpgradeMap(ModData modData, IReadWritePackage package, Int32 engineDate)
   at OpenRA.Mods.Common.UtilityCommands.UpgradeModCommand.Run(ModData modData, String[] args)
```

Might be Windows-only. I guess something went wrong with the split-map-rules-into-additional-files PR.

**Comment by GraionDilach** [comment]
Whoops, duplicate of #11203, sorry. >_>
