### ISSUE TITLE
Invalid Data Exception: nuyell5.aud is not a valid sound file

### ISSUE THREAD

**Issue by TiberiumRaider** [OpenRA/OpenRA#11735]
I had a crash when playing a skirmish match on Tiberium Dawn and it crashed. It appears to have been a System.IO.InvalidDataException error. Here is the exception.log : 
```
Tiberian Dawn Mod at Version release-20160508
on map 2ce3883d05981a4ec4b43104ee8218d78c6e4cbc (Sandstorm by pulse).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.InvalidDataException`: nuyell5.aud is not a valid sound file!
   at OpenRA.Sound.LoadSound(ISoundLoader[] loaders, IReadOnlyFileSystem fileSystem, String filename)
   at OpenRA.Sound.<Initialize>c__AnonStorey0.<>m__0(String s)
   at OpenRA.Exts.GetOrAdd[K,V](Dictionary`2 d, K k, Func`2 createFn)
   at OpenRA.Primitives.Cache`2.get_Item(T key)
   at OpenRA.Sound.PlayPredefined(Ruleset ruleset, Player p, Actor voicedActor, String type, String definition, String variant, Boolean relative, WPos pos, Single volumeModifier, Boolean attenuateVolume)
   at OpenRA.Mods.Common.Traits.Voiced.PlayVoiceLocal(Actor self, String phrase, String variant, Single volume)
   at OpenRA.VoiceExts.PlayVoiceLocal(Actor self, String phrase, Single volume)
   at OpenRA.Mods.Common.Traits.DeathSounds.Killed(Actor self, AttackInfo e)
   at OpenRA.Mods.Common.Traits.Health.InflictDamage(Actor self, Actor attacker, Int32 damage, IWarhead warhead, Boolean ignoreModifiers)
   at OpenRA.Actor.InflictDamage(Actor attacker, Int32 damage, IWarhead warhead)
   at OpenRA.Mods.Common.Warheads.DamageWarhead.DoImpact(Actor victim, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.Mods.Common.Warheads.DamageWarhead.DoImpact(Target target, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.GameRules.WeaponInfo.<Impact>c__AnonStorey1.<>m__0()
   at OpenRA.GameRules.WeaponInfo.Impact(Target target, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.Mods.Common.Effects.Bullet.Explode(World world)
   at OpenRA.Mods.Common.Effects.Bullet.Tick(World world)
   at OpenRA.World.<Tick>m__4(IEffect e)
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by obrakmann** [comment]
`nuyell5.aud` is one of the four infantry death sounds, so you can imagine it's played pretty often and we would have already heard if it was broken. My best guess therefore is that your game assets got corrupted somehow. Please try deleting the `%USERPROFILE%\My Documents\OpenRA\Content\cnc` directory and re-installing the assets.

**Comment by TiberiumRaider** [comment]
When i try to reinstall from my TFD disk, the exception.log says: 

> Mod Chooser Mod at Version release-20160508
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.FileNotFoundException`: File not found: E:\data1.hdr
   at OpenRA.FileSystem.FileSystem.Open(String filename)
   at OpenRA.FileSystem.InstallShieldCABExtractor..ctor(FileSystem context, String hdrFilename)
   at OpenRA.Mods.Common.Widgets.Logic.InstallFromCDLogic.<InstallTFD>c__AnonStorey1.<>m__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by obrakmann** [comment]
Please use the download option then for the time being. The asset installer has been completely rewritten for the next release, you might have better luck with that once we release it.

**Comment by TiberiumRaider** [comment]
Thanks for the help. It has been fixed

**Comment by sambonz** [comment]
For anyone who comes here looking for the fix, here it is:
[https://gist.github.com/abcdefg30/a4fe1110c2727c3960e340ae2ce45bc0?permalink_comment_id=3541919#gistcomment-3541919](https://gist.github.com/abcdefg30/a4fe1110c2727c3960e340ae2ce45bc0?permalink_comment_id=3541919#gistcomment-3541919)
