### ISSUE TITLE
TD and RA install error when trying to extract from the First Decade disk

### ISSUE THREAD

**Issue by TiberiumRaider** [OpenRA/OpenRA#11751]
I was trying to install Tiberian Dawn and Red Alert form my CD but when I tried to, openra crashed and left this exception.log :
```

Mod Chooser Mod at Version release-20160508
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.FileNotFoundException`: File not found: E:\data1.hdr
   at OpenRA.FileSystem.FileSystem.Open(String filename)
   at OpenRA.FileSystem.InstallShieldCABExtractor..ctor(FileSystem context, String hdrFilename)
   at OpenRA.Mods.Common.Widgets.Logic.InstallFromCDLogic.<InstallTFD>c__AnonStorey1.<>m__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart() 

``` 
The file it is asking for exists and I can install TFD normally from this disk.

**Comment by Mailaender** [comment]
Next release will have this redone https://github.com/OpenRA/OpenRA/pull/11536 so check out the development version for a fix if you can't wait for the next playtest release.
