### ISSUE TITLE
Crash to Desktop

### ISSUE THREAD

**Issue by Aquilar** [OpenRA/OpenRA#11754]
I'm trying make a new mod of RA but whenever i build my new unit the game just shuts down.

Red Alert Expanded Mod at Version v1
on map 690816b58b2e8e98d3f050327ad3361e7389aaeb (Temperal by Blarget2).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Can't find Build in voice pool.
   at OpenRA.Sound.PlayPredefined(Ruleset ruleset, Player p, Actor voicedActor, String type, String definition, String variant, Boolean relative, WPos pos, Single volumeModifier, Boolean attenuateVolume)
   at OpenRA.Mods.Common.Traits.Voiced.PlayVoice(Actor self, String phrase, String variant)
   at OpenRA.VoiceExts.PlayVoice(Actor self, String phrase)
   at OpenRA.Mods.Common.Traits.AnnounceOnBuild.BuildingComplete(Actor self)
   at OpenRA.Mods.Common.Traits.Production.<DoProduction>c__AnonStorey1.<>m__0(World w)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

I don't understand whats happening.

**Comment by Aquilar** [comment]
Don't worry I figured it out on my own, I forgot to set up the voice traits in the unit's code.
