### ISSUE TITLE
System.ArgumentNullException in SmudgeLayer.AddSmudge

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#11922]
You can find the replay and map at https://github.com/abcdefg30/OpenRA/tree/crash-mission.
```
Red Alert Mod at Version {DEV_VERSION}
on map fc07e13e80de569874bfa533198258d126962762 (Infiltration by Scott_NZ).
Date: 2016-08-30 11:11:11Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.ArgumentNullException`: The value must not be NULL. (Der Wert darf nicht NULL sein.)
Parametername: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenRA.Mods.Common.Traits.SmudgeLayer.AddSmudge(CPos loc)
   at OpenRA.Mods.Common.Warheads.LeaveSmudgeWarhead.DoImpact(Target target, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.GameRules.WeaponInfo.<>c__DisplayClassa.<Impact>b__6() in \OpenRA\OpenRA.Game\GameRules\WeaponInfo.cs:Line 162.
   at OpenRA.Effects.DelayedAction.<Tick>b__0(World w) in \OpenRA\OpenRA.Game\Effects\DelayedAction.cs:Line 32.
   at OpenRA.World.Tick() in \OpenRA\OpenRA.Game\World.cs:Line 347.
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in \OpenRA\OpenRA.Game\Game.cs:Line 561.
   at OpenRA.Game.LogicTick() in \OpenRA\OpenRA.Game\Game.cs:Line 586.
   at OpenRA.Game.Loop() in \OpenRA\OpenRA.Game\Game.cs:Line 713.
   at OpenRA.Game.Run() in \OpenRA\OpenRA.Game\Game.cs:Line 753.
   at OpenRA.Program.Run(String[] args) in \OpenRA\OpenRA.Game\Support\Program.cs:Line 119.
   at OpenRA.Program.Main(String[] args) in \OpenRA\OpenRA.Game\Support\Program.cs:Line 40.

**Comment by obrakmann** [comment]
I'm not 100% sure, but this might be related to #11721.

The replay doesn't help with investigating, because for some reason, the map hash doesn't match:
```
$ git status
HEAD detached at abcdefg30/crash-mission
nothing to commit, working directory clean
$ git rev-parse HEAD
daa4150ca2100264d60cb1ad8110039ec9245302
$ ./OpenRA.Utility.exe ra --map-hash mods/ra/maps/infiltration/
5ffcb8bea5467f716c5c74fd9a9522c920a890d8
$ ./OpenRA.Utility.exe ra --replay-metadata crash-mission.orarep 
crash-mission.orarep: 
	Mod: ra
	Version: {DEV_VERSION}
	MapUid: fc07e13e80de569874bfa533198258d126962762
	MapTitle: Infiltration
```
