### ISSUE TITLE
Crash in multiplayer while paused 

### ISSUE THREAD

**Issue by nicefive** [OpenRA/OpenRA#12210]
Version: Playtest 20161001
Exception of type 'System.OutOfMemoryException' was thrown.

I have 32GB of RAM.

This issue has been problematic for a while but OpenRA normally only crashes after many hours of being paused.

We play our own maps with are normally large 
![openra-2016-10-11t101310272z](https://cloud.githubusercontent.com/assets/22424535/19279683/4784420e-8fda-11e6-90a2-5ea6409470c8.png)
(typically 256x256) with carefully tweaked rules.  Our games often run on for several hours by design.

We started a "2 player with bots" MP game last night and left it paused all night without any issues (paused by client player).  I played a bit this morning before work and paused it again (paused by server player).  When I got back from work I found it had crashed after less than an hour of being paused.

Thanks to all the good work this is now the only crash bug we are seeing.

Server and client logs attached.  I have a replay and custom map available but it crashes 2 hours into the game and after severable long pauses,

I checked the Windows Event Viewer on both computers and could not find anything obvious.
[Logs.zip](https://github.com/OpenRA/OpenRA/files/522419/Logs.zip)
[Logs_Client.zip](https://github.com/OpenRA/OpenRA/files/522418/Logs_Client.zip)

Not sure if this is helpful.

**Comment by LipkeGu** [comment]
```
Red Alert Mod at Version playtest-20161001
on map c6960ffb61c240dd8c2a37c5983a8ce13ab462b3 (Huge Island Northeast v2 [256x256] by James Bunting).
Date: 2016-10-11 11:11:33Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.OutOfMemoryException`: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   at OpenRA.Network.SyncReport.GenerateSyncReport(Report report)
   at OpenRA.Network.SyncReport.UpdateSyncReport()
   at OpenRA.Network.OrderManager.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by nicefive** [comment]
Note that our computers don't go into hibernate, sleep standby.  They are set to "never sleep" but blank the screen after 10 minutes or so.

**Comment by nicefive** [comment]
I also have logs from a previous game that crashed but with a different call stack.


Red Alert Mod at Version playtest-20161001
on map 840f63d00c762924ceed53cdc837cf43b5759256 (Huge Island Northwest [190x190] by James Bunting).
Date: 2016-10-08 03:00:53Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.OutOfMemoryException`: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Collections.Generic.HashSet`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.HashSet`1.Overlaps(IEnumerable`1 other)
   at OpenRA.Mods.Common.Traits.Cloak.<IsVisible>c__AnonStorey2.<>m__0(TraitPair`1 a)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at OpenRA.Mods.Common.Traits.Cloak.IsVisible(Actor self, Player viewer)
   at OpenRA.Actor.CanBeViewedByPlayer(Player player)
   at OpenRA.World.FogObscures(Actor a)
   at OpenRA.Mods.Common.Traits.Render.SelectionDecorations.<OpenRA_Traits_IRenderAboveShroud_RenderAboveShroud>c__Iterator0.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at OpenRA.Graphics.WorldRenderer.Draw()
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)


[Logs 2016-10-07 2109 Huge Island Northwest [190x190].zip](https://github.com/OpenRA/OpenRA/files/522446/Logs.2016-10-07.2109.Huge.Island.Northwest.190x190.zip)

**Comment by LipkeGu** [comment]
The Problem is that OpenRA.Game.exe is an X86 binary (32Bit) so it can only use <= 2 GB Memory (limited by windows) currently we have a few of this problems and will hopefully fixed by this: #12138 
If you handy and have the Visual studio 2015 Community Edition you can do the following to fix it yourself until #12207 

*open cmd.exe and type ``` CD "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin"``` then press enter
* then run in the command prompt ```editbin /LARGEADDRESSAWARE <openra.game.exe-fullpath>```
* restart the Game

**Comment by nicefive** [comment]
This is interesting.  We have VS2015 on both machines as we sometimes compile the dev version to keep up-to-date with critical fixes.

I will try this workaround and report any problems if they arise.

**Comment by LipkeGu** [comment]
the make.ps1 doesnt include the fixheader.exe
