### ISSUE TITLE
Crash in Survival02 mission

### ISSUE THREAD

**Issue by royboyrox** [OpenRA/OpenRA#12362]
Hey guys,

Trying to figure out a fix for a crash that keeps re-occuring in survival02 mission when bombs drop from the bombers right before the final wave comes in.  I tried to search through the forums for an answer but the one thread I found wasn't clear on the fix.

I generate this exception log:

Red Alert Mod at Version release-20161019
on map 85e6243ee3c8d6aa7c6634a805678e30a508243b (Survival 02 by Nuke'm Bro.).
Date: 2016-11-08 01:46:47Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Unit `bomblet` does not have a sequence named `open`
   at OpenRA.Graphics.SequenceProvider.GetSequence(String unitName, String sequenceName)
   at OpenRA.Graphics.Animation.GetSequence(String sequenceName)
   at OpenRA.Graphics.Animation.PlaySequence(String sequenceName)
   at OpenRA.Graphics.Animation.PlayThen(String sequenceName, Action after)
   at OpenRA.Mods.Common.Projectiles.GravityBomb..ctor(GravityBombInfo info, ProjectileArgs args)
   at OpenRA.Mods.Common.Projectiles.GravityBombInfo.Create(ProjectileArgs args)
   at OpenRA.Mods.Common.Traits.Armament.<CheckFire>c__AnonStorey0.<>m__1()
   at OpenRA.Mods.Common.Traits.Armament.ScheduleDelayedAction(Int32 t, Action a)
   at OpenRA.Mods.Common.Traits.Armament.CheckFire(Actor self, IFacing facing, Target target)
   at OpenRA.Mods.Common.Traits.AttackBomber.Tick(Actor self)
   at OpenRA.World.<Tick>m__3(TraitPair`1 x)
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

'preciate it!

**Comment by wraezor** [comment]
Also experienced the same crash.

Red Alert Mod at Version release-20161019
on map 85e6243ee3c8d6aa7c6634a805678e30a508243b (Survival 02 by Nuke'm Bro.).
Date: 2016-11-25 05:53:11Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Unit `bomblet` does not have a sequence named `open`
   at OpenRA.Graphics.SequenceProvider.GetSequence(String unitName, String sequenceName)
   at OpenRA.Graphics.Animation.GetSequence(String sequenceName)
   at OpenRA.Graphics.Animation.PlaySequence(String sequenceName)
   at OpenRA.Graphics.Animation.PlayThen(String sequenceName, Action after)
   at OpenRA.Mods.Common.Projectiles.GravityBomb..ctor(GravityBombInfo info, ProjectileArgs args)
   at OpenRA.Mods.Common.Projectiles.GravityBombInfo.Create(ProjectileArgs args)
   at OpenRA.Mods.Common.Traits.Armament.<CheckFire>c__AnonStorey0.<>m__1()
   at OpenRA.Mods.Common.Traits.Armament.ScheduleDelayedAction(Int32 t, Action a)
   at OpenRA.Mods.Common.Traits.Armament.CheckFire(Actor self, IFacing facing, Target target)
   at OpenRA.Mods.Common.Traits.AttackBomber.Tick(Actor self)
   at OpenRA.World.<Tick>m__3(TraitPair`1 x)
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
