### ISSUE TITLE
Crash for Bleeding post 11/7

### ISSUE THREAD

**Issue by hypercube33** [OpenRA/OpenRA#12418]
We compile bleeding builds before playing, and since 11/7 and before 11/20 we noted a bug where the game will crash to the desktop after a fixed period of time. We've observed it both at the multiplayer game host screen (after waiting 5-10 minutes or so) and post starting a game, same bug.

Attached are the crash logs. Looks like some array overflows.
[Logs.zip](https://github.com/OpenRA/OpenRA/files/609413/Logs.zip)

Snippit:
Red Alert Mod at Version {DEV_VERSION}
on map 6c4e91a3ed3f00f4a73f9f711d4067e508c8c1ed (Synergy by Nuke'm Bro.).
Date: 2016-11-20 19:33:03Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IndexOutOfRangeException`: Index was outside the bounds of the array.
   at OpenRA.Traits.Shroud.IsExplored(PPos puv) in c:\Games\OpenRA-bleed-20161120\OpenRA.Game\Traits\World\Shroud.cs:line 343
   at OpenRA.Mods.Common.Traits.HiddenUnderShroud.IsVisibleInner(Actor self, Player byPlayer)
   at OpenRA.Mods.Common.Traits.HiddenUnderFog.IsVisibleInner(Actor self, Player byPlayer)
   at OpenRA.Mods.Common.Traits.HiddenUnderShroud.IsVisible(Actor self, Player byPlayer)
   at OpenRA.Actor.CanBeViewedByPlayer(Player player) in c:\Games\OpenRA-bleed-20161120\OpenRA.Game\Actor.cs:line 349
   at OpenRA.World.FogObscures(Actor a) in c:\Games\OpenRA-bleed-20161120\OpenRA.Game\World.cs:line 79
   at OpenRA.Mods.Common.Traits.Render.SelectionDecorations.<OpenRA.Traits.IRenderAboveShroud.RenderAboveShroud>d__a.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at OpenRA.Graphics.WorldRenderer.Draw() in c:\Games\OpenRA-bleed-20161120\OpenRA.Game\Graphics\WorldRenderer.cs:line 195
   at OpenRA.Game.RenderTick() in c:\Games\OpenRA-bleed-20161120\OpenRA.Game\Game.cs:line 604
   at OpenRA.Game.Loop() in c:\Games\OpenRA-bleed-20161120\OpenRA.Game\Game.cs:line 735
   at OpenRA.Game.Run() in c:\Games\OpenRA-bleed-20161120\OpenRA.Game\Game.cs:line 753
   at OpenRA.Program.Run(String[] args) in c:\Games\OpenRA-bleed-20161120\OpenRA.Game\Support\Program.cs:line 134
   at OpenRA.Program.Main(String[] args) in c:\Games\OpenRA-bleed-20161120\OpenRA.Game\Support\Program.cs:line 41

**Comment by pchote** [comment]
This was introduced by #12307 (specifically by dropping the bounds check on [this line](https://github.com/OpenRA/OpenRA/pull/12307/files#diff-7031ef0aed4d6ab5769ea55003af3d1cR339)).

**Comment by hypercube33** [comment]
I'm not sure specifically what line this is - can't we just put it back in the current bleeding branch and 'fix' whatever the real problem is later? I think stability is more important even on the test builds, than gap generators looking pretty.

If you'd like me to do the above, I'd need to know specifically what line - I'm not a developer by trade, unfortunately.
