### ISSUE TITLE
OpenRA crashes on launch

### ISSUE THREAD

**Issue by alyas0** [OpenRA/OpenRA#12455]
Whenever I attempt to launch OpenRA I get a window that says: OpenRA has encountered a fatal error and must close. Refer to the crash logs and FAQ for more information.

I am aware this the same problem as #12313, but the fix of plugging earphones into my PC doesn't work.

Date: 2016-12-06 13:53:38Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

This is the contents of graphics.log:
System.InvalidOperationException: Can't create OpenAL context
   at OpenRA.Platforms.Default.OpenAlSoundEngine..ctor(String deviceName)
   at OpenRA.Platforms.Default.DefaultPlatform.CreateSound(String device)
   at OpenRA.Sound..ctor(IPlatform platform, SoundSettings soundSettings)
   at OpenRA.Game.Initialize(Arguments args)
System.InvalidOperationException: Can't create OpenAL context
   at OpenRA.Platforms.Default.OpenAlSoundEngine..ctor(String deviceName)
   at OpenRA.Platforms.Default.DefaultPlatform.CreateSound(String device)
   at OpenRA.Sound..ctor(IPlatform platform, SoundSettings soundSettings)
   at OpenRA.Game.Initialize(Arguments args)

**Comment by pchote** [comment]
Does your motherboard use a sound chip that requires its own driver package (e.g. realtek)?  If so, then please try downloading and installing the latest drivers directly from the manufacturer (not through windows update).

**Comment by alyas0** [comment]
Thanks for the quick response and yes it does work now.
