### ISSUE TITLE
Fatal Error on OpenRA launch

### ISSUE THREAD

**Issue by TadasTT** [OpenRA/OpenRA#12496]
I am using intergrated Intel HD Graphics 4600 video card and Windows 8. Video drivers are up to date, but this crash still occurs. Any ideas?

Here are the logs:
exception:
Exception of type `System.InvalidOperationException`: OpenGL Error: See graphics.log for details.
   at OpenRA.Platforms.Default.OpenGL.CheckGLError()
   at OpenRA.Platforms.Default.Sdl2GraphicsDevice.Clear()
   at OpenRA.Renderer.BeginFrame(int2 scroll, Single zoom)
   at OpenRA.Mods.Common.LoadScreens.ModChooserLoadScreen.Display()
   at OpenRA.Graphics.ChromeProvider.LoadCollection(String name, MiniYaml yaml)
   at OpenRA.Graphics.ChromeProvider.Initialize(ModData modData)
   at OpenRA.ModData.InitializeLoaders(IReadOnlyFileSystem fileSystem)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

graphics:
GL Error: 1280
   at OpenRA.Platforms.Default.OpenGL.CheckGLError()
   at OpenRA.Platforms.Default.Sdl2GraphicsDevice.Clear()
   at OpenRA.Renderer.BeginFrame(int2 scroll, Single zoom)
   at OpenRA.Mods.Common.LoadScreens.ModChooserLoadScreen.Display()
   at OpenRA.Graphics.ChromeProvider.LoadCollection(String name, MiniYaml yaml)
   at OpenRA.Graphics.ChromeProvider.Initialize(ModData modData)
   at OpenRA.ModData.InitializeLoaders(IReadOnlyFileSystem fileSystem)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by pchote** [comment]
Are you sure that you're using the full Intel driver from the Intel website?

**Comment by TadasTT** [comment]
Yes, download latest 10.18.14.4414 drivers from Intel's website today and result is the same. Tried to restart the PC, reinstall OpenRA... but it didn't help.

**Comment by abcdefg30** [comment]
Is this still a problem with latest drivers, OS and OpenRA versions?

**Comment by abcdefg30** [comment]
Closing because of inactivity.
