### ISSUE TITLE
Client crashed when trying to join lobby

### ISSUE THREAD

**Issue by Omnomon** [OpenRA/OpenRA#13070]
I joined a lobby, immediately exited, and joined a different lobby. Upon trying to load the new lobby, my client crashed. 
I got an error that said "Unable to read beyond the end of the stream," which is completely new to me. I've attached the full exception.log below...I'm sure this is a minor issue that can be fixed after the next release. 

```
Red Alert Mod at Version release-20161019
Date: 2017-04-05 23:12:12Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.EndOfStreamException`: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadString()
   at OpenRA.Order.Deserialize(World world, BinaryReader r)
   at OpenRA.Network.OrderIO.ToOrderList(Byte[] bytes, World world)
   at OpenRA.Network.ReplayRecorder.IsGameStart(Byte[] data)
   at OpenRA.Network.ReplayRecorder.Receive(Int32 clientID, Byte[] data)
   at OpenRA.Network.EchoConnection.Receive(Action`2 packetFn)
   at OpenRA.Network.OrderManager.TickImmediate()
   at OpenRA.Sync.<CheckSyncUnchanged>c__AnonStorey0.<>m__0()
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   at OpenRA.Sync.CheckSyncUnchanged(World world, Action fn)
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by abcdefg30** [comment]
No activity since quite a while, so this is probably fixed by #14748.
