### ISSUE TITLE
Can't install Tiberian Dawn

### ISSUE THREAD

**Issue by segadude** [OpenRA/OpenRA#13689]
I am trying to install the content for Tiberian Dawn from my original C&C discs. I inserted Disc 1, clicked advanced install and had it detect the disc. It detects the disc, and I clicked the button to install the content. Then I got an error saying to check install.log. Here is the install.log

```
Copying F:\.\CONQUER.MIX -> C:\Users\Brandon\Documents\OpenRA\Content/cnc/conquer.mix
Copying F:\.\DESERT.MIX -> C:\Users\Brandon\Documents\OpenRA\Content/cnc/desert.mix
Copying F:\.\GENERAL.MIX -> C:\Users\Brandon\Documents\OpenRA\Content/cnc/general.mix
Copying F:\.\SCORES.MIX -> C:\Users\Brandon\Documents\OpenRA\Content/cnc/scores.mix
Copying F:\.\SOUNDS.MIX -> C:\Users\Brandon\Documents\OpenRA\Content/cnc/sounds.mix
Copying F:\.\TEMPERAT.MIX -> C:\Users\Brandon\Documents\OpenRA\Content/cnc/temperat.mix
Copying F:\.\WINTER.MIX -> C:\Users\Brandon\Documents\OpenRA\Content/cnc/winter.mix
Extracting F:\INSTALL/SETUP.Z -> C:\Users\Brandon\Documents\OpenRA\Content/cnc/speech.mix
System.IO.InvalidDataException: Invalid dictionary size
   at OpenRA.FileFormats.Blast.Decompress(Stream input, Stream output, Action`2 onProgress)
   at OpenRA.Mods.Common.Widgets.Logic.InstallFromDiscLogic.ExtractFromPackage(ExtractionType type, String path, MiniYaml actionYaml, List`1 extractedFiles, Action`1 updateMessage)
   at OpenRA.Mods.Common.Widgets.Logic.InstallFromDiscLogic.<InstallFromDisc>c__AnonStorey5.<>m__1()
Deleting C:\Users\Brandon\Documents\OpenRA\Content/cnc/conquer.mix
Deleting C:\Users\Brandon\Documents\OpenRA\Content/cnc/desert.mix
Deleting C:\Users\Brandon\Documents\OpenRA\Content/cnc/general.mix
Deleting C:\Users\Brandon\Documents\OpenRA\Content/cnc/scores.mix
Deleting C:\Users\Brandon\Documents\OpenRA\Content/cnc/sounds.mix
Deleting C:\Users\Brandon\Documents\OpenRA\Content/cnc/temperat.mix
Deleting C:\Users\Brandon\Documents\OpenRA\Content/cnc/winter.mix
Deleting C:\Users\Brandon\Documents\OpenRA\Content/cnc/speech.mix
```

I tried Googling the error in the log and didn't find anything relevant. I am using OpenRA 20170527 on Windows 10 15063.483 64-bit.  The discs are US English discs. Both the front cover of the jewel case and the discs say Windows 95 under the Command & Conquer logo if that means something.

**Comment by pchote** [comment]
The only way I can think for this to happen is if the disc has been physically damaged.  Do you know if the original game installs and runs correctly on Windows?

**Comment by segadude** [comment]
Not sure, I'll have to try to install it on one of my old PCs and see.

**Comment by segadude** [comment]
Tried it on an old PC. It installed no problem and I was able to get through the intro movie and the first GDI mission without issue.

**Comment by skarnl** [comment]
I'm getting the exact same error message in the install.log
It installed the files up until the speech.mix and than I get the same error:

```
Using installer `gdi95: C&C Gold (GDI Disc, English)` of type `Disc`:
Copying E:\.\CONQUER.MIX -> C:\Users\oskar\Documents\OpenRA\Content/cnc/conquer.mix
Copying E:\.\DESERT.MIX -> C:\Users\oskar\Documents\OpenRA\Content/cnc/desert.mix
Copying E:\.\GENERAL.MIX -> C:\Users\oskar\Documents\OpenRA\Content/cnc/general.mix
Copying E:\.\SCORES.MIX -> C:\Users\oskar\Documents\OpenRA\Content/cnc/scores.mix
Copying E:\.\SOUNDS.MIX -> C:\Users\oskar\Documents\OpenRA\Content/cnc/sounds.mix
Copying E:\.\TEMPERAT.MIX -> C:\Users\oskar\Documents\OpenRA\Content/cnc/temperat.mix
Copying E:\.\WINTER.MIX -> C:\Users\oskar\Documents\OpenRA\Content/cnc/winter.mix
Extracting E:\INSTALL/SETUP.Z -> C:\Users\oskar\Documents\OpenRA\Content/cnc/speech.mix
System.IO.InvalidDataException: Invalid dictionary size
   at OpenRA.Mods.Common.FileFormats.Blast.Decompress(Stream input, Stream output, Action`2 onProgress)
   at OpenRA.Mods.Common.Widgets.Logic.InstallFromDiscLogic.ExtractFromPackage(ExtractionType type, String path, MiniYaml actionYaml, List`1 extractedFiles, Action`1 updateMessage)
   at OpenRA.Mods.Common.Widgets.Logic.InstallFromDiscLogic.<InstallFromDisc>c__AnonStorey5.<>m__1()
Deleting C:\Users\oskar\Documents\OpenRA\Content/cnc/conquer.mix
Deleting C:\Users\oskar\Documents\OpenRA\Content/cnc/desert.mix
Deleting C:\Users\oskar\Documents\OpenRA\Content/cnc/general.mix
Deleting C:\Users\oskar\Documents\OpenRA\Content/cnc/scores.mix
Deleting C:\Users\oskar\Documents\OpenRA\Content/cnc/sounds.mix
Deleting C:\Users\oskar\Documents\OpenRA\Content/cnc/temperat.mix
Deleting C:\Users\oskar\Documents\OpenRA\Content/cnc/winter.mix
Deleting C:\Users\oskar\Documents\OpenRA\Content/cnc/speech.mix
```

I might have an older (non-Win95) version of the C&C disc laying here. So will try if that one works.
And could also try the NOD-disc (disc2) as well.

Will post back here when I did that.

**Comment by reaperrr** [comment]
Maybe there are some disc/installer revisions where the setup.z header isn't compatible with our decompression.

@skarnl could you upload your setup.z somewhere?

**Comment by skarnl** [comment]
Uhm... the `setup.z` is what? Is it in the installation package or in the folder where I got the game installed?

Btw... the old (non-Win95) disc didn't work at all. And the NOD-disc (disc2) also gave the same errors. So I stopped trying and just played the game without cutscenes - which is a bummer.
So I will look for the `setup.z` later today 👍

**Comment by pchote** [comment]
It is in the INSTALL directory on the game discs.

**Comment by bluetrepidation** [comment]
Hello. Can confirm this is still a bug. Running OpenRA TS 20190314. The following DropBox link has a copy of the GDI and NOD setup.z files that aren't working: https://www.dropbox.com/sh/8l4z7r5i9a0asj9/AACojQnn64UgdDyzXBOT3lzra?dl=0
If you need me to run additional tests just reply. 

Thanks,
A.J.

**Comment by tkzv** [comment]
Still this bug. OpenRA-Tiberian-Dawn-x86_64.AppImage, Release 20200503. The md5sum of the problematic setup.z is 118d2de58380372dfdf9eb2db4cab5d6, same on both disks, same as in DropBox above.

Is there a way to install it manually, maybe?

**Comment by abcdefg30** [comment]
Yes, I have a manual here: https://gist.github.com/abcdefg30/a4fe1110c2727c3960e340ae2ce45bc0
Note that as long as we don't know why that setup.z is rejected, the manual installation might not work with its files too, but you can try.

**Comment by augiem** [comment]
I'm getting this same issue in release-20230225. Original C&C Windows 95 disc in perfect condition. The same error happens whether I use an iso I created from the disc or the physical disc. MD5 of SETUP.Z is 118D2DE58380372DFDF9EB2DB4CAB5D6.

```
`Using installer `gdi95: C&C Gold (GDI Disc, English)` of type `Disc`:
Copying G:\.\CONQUER.MIX -> C:\Users\*****\AppData\Roaming\OpenRA\Content/cnc/conquer.mix
Copying G:\.\DESERT.MIX -> C:\Users\*****\AppData\Roaming\OpenRA\Content/cnc/desert.mix
Copying G:\.\GENERAL.MIX -> C:\Users\*****\AppData\Roaming\OpenRA\Content/cnc/general.mix
Copying G:\.\SCORES.MIX -> C:\Users\*****\AppData\Roaming\OpenRA\Content/cnc/scores.mix
Copying G:\.\SOUNDS.MIX -> C:\Users\*****\AppData\Roaming\OpenRA\Content/cnc/sounds.mix
Copying G:\.\TEMPERAT.MIX -> C:\Users\*****\AppData\Roaming\OpenRA\Content/cnc/temperat.mix
Copying G:\.\WINTER.MIX -> C:\Users\*****\AppData\Roaming\OpenRA\Content/cnc/winter.mix
Extracting G:\INSTALL/SETUP.Z -> C:\Users\*****\AppData\Roaming\OpenRA\Content/cnc/speech.mix
System.IO.InvalidDataException: Invalid dictionary size
   at OpenRA.Mods.Common.FileFormats.Blast.Decompress(Stream input, Stream output, Action`2 onProgress)
   at OpenRA.Mods.Common.Widgets.Logic.InstallFromDiscLogic.ExtractFromPackage(ModData modData, ExtractionType type, String path, MiniYaml actionYaml, List`1 extractedFiles, Action`1 updateMessage)
   at OpenRA.Mods.Common.Widgets.Logic.InstallFromDiscLogic.<>c__DisplayClass42_0.<InstallFromDisc>b__1()
Deleting C:\Users\*****\AppData\Roaming\OpenRA\Content/cnc/conquer.mix
Deleting C:\Users\*****\AppData\Roaming\OpenRA\Content/cnc/desert.mix
Deleting C:\Users\*****\AppData\Roaming\OpenRA\Content/cnc/general.mix
Deleting C:\Users\*****\AppData\Roaming\OpenRA\Content/cnc/scores.mix
Deleting C:\Users\*****\AppData\Roaming\OpenRA\Content/cnc/sounds.mix
Deleting C:\Users\*****\AppData\Roaming\OpenRA\Content/cnc/temperat.mix
Deleting C:\Users\*****\AppData\Roaming\OpenRA\Content/cnc/winter.mix
Deleting C:\Users\*****\AppData\Roaming\OpenRA\Content/cnc/speech.mix
```

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/20439 was merged. It just hasn't been released yet.
