### ISSUE TITLE
Playtest Crash

### ISSUE THREAD

**Issue by Omnomon** [OpenRA/OpenRA#13731]
`OpenRA engine version playtest-20170722
Red Alert mod version playtest-20170722
Date: 2017-07-26 22:29:54Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Mods.Common.Widgets.Logic.ClientTooltipLogic.<ClientTooltipLogic>c__AnonStorey0.<>m__2()
   at OpenRA.Mods.Common.Widgets.Logic.ClientTooltipLogic.<ClientTooltipLogic>c__AnonStorey0.<>m__1()
   at OpenRA.Mods.Common.Widgets.TooltipContainerWidget.Draw()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

`

**Comment by abcdefg30** [comment]
Maybe related to  #13554?

**Comment by pchote** [comment]
Nope, this will be a regression from #13365.  Notice the change in `ClientTooltipLogic.cs`, which means that `BeforeRender` can now run in cases where `ClientWithIndex(clientIndex)` is null.  Returning early from there *might* be enough to fix it, but I wouldn't guarantee it without a repro case.

Potential repro case: have a player leave the lobby while you have the client tooltip active for them.

**Comment by Omnomon** [comment]
Happened again. Something about the player leaving the lobby definitely crashes the game. 
`OpenRA engine version playtest-20170722
Red Alert mod version playtest-20170722
Date: 2017-07-30 22:45:19Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Mods.Common.Widgets.Logic.ClientTooltipLogic.<ClientTooltipLogic>c__AnonStorey0.<>m__2()
   at OpenRA.Mods.Common.Widgets.Logic.ClientTooltipLogic.<ClientTooltipLogic>c__AnonStorey0.<>m__1()
   at OpenRA.Mods.Common.Widgets.TooltipContainerWidget.Draw()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

`

**Comment by rob-v** [comment]
Fixed by #13757
