### ISSUE TITLE
ReflectionTypeLoadException upon launch with .NET 4.0

### ISSUE THREAD

**Issue by sp2911** [OpenRA/OpenRA#13773]
```
Date: 2017-08-04 23:43:03Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.1
Exception of type `System.Reflection.ReflectionTypeLoadException`: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at OpenRA.Exts.GetNamespaces(Assembly a)
   at OpenRA.ObjectCreator.<ObjectCreator>m__0(Assembly asm)
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OpenRA.ObjectCreator..ctor(Manifest manifest, FileSystem modFiles)
   at OpenRA.ModData..ctor(Manifest mod, InstalledMods mods, Boolean useLoadScreen)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by reaperrr** [comment]
> Runtime Version: .NET CLR 4.0.30319.1

That last digit means you only have .NET 4.0 installed, however OpenRA needs at least 4.5.

**Comment by sp2911** [comment]
thanx !!! now it work !!!

**Comment by Mailaender** [comment]
Keeping this open as I believe the error message could be improved.

**Comment by reaperrr** [comment]
I also thought we had something in our installer that prevents installation if 4.5+ isn't installed, maybe that got lost or broken somewhere.

**Comment by Mailaender** [comment]
Indeed the installer should abort. https://github.com/OpenRA/OpenRA/issues/12256

**Comment by pchote** [comment]
@sp2911 did you install OpenRA using the installer from the website, or some other way?

**Comment by pchote** [comment]
Closing due to lack of followup.
