### ISSUE TITLE
crash in lobby

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#13915]
in lobby, after selecing map, while people were joining

```
External mods:
        ra-release-20170527: Red Alert (release-20170527)
        ra-{DEV_VERSION}: Red Alert ({DEV_VERSION})
Loading mod: ra
NAT discovery failed: One or more errors occurred.
Exception of type `System.InvalidOperationException`: Sequence contains more than one matching element
  at System.Linq.Enumerable.SingleOrDefault[TSource] (IEnumerable`1 source, System.Func`2 predicate) <0x406a9580 + 0x0018f> in <filename unknown>:0 
  at OpenRA.Network.Session.ClientInSlot (System.String slot) <0x4099cb90 + 0x00117> in <filename unknown>:0 
  at OpenRA.Mods.Common.Widgets.Logic.LobbyLogic.UpdatePlayerList () <0x4099b000 + 0x001ab> in <filename unknown>:0 
  at (wrapper delegate-invoke) <Module>:invoke_void ()
  at OpenRA.Game.SyncLobbyInfo () <0x4099ac20 + 0x00015> in <filename unknown>:0 
  at OpenRA.Network.UnitOrders.ProcessOrder (OpenRA.Network.OrderManager orderManager, OpenRA.World world, Int32 clientId, OpenRA.Order order) <0x40993730 + 0x018eb> in <filename unknown>:0 
  at OpenRA.Network.OrderManager.TickImmediate () <0x408916a0 + 0x00413> in <filename unknown>:0 
  at OpenRA.Sync+<CheckSyncUnchanged>c__AnonStorey0.<>m__0 () <0x40891160 + 0x00019> in <filename unknown>:0 
  at OpenRA.Sync.CheckSyncUnchanged[T] (OpenRA.World world, System.Func`1 fn) <0x40891020 + 0x00039> in <filename unknown>:0 
  at OpenRA.Sync.CheckSyncUnchanged (OpenRA.World world, System.Action fn) <0x40890ee0 + 0x00103> in <filename unknown>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) <0x40890650 + 0x00327> in <filename unknown>:0 
  at OpenRA.Game.LogicTick () <0x4088faf0 + 0x000b3> in <filename unknown>:0 
  at OpenRA.Game.Loop () <0x4088f890 + 0x0014f> in <filename unknown>:0 
  at OpenRA.Game.Run () <0x4088f730 + 0x00077> in <filename unknown>:0 
  at OpenRA.Program.Run (System.String[] args) <0x40658a80 + 0x0004f> in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) <0x40657d60 + 0x000f7> in <filename unknow
```

**Comment by pchote** [comment]
What version and mod was this with?

**Comment by anvilvapre** [comment]
20170527
red alert

**Comment by anvilvapre** [comment]
possibly caused by someone leaving and rejoining (due to slow connection or map download)

i myself was game admin, selecting a different map, the crash happened when i selected the new map.

**Comment by LipkeGu** [comment]
it seems to be related with #13070

**Comment by teinarss** [comment]
Happend right now in Playtest, so the bug is still here.

OpenRA engine version playtest-20180825
Tiberian Dawn mod version playtest-20180825
Date: 2018-09-08 20:03:50Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at OpenRA.Network.Session.ClientInSlot(String slot)
   at OpenRA.Mods.Common.Widgets.Logic.LobbyLogic.UpdatePlayerList()
   at System.Action.Invoke()
   at OpenRA.Game.SyncLobbyInfo()
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.TickImmediate()
   at OpenRA.Sync.<CheckSyncUnchanged>c__AnonStorey0.<>m__0()
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   at OpenRA.Sync.CheckSyncUnchanged(World world, Action fn)
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)

**Comment by pchote** [comment]
Looks like we are assigning the `Slot` for newly joined clients at the start of `ValidateClient` -- but we don't add this client to `LobbyInfo.Clients` until `completeConnection`, which may not run until many milliseconds later.  If the map changes during this window then I expect we would trigger this crash.

**Comment by anvilvapre** [comment]
Just happened again.
