### ISSUE TITLE
Game crash when hovering over a support power while its providing building is destroyed

### ISSUE THREAD

**Issue by dsimmons87** [OpenRA/OpenRA#14639]
If you hover over a support power's icon in the top left of the screen while the building that provides it gets destroyed, it crashes the game. This happened in the current playtest - I haven't tried the release version to see if it happens there.

In case it helps - I was testing this with a Ukraine Airstrip and Parabombs.

**Comment by ltem** [comment]
I could reproduce it. 

Exception log:
```
OpenRA engine version playtest-20180102
Tiberian Dawn mod version playtest-20180102
on map c39e94b8d9fb1f733a2c39af93e388649ed8d188 (Aggressive Tendencies by pulse).
Date: 2018-01-02 20:05:51Z
Operating System: Linux (Unix 4.9.0.3)
Runtime Version: Mono 4.6.2 (Debian 4.6.2.7+dfsg-1) CLR 4.0.30319.42000
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object
  at OpenRA.Mods.Common.Widgets.Logic.SupportPowerTooltipLogic+<SupportPowerTooltipLogic>c__AnonStorey0.<>m__1 () [0x00096] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Widgets/Logic/Ingame/SupportPowerTooltipLogic.cs:56 
  at OpenRA.Mods.Common.Widgets.TooltipContainerWidget.Draw () [0x00007] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Widgets/TooltipContainerWidget.cs:47 
  at OpenRA.Widgets.Widget.DrawOuter () [0x00012] in <a3fa31eb729947459e6c9fe4a90c19fe>:0 
  at OpenRA.Widgets.Widget.DrawOuter () [0x00032] in <a3fa31eb729947459e6c9fe4a90c19fe>:0 
  at OpenRA.Widgets.Widget.DrawOuter () [0x00032] in <a3fa31eb729947459e6c9fe4a90c19fe>:0 
  at OpenRA.Widgets.Ui.Draw () [0x00001] in <a3fa31eb729947459e6c9fe4a90c19fe>:0 
  at OpenRA.Game.RenderTick () [0x000ba] in <a3fa31eb729947459e6c9fe4a90c19fe>:0 
  at OpenRA.Game.Loop () [0x00142] in <a3fa31eb729947459e6c9fe4a90c19fe>:0 
  at OpenRA.Game.Run () [0x00042] in <a3fa31eb729947459e6c9fe4a90c19fe>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00011] in <a3fa31eb729947459e6c9fe4a90c19fe>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <a3fa31eb729947459e6c9fe4a90c19fe>:0 
```

**Comment by Arular101** [comment]
On release the tooltip stays when the providing building is destroyed (tested with Iron Curtain):

![image](https://user-images.githubusercontent.com/33390659/34499311-c3bf72bc-f005-11e7-8732-c2a3185de541.png)

Playtest exception log:
```
OpenRA` engine version playtest-20180102
Red Alert mod version playtest-20180102
on map 234958878883c05aa3eb40456f73896d39d621eb (Dual Cold Front by PizzaAtomica).
Date: 2018-01-02 20:27:46Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Mods.Common.Widgets.Logic.SupportPowerTooltipLogic.<SupportPowerTooltipLogic>c__AnonStorey0.<>m__1()
   at OpenRA.Mods.Common.Widgets.TooltipContainerWidget.Draw()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)
```
