### ISSUE TITLE
`System.InvalidOperationException` Crash when loading the OpenRA mod

### ISSUE THREAD

**Issue by mattitk** [OpenRA/OpenRA#14691]
After the latest update I have been encountering the following issue:

dump:
```
OpenRA engine version release-20171014
Date: 2018-01-08 14:04:54Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Game.Mod argument missing.
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by GraionDilach** [comment]
You have installed the last release over a previous one and launched the leftover OpenRA.exe thenafter. Mods have their own launcher executables now, the generic OpenRA.exe will not work anymore.
