### ISSUE TITLE
Crash: Attempting to query the position of an invalid Target

### ISSUE THREAD

**Issue by onnd** [OpenRA/OpenRA#14766]
Crashed after a bit less than an hour. I was moving a bunch of helicopters around the map.

exception log:

> OpenRA engine version playtest-20180102
> Red Alert mod version playtest-20180102
> on map 5a47b8b567665d8c7d7e905bdf90c20942b73efb (Regeneration Basin by Westwood Studios).
> Date: 2018-01-26 22:35:44Z
> Operating System: Linux (Unix 4.14.11.2)
> Runtime Version: Mono 4.6.1 (Stable 4.6.1.5/ef43c15 Sat Jan 13 21:02:45 CET 2018) CLR 4.0.30319.42000
> Exception of type `System.InvalidOperationException`: Attempting to query the position of an invalid Target
>   at OpenRA.Traits.Target.get_CenterPosition () [0x00051] in <a670b52c165c4b98b87e96cbd7f4c7a4>:0 
>   at OpenRA.Orders.UnitOrderGenerator.InputOverridesSelection (OpenRA.Graphics.WorldRenderer wr, OpenRA.World world, OpenRA.int2 xy, OpenRA.MouseInput mi) [0x00035] in <a670b52c165c4b98b87e96cbd7f4c7a4>:0 
>   at OpenRA.Mods.Common.Widgets.WorldInteractionControllerWidget.HandleMouseInput (OpenRA.MouseInput mi) [0x0019c] in /var/tmp/portage/games-strategy/openra-20180102/work/openra-20180102/OpenRA.Mods.Common/Widgets/WorldInteractionControllerWidget.cs:120 
>   at OpenRA.Widgets.Widget.HandleMouseInputOuter (OpenRA.MouseInput mi) [0x000cc] in <a670b52c165c4b98b87e96cbd7f4c7a4>:0 
>   at OpenRA.Widgets.Ui.HandleInput (OpenRA.MouseInput mi) [0x00026] in <a670b52c165c4b98b87e96cbd7f4c7a4>:0 
>   at OpenRA.DefaultInputHandler+<OnMouseInput>c__AnonStorey2.<>m__0 () [0x00000] in <a670b52c165c4b98b87e96cbd7f4c7a4>:0 
>   at OpenRA.Sync.CheckSyncUnchanged[T] (OpenRA.World world, System.Func`1[TResult] fn) [0x00043] in <a670b52c165c4b98b87e96cbd7f4c7a4>:0 
>   at OpenRA.DefaultInputHandler.OnMouseInput (OpenRA.MouseInput input) [0x0000e] in <a670b52c165c4b98b87e96cbd7f4c7a4>:0 
>   at OpenRA.Platforms.Default.Sdl2Input.PumpInput (OpenRA.Platforms.Default.Sdl2GraphicsDevice device, OpenRA.IInputHandler inputHandler) [0x001fe] in <56d09cde973b467b8405b9d847d37e86>:0 
>   at OpenRA.Platforms.Default.Sdl2GraphicsDevice.PumpInput (OpenRA.IInputHandler inputHandler) [0x00007] in <56d09cde973b467b8405b9d847d37e86>:0 
>   at OpenRA.Renderer.EndFrame (OpenRA.IInputHandler inputHandler) [0x0000d] in <a670b52c165c4b98b87e96cbd7f4c7a4>:0 
>   at OpenRA.Game.RenderTick () [0x00142] in <a670b52c165c4b98b87e96cbd7f4c7a4>:0 
>   at OpenRA.Game.Loop () [0x00142] in <a670b52c165c4b98b87e96cbd7f4c7a4>:0 
>   at OpenRA.Game.Run () [0x00042] in <a670b52c165c4b98b87e96cbd7f4c7a4>:0 
>   at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00011] in <a670b52c165c4b98b87e96cbd7f4c7a4>:0 
>   at OpenRA.Program.Main (System.String[] args) [0x0004f] in <a670b52c165c4b98b87e96cbd7f4c7a4>:0

**Comment by pchote** [comment]
`ScreenMap.ActorsAtMouse` checks for actors being in the world, but does not check for actors being dead.  It looks like `UnitOrderGenerator.InputOverridesSelection` managed to pull out an actor between it being killed and it being removed from the world, which then creates an invalid target.

**Comment by vgaming** [comment]
UPDATE: not relevant as the text below is for OpenRA's fork, Shattered Paradise.

<strike>I'm still getting this with the current version of OpenRA.

```log
Platform is Linux (X64)
Engine version is 3cf8d362182ffc6431b011ebef6ef70616f696ab
Runtime: .NET CLR 6.0.30
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 3840x2160
No custom resolution provided, using desktop resolution
Using resolution: 3840x2160
Using window scale 1,00
OpenGL renderer: AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 17.0.6, DRM 3.57, 6.9.3-arch1-1)
OpenGL version: 4.6 (Core Profile) Mesa 24.1.0-arch1.1
Using default sound device
Internal mods:
	modcontent: Mod Content Manager (3cf8d362182ffc6431b011ebef6ef70616f696ab)
	sp: Shattered Paradise (playtest-20240526)
External mods:
	sp-playtest-20240427: Shattered Paradise (playtest-20240427)
	sp-playtest-20240526: Shattered Paradise (playtest-20240526)
Loading mod: sp
[2024-06-05T12.35.17] Game started
Exception of type `System.InvalidOperationException`: Attempting to query the position of an invalid Target
   at OpenRA.Traits.Target.get_CenterPosition() in /home/runner/work/Shattered-Paradise-SDK/Shattered-Paradise-SDK/engine/OpenRA.Game/Traits/Target.cs:line 169
   at OpenRA.Mods.AS.Warheads.BackFireShrapnelWarhead.DoImpact(Target& target, WarheadArgs args) in /home/runner/work/Shattered-Paradise-SDK/Shattered-Paradise-SDK/engine/OpenRA.Mods.AS/Warheads/BackFireShrapnelWarhead.cs:line 44
   at OpenRA.GameRules.WeaponInfo.Impact(Target& target, WarheadArgs args) in /home/runner/work/Shattered-Paradise-SDK/Shattered-Paradise-SDK/engine/OpenRA.Game/GameRules/WeaponInfo.cs:line 262
   at OpenRA.Mods.AS.Projectiles.BulletAS.Explode(World world) in /home/runner/work/Shattered-Paradise-SDK/Shattered-Paradise-SDK/engine/OpenRA.Mods.AS/Duplicates/Projectiles/BulletAS.cs:line 368
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text) in /home/runner/work/Shattered-Paradise-SDK/Shattered-Paradise-SDK/engine/OpenRA.Game/WorldUtils.cs:line 106
   at OpenRA.World.Tick() in /home/runner/work/Shattered-Paradise-SDK/Shattered-Paradise-SDK/engine/OpenRA.Game/World.cs:line 460
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/Shattered-Paradise-SDK/Shattered-Paradise-SDK/engine/OpenRA.Game/Game.cs:line 651
   at OpenRA.Game.LogicTick() in /home/runner/work/Shattered-Paradise-SDK/Shattered-Paradise-SDK/engine/OpenRA.Game/Game.cs:line 666
   at OpenRA.Game.Loop() in /home/runner/work/Shattered-Paradise-SDK/Shattered-Paradise-SDK/engine/OpenRA.Game/Game.cs:line 835
   at OpenRA.Game.Run() in /home/runner/work/Shattered-Paradise-SDK/Shattered-Paradise-SDK/engine/OpenRA.Game/Game.cs:line 888
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/Shattered-Paradise-SDK/Shattered-Paradise-SDK/engine/OpenRA.Game/Game.cs:line 313
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/Shattered-Paradise-SDK/Shattered-Paradise-SDK/engine/OpenRA.Launcher/Program.cs:line 32
```

UPD: although the [engine's commit](https://github.com/OpenRA/OpenRA/commit/3cf8d362182ffc6431b011ebef6ef70616f696ab) does not belong to github.com/OpenRA/OpenRA.. Perhaps it is a bug in the fork (Shattered Paradise).
</strike>

**Comment by PunkPun** [comment]
this is an error in Shattered Paradise traits

**Comment by Mailaender** [comment]
Is the error reported/fixed already?

**Comment by Mailaender** [comment]
See https://github.com/ABrandau/Shattered-Paradise-SDK/issues/65
