### ISSUE TITLE
Game crash (KeyNotFoundException)

### ISSUE THREAD

**Issue by Alberthaff** [OpenRA/OpenRA#14820]
The game crashes after about 20-30 minutes of gameplay.
I have tested on both Mac and Windows with the same result.

Game version: bb801e5
Game mode: ts

Exception.log:
```
OpenRA engine version {DEV_VERSION}
Tiberian Sun mod version {DEV_VERSION}
on map dfb5ba8fa06f863637168b2fe168f5c778c14b66 (Forest Fires by Westwood Studios).
Date: 2018-02-14 08:52:08Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenRA.Mods.Common.Pathfinder.PathGraph.set_Item(CPos pos, CellInfo value) in d:\OpenRA-bleed\OpenRA.Mods.Common\Pathfinder\PathGraph.cs:line 224
   at OpenRA.Mods.Common.Pathfinder.PathSearch.AddInitialCell(CPos location) in d:\OpenRA-bleed\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 100
   at OpenRA.Mods.Common.Pathfinder.PathSearch.FromPoint(World world, MobileInfo mi, Actor self, CPos from, CPos target, Boolean checkForBlocked) in d:\OpenRA-bleed\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 72
   at OpenRA.Mods.Common.Traits.PathFinder.FindUnitPath(CPos source, CPos target, Actor self, Actor ignoreActor) in d:\OpenRA-bleed\OpenRA.Mods.Common\Traits\World\PathFinder.cs:line 77
   at OpenRA.Mods.Common.Pathfinder.PathFinderUnitPathCacheDecorator.FindUnitPath(CPos source, CPos target, Actor self, Actor ignoreActor) in d:\OpenRA-bleed\OpenRA.Mods.Common\Pathfinder\PathFinderUnitPathCacheDecorator.cs:line 43
   at OpenRA.Mods.Common.Activities.Move.<>c__DisplayClass6.<.ctor>b__4() in d:\OpenRA-bleed\OpenRA.Mods.Common\Activities\Move\Move.cs:line 72
   at OpenRA.Mods.Common.Activities.Move.EvalPath() in d:\OpenRA-bleed\OpenRA.Mods.Common\Activities\Move\Move.cs:line 133
   at OpenRA.Mods.Common.Activities.Move.Tick(Actor self) in d:\OpenRA-bleed\OpenRA.Mods.Common\Activities\Move\Move.cs:line 207
   at OpenRA.Activities.Activity.TickOuter(Actor self) in d:\OpenRA-bleed\OpenRA.Game\Activities\Activity.cs:line 174
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in d:\OpenRA-bleed\OpenRA.Game\Traits\ActivityUtils.cs:line 37
   at OpenRA.Mods.Common.Activities.AttackMoveActivity.Tick(Actor self) in d:\OpenRA-bleed\OpenRA.Mods.Common\Activities\Move\AttackMoveActivity.cs:line 44
   at OpenRA.Activities.Activity.TickOuter(Actor self) in d:\OpenRA-bleed\OpenRA.Game\Activities\Activity.cs:line 174
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in d:\OpenRA-bleed\OpenRA.Game\Traits\ActivityUtils.cs:line 37
   at OpenRA.Actor.Tick() in d:\OpenRA-bleed\OpenRA.Game\Actor.cs:line 128
   at OpenRA.World.Tick() in d:\OpenRA-bleed\OpenRA.Game\World.cs:line 351
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in d:\OpenRA-bleed\OpenRA.Game\Game.cs:line 605
   at OpenRA.Game.LogicTick() in d:\OpenRA-bleed\OpenRA.Game\Game.cs:line 629
   at OpenRA.Game.Loop() in d:\OpenRA-bleed\OpenRA.Game\Game.cs:line 759
   at OpenRA.Game.Run() in d:\OpenRA-bleed\OpenRA.Game\Game.cs:line 799
   at OpenRA.Game.InitializeAndRun(String[] args) in d:\OpenRA-bleed\OpenRA.Game\Game.cs:line 253
   at OpenRA.Program.Main(String[] args) in d:\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 37

```

**Comment by GraionDilach** [comment]
Can you reproduce the crash in the replay? If yes, could you provide an instance of such?

**Comment by degenkolb** [comment]
Hi, 

can confirm the error on Linux version [0f1cd07](https://github.com/OpenRA/OpenRA/commit/0f1cd07dee3c86e44b553f3b4138db19ba2384ce)

Replay can be found here https://nofile.io/f/SC11oJZGAvv/OpenRA-2018-02-19T182046Z.orarep
Crash happened at 12:50 (Please ignore the long pause I had to bring my kid to bed).
Nothing remarkable happend at this moment. 

```
./launch-game.sh Game.Mod=ts
Platform is Linux
Engine version is {DEV_VERSION}
Using SDL 2 with OpenGL renderer
Desktop resolution: 1680x1050
Using resolution: 1024x768
Using window scale 1.00
OpenGL version: 4.5.0 NVIDIA 384.111
Using default sound device
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
Internal mods:
        all: All mods ({DEV_VERSION})
        cnc: Tiberian Dawn ({DEV_VERSION})
        d2k: Dune 2000 ({DEV_VERSION})
        modcontent: Mod Content Manager ({DEV_VERSION})
        ra: Red Alert ({DEV_VERSION})
        ts: Tiberian Sun ({DEV_VERSION})
External mods:
        cnc-{DEV_VERSION}: Tiberian Dawn ({DEV_VERSION})
        d2k-{DEV_VERSION}: Dune 2000 ({DEV_VERSION})
        ra-{DEV_VERSION}: Red Alert ({DEV_VERSION})
        ts-{DEV_VERSION}: Tiberian Sun ({DEV_VERSION})
Loading mod: ts
[2018-02-19T19:20:46] Game started
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x00021] in <8f2c484307284b51944a1a13a14c0266>:0 
  at OpenRA.Mods.Common.Pathfinder.PathGraph.set_Item (OpenRA.CPos pos, OpenRA.Mods.Common.Pathfinder.CellInfo value) [0x00018] in <e7fbd33180ee40fbb437eaf31a2ed42b>:0 
  at OpenRA.Mods.Common.Pathfinder.PathSearch.AddInitialCell (OpenRA.CPos location) [0x0001e] in <e7fbd33180ee40fbb437eaf31a2ed42b>:0 
  at OpenRA.Mods.Common.Pathfinder.PathSearch.FromPoint (OpenRA.World world, OpenRA.Mods.Common.Traits.MobileInfo mi, OpenRA.Actor self, OpenRA.CPos from, OpenRA.CPos target, System.Boolean checkForBlocked) [0x0005b] in <e7fbd33180ee40fbb437eaf31a2ed42b>:0 
  at OpenRA.Mods.Common.Traits.PathFinder.FindUnitPath (OpenRA.CPos source, OpenRA.CPos target, OpenRA.Actor self, OpenRA.Actor ignoreActor) [0x0005c] in <e7fbd33180ee40fbb437eaf31a2ed42b>:0 
  at OpenRA.Mods.Common.Pathfinder.PathFinderUnitPathCacheDecorator.FindUnitPath (OpenRA.CPos source, OpenRA.CPos target, OpenRA.Actor self, OpenRA.Actor ignoreActor) [0x00086] in <e7fbd33180ee40fbb437eaf31a2ed42b>:0 
  at OpenRA.Mods.Common.Activities.Move+<Move>c__AnonStorey1.<>m__0 () [0x00056] in <e7fbd33180ee40fbb437eaf31a2ed42b>:0 
  at OpenRA.Mods.Common.Activities.Move.EvalPath () [0x00001] in <e7fbd33180ee40fbb437eaf31a2ed42b>:0 
  at OpenRA.Mods.Common.Activities.Move.Tick (OpenRA.Actor self) [0x000ea] in <e7fbd33180ee40fbb437eaf31a2ed42b>:0 
  at OpenRA.Activities.Activity.TickOuter (OpenRA.Actor self) [0x0005f] in <aa88afe2130343289cf3a5908e65903e>:0 
  at OpenRA.Traits.ActivityUtils.RunActivity (OpenRA.Actor self, OpenRA.Activities.Activity act) [0x00022] in <aa88afe2130343289cf3a5908e65903e>:0 
  at OpenRA.Mods.Common.Activities.AttackMoveActivity.Tick (OpenRA.Actor self) [0x00050] in <e7fbd33180ee40fbb437eaf31a2ed42b>:0 
  at OpenRA.Activities.Activity.TickOuter (OpenRA.Actor self) [0x0005f] in <aa88afe2130343289cf3a5908e65903e>:0 
  at OpenRA.Traits.ActivityUtils.RunActivity (OpenRA.Actor self, OpenRA.Activities.Activity act) [0x00022] in <aa88afe2130343289cf3a5908e65903e>:0 
  at OpenRA.Actor.Tick () [0x00010] in <aa88afe2130343289cf3a5908e65903e>:0 
  at OpenRA.World.Tick () [0x000c1] in <aa88afe2130343289cf3a5908e65903e>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x0020a] in <aa88afe2130343289cf3a5908e65903e>:0 
  at OpenRA.Game.LogicTick () [0x00050] in <aa88afe2130343289cf3a5908e65903e>:0 
  at OpenRA.Game.Loop () [0x000d6] in <aa88afe2130343289cf3a5908e65903e>:0 
  at OpenRA.Game.Run () [0x00042] in <aa88afe2130343289cf3a5908e65903e>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00011] in <aa88afe2130343289cf3a5908e65903e>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <aa88afe2130343289cf3a5908e65903e>:0 

OpenRA has encountered a fatal error.
  -> Log Files are available in ~/.openra
  -> FAQ is available at https://github.com/OpenRA/OpenRA/wiki/FAQ
```

**Comment by Alberthaff** [comment]
Sure.
Here is a crash from my Mac from a new crash.

I was not able to reproduce the issue in a 1v1 map. So it might only be an issue in "Forest Fires".

Replay: [Gamecrash.orarep.zip](https://github.com/OpenRA/OpenRA/files/1738012/Gamecrash.orarep.zip)

Exception.log:
```
OpenRA engine version {DEV_VERSION}
Tiberian Sun mod version {DEV_VERSION}
on map dfb5ba8fa06f863637168b2fe168f5c778c14b66 (Forest Fires by Westwood Studios).
Date: 2018-02-19 19:34:26Z
Operating System: OSX (Unix 17.2.0.0)
Runtime Version: Mono 5.4.1.7 (2017-06/e66d9abbb27 Wed Oct 25 12:10:41 EDT 2017) CLR 4.0.30319.42000
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
  at OpenRA.Mods.Common.Pathfinder.PathGraph.set_Item (OpenRA.CPos pos, OpenRA.Mods.Common.Pathfinder.CellInfo value) [0x00018] in <c6c9c17377304a79a4638684e035c47f>:0 
  at OpenRA.Mods.Common.Pathfinder.PathSearch.AddInitialCell (OpenRA.CPos location) [0x0001e] in <c6c9c17377304a79a4638684e035c47f>:0 
  at OpenRA.Mods.Common.Pathfinder.PathSearch.FromPoint (OpenRA.World world, OpenRA.Mods.Common.Traits.MobileInfo mi, OpenRA.Actor self, OpenRA.CPos from, OpenRA.CPos target, System.Boolean checkForBlocked) [0x0005b] in <c6c9c17377304a79a4638684e035c47f>:0 
  at OpenRA.Mods.Common.Traits.PathFinder.FindUnitPath (OpenRA.CPos source, OpenRA.CPos target, OpenRA.Actor self, OpenRA.Actor ignoreActor) [0x0005c] in <c6c9c17377304a79a4638684e035c47f>:0 
  at OpenRA.Mods.Common.Pathfinder.PathFinderUnitPathCacheDecorator.FindUnitPath (OpenRA.CPos source, OpenRA.CPos target, OpenRA.Actor self, OpenRA.Actor ignoreActor) [0x00086] in <c6c9c17377304a79a4638684e035c47f>:0 
  at OpenRA.Mods.Common.Activities.Move+<Move>c__AnonStorey1.<>m__0 () [0x00056] in <c6c9c17377304a79a4638684e035c47f>:0 
  at OpenRA.Mods.Common.Activities.Move.EvalPath () [0x00001] in <c6c9c17377304a79a4638684e035c47f>:0 
  at OpenRA.Mods.Common.Activities.Move.Tick (OpenRA.Actor self) [0x000ea] in <c6c9c17377304a79a4638684e035c47f>:0 
  at OpenRA.Activities.Activity.TickOuter (OpenRA.Actor self) [0x0005f] in <10ae5085a20848b69c727a77d009c0f2>:0 
  at OpenRA.Traits.ActivityUtils.RunActivity (OpenRA.Actor self, OpenRA.Activities.Activity act) [0x00022] in <10ae5085a20848b69c727a77d009c0f2>:0 
  at OpenRA.Mods.Common.Activities.AttackMoveActivity.Tick (OpenRA.Actor self) [0x00050] in <c6c9c17377304a79a4638684e035c47f>:0 
  at OpenRA.Activities.Activity.TickOuter (OpenRA.Actor self) [0x0005f] in <10ae5085a20848b69c727a77d009c0f2>:0 
  at OpenRA.Traits.ActivityUtils.RunActivity (OpenRA.Actor self, OpenRA.Activities.Activity act) [0x00022] in <10ae5085a20848b69c727a77d009c0f2>:0 
  at OpenRA.Actor.Tick () [0x00010] in <10ae5085a20848b69c727a77d009c0f2>:0 
  at OpenRA.World.Tick () [0x000c1] in <10ae5085a20848b69c727a77d009c0f2>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x0020a] in <10ae5085a20848b69c727a77d009c0f2>:0 
  at OpenRA.Game.LogicTick () [0x00050] in <10ae5085a20848b69c727a77d009c0f2>:0 
  at OpenRA.Game.Loop () [0x000d6] in <10ae5085a20848b69c727a77d009c0f2>:0 
  at OpenRA.Game.Run () [0x00042] in <10ae5085a20848b69c727a77d009c0f2>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00011] in <10ae5085a20848b69c727a77d009c0f2>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <10ae5085a20848b69c727a77d009c0f2>:0 
```

**Comment by MunWolf** [comment]
I haven't tested this in code yet but this seems to have something to do with an invalid layer value.
The exception happens in line 224 of PathGraph
```
set { (pos.Layer == 0 ? groundInfo : customLayerInfo[pos.Layer].Second)[pos] = value; }
```
where this call fails
```
customLayerInfo[pos.Layer]
```
So either pos.Layer is invalid or a specific layer is missing in customLayerInfo.

**Comment by PeterAntal** [comment]
I took a crack at both replays. As @MunWolf observing, Custom layers were empty - that AI controlled Actor did not have the ability to use Jumpjet. So the question is, how did that Layer get used for this move?


@degenkolb  repro had customLayerInfo as an empty dictionary. The move target referred to jetpack layer, which the map supported, but the actor didn't. 

The destination in Move.EvalPath refers to the target location, using Layer 0, but the next level in the stack (the Move Ctor), the layer for the target destination has been overwritten to 3. Not clear to me who assigned the destination onto that layer.

public static class CustomMovementLayerType
	{
		public const byte Tunnel = 1;
		public const byte Subterranean = 2;
		**public const byte Jumpjet = 3;**
		public const byte ElevatedBridge = 4;
	}

That world had support for the Jump Jet Movement Layer, but PathGraph was rejecting the layer as enabled for that Actor, as their info lacked the Jumpjet flag.

public PathGraph(CellInfoLayerPool layerPool, MobileInfo mobileInfo, Actor actor, World world, bool checkForBlocked)
		{
...
			var layers = world.GetCustomMovementLayers().Values
				.Where(cml => cml.EnabledForActor(actor.Info, mobileInfo));

e.g. You can evaluate the test at the failure point:
World.GetCustomMovementLayers()[3].EnabledForActor(Actor.Info, mobileInfo) == false


Debug Callstack: 	OpenRA.Mods.Common.dll!OpenRA.Mods.Common.Pathfinder.PathGraph.this[OpenRA.CPos].set(OpenRA.CPos pos, OpenRA.Mods.Common.Pathfinder.CellInfo value) Line 224	C#
 OpenRA.Mods.Common.dll!OpenRA.Mods.Common.Pathfinder.PathSearch.AddInitialCell(OpenRA.CPos location) Line 100	C#
 OpenRA.Mods.Common.dll!OpenRA.Mods.Common.Pathfinder.PathSearch.FromPoint(OpenRA.World world, OpenRA.Mods.Common.Traits.MobileInfo mi, OpenRA.Actor self, OpenRA.CPos from, OpenRA.CPos target, bool checkForBlocked) Line 72	C#
 	OpenRA.Mods.Common.dll!OpenRA.Mods.Common.Traits.PathFinder.FindUnitPath(OpenRA.CPos source, OpenRA.CPos target, OpenRA.Actor self, OpenRA.Actor ignoreActor) Line 77	C#
 OpenRA.Mods.Common.dll!OpenRA.Mods.Common.Pathfinder.PathFinderUnitPathCacheDecorator.FindUnitPath(OpenRA.CPos source, OpenRA.CPos target, OpenRA.Actor self, OpenRA.Actor ignoreActor) Line 43	C#
 	OpenRA.Mods.Common.dll!OpenRA.Mods.Common.Activities.Move..ctor.AnonymousMethod__0() Line 72	C#
>	OpenRA.Mods.Common.dll!OpenRA.Mods.Common.Activities.Move.EvalPath() Line 133	C#



I couldn't run Albert's GameCrash.orarep.zip - it failed out at the start with this:
_Additional information: Out of sync in frame 1.

 Compare syncreport.log with other players._

**Comment by array42** [comment]
I have the same bug pretty much every time we try the current edge version in multiplayer mode.

**Comment by array42** [comment]
(Maybe) fast way to get it to crash: Start skirmish with Hot Springs map. Give yourself some of those jumpjet units with the Debug menu. Fly over to AI enemy base and attack. For me it crashed then.

**Comment by AndrewHeim** [comment]
Here's another two replays ending in what looks like this crash.  Both on the most recent commit of bleed, which in this case was be96baf.

The first one crashes right about 15:20.
[crash1.zip](https://github.com/OpenRA/OpenRA/files/1821937/crash1.zip)
[crash2.zip](https://github.com/OpenRA/OpenRA/files/1821938/crash2.zip)

**Comment by AndrewHeim** [comment]
Looking at this, #14863, and #14923.

Got a couple of replays to help:
[crash1.zip](https://github.com/OpenRA/OpenRA/files/1821951/crash1.zip)
[crash2.zip](https://github.com/OpenRA/OpenRA/files/1821952/crash2.zip)

I recall that crash 1 happens at about 15:20.
