### ISSUE TITLE
latest version new install game crashes on load 

### ISSUE THREAD

**Issue by Feirfek** [OpenRA/OpenRA#14865]
Mod Chooser Mod at Version release-20160508
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.FileNotFoundException`: File not found: F:\data1.hdr
   at OpenRA.FileSystem.FileSystem.Open(String filename)
   at OpenRA.FileSystem.InstallShieldCABExtractor..ctor(FileSystem context, String hdrFilename)
   at OpenRA.Mods.Common.Widgets.Logic.InstallFromCDLogic.<InstallTFD>c__AnonStorey1.<>m__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by pchote** [comment]
> Mod Chooser Mod at Version release-20160508

The game thinks it is running release-20160508, but the latest version is release-20180218.
This suggests that your installation has been corrupted (maybe by installing new versions on top of old versions?).

Try uninstalling all versions of OpenRA, deleting any files left in the program files directory, and then reinstall the latest version.

**Comment by Feirfek** [comment]
tired that didn't work however i have found the soloution for some reason my anti-virus Program Bit defender was stoping open RA form starting up / updating the Crash log

**Comment by ltem** [comment]
So @Feirfek your crash is fixed?

**Comment by Feirfek** [comment]
yes seems for some reason that if i uninstall the game then reinstall it the Application then gets blocked by Bit Defender so i have to readd it to the exceptions for it to work but yes problem sorted

**Comment by ltem** [comment]
Good, then I'll close the issue.
