### ISSUE TITLE
TS crash: 20-30 minutes in game

### ISSUE THREAD

**Issue by qordaz** [OpenRA/OpenRA#14863]
Error log:
```
OpenRA engine version {DEV_VERSION}
Tiberian Sun mod version {DEV_VERSION}
on map f58ee760767563c184c6541e31cffeb032a18b02 (Tread Lightly by Westwood Studios).
Date: 2018-02-28 15:04:31Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenRA.Mods.Common.Pathfinder.PathGraph.set_Item(CPos pos, CellInfo value) in e:\Games\OpenRA-bleed\OpenRA.Mods.Common\Pathfinder\PathGraph.cs:line 224
   at OpenRA.Mods.Common.Pathfinder.PathSearch.AddInitialCell(CPos location) in e:\Games\OpenRA-bleed\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 100
   at OpenRA.Mods.Common.Pathfinder.PathSearch.FromPoint(World world, MobileInfo mi, Actor self, CPos from, CPos target, Boolean checkForBlocked) in e:\Games\OpenRA-bleed\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 72
   at OpenRA.Mods.Common.Traits.PathFinder.FindUnitPath(CPos source, CPos target, Actor self, Actor ignoreActor) in e:\Games\OpenRA-bleed\OpenRA.Mods.Common\Traits\World\PathFinder.cs:line 77
   at OpenRA.Mods.Common.Pathfinder.PathFinderUnitPathCacheDecorator.FindUnitPath(CPos source, CPos target, Actor self, Actor ignoreActor) in e:\Games\OpenRA-bleed\OpenRA.Mods.Common\Pathfinder\PathFinderUnitPathCacheDecorator.cs:line 43
   at OpenRA.Mods.Common.Activities.Move.<>c__DisplayClass6.<.ctor>b__4() in e:\Games\OpenRA-bleed\OpenRA.Mods.Common\Activities\Move\Move.cs:line 72
   at OpenRA.Mods.Common.Activities.Move.EvalPath() in e:\Games\OpenRA-bleed\OpenRA.Mods.Common\Activities\Move\Move.cs:line 133
   at OpenRA.Mods.Common.Activities.Move.Tick(Actor self) in e:\Games\OpenRA-bleed\OpenRA.Mods.Common\Activities\Move\Move.cs:line 207
   at OpenRA.Activities.Activity.TickOuter(Actor self) in e:\Games\OpenRA-bleed\OpenRA.Game\Activities\Activity.cs:line 174
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in e:\Games\OpenRA-bleed\OpenRA.Game\Traits\ActivityUtils.cs:line 37
   at OpenRA.Mods.Common.Activities.AttackMoveActivity.Tick(Actor self) in e:\Games\OpenRA-bleed\OpenRA.Mods.Common\Activities\Move\AttackMoveActivity.cs:line 44
   at OpenRA.Activities.Activity.TickOuter(Actor self) in e:\Games\OpenRA-bleed\OpenRA.Game\Activities\Activity.cs:line 174
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in e:\Games\OpenRA-bleed\OpenRA.Game\Traits\ActivityUtils.cs:line 37
   at OpenRA.Actor.Tick() in e:\Games\OpenRA-bleed\OpenRA.Game\Actor.cs:line 128
   at OpenRA.World.Tick() in e:\Games\OpenRA-bleed\OpenRA.Game\World.cs:line 351
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in e:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:line 605
   at OpenRA.Game.LogicTick() in e:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:line 629
   at OpenRA.Game.Loop() in e:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:line 759
   at OpenRA.Game.Run() in e:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:line 799
   at OpenRA.Game.InitializeAndRun(String[] args) in e:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:line 253
   at OpenRA.Program.Main(String[] args) in e:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 37
```

### Issue Summary
I am experiencing game crash 20-30 minutes into the game. This happens with any map. Play with Test AI. Have experienced this every time I try to play. 5-6 times

#### System Information
- **Operating System:** Windows 10 (also experiencing on Ubuntu 16.04)
- **OpenRA Version: Compiled OpenRA bleed today
- **Mod:** Tiberian Sun

**Comment by abcdefg30** [comment]
Looks like #14820.
