### ISSUE TITLE
Crash in AttackMoveOrderGenerator

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#14942]
may have happened when i accidently clicked tab or tilde key on my keyboard, but probably unrelated, perhaps the mouse was outside the game windows while alt+tabbing?

ubuntu
latest game release

```
Lua debug: Player: Multi2 got 3 oilb
Lua debug:   He got 0 kills
Lua debug:  isGreedy check: Multi2, 3 >? 5
Lua debug: Player: Multi3 got 0 oilb
Lua debug:   He got 0 kills
Lua debug:  isGreedy check: Multi3, 0 >? 5
Lua debug: Player: Multi4 got 5 oilb
Lua debug:   He got 0 kills
Lua debug:  isGreedy check: Multi4, 5 >? 5
Lua debug: Player: Multi5 got 6 oilb
Lua debug:   He got 0 kills
Lua debug:  isGreedy check: Multi5, 6 >? 5
Lua debug: sending AI units!
Lua debug:  
Lua debug: Main loop. GameTime: 7511
Exception of type `System.InvalidOperationException`: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (IEnumerable`1 source) <0x41abc3a0 + 0x0022b> in <filename unknown>:0 
  at OpenRA.Mods.Common.Traits.AttackMoveOrderGenerator.GetCursor (OpenRA.World world, CPos cell, int2 worldPixel, MouseInput mi) [0x0003b] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/AttackMove.cs:174 
  at OpenRA.Mods.Common.Widgets.WorldInteractionControllerWidget+<GetCursor>c__AnonStorey5.<>m__0 () [0x000ad] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Widgets/WorldInteractionControllerWidget.cs:243 
  at OpenRA.Sync.CheckSyncUnchanged[T] (OpenRA.World world, System.Func`1 fn) <0x41a16e40 + 0x0009b> in <filename unknown>:0 
  at OpenRA.Mods.Common.Widgets.WorldInteractionControllerWidget.GetCursor (int2 screenPos) [0x00027] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Widgets/WorldInteractionControllerWidget.cs:227 
  at OpenRA.Widgets.Widget.GetCursorOuter (int2 pos) <0x4191acd0 + 0x0017b> in <filename unknown>:0 
  at OpenRA.Widgets.Widget.GetCursorOuter (int2 pos) <0x4191acd0 + 0x000d7> in <filename unknown>:0 
  at OpenRA.Widgets.Widget.GetCursorOuter (int2 pos) <0x4191acd0 + 0x000d7> in <filename unknown>:0 
  at OpenRA.Widgets.Widget.GetCursorOuter (int2 pos) <0x4191acd0 + 0x000d7> in <filename unknown>:0 
  at OpenRA.Game.RenderTick () <0x41902000 + 0x0029f> in <filename unknown>:0 
  at OpenRA.Game.Loop () <0x418a1600 + 0x001f3> in <filename unknown>:0 
  at OpenRA.Game.Run () <0x418a1480 + 0x00077> in <filename unknown>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) <0x4160fa80 + 0x0004f> \
```

**Comment by RoosterDragon** [comment]
Speculation from reading the code:

`AttackMoveOrderGenerator` filters out dead actors (`a => !a.IsDead`) on creation - this could cause there to be no actors and possibly lead the the above error.

https://github.com/OpenRA/OpenRA/blob/3b642b1a7942bea30380d7c9c91a17f6e1277a7f/OpenRA.Mods.Common/Traits/AttackMove.cs#L134-L142

`CommandBarLogic` disables attack-move if do actors in the world have it - but it a dead actor had it, then it would remain enabled - and when it creates the order, it would pass a dead actor which the order generator would filter out.

https://github.com/OpenRA/OpenRA/blob/3b642b1a7942bea30380d7c9c91a17f6e1277a7f/OpenRA.Mods.Common/Widgets/Logic/Ingame/CommandBarLogic.cs#L269-L277

(If attack-move is enabled - `CommandBarLogic` passes `selectedActors` to the `AttackMoveOrderGenerator`)

My gut says `CommandBarLogic` should also filter out dead actors (and then we could remove the check in the order generator as it would be redundant) - but somebody who knows orders better may wish to verify.

**Comment by pchote** [comment]
Sounds reasonable.  Do you want to open a PR?  We will still need a check in the OG so that it can cancel itself if the selected actors all die.

**Comment by teinarss** [comment]
Just happend in a game played on the current release-
`
OpenRA engine version release-20180923
Tiberian Dawn mod version release-20180923
on map 449308b7191bce0e74f4adca69f12453abd80e6e (Control and Chaos by pulse).
Date: 2018-11-14 18:18:36Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at OpenRA.Mods.Common.Traits.AttackMoveOrderGenerator.GetCursor(World world, CPos cell, int2 worldPixel, MouseInput mi)
   at OpenRA.Mods.Common.Widgets.WorldInteractionControllerWidget.<GetCursor>c__AnonStorey3.<>m__0()
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   at OpenRA.Mods.Common.Widgets.WorldInteractionControllerWidget.GetCursor(int2 screenPos)
   at OpenRA.Widgets.Widget.GetCursorOuter(int2 pos)
   at OpenRA.Widgets.Widget.GetCursorOuter(int2 pos)
   at OpenRA.Widgets.Widget.GetCursorOuter(int2 pos)
   at OpenRA.Widgets.Widget.GetCursorOuter(int2 pos)
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)
`
