### ISSUE TITLE
Traits and conditions are applied to actors in APCs

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#14989]
![mammoth crash](https://user-images.githubusercontent.com/11763228/37869226-ad8c7126-2f92-11e8-9770-6875cef15d38.gif)
What you see here is a unit about to die, it gets hit by an alien trooper that applies a negative self heal debuff, the mammoth is loaded into a carryall (which is used as an APC for now) and the self heal kills the unit, causing the following crash.

You can see shrapnel flying on the background, I suspect this comes from the killed unit, just like the smoke.

Edit: my suggestion here is to allow the modder to enable a condition on the loaded unit, then I could disable all the negative self healing traits.

```OpenRA engine version {DEV_VERSION}
Shattered Paradise mod version {Build 20180324 II}
on map f7ddd62f26a22bd802e7204114b6b63bd94265bb (Blistering Sands by MadHQ).
Date: 2018-03-24 20:57:45Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (hmec 732 (not in world))
   at OpenRA.TraitDictionary.CheckDestroyed(Actor actor) in C:\Users\Alfredo\Desktop\SP 20180314\OpenRA.Game\TraitDictionary.cs:line 83
   at OpenRA.TraitDictionary.Get[T](Actor actor) in C:\Users\Alfredo\Desktop\SP 20180314\OpenRA.Game\TraitDictionary.cs:line 88
   at OpenRA.Actor.Trait[T]() in C:\Users\Alfredo\Desktop\SP 20180314\OpenRA.Game\Actor.cs:line 237
   at OpenRA.Mods.Common.Traits.Cargo.<>c__DisplayClassf.<CanUnload>b__e(Actor p) in c:\Users\Alfredo\Desktop\OpenRA-SP-Master-Branch\OpenRA.Mods.Common\Traits\Cargo.cs:line 214
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at OpenRA.Mods.Common.Traits.Cargo.<CanUnload>b__d(CPos c) in c:\Users\Alfredo\Desktop\OpenRA-SP-Master-Branch\OpenRA.Mods.Common\Traits\Cargo.cs:line 214
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at OpenRA.Mods.Common.Traits.Cargo.CanUnload() in c:\Users\Alfredo\Desktop\OpenRA-SP-Master-Branch\OpenRA.Mods.Common\Traits\Cargo.cs:line 213
   at OpenRA.Mods.Common.Traits.Cargo.ResolveOrder(Actor self, Order order) in c:\Users\Alfredo\Desktop\OpenRA-SP-Master-Branch\OpenRA.Mods.Common\Traits\Cargo.cs:line 187
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order) in C:\Users\Alfredo\Desktop\SP 20180314\OpenRA.Game\Network\UnitOrders.cs:line 291
   at OpenRA.Network.OrderManager.Tick() in C:\Users\Alfredo\Desktop\SP 20180314\OpenRA.Game\Network\OrderManager.cs:line 179
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in C:\Users\Alfredo\Desktop\SP 20180314\OpenRA.Game\Game.cs:line 597
   at OpenRA.Game.LogicTick() in C:\Users\Alfredo\Desktop\SP 20180314\OpenRA.Game\Game.cs:line 629
   at OpenRA.Game.Loop() in C:\Users\Alfredo\Desktop\SP 20180314\OpenRA.Game\Game.cs:line 759
   at OpenRA.Game.Run() in C:\Users\Alfredo\Desktop\SP 20180314\OpenRA.Game\Game.cs:line 799
   at OpenRA.Game.InitializeAndRun(String[] args) in C:\Users\Alfredo\Desktop\SP 20180314\OpenRA.Game\Game.cs:line 253
   at OpenRA.Program.Main(String[] args) in C:\Users\Alfredo\Desktop\SP 20180314\OpenRA.Game\Support\Program.cs:line 37```

**Comment by MustaphaTR** [comment]
Your example sounds like we would want to fix units dying in a cargo properly (for future stuff like Garrison cleaning weapons from Generals), in other hand we already want conditions for passengers to make Infantry in pillbox not get veterancy.

**Comment by pchote** [comment]
> Edit: my suggestion here is to allow the modder to enable a condition on the loaded unit, then I could disable all the negative self healing traits.

This exists: take a look at `CarriedCondition` on the `Carryable` trait.

**Comment by GraionDilach** [comment]
IIRC that's not included in thev engine revision used by @ABrandau atm though.

**Comment by ABrandau** [comment]
The bug also happens with infantry entering an APC so it doesnt solve issue, also carryalls are extremely hard to use in big groups (because every single aircraft will try to land on the same cell) so I phased them out.

**Comment by MustaphaTR** [comment]
https://github.com/OpenRA/OpenRA/pull/15066 added that for cargo. This is technically fixed now imo.

But my comment about killing passengers also applies. IMO we would want to solve that properly.

**Comment by pchote** [comment]
@MustaphaTR can you please create a new ticket for that?
Better to close this one as fixed to avoid confusion.
