### ISSUE TITLE
Playing a video in radar will crush the game in replay mode

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#15051]
Red Alert mod version release-20180307

The error log:

Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Widget  has no child PLAYER of type VqaPlayerWidget
   at OpenRA.Widgets.Widget.Get[T](String id)
   at OpenRA.Mods.Common.Scripting.Media.StopFMVInRadar()
   at OpenRA.Mods.Common.Scripting.MediaGlobal.<PlayMovieInRadar>c__AnonStorey3.<>m__0()
   at OpenRA.Effects.AsyncAction.<Tick>m__0(World w)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)

The map you can test this:
https://resource.openra.net/maps/26690/

**Comment by abcdefg30** [comment]
Interesting, the testmap doesn't crash for me. Can anyone else reproduce this?

**Comment by airetaM** [comment]
this crash appears in the replay **and spectator** mode for me too

**Comment by abcdefg30** [comment]
> this crash appears in the replay and spectator mode for me too

Ah, thanks that did the trick.

**Comment by KOYK** [comment]
abcdefg30 thank you for the pr man!
