### ISSUE TITLE
Actors cant support multiple instances of Transforms

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#15126]
Why is this even conditional if it cant be used?

```OpenRA engine version {DEV_VERSION}
Nomad Galaxy mod version Experimental-Version
on map 751338fe954236cf292030b79fe30601e391ecc9 (Escalation by Nolt).
Date: 2018-05-08 03:00:18Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Actor gcivship has multiple traits of type `OpenRA.Mods.Common.Traits.Transforms`
   at OpenRA.TraitDictionary.TraitContainer`1.GetOrDefault(UInt32 actor) in c:\Users\Alfredo\Desktop\OpenRA-SP-Bleed-Branch\OpenRA.Game\TraitDictionary.cs:line 162
   at OpenRA.TraitDictionary.GetOrDefault[T](Actor actor) in c:\Users\Alfredo\Desktop\OpenRA-SP-Bleed-Branch\OpenRA.Game\TraitDictionary.cs:line 95
   at OpenRA.Actor.TraitOrDefault[T]() in c:\Users\Alfredo\Desktop\OpenRA-SP-Bleed-Branch\OpenRA.Game\Actor.cs:line 253
   at OpenRA.Mods.Common.Activities.Transform.Tick(Actor self) in c:\Users\Alfredo\Desktop\OpenRA-SP-Bleed-Branch\OpenRA.Mods.Common\Activities\Transform.cs:line 58
   at OpenRA.Activities.Activity.TickOuter(Actor self) in c:\Users\Alfredo\Desktop\OpenRA-SP-Bleed-Branch\OpenRA.Game\Activities\Activity.cs:line 174
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in c:\Users\Alfredo\Desktop\OpenRA-SP-Bleed-Branch\OpenRA.Game\Traits\ActivityUtils.cs:line 37
   at OpenRA.Actor.Tick() in c:\Users\Alfredo\Desktop\OpenRA-SP-Bleed-Branch\OpenRA.Game\Actor.cs:line 139
   at OpenRA.World.Tick() in c:\Users\Alfredo\Desktop\OpenRA-SP-Bleed-Branch\OpenRA.Game\World.cs:line 351
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in c:\Users\Alfredo\Desktop\OpenRA-SP-Bleed-Branch\OpenRA.Game\Game.cs:line 605
   at OpenRA.Game.LogicTick() in c:\Users\Alfredo\Desktop\OpenRA-SP-Bleed-Branch\OpenRA.Game\Game.cs:line 629
   at OpenRA.Game.Loop() in c:\Users\Alfredo\Desktop\OpenRA-SP-Bleed-Branch\OpenRA.Game\Game.cs:line 759
   at OpenRA.Game.Run() in c:\Users\Alfredo\Desktop\OpenRA-SP-Bleed-Branch\OpenRA.Game\Game.cs:line 799
   at OpenRA.Game.InitializeAndRun(String[] args) in c:\Users\Alfredo\Desktop\OpenRA-SP-Bleed-Branch\OpenRA.Game\Game.cs:line 253
   at OpenRA.Program.Main(String[] args) in c:\Users\Alfredo\Desktop\OpenRA-SP-Bleed-Branch\OpenRA.Game\Support\Program.cs:line 37```

**Comment by ABrandau** [comment]
Okay fair enough, the controls dont allow you to use more than one deploy command in case two transforms were being used, a shame tho, since I wanted to use many of these using exclusive conditions (you can only use one)

**Comment by pchote** [comment]
We still want to be able to support swapping between different versions.

**Comment by GraionDilach** [comment]
PausableConditionaling the Transforms trait with pause being the deploy-blocked behaviour and disabled blocking all interactions would work.

**Comment by pchote** [comment]
I’d go even further, following the precident set by #15043: remove all user interaction, and have it trigger exclusively from a condition.  The current use cases could be automatically updated to add a matching GrantConditionOnDeploy.

**Comment by GraionDilach** [comment]
Ypu can still apply this mindset for GCoD - I am using that setup for my GrantTimedConditionOnDeploy atm (which I maybe should upstream these days, I guess).

**Comment by ABrandau** [comment]
If I use GCoD + TransformOnCondition to turn an actor into a building, then it will most likely wont take into consideration the footprint of the building, correct me if I am wrong.

**Comment by pchote** [comment]
Right.  That kills my idea for removing the cursor/hotkey interaction, but we can still easily fix support for multiple trait instances.
