### ISSUE TITLE
Game crashes when mouse is placed outside the map

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#15195]
I dont know what is going on, if I select a movable unit and hover over the edge of the map, the mod crashes

``OpenRA engine version {DEV_VERSION}
Nomad Galaxy mod version Experimental-Version
on map 794cde3c597ce87bf5a0660266575474c1b5c831 (Escalation by Nolt).
Date: 2018-06-01 04:42:20Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IndexOutOfRangeException`: Index was outside the bounds of the array.
   at OpenRA.Graphics.HardwareCursor.Update() in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\Graphics\HardwareCursor.cs:line 122
   at OpenRA.Graphics.HardwareCursor.SetCursor(String cursorName) in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\Graphics\HardwareCursor.cs:line 94
   at OpenRA.Game.RenderTick() in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\Game.cs:line 665
   at OpenRA.Game.Loop() in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\Game.cs:line 781
   at OpenRA.Game.Run() in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\Game.cs:line 799
   at OpenRA.Game.InitializeAndRun(String[] args) in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\Game.cs:line 253
   at OpenRA.Program.Main(String[] args) in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\Support\Program.cs:line 37``

**Comment by pchote** [comment]
I can't reproduce this in the default mods.  I suspect your mod may not (or might, but incorrectly) define the move-blocked cursor that is always shown outside map.

**Comment by ABrandau** [comment]
I dont know. I had undo all my changes to get this fixed, I cant even track what caused it.

**Comment by ABrandau** [comment]
Closing until it happens again or I have more info about this.
