### ISSUE TITLE
Area beam does not seem to be able to support attack type switching

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#15190]
I have a similar setup to the TS tick tank in this case, I confirmed the bug by replacing the Area Beam weapon with a regular lazer zap projectile.

''OpenRA engine version {DEV_VERSION}
Nomad Galaxy mod version Experimental-Version
on map 80e711ffda9f8b2a4e937705b5d17444b2c1164b (System out of Memory by ZxGanon).
Date: 2018-05-31 03:13:06Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Actor dunit3 has multiple traits of type `OpenRA.Mods.Common.Traits.AttackBase`
   at OpenRA.TraitDictionary.TraitContainer`1.GetOrDefault(UInt32 actor) in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\TraitDictionary.cs:line 162
   at OpenRA.TraitDictionary.TraitContainer`1.Get(UInt32 actor) in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\TraitDictionary.cs:line 149
   at OpenRA.TraitDictionary.Get[T](Actor actor) in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\TraitDictionary.cs:line 89
   at OpenRA.Actor.Trait[T]() in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\Actor.cs:line 248
   at OpenRA.Mods.Common.Projectiles.AreaBeam..ctor(AreaBeamInfo info, ProjectileArgs args, Color color) in c:\Users\Alfredo\Desktop\SP 20180509\OpenRA.Mods.Common\Projectiles\AreaBeam.cs:line 106
   at OpenRA.Mods.Common.Projectiles.AreaBeamInfo.Create(ProjectileArgs args) in c:\Users\Alfredo\Desktop\SP 20180509\OpenRA.Mods.Common\Projectiles\AreaBeam.cs:line 75
   at OpenRA.Mods.Common.Traits.Armament.<>c__DisplayClass10.<FireBarrel>b__f() in c:\Users\Alfredo\Desktop\SP 20180509\OpenRA.Mods.Common\Traits\Armament.cs:line 299
   at OpenRA.Mods.Common.Traits.Armament.ScheduleDelayedAction(Int32 t, Action a) in c:\Users\Alfredo\Desktop\SP 20180509\OpenRA.Mods.Common\Traits\Armament.cs:line 207
   at OpenRA.Mods.Common.Traits.Armament.FireBarrel(Actor self, IFacing facing, Target target, Barrel barrel) in c:\Users\Alfredo\Desktop\SP 20180509\OpenRA.Mods.Common\Traits\Armament.cs:line 295
   at OpenRA.Mods.Common.Traits.Armament.CheckFire(Actor self, IFacing facing, Target target) in c:\Users\Alfredo\Desktop\SP 20180509\OpenRA.Mods.Common\Traits\Armament.cs:line 245
   at OpenRA.Mods.Common.Traits.AttackBase.DoAttack(Actor self, Target target, IEnumerable`1 armaments) in c:\Users\Alfredo\Desktop\SP 20180509\OpenRA.Mods.Common\Traits\Attack\AttackBase.cs:line 113
   at OpenRA.Mods.Common.Traits.AttackFollow.Tick(Actor self) in c:\Users\Alfredo\Desktop\SP 20180509\OpenRA.Mods.Common\Traits\Attack\AttackFollow.cs:line 45
   at OpenRA.Mods.Common.Traits.AttackFollow.OpenRA.Traits.ITick.Tick(Actor self) in c:\Users\Alfredo\Desktop\SP 20180509\OpenRA.Mods.Common\Traits\Attack\AttackFollow.cs:line 34
   at OpenRA.World.<>c.<Tick>b__91_0(TraitPair`1 x) in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\World.cs:line 353
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text) in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\WorldUtils.cs:line 75
   at OpenRA.World.Tick() in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\World.cs:line 353
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\Game.cs:line 605
   at OpenRA.Game.LogicTick() in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\Game.cs:line 629
   at OpenRA.Game.Loop() in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\Game.cs:line 759
   at OpenRA.Game.Run() in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\Game.cs:line 799
   at OpenRA.Game.InitializeAndRun(String[] args) in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\Game.cs:line 253
   at OpenRA.Program.Main(String[] args) in C:\Users\Alfredo\Desktop\SP 20180510 I\OpenRA.Game\Support\Program.cs:line 37''

**Comment by reaperrr** [comment]
Yeah, support for multiple Attack* traits on a single actor is currently sketchy at best.
