### ISSUE TITLE
Exception of type `System.InvalidOperationException`: Game.Mod argument missing

### ISSUE THREAD

**Issue by OHussain** [OpenRA/OpenRA#15256]
### Issue Summary
I just found this repo, and installed to a folder so I could put it on a flash drive. Upon running any of the executables (RedAlert, TiberianDawn, or Dune2000) The game crashes after a black screen and I get the following error in the exception log:
 `System.InvalidOperationException`: Game.Mod argument missing.
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.Program.Main(String[] args)

I checked on here for similar issues, but they're all related to previous versions having old executables. This is not the case. Thanks
... ... ...

#### System Information
- **Operating System:** Windows 7
- **.NET / Mono Version:** .NET CLR 4.0.30319.42000
- **OpenRA Version:** release-20180307
- **Mod:** All - Red Alert, Tiberian Dawn, and Dune2000

#### Additional Information:
- Steps to reproduce
	1. Open RedAlert.exe or other

- Logs

See attached zip folder.
[debug.zip](https://github.com/OpenRA/OpenRA/files/2098327/debug.zip)

**Comment by pchote** [comment]
As per the wiki (https://github.com/OpenRA/OpenRA/wiki/Compiling) you need to launch the game using the `launch-game` script.  Running `OpenRA.Game.exe` directly without arguments won't work.

**Comment by OHussain** [comment]
I did not compile from source. As mentioned, I only ran the mod executable files (e.g. RedAlert.exe).  I deleted the log files and tried again, then downloaded the installed version and ran that before opening the issue.

**Comment by pchote** [comment]
Do you have Norton or any other invasive security software suites installed?  These have been known to cause problems in the past.

**Comment by OHussain** [comment]
You are correct, I use Avast. However, I made sure to add the OpenRA install directory to my exceptions list.

**Comment by matjaeck** [comment]
@OHussain Did you find a way to get it working or identify the cause of the issue?

**Comment by abcdefg30** [comment]
Closing because of inactivity.

**Comment by JasonGuthrie-Mesmerise** [comment]
Same thing just happened to me
