### ISSUE TITLE
My game crashed and won't let me play.

### ISSUE THREAD

**Issue by JWBagginses** [OpenRA/OpenRA#15534]
I recently downloaded all of the OpenRA games on my computer. I have only played Red Alert maybe 3 times. When I went to get on this morning, the game crashed and told me that the game had undergone a "Fatal Error", not allowing me to play the game. This notice would be pulled up before I could see any kind of screen from the game. Just off the bat.

My computer isn't bad. It isn't the newest, but it can run Minecraft, 3D Blender, Star Wars the Old Republic, etc.

Windows 10 Operating System
My newest .NET is v4.0.30319
The version of the game was Release 20180307 for Windows
The game was Red Alert

Here is one of the crash reports

OpenRA engine version release-20180307
Red Alert mod version release-20180307
Date: 2018-08-16 15:46:26Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.ArgumentOutOfRangeException`: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at OpenRA.Mods.Common.Widgets.Logic.ServerListLogic.<RefreshServerList>m__1(DownloadDataCompletedEventArgs i)
   at OpenRA.Download.<Download>c__AnonStorey1.<>m__1(Object _, DownloadDataCompletedEventArgs a)
   at System.Net.WebClient.OnDownloadDataCompleted(DownloadDataCompletedEventArgs e)
   at System.Net.WebClient.DownloadDataOperationCompleted(Object arg)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by pchote** [comment]
That is a very odd crash report.

Can you confirm that this crash is still happening, and that it crashes before it shows a loading screen or anything else?  Can you try deleting all of the log files from the logs folder, running the game, and then copying the fresh crash log that it generates here?

**Comment by JWBagginses** [comment]
Sure.

**Comment by JWBagginses** [comment]
Just the Crash Reports, or all logs?

**Comment by pchote** [comment]
Delete all logs, but then only need to upload the crash report.

**Comment by JWBagginses** [comment]
Here is the new Crash Report.

OpenRA engine version release-20180307
Date: 2018-08-17 19:06:22Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)

**Comment by pchote** [comment]
Ok good, that is a more sensible looking log.  Can you please share the contents of `graphics.log`?

**Comment by JWBagginses** [comment]
Sure.

**Comment by JWBagginses** [comment]
GL Info Log:
ERROR: Definition for "void main()" not found.

System.InvalidProgramException: Link error in shader program 'shp'
   at OpenRA.Platforms.Default.Shader..ctor(String name)
   at OpenRA.Platforms.Default.Sdl2GraphicsDevice.CreateShader(String name)
   at OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings)
   at OpenRA.Game.Initialize(Arguments args)
GL Info Log:
ERROR: Definition for "void main()" not found.

System.InvalidProgramException: Link error in shader program 'shp'
   at OpenRA.Platforms.Default.Shader..ctor(String name)
   at OpenRA.Platforms.Default.Sdl2GraphicsDevice.CreateShader(String name)
   at OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings)
   at OpenRA.Game.Initialize(Arguments args)

**Comment by pchote** [comment]
It looks like your OpenRA installation has been corrupted.  The most common cause for this is security software like Norton deciding that one or more files are suspicious and deleting them.

**Comment by JWBagginses** [comment]
Ok.

**Comment by JWBagginses** [comment]
Would deleting all applications and then reinstalling them work?

**Comment by pchote** [comment]
Uninstalling through the programs and features menu, then reinstalling should be good enough - but you need to be careful that whatever corrupted the install in the first place won't immediately do it again.

**Comment by JWBagginses** [comment]
how do I get to that menu

**Comment by JWBagginses** [comment]
and how do I prevent that

**Comment by GraionDilach** [comment]
Is this on Win10? Just right click on a Start menu shortcut and choose uninstall.

Although I wonder what is your exact antivir software moreso to see if that could indeed be the problem.

**Comment by JWBagginses** [comment]
Thank you guys.
