### ISSUE TITLE
Crashes during load, after successful first play

### ISSUE THREAD

**Issue by BeardyHat** [OpenRA/OpenRA#15578]
### Issue Summary
Red Alert crashes when attempting to load. 

#### System Information
- **Operating System:** Windows 10 Pro
- **.NET** v4.0.30319
- **OpenRA Version:** OpenRA-release-20180307
- **Mod:** Red Alert

#### Additional Information:
- Steps to reproduce
	1. Install OpenRA
	2. Install Red Alert packs upon opening Red Alert. All available downloads, inc. Music
	3. Works, at least briefly.
        4. Any subsequent attempts to load Red Alert result in a crash to desktop

- Logs

[Logs.zip](https://github.com/OpenRA/OpenRA/files/2341113/Logs.zip)
exception.log:
```
OpenRA engine version release-20180307
Red Alert mod version release-20180307
Date: 2018-08-31 18:07:08Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Map.get_Package()
   at OpenRA.Map..ctor(ModData modData, IReadOnlyPackage package)
```
debug.log
```
local.mix: failed to resolve filenames for 48 unknown hashes
```

**Comment by pchote** [comment]
Can you please check that your virus scanner hasn't blocked or corrupted OpenRA?

We have had a series of unusual bug reports lately that have been caused by Windows Defender, which makes me wonder if Microsoft have put OpenRA on some blacklist.

**Comment by abcdefg30** [comment]
Closing because of inactivity.
