### ISSUE TITLE
Exception on completing d2k mission Atreides02a

### ISSUE THREAD

**Issue by drogoganor** [OpenRA/OpenRA#15872]
### Issue Summary
When completing the D2k mission Atreides02a, I get this exception:

> OpenRA engine version {DEV_VERSION}
> Dune 2000 mod version {DEV_VERSION}
> on map 49e806fecf20794d5af6471ca319818369eb22e6 (Atreides 02a by Westwood Studios).
> Date: 2018-12-02 02:57:58Z
> Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
> Runtime Version: .NET CLR 4.0.30319.42000
> Exception of type `System.IndexOutOfRangeException`: Index was outside the bounds of the array.
>    at OpenRA.CellLayer`1.get_Item(CPos cell) in D:\Development\OpenRA\OpenRA.Game\Map\CellLayer.cs:line 83
>    at OpenRA.Mods.D2k.Traits.BuildableTerrainLayer.HitTile(CPos cell, Int32 damage) in D:\Development\OpenRA\OpenRA.Mods.D2k\Traits\World\BuildableTerrainLayer.cs:line 66
>    at OpenRA.Mods.D2k.Warheads.DamagesConcreteWarhead.DoImpact(Target target, Actor firedBy, IEnumerable`1 damageModifiers) in D:\Development\OpenRA\OpenRA.Mods.D2k\Warheads\DamagesConcreteWarhead.cs:line 31
>    at OpenRA.GameRules.WeaponInfo.Impact(Target target, Actor firedBy, IEnumerable`1 damageModifiers) in D:\Development\OpenRA\OpenRA.Game\GameRules\WeaponInfo.cs:line 189
>    at OpenRA.Mods.Common.Projectiles.Bullet.Explode(World world) in D:\Development\OpenRA\OpenRA.Mods.Common\Projectiles\Bullet.cs:line 279
>    at OpenRA.Mods.Common.Projectiles.Bullet.Tick(World world) in D:\Development\OpenRA\OpenRA.Mods.Common\Projectiles\Bullet.cs:line 244
>    at OpenRA.World.<Tick>b__95_1(IEffect e) in D:\Development\OpenRA\OpenRA.Game\World.cs:line 364
>    at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text) in D:\Development\OpenRA\OpenRA.Game\WorldUtils.cs:line 78
>    at OpenRA.World.Tick() in D:\Development\OpenRA\OpenRA.Game\World.cs:line 364
>    at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\Development\OpenRA\OpenRA.Game\Game.cs:line 616
>    at OpenRA.Game.LogicTick() in D:\Development\OpenRA\OpenRA.Game\Game.cs:line 640
>    at OpenRA.Game.Loop() in D:\Development\OpenRA\OpenRA.Game\Game.cs:line 770
>    at OpenRA.Game.Run() in D:\Development\OpenRA\OpenRA.Game\Game.cs:line 810
>    at OpenRA.Game.InitializeAndRun(String[] args) in D:\Development\OpenRA\OpenRA.Game\Game.cs:line 256
>    at OpenRA.Program.Main(String[] args) in 
> D:\Development\OpenRA\OpenRA.Game\Support\Program.cs:line 37

#### System Information
- **Operating System:** Windows 10
- **.NET / Mono Version:** .NET 4.7.1
- **OpenRA Version:** bleed
- **Mod:** Dune2000

- Logs
[exception-2018-12-02T025758Z.zip](https://github.com/OpenRA/OpenRA/files/2636554/exception-2018-12-02T025758Z.zip)

- OpenRA Replays
[OpenRA-2018-12-02T025114Z.zip](https://github.com/OpenRA/OpenRA/files/2636558/OpenRA-2018-12-02T025114Z.zip)
Right at the end

**Comment by drogoganor** [comment]
It's now been fixed in release-20181215, thank you.
