### ISSUE TITLE
InvalidOperationException when erasing text in Set ActorID dialog

### ISSUE THREAD

**Issue by teinarss** [OpenRA/OpenRA#16199]
### Issue Summary
Map editor crashes when erasing actorID text in the dialog

#### System Information
- **Operating System:** Windows 10
- **.NET / Mono Version:**  .NET 4.7.1
- **OpenRA Version:** playtest-20190209
- **Mod:** Tiberian Dawn

#### Additional Information:
- Steps to reproduce
	1. Load a map in the map editor
	2. Place several waypoints  
	3. Open the ActorId dialog for one of the waypoints
        4. Start erasing the text

- Logs
```
OpenRA engine version playtest-20190209
Tiberian Dawn mod version playtest-20190209
on map 293cdf1766a282aa8747bbec99b1abb7e2f5b928 (Model 150 by norman).
Date: 2019-02-12 18:45:23Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at OpenRA.Mods.Common.Widgets.Logic.ActorEditLogic.SetActorID(World world, String actorId)
   at OpenRA.Mods.Common.Widgets.Logic.ActorEditLogic.<ActorEditLogic>c__AnonStorey0.<>m__4()
   at OpenRA.Mods.Common.Widgets.TextFieldWidget.HandleKeyPress(KeyInput e)
   at OpenRA.Widgets.Widget.HandleKeyPressOuter(KeyInput e)
   at OpenRA.Widgets.Ui.HandleKeyPress(KeyInput e)
   at OpenRA.DefaultInputHandler.<OnKeyInput>c__AnonStorey0.<>m__0()
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn)
   at OpenRA.DefaultInputHandler.OnKeyInput(KeyInput input)
   at OpenRA.Platforms.Default.Sdl2Input.PumpInput(Sdl2PlatformWindow device, IInputHandler inputHandler)
   at OpenRA.Platforms.Default.Sdl2PlatformWindow.PumpInput(IInputHandler inputHandler)
   at OpenRA.Renderer.EndFrame(IInputHandler inputHandler)
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)

```

**Comment by abcdefg30** [comment]
`world.Map.ActorDefinitions` does not contain any newly placed actors, so this will fail when doing anything with that text field. I guess we somehow need to rely on the `EditorActorLayer` instead. (Duplicate detect will fail, too.)
