### ISSUE TITLE
Soviet 05 Distant Thunder script error

### ISSUE THREAD

**Issue by anon006** [OpenRA/OpenRA#16204]
I completed the "Kill all Units and Structures" objective before trying to capture the green Radar Dome, the mission immediately crashed before I could capture the Radar Dome.

Might be unrelated but I also sequence-broke the mission by killing the MCV before it could leave the mainland with Yaks.

![ra1 crash](https://user-images.githubusercontent.com/47646957/52822901-0bcf5e80-30ee-11e9-93bd-7884ac5c3712.png)

**Comment by abcdefg30** [comment]
Can you post `lua.log`, please?
(In case you don't know where OpenRA writes logs to: https://github.com/OpenRA/OpenRA/wiki/FAQ#my-game-just-crashed )

**Comment by pchote** [comment]
Ping @anon006. The lua.log will tell us exactly what went wrong, which will make this much easier to fix.

**Comment by FrameLimiter** [comment]
To reproduce:
∙Start the mission & debug "/all", then kill everything except the green radar dome.
->if you fail to capture the green radar dome before killing off the enemy it'll produce this lua crash:
```
Fatal Lua Error: 
Stack Traceback
===============
(2) global C function 'error'
(3) Lua function '(anonymous)' at file 'C:\Program Files (x86)\OpenRA (playtest)\/lua/sandbox.lua:150' (best guess)
	Local variables:
	 arg = nil
	 ok = boolean: false
	 result = string: "[string \"BindingSupport.lua\"]:30: Unable to convert parameter 0 to Int32"
(4) tail call
(5) Lua function '?' at line 23 of chunk '"scriptwrapper.lua"]'
(6) global C function 'xpcall'
(7) Lua upvalue 'TryRunSandboxed' at line 23 of chunk '"scriptwrapper.lua"]'
	Local variables:
	 fn = Lua function '?' (defined at line 144 of chunk "soviet05.lua"])
(8) Lua function '?' at line 37 of chunk '"scriptwrapper.lua"]'

Error message
===============
...ogram Files (x86)\OpenRA (playtest)\/lua/sandbox.lua:150: [string "BindingSupport.lua"]:30: Unable to convert parameter 0 to Int32
===============
   at OpenRA.Scripting.ScriptContext.FatalError(String message)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eluant.LuaRuntime.MethodWrapper.Invoke(Object[] parms)
   at Eluant.LuaRuntime.MakeManagedCall(IntPtr state, MethodWrapper wrapper)
   at Eluant.LuaRuntime.MethodWrapperCallCallback(IntPtr state)
   at Eluant.LuaRuntime.MethodWrapperCallCallbackWrapper(IntPtr state)
   at Eluant.LuaApi.lua_pcall(IntPtr L, Int32 nargs, Int32 nresults, Int32 errfunc)
   at Eluant.LuaRuntime.Call(IList`1 args)
   at Eluant.LuaRuntime.Call(LuaFunction fn, IList`1 args)
   at Eluant.LuaFunction.Call(IList`1 args)
   at OpenRA.Scripting.ScriptContext.Tick(Actor self)
   at OpenRA.Mods.Common.Scripting.LuaScript.OpenRA.Traits.ITick.Tick(Actor self)
   at OpenRA.World.<Tick>m__4(TraitPair`1 x)
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)
   at OpenRA.WindowsLauncher.Main(String[] args)

```
