### ISSUE TITLE
Map editor crashes on map load on bleed

### ISSUE THREAD

**Issue by teinarss** [OpenRA/OpenRA#16628]
System.InvalidOperationException: 'Unit `editor-overlay` does not have a sequence named `copy`'

 ``` at OpenRA.Graphics.SequenceProvider.GetSequence(String unitName, String sequenceName)
   at OpenRA.Mods.Common.Traits.EditorSelectionLayer..ctor(Actor self, EditorSelectionLayerInfo info)
   at OpenRA.Mods.Common.Traits.EditorSelectionLayerInfo.Create(ActorInitializer init)
   at OpenRA.Actor..ctor(World world, String name, TypeDictionary initDict)
   at OpenRA.World.CreateActor(Boolean addToWorld, String name, TypeDictionary initDict)
   at OpenRA.World.CreateActor(String name, TypeDictionary initDict)
   at OpenRA.World..ctor(ModData modData, Map map, OrderManager orderManager, WorldType type)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Game.LoadEditor(String mapUid)
   at OpenRA.Mods.Common.Widgets.Logic.MainMenuLogic.<>c__DisplayClass17_0.<LoadMapIntoEditor>b__0()
   at OpenRA.Mods.Common.Widgets.Logic.ConnectionLogic.ConnectionStateChanged(OrderManager om)
   at System.Action`1.Invoke(T obj)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.Program.Main(String[] args)```

**Comment by pchote** [comment]
Regression from #16553.
