### ISSUE TITLE
Selling helipad/airfield/repairpad with docked unit causes crash

### ISSUE THREAD

**Issue by teinarss** [OpenRA/OpenRA#16857]
This is on bleed

```
   at OpenRA.Traits.Target.get_CenterPosition() in C:\projects\OpenRa1\OpenRA.Game\Traits\Target.cs:line 174
   at OpenRA.Mods.Common.Activities.Resupply.Tick(Actor self) in C:\projects\OpenRa1\OpenRA.Mods.Common\Activities\Resupply.cs:line 82
   at OpenRA.Activities.Activity.TickOuter(Actor self) in C:\projects\OpenRa1\OpenRA.Game\Activities\Activity.cs:line 63
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in C:\projects\OpenRa1\OpenRA.Game\Traits\ActivityUtils.cs:line 37
   at OpenRA.Activities.Activity.TickChild(Actor self) in C:\projects\OpenRa1\OpenRA.Game\Activities\Activity.cs:line 92
   at OpenRA.Activities.Activity.TickOuter(Actor self) in C:\projects\OpenRa1\OpenRA.Game\Activities\Activity.cs:line 63
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in C:\projects\OpenRa1\OpenRA.Game\Traits\ActivityUtils.cs:line 37
   at OpenRA.Actor.Tick() in C:\projects\OpenRa1\OpenRA.Game\Actor.cs:line 144
   at OpenRA.World.Tick() in C:\projects\OpenRa1\OpenRA.Game\World.cs:line 453
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in C:\projects\OpenRa1\OpenRA.Game\Game.cs:line 610
   at OpenRA.Game.LogicTick() in C:\projects\OpenRa1\OpenRA.Game\Game.cs:line 637
   at OpenRA.Game.Loop() in C:\projects\OpenRa1\OpenRA.Game\Game.cs:line 779
   at OpenRA.Game.Run() in C:\projects\OpenRa1\OpenRA.Game\Game.cs:line 819
   at OpenRA.Game.InitializeAndRun(String[] args) in C:\projects\OpenRa1\OpenRA.Game\Game.cs:line 261
   at OpenRA.Program.Main(String[] args) in C:\projects\OpenRa1\OpenRA.Game\Support\Program.cs:line 31```

**Comment by tovl** [comment]
This is probably related to #16830.
