### ISSUE TITLE
GL error 1282 on TS [Bleed]

### ISSUE THREAD

**Issue by teinarss** [OpenRA/OpenRA#17087]
Happens when starting a skirmish game on bleed.

```
GL Error: 1282
   at OpenRA.Platforms.Default.OpenGL.CheckGLError()
   at OpenRA.Platforms.Default.Texture.GetData()
   at OpenRA.Graphics.Sheet.CreateBuffer()
   at OpenRA.Graphics.SequenceProvider.Preload()
   at OpenRA.Map.PostInit()
   at OpenRA.Map..ctor(ModData modData, IReadOnlyPackage package)
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.TickImmediate()
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0()
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn)
   at OpenRA.Sync.RunUnsynced(Boolean checkSyncHash, World world, Action fn)
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.Program.Main(String[] args)


OpenGL Information:
Vendor: NVIDIA Corporation
Renderer: GeForce GTX 1080 Ti/PCIe/SSE2
GL Version: OpenGL ES 3.2 NVIDIA 431.85
Shader Version: OpenGL ES GLSL ES 3.20
Available extensions:
GL_EXT_base_instance
GL_EXT_blend_func_extended
GL_EXT_blend_minmax
GL_EXT_buffer_storage
GL_EXT_clear_texture
GL_EXT_clip_control
GL_EXT_clip_cull_distance
GL_EXT_color_buffer_float
GL_EXT_color_buffer_half_float
GL_EXT_conservative_depth
GL_EXT_copy_image
GL_EXT_debug_label
GL_EXT_discard_framebuffer
GL_EXT_disjoint_timer_query
GL_EXT_draw_buffers_indexed
GL_EXT_draw_elements_base_vertex
GL_EXT_EGL_image_external_wrap_modes
GL_EXT_float_blend
GL_EXT_frag_depth
GL_EXT_geometry_point_size
GL_EXT_geometry_shader
GL_EXT_gpu_shader5
GL_EXT_map_buffer_range
GL_EXT_multi_draw_indirect
GL_EXT_multisample_compatibility
GL_EXT_occlusion_query_boolean
GL_EXT_polygon_offset_clamp
GL_EXT_post_depth_coverage
GL_EXT_primitive_bounding_box
GL_EXT_raster_multisample
GL_EXT_render_snorm
GL_EXT_robustness
GL_EXT_separate_shader_objects
GL_EXT_shader_group_vote
GL_EXT_shader_implicit_conversions
GL_EXT_shader_integer_mix
GL_EXT_shader_io_blocks
GL_EXT_shader_non_constant_global_initializers
GL_EXT_shader_texture_lod
GL_EXT_shadow_samplers
GL_EXT_sparse_texture
GL_EXT_sparse_texture2
GL_EXT_sRGB
GL_EXT_sRGB_write_control
GL_EXT_tessellation_point_size
GL_EXT_tessellation_shader
GL_EXT_texture_border_clamp
GL_EXT_texture_buffer
GL_EXT_texture_compression_bptc
GL_EXT_texture_compression_dxt1
GL_EXT_texture_compression_rgtc
GL_EXT_texture_compression_s3tc
GL_EXT_texture_cube_map_array
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_filter_minmax
GL_EXT_texture_format_BGRA8888
GL_EXT_texture_mirror_clamp_to_edge
GL_EXT_texture_norm16
GL_EXT_texture_rg
GL_EXT_texture_sRGB_R8
GL_EXT_texture_sRGB_decode
GL_EXT_texture_storage
GL_EXT_texture_view
GL_EXT_draw_transform_feedback
GL_EXT_unpack_subimage
GL_EXT_window_rectangles
GL_KHR_context_flush_control
GL_KHR_debug
GL_EXT_memory_object
GL_EXT_memory_object_win32
GL_EXT_win32_keyed_mutex
GL_KHR_parallel_shader_compile
GL_KHR_no_error
GL_KHR_robust_buffer_access_behavior
GL_KHR_robustness
GL_EXT_semaphore
GL_EXT_semaphore_win32
GL_NV_bgr
GL_NV_bindless_texture
GL_NV_blend_equation_advanced
GL_NV_blend_equation_advanced_coherent
GL_NVX_blend_equation_advanced_multi_draw_buffers
GL_NV_blend_minmax_factor
GL_NV_clip_space_w_scaling
GL_NV_conditional_render
GL_NV_conservative_raster
GL_NV_conservative_raster_pre_snap_triangles
GL_NV_copy_buffer
GL_NV_copy_image
GL_NV_draw_buffers
GL_NV_draw_instanced
GL_NV_draw_texture
GL_NV_draw_vulkan_image
GL_NV_explicit_attrib_location
GL_NV_fbo_color_attachments
GL_NV_fill_rectangle
GL_NV_fragment_coverage_to_color
GL_NV_fragment_shader_interlock
GL_NV_framebuffer_blit
GL_NV_framebuffer_mixed_samples
GL_NV_framebuffer_multisample
GL_NV_generate_mipmap_sRGB
GL_NV_geometry_shader_passthrough
GL_NV_instanced_arrays
GL_NV_internalformat_sample_query
GL_NV_gpu_shader5
GL_NV_image_formats
GL_NV_memory_attachment
GL_NV_occlusion_query_samples
GL_NV_non_square_matrices
GL_NV_pack_subimage
GL_NV_packed_float
GL_NV_packed_float_linear
GL_NV_path_rendering
GL_NV_path_rendering_shared_edge
GL_NV_pixel_buffer_object
GL_NV_polygon_mode
GL_NV_read_buffer
GL_NV_read_depth
GL_NV_read_depth_stencil
GL_NV_read_stencil
GL_NV_sample_locations
GL_NV_sample_mask_override_coverage
GL_NV_shader_atomic_fp16_vector
GL_NV_shader_noperspective_interpolation
GL_NV_shadow_samplers_array
GL_NV_shadow_samplers_cube
GL_NV_sRGB_formats
GL_NV_stereo_view_rendering
GL_NV_texture_array
GL_NV_texture_barrier
GL_NV_texture_border_clamp
GL_NV_texture_compression_latc
GL_NV_texture_compression_s3tc
GL_NV_texture_compression_s3tc_update
GL_NV_timer_query
GL_NV_viewport_array
GL_NV_viewport_array2
GL_NV_viewport_swizzle
GL_KHR_blend_equation_advanced
GL_KHR_blend_equation_advanced_coherent
GL_OES_compressed_ETC1_RGB8_texture
GL_EXT_compressed_ETC1_RGB8_sub_texture
GL_OES_depth24
GL_OES_depth32
GL_OES_depth_texture
GL_OES_depth_texture_cube_map
GL_OES_copy_image
GL_OES_draw_buffers_indexed
GL_OES_draw_elements_base_vertex
GL_OES_texture_border_clamp
GL_OES_tessellation_point_size
GL_OES_tessellation_shader
GL_OES_texture_buffer
GL_OES_geometry_point_size
GL_OES_geometry_shader
GL_OES_gpu_shader5
GL_OES_shader_io_blocks
GL_OES_texture_view
GL_OES_primitive_bounding_box
GL_OES_element_index_uint
GL_OES_fbo_render_mipmap
GL_OES_get_program_binary
GL_OES_mapbuffer
GL_OES_packed_depth_stencil
GL_OES_rgb8_rgba8
GL_OES_sample_shading
GL_OES_sample_variables
GL_OES_shader_image_atomic
GL_OES_shader_multisample_interpolation
GL_OES_standard_derivatives
GL_OES_texture_cube_map_array
GL_OES_texture_npot
GL_OES_texture_float
GL_OES_texture_float_linear
GL_OES_texture_half_float
GL_OES_texture_half_float_linear
GL_OES_texture_stencil8
GL_OES_texture_storage_multisample_2d_array
GL_OES_vertex_array_object
GL_OES_vertex_half_float
GL_OES_viewport_array
GL_OVR_multiview
GL_OVR_multiview2
GL_ANDROID_extension_pack_es31a
```

**Comment by teinarss** [comment]
Looks like it only happens on the map `Tiers of sorrow`

**Comment by pchote** [comment]
Can you please test with #16984 (rebased onto current bleed) to see if it can report more detail?

**Comment by teinarss** [comment]
![image](https://user-images.githubusercontent.com/19173272/64889530-d7188b00-d66d-11e9-8881-acf205416066.png)

**Comment by teinarss** [comment]
```
High - GL Debug API Output: Error - GL_INVALID_OPERATION error generated. Invalid <format> parameter for current read framebuffer.
   at OpenRA.Platforms.Default.OpenGL.DebugMessageHandler(Int32 source, Int32 type, UInt32 id, Int32 severity, Int32 length, StringBuilder message, IntPtr userparam)
   at OpenRA.Platforms.Default.Texture.GetData()
   at OpenRA.Graphics.Sheet.CreateBuffer()
   at OpenRA.Graphics.SequenceProvider.Preload()
   at OpenRA.Map.PostInit()
   at OpenRA.Map..ctor(ModData modData, IReadOnlyPackage package)
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.TickImmediate()
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0()
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn)
   at OpenRA.Sync.RunUnsynced(Boolean checkSyncHash, World world, Action fn)
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.Program.Main(String[] args)


OpenGL Information:
Vendor: NVIDIA Corporation
Renderer: GeForce GTX 1080 Ti/PCIe/SSE2
GL Version: OpenGL ES 3.2 NVIDIA 431.85
Shader Version: OpenGL ES GLSL ES 3.20
Available extensions:
GL_EXT_base_instance
GL_EXT_blend_func_extended
GL_EXT_blend_minmax
GL_EXT_buffer_storage
GL_EXT_clear_texture
GL_EXT_clip_control
GL_EXT_clip_cull_distance
GL_EXT_color_buffer_float
GL_EXT_color_buffer_half_float
GL_EXT_conservative_depth
GL_EXT_copy_image
GL_EXT_debug_label
GL_EXT_discard_framebuffer
GL_EXT_disjoint_timer_query
GL_EXT_draw_buffers_indexed
GL_EXT_draw_elements_base_vertex
GL_EXT_EGL_image_external_wrap_modes
GL_EXT_float_blend
GL_EXT_frag_depth
GL_EXT_geometry_point_size
GL_EXT_geometry_shader
GL_EXT_gpu_shader5
GL_EXT_map_buffer_range
GL_EXT_multi_draw_indirect
GL_EXT_multisample_compatibility
GL_EXT_occlusion_query_boolean
GL_EXT_polygon_offset_clamp
GL_EXT_post_depth_coverage
GL_EXT_primitive_bounding_box
GL_EXT_raster_multisample
GL_EXT_render_snorm
GL_EXT_robustness
GL_EXT_separate_shader_objects
GL_EXT_shader_group_vote
GL_EXT_shader_implicit_conversions
GL_EXT_shader_integer_mix
GL_EXT_shader_io_blocks
GL_EXT_shader_non_constant_global_initializers
GL_EXT_shader_texture_lod
GL_EXT_shadow_samplers
GL_EXT_sparse_texture
GL_EXT_sparse_texture2
GL_EXT_sRGB
GL_EXT_sRGB_write_control
GL_EXT_tessellation_point_size
GL_EXT_tessellation_shader
GL_EXT_texture_border_clamp
GL_EXT_texture_buffer
GL_EXT_texture_compression_bptc
GL_EXT_texture_compression_dxt1
GL_EXT_texture_compression_rgtc
GL_EXT_texture_compression_s3tc
GL_EXT_texture_cube_map_array
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_filter_minmax
GL_EXT_texture_format_BGRA8888
GL_EXT_texture_mirror_clamp_to_edge
GL_EXT_texture_norm16
GL_EXT_texture_rg
GL_EXT_texture_sRGB_R8
GL_EXT_texture_sRGB_decode
GL_EXT_texture_storage
GL_EXT_texture_view
GL_EXT_draw_transform_feedback
GL_EXT_unpack_subimage
GL_EXT_window_rectangles
GL_KHR_context_flush_control
GL_KHR_debug
GL_EXT_memory_object
GL_EXT_memory_object_win32
GL_EXT_win32_keyed_mutex
GL_KHR_parallel_shader_compile
GL_KHR_no_error
GL_KHR_robust_buffer_access_behavior
GL_KHR_robustness
GL_EXT_semaphore
GL_EXT_semaphore_win32
GL_NV_bgr
GL_NV_bindless_texture
GL_NV_blend_equation_advanced
GL_NV_blend_equation_advanced_coherent
GL_NVX_blend_equation_advanced_multi_draw_buffers
GL_NV_blend_minmax_factor
GL_NV_clip_space_w_scaling
GL_NV_conditional_render
GL_NV_conservative_raster
GL_NV_conservative_raster_pre_snap_triangles
GL_NV_copy_buffer
GL_NV_copy_image
GL_NV_draw_buffers
GL_NV_draw_instanced
GL_NV_draw_texture
GL_NV_draw_vulkan_image
GL_NV_explicit_attrib_location
GL_NV_fbo_color_attachments
GL_NV_fill_rectangle
GL_NV_fragment_coverage_to_color
GL_NV_fragment_shader_interlock
GL_NV_framebuffer_blit
GL_NV_framebuffer_mixed_samples
GL_NV_framebuffer_multisample
GL_NV_generate_mipmap_sRGB
GL_NV_geometry_shader_passthrough
GL_NV_instanced_arrays
GL_NV_internalformat_sample_query
GL_NV_gpu_shader5
GL_NV_image_formats
GL_NV_memory_attachment
GL_NV_occlusion_query_samples
GL_NV_non_square_matrices
GL_NV_pack_subimage
GL_NV_packed_float
GL_NV_packed_float_linear
GL_NV_path_rendering
GL_NV_path_rendering_shared_edge
GL_NV_pixel_buffer_object
GL_NV_polygon_mode
GL_NV_read_buffer
GL_NV_read_depth
GL_NV_read_depth_stencil
GL_NV_read_stencil
GL_NV_sample_locations
GL_NV_sample_mask_override_coverage
GL_NV_shader_atomic_fp16_vector
GL_NV_shader_noperspective_interpolation
GL_NV_shadow_samplers_array
GL_NV_shadow_samplers_cube
GL_NV_sRGB_formats
GL_NV_stereo_view_rendering
GL_NV_texture_array
GL_NV_texture_barrier
GL_NV_texture_border_clamp
GL_NV_texture_compression_latc
GL_NV_texture_compression_s3tc
GL_NV_texture_compression_s3tc_update
GL_NV_timer_query
GL_NV_viewport_array
GL_NV_viewport_array2
GL_NV_viewport_swizzle
GL_KHR_blend_equation_advanced
GL_KHR_blend_equation_advanced_coherent
GL_OES_compressed_ETC1_RGB8_texture
GL_EXT_compressed_ETC1_RGB8_sub_texture
GL_OES_depth24
GL_OES_depth32
GL_OES_depth_texture
GL_OES_depth_texture_cube_map
GL_OES_copy_image
GL_OES_draw_buffers_indexed
GL_OES_draw_elements_base_vertex
GL_OES_texture_border_clamp
GL_OES_tessellation_point_size
GL_OES_tessellation_shader
GL_OES_texture_buffer
GL_OES_geometry_point_size
GL_OES_geometry_shader
GL_OES_gpu_shader5
GL_OES_shader_io_blocks
GL_OES_texture_view
GL_OES_primitive_bounding_box
GL_OES_element_index_uint
GL_OES_fbo_render_mipmap
GL_OES_get_program_binary
GL_OES_mapbuffer
GL_OES_packed_depth_stencil
GL_OES_rgb8_rgba8
GL_OES_sample_shading
GL_OES_sample_variables
GL_OES_shader_image_atomic
GL_OES_shader_multisample_interpolation
GL_OES_standard_derivatives
GL_OES_texture_cube_map_array
GL_OES_texture_npot
GL_OES_texture_float
GL_OES_texture_float_linear
GL_OES_texture_half_float
GL_OES_texture_half_float_linear
GL_OES_texture_stencil8
GL_OES_texture_storage_multisample_2d_array
GL_OES_vertex_array_object
GL_OES_vertex_half_float
GL_OES_viewport_array
GL_OVR_multiview
GL_OVR_multiview2
GL_ANDROID_extension_pack_es31a
```

**Comment by pchote** [comment]
Note: this only happens under GLES.

**Comment by teinarss** [comment]
```
Medium - GL Debug API Output: Performance - Pixel-path performance warning: Pixel transfer is synchronized with 3D rendering.
   at OpenRA.Platforms.Default.OpenGL.DebugMessageHandler(Int32 source, Int32 type, UInt32 id, Int32 severity, Int32 length, StringBuilder message, IntPtr userparam)
   at OpenRA.Platforms.Default.Texture.SetData(IntPtr data, Int32 width, Int32 height)
   at OpenRA.Platforms.Default.Texture.SetData(Byte[] colors, Int32 width, Int32 height)
   at OpenRA.Graphics.Sheet.GetTexture()
   at OpenRA.Graphics.Sheet.ReleaseBuffer()
   at OpenRA.Graphics.SequenceProvider.Preload()
   at OpenRA.Map.PostInit()
   at OpenRA.Map..ctor(ModData modData, IReadOnlyPackage package)
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.TickImmediate()
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0()
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn)
   at OpenRA.Sync.RunUnsynced(Boolean checkSyncHash, World world, Action fn)
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.Program.Main(String[] args)


OpenGL Information:
Vendor: NVIDIA Corporation
Renderer: GeForce GTX 1080 Ti/PCIe/SSE2
GL Version: OpenGL ES 3.2 NVIDIA 431.85
Shader Version: OpenGL ES GLSL ES 3.20
Available extensions:
GL_EXT_base_instance
GL_EXT_blend_func_extended
GL_EXT_blend_minmax
GL_EXT_buffer_storage
GL_EXT_clear_texture
GL_EXT_clip_control
GL_EXT_clip_cull_distance
GL_EXT_color_buffer_float
GL_EXT_color_buffer_half_float
GL_EXT_conservative_depth
GL_EXT_copy_image
GL_EXT_debug_label
GL_EXT_discard_framebuffer
GL_EXT_disjoint_timer_query
GL_EXT_draw_buffers_indexed
GL_EXT_draw_elements_base_vertex
GL_EXT_EGL_image_external_wrap_modes
GL_EXT_float_blend
GL_EXT_frag_depth
GL_EXT_geometry_point_size
GL_EXT_geometry_shader
GL_EXT_gpu_shader5
GL_EXT_map_buffer_range
GL_EXT_multi_draw_indirect
GL_EXT_multisample_compatibility
GL_EXT_occlusion_query_boolean
GL_EXT_polygon_offset_clamp
GL_EXT_post_depth_coverage
GL_EXT_primitive_bounding_box
GL_EXT_raster_multisample
GL_EXT_render_snorm
GL_EXT_robustness
GL_EXT_separate_shader_objects
GL_EXT_shader_group_vote
GL_EXT_shader_implicit_conversions
GL_EXT_shader_integer_mix
GL_EXT_shader_io_blocks
GL_EXT_shader_non_constant_global_initializers
GL_EXT_shader_texture_lod
GL_EXT_shadow_samplers
GL_EXT_sparse_texture
GL_EXT_sparse_texture2
GL_EXT_sRGB
GL_EXT_sRGB_write_control
GL_EXT_tessellation_point_size
GL_EXT_tessellation_shader
GL_EXT_texture_border_clamp
GL_EXT_texture_buffer
GL_EXT_texture_compression_bptc
GL_EXT_texture_compression_dxt1
GL_EXT_texture_compression_rgtc
GL_EXT_texture_compression_s3tc
GL_EXT_texture_cube_map_array
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_filter_minmax
GL_EXT_texture_format_BGRA8888
GL_EXT_texture_mirror_clamp_to_edge
GL_EXT_texture_norm16
GL_EXT_texture_rg
GL_EXT_texture_sRGB_R8
GL_EXT_texture_sRGB_decode
GL_EXT_texture_storage
GL_EXT_texture_view
GL_EXT_draw_transform_feedback
GL_EXT_unpack_subimage
GL_EXT_window_rectangles
GL_KHR_context_flush_control
GL_KHR_debug
GL_EXT_memory_object
GL_EXT_memory_object_win32
GL_EXT_win32_keyed_mutex
GL_KHR_parallel_shader_compile
GL_KHR_no_error
GL_KHR_robust_buffer_access_behavior
GL_KHR_robustness
GL_EXT_semaphore
GL_EXT_semaphore_win32
GL_NV_bgr
GL_NV_bindless_texture
GL_NV_blend_equation_advanced
GL_NV_blend_equation_advanced_coherent
GL_NVX_blend_equation_advanced_multi_draw_buffers
GL_NV_blend_minmax_factor
GL_NV_clip_space_w_scaling
GL_NV_conditional_render
GL_NV_conservative_raster
GL_NV_conservative_raster_pre_snap_triangles
GL_NV_copy_buffer
GL_NV_copy_image
GL_NV_draw_buffers
GL_NV_draw_instanced
GL_NV_draw_texture
GL_NV_draw_vulkan_image
GL_NV_explicit_attrib_location
GL_NV_fbo_color_attachments
GL_NV_fill_rectangle
GL_NV_fragment_coverage_to_color
GL_NV_fragment_shader_interlock
GL_NV_framebuffer_blit
GL_NV_framebuffer_mixed_samples
GL_NV_framebuffer_multisample
GL_NV_generate_mipmap_sRGB
GL_NV_geometry_shader_passthrough
GL_NV_instanced_arrays
GL_NV_internalformat_sample_query
GL_NV_gpu_shader5
GL_NV_image_formats
GL_NV_memory_attachment
GL_NV_occlusion_query_samples
GL_NV_non_square_matrices
GL_NV_pack_subimage
GL_NV_packed_float
GL_NV_packed_float_linear
GL_NV_path_rendering
GL_NV_path_rendering_shared_edge
GL_NV_pixel_buffer_object
GL_NV_polygon_mode
GL_NV_read_buffer
GL_NV_read_depth
GL_NV_read_depth_stencil
GL_NV_read_stencil
GL_NV_sample_locations
GL_NV_sample_mask_override_coverage
GL_NV_shader_atomic_fp16_vector
GL_NV_shader_noperspective_interpolation
GL_NV_shadow_samplers_array
GL_NV_shadow_samplers_cube
GL_NV_sRGB_formats
GL_NV_stereo_view_rendering
GL_NV_texture_array
GL_NV_texture_barrier
GL_NV_texture_border_clamp
GL_NV_texture_compression_latc
GL_NV_texture_compression_s3tc
GL_NV_texture_compression_s3tc_update
GL_NV_timer_query
GL_NV_viewport_array
GL_NV_viewport_array2
GL_NV_viewport_swizzle
GL_KHR_blend_equation_advanced
GL_KHR_blend_equation_advanced_coherent
GL_OES_compressed_ETC1_RGB8_texture
GL_EXT_compressed_ETC1_RGB8_sub_texture
GL_OES_depth24
GL_OES_depth32
GL_OES_depth_texture
GL_OES_depth_texture_cube_map
GL_OES_copy_image
GL_OES_draw_buffers_indexed
GL_OES_draw_elements_base_vertex
GL_OES_texture_border_clamp
GL_OES_tessellation_point_size
GL_OES_tessellation_shader
GL_OES_texture_buffer
GL_OES_geometry_point_size
GL_OES_geometry_shader
GL_OES_gpu_shader5
GL_OES_shader_io_blocks
GL_OES_texture_view
GL_OES_primitive_bounding_box
GL_OES_element_index_uint
GL_OES_fbo_render_mipmap
GL_OES_get_program_binary
GL_OES_mapbuffer
GL_OES_packed_depth_stencil
GL_OES_rgb8_rgba8
GL_OES_sample_shading
GL_OES_sample_variables
GL_OES_shader_image_atomic
GL_OES_shader_multisample_interpolation
GL_OES_standard_derivatives
GL_OES_texture_cube_map_array
GL_OES_texture_npot
GL_OES_texture_float
GL_OES_texture_float_linear
GL_OES_texture_half_float
GL_OES_texture_half_float_linear
GL_OES_texture_stencil8
GL_OES_texture_storage_multisample_2d_array
GL_OES_vertex_array_object
GL_OES_vertex_half_float
GL_OES_viewport_array
GL_OVR_multiview
GL_OVR_multiview2
GL_ANDROID_extension_pack_es31a
```

**Comment by pchote** [comment]
The issue here seems to be that the nvidia implementation of `GL_EXT_texture_format_BGRA8888` doesn't support `GL_BGRA` formats for `glReadPixels` under GLES.

The cleanest fix is probably going to be reworking our texture code to use RGBA textures under GLES and remove our requirement on `GL_EXT_texture_format_BGRA8888` there.

**Comment by dragunoff** [comment]
I get the same `GL_INVALID_OPERATION error generated. Invalid <format> parameter for current read framebuffer.` on Windows 7. Funny it only happens when starting a game on particular tilesets (RA: desert, TD: desert, TS: temperat and the default D2k).

Here is `graphics.log`:
```
High - GL Debug API Output: Error - GL_INVALID_OPERATION error generated. Invalid <format> parameter for current read framebuffer.
   at OpenRA.Platforms.Default.OpenGL.BuildErrorText(Int32 source, Int32 type, Int32 severity, StringBuilder message)
   at OpenRA.Platforms.Default.OpenGL.DebugMessageHandler(Int32 source, Int32 type, UInt32 id, Int32 severity, Int32 length, StringBuilder message, IntPtr userparam)
   at OpenRA.Platforms.Default.Texture.GetData()
   at OpenRA.Graphics.Sheet.CreateBuffer()
   at OpenRA.Graphics.SequenceProvider.Preload()
   at OpenRA.Map.PostInit()
   at OpenRA.Map..ctor(ModData modData, IReadOnlyPackage package)
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.TickImmediate()
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.Program.Main(String[] args)


OpenGL Information:
Vendor: NVIDIA Corporation
Renderer: GeForce GTX 650/PCIe/SSE2
GL Version: OpenGL ES 3.0 335.23
Shader Version: OpenGL ES GLSL ES 3.00
Available extensions:
GL_EXT_blend_minmax
GL_EXT_color_buffer_float
GL_EXT_color_buffer_half_float
GL_EXT_debug_label
GL_EXT_frag_depth
GL_EXT_map_buffer_range
GL_EXT_occlusion_query_boolean
GL_EXT_robustness
GL_EXT_separate_shader_objects
GL_EXT_shader_integer_mix
GL_EXT_shadow_samplers
GL_EXT_sRGB
GL_EXT_texture_compression_dxt1
GL_EXT_texture_compression_s3tc
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_format_BGRA8888
GL_EXT_texture_sRGB_decode
GL_EXT_texture_storage
GL_EXT_unpack_subimage
GL_KHR_debug
GL_NV_bgr
GL_NV_bindless_texture
GL_NV_blend_equation_advanced
GL_NV_copy_buffer
GL_NV_copy_image
GL_NV_draw_buffers
```

**Comment by dragunoff** [comment]
I'm getting the same crash when leaving a single player game on any of the mods.

**Comment by dragunoff** [comment]
The crash is no longer occurring on bleed for me.

**Comment by pchote** [comment]
According to https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glReadPixels.xhtml only `GL_RGBA` and `GL_RGBA_INTEGER` are supported by `glReadPixels`. 

https://github.com/OpenRA/OpenRA/blob/2094142b7d4bac9d87ea895555a69bed4fd17efd/OpenRA.Platforms.Default/Texture.cs#L141

passes `GL_BGRA`, so the `GL_INVALID_OPERATION` is indeed expected and correct.

@teinarss can you please report back with what happens if you change `OpenGL.GL_BGRA` to `0x1908` on that line? Its not clear to me whether this will return actual RGBA data (which we will then have to byte-swap), or whether this is just specifying that we want all four channels, which are returned in BGRA format (maybe @chrisforbes can comment?).

**Comment by teinarss** [comment]
> 
> 
> According to https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glReadPixels.xhtml only `GL_RGBA` and `GL_RGBA_INTEGER` are supported by `glReadPixels`.
> 
> https://github.com/OpenRA/OpenRA/blob/2094142b7d4bac9d87ea895555a69bed4fd17efd/OpenRA.Platforms.Default/Texture.cs#L141
> 
> passes `GL_BGRA`, so the `GL_INVALID_OPERATION` is indeed expected and correct.
> 
> @teinarss can you please report back with what happens if you change `OpenGL.GL_BGRA` to `0x1908` on that line? Its not clear to me whether this will return actual RGBA data (which we will then have to byte-swap), or whether this is just specifying that we want all four channels, which are returned in BGRA format (maybe @chrisforbes can comment?).


Getting this with that change.
```
Medium - GL Debug API Output: Performance - Pixel-path performance warning: Pixel transfer is synchronized with 3D rendering.
   at OpenRA.Platforms.Default.OpenGL.BuildErrorText(Int32 source, Int32 type, Int32 severity, StringBuilder message)
   at OpenRA.Platforms.Default.OpenGL.DebugMessageHandler(Int32 source, Int32 type, UInt32 id, Int32 severity, Int32 length, StringBuilder message, IntPtr userparam)
   at OpenRA.Platforms.Default.Texture.SetData(IntPtr data, Int32 width, Int32 height)
   at OpenRA.Platforms.Default.Texture.SetData(Byte[] colors, Int32 width, Int32 height)
   at OpenRA.Graphics.Sheet.GetTexture()
   at OpenRA.Graphics.Sheet.ReleaseBuffer()
   at OpenRA.Graphics.SequenceProvider.Preload()
   at OpenRA.Map.PostInit()
   at OpenRA.Map..ctor(ModData modData, IReadOnlyPackage package)
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Game.LoadShellMap()
   at OpenRA.Mods.Common.Widgets.Logic.IngameMenuLogic.<OnQuit>b__15_1()
   at OpenRA.Primitives.ActionQueue.PerformActions(Int64 currentTime)
   at OpenRA.Game.PerformDelayedActions()
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by pchote** [comment]
Is that a crash, or just a warning and everything looks correct? Medium isn't supposed to throw.

**Comment by teinarss** [comment]
> 
> 
> Is that a crash, or just a warning and everything looks correct? Medium isn't supposed to throw.

Just a warning in the console.

**Comment by pchote** [comment]
https://stackoverflow.com/questions/49368575/pixel-path-performance-warning-pixel-transfer-is-synchronized-with-3d-rendering suggests that this is expected:

> This performance warning is nividia-specific and it is intended as a hint to tell you that you're not going to use a separate hw transfer queue, which is no wonder since you use a single thread, single GL context model, where both rendering (at least your your blit) and transfer are carried out.

We are also using a single thread, single GL context.

**Comment by pchote** [comment]
I tested this a bit further on my raspberry pi:
* The Linux Mesa drivers implement [EXT_read_format_bgra](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_read_format_bgra.txt), which is why BGRA works there, and why we didn't catch the bug during initial testing. It seems that the nvidia driver does not.
* Switching to `GL_RGBA` does indeed reverse the colour channels, so we need to manually swizzle the data before returning.
* We are reading back data because of the CreateBuffer calls in https://github.com/OpenRA/OpenRA/blob/23b3c237b7071fd308c4664b0b6c5d719c0f3c74/OpenRA.Game/Graphics/SequenceProvider.cs#L131-L137 It has been a long time since i've last thought about this code, but i'm pretty sure we shouldn't need to read back and then recommit the sheet data if we haven't changed anything in the sequences.

So the simplest fix here will be to add a feature flag for EXT_read_format_bgra and if it isn't set fall back to `GL_RGBA` and manual swizzling.
