### ISSUE TITLE
Transport helicopter causing game crash

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#17142]
Order infantry to enter an airborne transport helicopter. As soon as the helicopter begins its descent, destroy it.
```
OpenRA engine version playtest-20190825
Red Alert mod version playtest-20190825
on map d23832a3d8cd1d05a3b7a66155e3207e609c64b0 (Barracuda by PizzaAtomica).
Date: 2019-09-23 17:58:26Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (tran 161 (not in world))
   at OpenRA.TraitDictionary.CheckDestroyed(Actor actor)
   at OpenRA.TraitDictionary.Get[T](Actor actor)
   at OpenRA.Mods.Common.Activities.TakeOff..ctor(Actor self)
   at OpenRA.Mods.Common.Traits.Cargo.ReleaseLock(Actor self)
   at OpenRA.Mods.Common.Traits.Cargo.UnreserveSpace(Actor a)
   at OpenRA.Mods.Common.Traits.Passenger.Unreserve(Actor self)
   at OpenRA.Mods.Common.Activities.RideTransport.Cancel(Actor self, Boolean keepQueue)
   at OpenRA.Mods.Common.Activities.Enter.Tick(Actor self)
   at OpenRA.Activities.Activity.TickOuter(Actor self)
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act)
   at OpenRA.Actor.Tick()
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)
```

**Comment by fruestueck** [comment]
nice catch!
Tested transporter landing for offload and TS carryall without a crash.
