### ISSUE TITLE
Cluster Warhead crashes when weapons have Projectile: LaserZap

### ISSUE THREAD

**Issue by Inq8** [OpenRA/OpenRA#17301]
`OpenRA engine version playtest-20191021
Combined Arms mod version playtest-20191021
on map 1abdcd434ea808788d28a7d3d84bb7e34e3b34fa (Snowy Island by Westwood Studios).
Date: 2019-11-01 23:01:13Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Graphics.Animation.get_Image()
   at OpenRA.Graphics.Animation.Render(WPos pos, WVec offset, Int32 zOffset, PaletteReference palette, Single scale)
   at OpenRA.Graphics.Animation.Render(WPos pos, PaletteReference palette)
   at OpenRA.Mods.Common.Projectiles.LaserZap.<Render>d__13.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OpenRA.Graphics.WorldRenderer.GenerateRenderables()
   at OpenRA.Graphics.WorldRenderer.Draw()
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.Program.Main(String[] args)`

This is probably not a "real" bug as ClusterWarhead is intended to work with Bullet projectiles for cluster bombs (Which works as intended)

However it would be a nice additional feature if it could randomly burst lasers to replicate RA2 Prism Tank weapon behaviour.

**Comment by GraionDilach** [comment]
1) Cluster lacks Prism tank functionality with spawned weapons targeting exact units and not cells.

2) This looks like a modder error with `LaserZap`-> `HitAnim(Sequence)` having a typo.

**Comment by Inq8** [comment]
Having done further testing, Cluster Warhead does actually support LaserZap, however if you assign a HitAnim it will crash.

**Comment by GraionDilach** [comment]
TBH, since you're using `FireClusterWarhead` anyway, you can use `CreateEffectWarhead`.

`HitAnim`'s only benefit is that it moves along with the target unit but since FCW targets positions, it can't move anyway, so no degradation of result.

**Comment by Inq8** [comment]
Yep, that’s a good workaround, thanks.
 🙏 

> Also offtopic, but you should set up that the fire animations end up chained (fire4->fire3->fire2->fire1) so that the flames disappear less abruptly. RA/TS did this.

Yeah I was trying to replicate the original behaviour. I’ll need to have a closer look. I didn’t think it was chained with all 4 in a row. 

Maybe a mix of:
Big (bright) > Big (dull)
&
Small (bright) > small (dull)
Randomised.

I may be wrong.

**Comment by GraionDilach** [comment]
https://github.com/LipkeGu/TSIniFiles/blob/master/art.ini#L3660-L3697

Apparently fire4 wasn't linked to 3 in TS and this only worked for 1-2-3.
