### ISSUE TITLE
Demo truck + heli over service depot causes game crash

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#17341]
-Build a service depot.
-Position a heli over the center of the service depot.
-Detonate a demo truck next to the service depot.

```
OpenRA engine version playtest-20191102
Exception of type `System.InvalidOperationException`: Collection was modified after the enumerator was instantiated.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.SortedSet`1.Enumerator.MoveNext()
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)
```

**Comment by pchote** [comment]
I can't reproduce this using the given steps.

The submitter deleted their account immediately after posting the issue, so I don't hold any hope for an answer but: What OS are you using, and were you using the official installers or a self-compiled build? If self compiled and not Windows, what version of Mono are you using?

**Comment by pchote** [comment]
Interesting, crash confirmed when running the packaged macOS build but not when building from source.

**Comment by pchote** [comment]
Regression from #17287, which accidentally moved actor spawning outside of the `FrameEndTask`.

The service depot is a red herring, and this is only sporadically reproducible because of the random chance of spawning the pilot.
