### ISSUE TITLE
Content Manager crashes on load with missing sprite loader

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#17444]
Trying to open the mod Content Manager results in the following crash on `bleed`:
```
Loading mod: modcontent
Exception of type `System.InvalidOperationException`:
Unable to find a sprite loader for type 'ShpTD'.
   at OpenRA.ObjectCreator.GetLoaders[TLoader](IEnumerable`1 formats, String name)
   at OpenRA.ModData..ctor(Manifest mod, InstalledMods mods, Boolean useLoadScreen)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Mods.Common.Widgets.Logic.MainMenuLogic.<>c__DisplayClass13_0.<.ctor>b__24()
   at OpenRA.Primitives.ActionQueue.PerformActions(Int64 currentTime)
   at OpenRA.Game.PerformDelayedActions()
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by pchote** [comment]
Probably a regression from #17410.
