### ISSUE TITLE
Sequence contains no elements in RallyPointIndicator

### ISSUE THREAD

**Issue by teinarss** [OpenRA/OpenRA#17492]
D2K at `dbe73a06ad8dcedf0d21a266a60dbac104b88fa0`

```
System.InvalidOperationException: 'Sequence contains no elements'
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at OpenRA.Mods.Common.Effects.RallyPointIndicator.OpenRA.Effects.IEffectAboveShroud.RenderAboveShroud(WorldRenderer wr) in C:\projects\OpenRa1\OpenRA.Mods.Common\Effects\RallyPointIndicator.cs:line 102
   at OpenRA.Graphics.WorldRenderer.<GenerateOverlayRenderables>b__30_6(IEffectAboveShroud e) in C:\projects\OpenRa1\OpenRA.Game\Graphics\WorldRenderer.cs:line 145
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at OpenRA.Graphics.WorldRenderer.PrepareRenderables() in C:\projects\OpenRa1\OpenRA.Game\Graphics\WorldRenderer.cs:line 194
   at OpenRA.Game.RenderTick() in C:\projects\OpenRa1\OpenRA.Game\Game.cs:line 678
   at OpenRA.Game.Loop() in C:\projects\OpenRa1\OpenRA.Game\Game.cs:line 833
   at OpenRA.Game.Run() in C:\projects\OpenRa1\OpenRA.Game\Game.cs:line 851
   at OpenRA.Game.InitializeAndRun(String[] args) in C:\projects\OpenRa1\OpenRA.Game\Game.cs:line 262
   at OpenRA.Program.Main(String[] args) in C:\projects\OpenRa1\OpenRA.Game\Support\Program.cs:line 31
```

**Comment by teinarss** [comment]
Duplicate of #17461
