### ISSUE TITLE
Crash when Unit Explodes and has DamageSource: Killer

### ISSUE THREAD

**Issue by Inq8** [OpenRA/OpenRA#17644]
Tested on bleed

Bit of a niche bug/crash but if you hit a unit that explodes that has damage source set to Killer with a weapon with a FireCluster warhead, such as the deathhand missile the game crashes with:

```
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Actor.get_CenterPosition()
   at OpenRA.GameRules.WeaponInfo.Impact(Target target, Actor firedBy)
   at OpenRA.Mods.Common.Traits.Explodes.OpenRA.Mods.Common.Traits.INotifyKilled.Killed(Actor self, AttackInfo e)
   at OpenRA.Mods.Common.Traits.Health.InflictDamage(Actor self, Actor attacker, Damage damage, Boolean ignoreModifiers)
   at OpenRA.Actor.InflictDamage(Actor attacker, Damage damage)
   at OpenRA.Mods.Common.Warheads.DamageWarhead.InflictDamage(Actor victim, Actor firedBy, HitShapeInfo hitshapeInfo, IEnumerable`1 damageModifiers)
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.Mods.Common.Warheads.DamageWarhead.DoImpact(Target target, WarheadArgs args)
   at OpenRA.Effects.DelayedImpact.<Tick>b__5_0(World w)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.Program.Main(String[] args)
```

To reproduce you need to add DamageSource: Killer to Explodes on grenadiers in D2k & shoot a deathhand missile at them. It may or may not require you to hit a building at the same time.

**Comment by pchote** [comment]
See also #17628.
