### ISSUE TITLE
Game encounters a fatal error at launch

### ISSUE THREAD

**Issue by IntelligentShitposter** [OpenRA/OpenRA#17707]
Open RA on windows ten
OpenRA engine version release-20200202
Mod Content Manager mod version release-20200202
Date: 2020-02-22 03:32:32Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at OpenRA.Graphics.ChromeProvider.Initialize(ModData modData)
   at OpenRA.ModData.InitializeLoaders(IReadOnlyFileSystem fileSystem)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.BeforeLoad()
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)

**Comment by abcdefg30** [comment]
Does this still happen on the latest playtest version?

**Comment by IntelligentShitposter** [comment]
Yes it still happens on the latest version

**Comment by pchote** [comment]
Did you install OpenRA using the installer from https://www.openra.net/download/, or some different method/build?

**Comment by IntelligentShitposter** [comment]
I used the installer from https://www.openra.net/download/

**Comment by abcdefg30** [comment]
Closing due to inactivity.
