### ISSUE TITLE
My game crashed during minor battle; One time event.

### ISSUE THREAD

**Issue by ElMoonLite** [OpenRA/OpenRA#18056]
## System Information

- Operating System:  Windows 10
- OpenRA Version: 20200503
- OpenRA Mod: Tiberium Dawn
- Source: Official download package
- For self-compiled or third-party packages: Mono version

## Exception log

```
OpenRA engine version release-20200503
Tiberian Dawn mod version release-20200503
on map 8a31e50d90e3a472f9ca951b482c9d5d74a65e4f (C&C64 Special Ops - GDI 1 by Westwood Studios).
Date: 2020-05-08 15:11:31Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `Eluant.LuaException`: [string "BindingSupport.lua"]:30: Unable to convert parameter 0 to Actor
   at Eluant.LuaRuntime.Call(IList`1 args)
   at Eluant.LuaRuntime.Call(LuaFunction fn, IList`1 args)
   at Eluant.LuaFunction.Call(IList`1 args)
   at OpenRA.Mods.Common.Scripting.ProductionQueueProperties.<>c__DisplayClass3_2.<Build>b__4(Actor factory, Actor unit)
   at System.Action`2.Invoke(T1 arg1, T2 arg2)
   at OpenRA.Mods.Common.Scripting.ScriptTriggers.OpenRA.Mods.Common.Traits.INotifyProduction.UnitProduced(Actor self, Actor other, CPos exit)
   at OpenRA.Mods.Common.Traits.Production.<>c__DisplayClass6_0.<DoProduction>b__0(World w)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)

```

## Additional information

My game crashed; think it was a one time fluke though. Just posting this in case the new data helps solve an existing issue :)
I think I was right clicking on an enemy harvester that just died (already husk? or just before that appeared? or exactly that moment?) while I had some rocket troopers selected. 
During a casual single player mission. Happens again if I play the replay (after about 6minutes gameplay).
I have some tweaks to rules, but I have a feeling they are not relevant this time if I check the exception and trace. 

[OpenRA-2020-05-08T145056Z.zip](https://github.com/OpenRA/OpenRA/files/4599964/OpenRA-2020-05-08T145056Z.zip)

**Comment by georgeabr** [comment]
The same map crashed for me,  see below:
[Logs.zip](https://github.com/OpenRA/OpenRA/files/4659417/Logs.zip)

```
OpenRA engine version release-20200503
Tiberian Dawn mod version release-20200503
on map 8a31e50d90e3a472f9ca951b482c9d5d74a65e4f (C&C64 Special Ops - GDI 1 by Westwood Studios).
Date: 2020-05-20 21:26:26Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `Eluant.LuaException`: [string "BindingSupport.lua"]:30: Unable to convert parameter 0 to Actor
   at Eluant.LuaRuntime.Call(IList`1 args)
   at Eluant.LuaRuntime.Call(LuaFunction fn, IList`1 args)
   at Eluant.LuaFunction.Call(IList`1 args)
   at OpenRA.Mods.Common.Scripting.ProductionQueueProperties.<>c__DisplayClass3_2.<Build>b__4(Actor factory, Actor unit)
   at System.Action`2.Invoke(T1 arg1, T2 arg2)
   at OpenRA.Mods.Common.Scripting.ScriptTriggers.OpenRA.Mods.Common.Traits.INotifyProduction.UnitProduced(Actor self, Actor other, CPos exit)
   at OpenRA.Mods.Common.Traits.Production.<>c__DisplayClass6_0.<DoProduction>b__0(World w)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.WindowsLauncher.RunGame(String[] args)
```
