### ISSUE TITLE
Three Crashes about 5-10(?) minutes into game

### ISSUE THREAD

**Issue by NaokiP** [OpenRA/OpenRA#18085]
## System Information
- Operating System:  Windows 10
- OpenRA Version: release-20200503
- OpenRA Mod: Red Alert
- Source: Official download package
- Ryzen 5 2600

## Exception log
Hope it's fine that I drop the three log files?

 

```

[exception-2020-05-12T060148Z.log](https://github.com/OpenRA/OpenRA/files/4613767/exception-2020-05-12T060148Z.log)
[exception-2020-05-12T041408Z.log](https://github.com/OpenRA/OpenRA/files/4613768/exception-2020-05-12T041408Z.log)
[exception-2020-05-12T050442Z.log](https://github.com/OpenRA/OpenRA/files/4613769/exception-2020-05-12T050442Z.log)

```

Edit:
```
OpenRA engine version release-20200503
Red Alert mod version release-20200503
on map 4475604e2a5fd66aca028e92072a7248093cf7e4 (Icy Ridge by PizzaAtomica).
Date: 2020-05-12 05:04:42Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
   at OpenRA.Sound.LoadSound[T](String filename, Func`2 loadFormat)
   at OpenRA.Exts.GetOrAdd[K,V](Dictionary`2 d, K k, Func`2 createFn)
   at OpenRA.Sound.Play(SoundType type, Player player, String name, Boolean headRelative, WPos pos, Single volumeModifier, Boolean loop)
   at OpenRA.Mods.Common.Traits.Armament.<>c__DisplayClass35_0.<FireBarrel>b__2()
   at OpenRA.Mods.Common.Traits.Armament.ScheduleDelayedAction(Int32 t, Action a)
   at OpenRA.Mods.Common.Traits.Armament.FireBarrel(Actor self, IFacing facing, Target target, Barrel barrel)
   at OpenRA.Mods.Common.Traits.Armament.CheckFire(Actor self, IFacing facing, Target target)
   at OpenRA.Mods.Common.Activities.Attack.DoAttack(Actor self, AttackFrontal attack, IEnumerable`1 armaments)
   at OpenRA.Mods.Common.Activities.Attack.TickAttack(Actor self, AttackFrontal attack)
   at OpenRA.Mods.Common.Activities.Attack.Tick(Actor self)
   at OpenRA.Activities.Activity.TickOuter(Actor self)
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act)
   at OpenRA.Actor.Tick()
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)
```

## Replay
Three replays, I am first Orange, then Green x2
[release-20200503.zip](https://github.com/OpenRA/OpenRA/files/4613743/release-20200503.zip)

## Additional information
The first two times it seemed to crash just as Allied Artillery shots were hitting targets, but I don't actually know. The third time I didn't notice anything in particular that could have done it. played one game between game 2 and 3 that did not crash. Replays also crash.

**Comment by abcdefg30** [comment]
This appears to be the same crash as #12420. From https://github.com/OpenRA/OpenRA/issues/12420#issuecomment-262778529:
> `fixit1.aud` comes from the aftermath expansion disk. The aftermath iso from [CNCNZ](http://www.cncnz.com/features/freeware-classic-command-conquer-games/) is corrupted, so if you used that version it would explain this.

Did you install the game content from the CNCNZ iso by any chance?

Anyway, to fix this you'll have to go into the support directory ("%APPDATA%/OpenRA/Content" -  where you found the logs, but this time in the "Content" folder) and delete the RA content. And afterwards install it again from somewhere else (download for example).

Final note: We appear to check a checksum for downloaded content, but not for installing from a disc? Maybe we should consider doing it there as well.

**Comment by NaokiP** [comment]
I see, so it was the Mechanic. I don't remember where the install was from because I did it over a year ago and primarily for d2k, didn't play RA in the meanwhile. Redownloaded from built-in freeware mirror and it seems to be fine now. Replays also simply hang instead of crashing since I technically left the game at that point. Thank you.

**Comment by abcdefg30** [comment]
Glad to hear you could resolve the issue. I suppose this can be closed then.
I opened #18094 so we can keep track of adding checks to prevent issues like this.
