### ISSUE TITLE
Attempting to revoke condition with invalid token during engineer capture

### ISSUE THREAD

**Issue by Smittytron** [OpenRA/OpenRA#18176]
Got this crash after moving this mission from release to bleed. I believe it doesn't like that I gave the engineers a tag with GetActors(), then attempted to capture a building.

Here's the script I am running and exception log:
https://gist.github.com/Smittytron/e7ef59d740681dc7cb7e75c595eb52f8

> Exception of type `System.InvalidOperationException`: Attempting to revoke condition with invalid token 3 for e6 225.
>    at OpenRA.Actor.RevokeCondition(Int32 token) in C:\Users\Smitty\OpenRA\OpenRA.Game\Actor.cs:line 556
>    at OpenRA.Mods.Common.Traits.CaptureManager.CancelCapture(Actor self, Actor target, CaptureManager targetManager) in C:\Users\Smitty\OpenRA\OpenRA.Mods.Common\Traits\CaptureManager.cs:line 264
>    at OpenRA.Mods.Common.Activities.CaptureActor.OnActorDispose(Actor self) in C:\Users\Smitty\OpenRA\OpenRA.Mods.Common\Activities\CaptureActor.cs:line 137
>    at OpenRA.Actor.Dispose() in C:\Users\Smitty\OpenRA\OpenRA.Game\Actor.cs:line 380
>    at OpenRA.Mods.Common.Activities.CaptureActor.<>c__DisplayClass6_0.<DoCapture>b__0(World w) in C:\Users\Smitty\OpenRA\OpenRA.Mods.Common\Activities\CaptureActor.cs:line 124
>    at OpenRA.World.Tick() in C:\Users\Smitty\OpenRA\OpenRA.Game\World.cs:line 469
>    at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in C:\Users\Smitty\OpenRA\OpenRA.Game\Game.cs:line 604
>    at OpenRA.Game.LogicTick() in C:\Users\Smitty\OpenRA\OpenRA.Game\Game.cs:line 630
>    at OpenRA.Game.Loop() in C:\Users\Smitty\OpenRA\OpenRA.Game\Game.cs:line 796
>    at OpenRA.Game.Run() in C:\Users\Smitty\OpenRA\OpenRA.Game\Game.cs:line 834
>    at OpenRA.Game.InitializeAndRun(String[] args) in C:\Users\Smitty\OpenRA\OpenRA.Game\Game.cs:line 260
>    at OpenRA.Program.Main(String[] args) in C:\Users\Smitty\OpenRA\OpenRA.Game\Support\Program.cs:line 33

**Comment by Smittytron** [comment]
Got the same crash when "capturing" the truck in the shipped mission, Infiltration.

> Exception of type `System.InvalidOperationException`: Attempting to revoke condition with invalid token 1 for spy.strong 587.
