### ISSUE TITLE
My game crashed when opening Medieval Warfare

### ISSUE THREAD

**Issue by imasyour** [OpenRA/OpenRA#18172]
OpenRA engine version release-20180307
Date: 2020-05-23 04:24:59Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000

## exception-2020-05-23T042459Z.log

```
Exception of type `System.InvalidOperationException`: Unknown or invalid mod 'modcontent'.
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.BeforeLoad()
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)
```

**Comment by abcdefg30** [comment]
This is an issue within the Medieval Warfare mod, not the engine. From the error I'd guess it is referencing `modcontent` from it's `mod.yaml` while that doesn't exist. The mod is currently abandoned afaik, but you might get some help if you raise that issue on their Discord or repository.
