### ISSUE TITLE
System.InvalidOperationException: OpenGL Error: See graphics.log for details.

### ISSUE THREAD

**Issue by mikeik** [OpenRA/OpenRA#18208]
Platform: W10
Opened openra, created a multiplayer lobby. Was configuring options when the game suddenly crashed. 

Exception.log:
OpenRA engine version release-20200503
Red Alert mod version release-20200503
Date: 2020-05-30 14:40:12Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: OpenGL Error: See graphics.log for details.
   at OpenRA.Platforms.Default.OpenGL.DebugMessageHandler(Int32 source, Int32 type, UInt32 id, Int32 severity, Int32 length, StringBuilder message, IntPtr userparam)
   at OpenRA.Platforms.Default.VertexBuffer`1.SetData(T[] data, Int32 start, Int32 length)
   at OpenRA.Graphics.SpriteRenderer.Flush()
   at OpenRA.Renderer.DisableScissor()
   at OpenRA.Mods.Common.Widgets.ScrollPanelWidget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)

[exception-2020-05-30T144012Z.log](https://github.com/OpenRA/OpenRA/files/4705888/exception-2020-05-30T144012Z.log)
[debug.log](https://github.com/OpenRA/OpenRA/files/4705889/debug.log)

Note: the graphics.log file that's suggested in the exception is empty. 

Have played games before & since that have been fine. This was 1-time.

**Comment by abcdefg30** [comment]
Closing due to inactivity.
