### ISSUE TITLE
double free or corruption

### ISSUE THREAD

**Issue by xiangzhai** [OpenRA/OpenRA#18258]
Hi,

## System Information

- Operating System:  Ubuntu 18.04.4 LTS
- OpenRA Version: git-31a965b29
- OpenRA Mod: ra
- Source: self-compiled
- For self-compiled or third-party packages: Mono version

```
Mono JIT compiler version 6.13.0 (master/ba14e694745)
Copyright (C) Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

## Exception log

```
$ gdb -ex=r --args mono OpenRA.Game.exe Engine.LaunchPath=/disk/zhaixiang/OpenRA/launch-game.sh Game.Mod=ra

Starting program: /usr/bin/mono OpenRA.Game.exe Engine.LaunchPath=/disk/zhaixiang/OpenRA/launch-game.sh Game.Mod=ra

Platform is Linux
Engine version is git-31a965b29
double free or corruption (!prev)

Thread 1 "mono" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6c26801 in __GI_abort () at abort.c:79
#2  0x00007ffff6c6f897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff6d9cb9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff6c7690a in malloc_printerr (str=str@entry=0x7ffff6d9e890 "double free or corruption (!prev)") at malloc.c:5350
#4  0x00007ffff6c7de84 in _int_free (have_lock=0, p=0x555555c2a920, av=0x7ffff6fd1c40 <main_arena>) at malloc.c:4281
#5  __GI___libc_free (mem=0x555555c2a930) at malloc.c:3124
#6  0x00007fffe80c0719 in ?? () from /usr/lib/x86_64-linux-gnu/libEGL.so.1
#7  0x00007fffe80c0f15 in ?? () from /usr/lib/x86_64-linux-gnu/libEGL.so.1
#8  0x00007fffe80c8fd6 in ?? () from /usr/lib/x86_64-linux-gnu/libEGL.so.1
#9  0x00007ffff195a48c in SDL_EGL_UnloadLibrary (_this=0x555555ec23c0) at /home/travis/build/OpenRA/AppImageSupport/SDL2-2.0.8/src/video/SDL_egl.c:239
#10 0x00007ffff196b397 in SDL_GL_LoadLibrary_REAL (path=0x0) at /home/travis/build/OpenRA/AppImageSupport/SDL2-2.0.8/src/video/SDL_video.c:2798
#11 SDL_CreateWindow_REAL (title=0x7ffff5c3c808 "", x=0, y=0, w=1, h=<optimized out>, flags=10)
    at /home/travis/build/OpenRA/AppImageSupport/SDL2-2.0.8/src/video/SDL_video.c:1389
#12 0x000000004004b94b in ?? ()
#13 0x00007fffffffded0 in ?? ()
#14 0x00007fffffffd710 in ?? ()
#15 0x0000000000000001 in ?? ()
#16 0x00007ffff5c3c668 in ?? ()
#17 0x0000000000000001 in ?? ()
#18 0x0000000000000001 in ?? ()
#19 0x00007fffffffd710 in ?? ()
#20 0x00007ffff368d2b1 in System_Text_Encoding_GetBytes_string (this=..., s=0x7ffff5c3c808)
    at /disk/zhaixiang/mono/mcs/class/referencesource/mscorlib/system/text/encoding.cs:1096
#21 0x0000000000000001 in ?? ()
#22 0x000000000000000a in ?? ()
#23 0x00007ffff5c0e860 in ?? ()
#24 0x0000555555bef760 in ?? ()
#25 0x000000004004b788 in ?? ()
#26 0x00007ffff7f10130 in ?? ()
#27 0x0000000000000000 in ?? ()
(gdb) c
Continuing.

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x5555556186f9 - /usr/bin/mono : 
	0x555555618a79 - /usr/bin/mono : 
	0x5555555c5ea9 - /usr/bin/mono : 
	0x555555617caf - /usr/bin/mono : 
	0x7ffff7201890 - /lib/x86_64-linux-gnu/libpthread.so.0 : 
	0x7ffff6c24e97 - /lib/x86_64-linux-gnu/libc.so.6 : gsignal
	0x7ffff6c26801 - /lib/x86_64-linux-gnu/libc.so.6 : abort
	0x7ffff6c6f897 - /lib/x86_64-linux-gnu/libc.so.6 : 
	0x7ffff6c7690a - /lib/x86_64-linux-gnu/libc.so.6 : 
	0x7ffff6c7de84 - /lib/x86_64-linux-gnu/libc.so.6 : cfree
	0x7fffe80c0719 - /usr/lib/x86_64-linux-gnu/libEGL.so.1 : 
	0x7fffe80c0f15 - /usr/lib/x86_64-linux-gnu/libEGL.so.1 : 
	0x7fffe80c8fd6 - /usr/lib/x86_64-linux-gnu/libEGL.so.1 : 
	0x7ffff195a48c - /disk/zhaixiang/OpenRA/SDL2.so : 
	0x7ffff196b397 - /disk/zhaixiang/OpenRA/SDL2.so : 
	0x4004b94b - Unknown

=================================================================
	Telemetry Dumper:
=================================================================


```

Thanks,
Leslie Zhai

**Comment by abcdefg30** [comment]
Ubuntu sadly ships a broken mono version. Does installing https://www.mono-project.com/download/stable/#download-lin help?

**Comment by xiangzhai** [comment]
Hi @abcdefg30 

Thanks for your response!

> Ubuntu sadly ships a broken mono version.

Yes, it is better to report the issue to the mono.

I also tried to build [mono-6.8.0.123](https://github.com/mono/mono/tree/mono-6.8.0.123):

```
mono JIT compiler version 6.8.0 (explicit/1d0d939dc30)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

[HelloWorld](https://github.com/dotnet/samples/tree/master/core/console-apps/HelloMsBuild) is able to run:

```
mono /home/loongson/zhaixiang/Hello.dll 
Hello World!
```

And I use `dotnet build` for workaround `MSBUILD`:

```
diff --git a/Makefile b/Makefile
index 4f8d44225..3c865a482 100644
--- a/Makefile
+++ b/Makefile
@@ -75,7 +75,7 @@ INSTALL_PROGRAM = $(INSTALL) -m755
 INSTALL_DATA = $(INSTALL) -m644
 
 # Toolchain
-MSBUILD = msbuild -verbosity:m -nologo
+MSBUILD = dotnet build -verbosity:m -nologo
 
 # Enable 32 bit builds while generating the windows installer
 WIN32 = false
```

Then `make all`:

```
  Restore completed in 33.91 ms for /disk/zhaixiang/OpenRA/OpenRA.Mods.D2k/OpenRA.Mods.D2k.csproj.
  Restore completed in 33.92 ms for /disk/zhaixiang/OpenRA/OpenRA.Mods.Cnc/OpenRA.Mods.Cnc.csproj.
  Restore completed in 33.9 ms for /disk/zhaixiang/OpenRA/OpenRA.Server/OpenRA.Server.csproj.
  Restore completed in 33.91 ms for /disk/zhaixiang/OpenRA/OpenRA.Platforms.Default/OpenRA.Platforms.Default.csproj.
  Restore completed in 33.92 ms for /disk/zhaixiang/OpenRA/OpenRA.Utility/OpenRA.Utility.csproj.
  Restore completed in 33.9 ms for /disk/zhaixiang/OpenRA/OpenRA.Test/OpenRA.Test.csproj.
  Restore completed in 33.89 ms for /disk/zhaixiang/OpenRA/OpenRA.Game/OpenRA.Game.csproj.
  Restore completed in 33.91 ms for /disk/zhaixiang/OpenRA/OpenRA.Mods.Common/OpenRA.Mods.Common.csproj.
  OpenRA.Game -> /disk/zhaixiang/OpenRA/OpenRA.Game.exe
  OpenRA.Utility -> /disk/zhaixiang/OpenRA/OpenRA.Utility.exe
  OpenRA.Server -> /disk/zhaixiang/OpenRA/OpenRA.Server.exe
  OpenRA.Platforms.Default -> /disk/zhaixiang/OpenRA/OpenRA.Platforms.Default.dll
  OpenRA.Mods.Common -> /disk/zhaixiang/OpenRA/mods/common/OpenRA.Mods.Common.dll
  OpenRA.Mods.D2k -> /disk/zhaixiang/OpenRA/mods/d2k/OpenRA.Mods.D2k.dll
  OpenRA.Test -> /disk/zhaixiang/OpenRA/OpenRA.Test.dll
  OpenRA.Mods.Cnc -> /disk/zhaixiang/OpenRA/mods/common/OpenRA.Mods.Cnc.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.01
```

Lost something to build?

```
find . -name "*.dll" | xargs file
./nunit.engine.dll:                                                  PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./Open.Nat.dll:                                                      PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./nunit.engine.api.dll:                                              PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./Eluant.dll:                                                        PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./OpenRA.Platforms.Default/obj/Release/OpenRA.Platforms.Default.dll: PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./mods/common/Open.Nat.dll:                                          PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./mods/common/Eluant.dll:                                            PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./mods/common/OpenRA.Mods.Common.dll:                                PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./mods/common/ICSharpCode.SharpZipLib.dll:                           PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./mods/common/BeaconLib.dll:                                         PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./mods/common/OpenRA.Mods.Cnc.dll:                                   PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./mods/common/FuzzyLogicLibrary.dll:                                 PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./mods/d2k/Open.Nat.dll:                                             PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./mods/d2k/Eluant.dll:                                               PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./mods/d2k/ICSharpCode.SharpZipLib.dll:                              PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./mods/d2k/OpenRA.Mods.D2k.dll:                                      PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./mods/d2k/BeaconLib.dll:                                            PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./mods/d2k/FuzzyLogicLibrary.dll:                                    PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./OpenRA.Mods.Cnc/obj/Release/OpenRA.Mods.Cnc.dll:                   PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./OpenRA.Test.dll:                                                   PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./SDL2-CS.dll:                                                       PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./ICSharpCode.SharpZipLib.dll:                                       PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./OpenAL-CS.Core.dll:                                                PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./BeaconLib.dll:                                                     PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./OpenRA.Mods.D2k/obj/Release/OpenRA.Mods.D2k.dll:                   PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./OpenRA.Test/obj/Release/OpenRA.Test.dll:                           PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./NUnit3.TestAdapter.dll:                                            PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./nunit.framework.dll:                                               PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./OpenRA.Mods.Common/obj/Release/OpenRA.Mods.Common.dll:             PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./OpenRA.Platforms.Default.dll:                                      PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
./FuzzyLogicLibrary.dll:                                             PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows

find . -name "*.so" | xargs file
./freetype6.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=e70379e0eb4974b30d5cce929041c4c5e8765d9d, with debug_info, not stripped
./SDL2.so:      ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=fbad62fec2c72ab79f1d5cfce32818d3e2c7ee80, with debug_info, not stripped
./soft_oal.so:  ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=78f3515899946999d4a0ce14dbdb775fa1fd365b, stripped
./lua51.so:     ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=4cb4444b45ce5980694240c76617bf823f86494f, not stripped
```

Thanks,
Leslie Zhai

**Comment by pchote** [comment]
OpenRA does not yet support building with `dotnet`. If you install the official mono repository that @abcdefg30 linked and upgrade your system packages OpenRA will compile and run correctly.

**Comment by xiangzhai** [comment]
Hi @pchote 

Thanks for your response!

> If you install the official mono repository that @abcdefg30 linked

I `apt` install mono-devel:

```
Mono JIT compiler version 6.8.0.123 (tarball Tue May 12 15:11:57 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)

```

> OpenRA does not yet support building with dotnet

And use `msbuild` instead of `dotnet build`.

But it is still able to repro after `make clean` and `make all`.

PS:

Would OpenRA migrate to CoreCLR? https://github.com/OpenRA/OpenRA/pull/17989

We have ported CoreCLR to MIPS64 https://github.com/dotnet/runtime/issues/4234#issuecomment-638254024

We want to play OpenRA :)

Thanks,
Leslie Zhai

**Comment by anvilvapre** [comment]
perhaps try a different opengl library version, 
perhaps the double free happens after sdl is unable to create a gl window.

**Comment by xiangzhai** [comment]
Hi @anvilvapre 

Thanks for your advice!

I will try in my ArchLinux box again.

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
openra-20200503-2 is able to run happily in my ArchLinux box!
