### ISSUE TITLE
Another fatal error

### ISSUE THREAD

**Issue by IntelligentShitposter** [OpenRA/OpenRA#18299]
error log: OpenRA engine version release-20200503
Red Alert mod version release-20200503
Date: 2020-06-18 04:54:28Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Game.LoadShellMap()
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Primitives.ActionQueue.PerformActions(Int64 currentTime)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)
played on windows ten using the latest version

**Comment by abcdefg30** [comment]
Possibly related: #17707

**Comment by IntelligentShitposter** [comment]
I think this is a different issue. The last issue I couldn't even get into the game at all. This one allows me to at least download the content but then still crashes. Ahhhhh this game used to never crash on me.

**Comment by abcdefg30** [comment]
Closing due to inactivity. (Also a clean reinstall might fix the issue.)
