### ISSUE TITLE
OpenRA not working on windows 7

### ISSUE THREAD

**Issue by jabolko909** [OpenRA/OpenRA#18493]
## System Information

- Operating System: windows 7
- OpenRA Version: release-20200503
- OpenRA Mod: no mod
- Source: Official download package

## Exception log

there are 10 files that start with "exception-2020-80-06t0" and each with 6 different numbers just after the "06t0"

when I click "View logs" in the crash report windows, it takes me to a folder called "logs". were can I find the crash log?

## Replay
I attached a screenshot.
## Additional information
It crashes when i try to open it. i have just installed it and it always crashes when i try to open it. i also attached a screenshot.
![crashreportscrn](https://user-images.githubusercontent.com/68598439/89527505-b909cb00-d7e9-11ea-89c6-ecd617fd498d.png)

**Comment by deleted-user-1** [comment]
Sort by date and post the contents of the most recent exception.log.

**Comment by jabolko909** [comment]
ok!
here:

OpenRA engine version release-20200503
Date: 2020-08-06 17:06:06Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)

BTW, that happens when I try to run any of the 3 games by OpenRA (Red Alert, Dune 2000 and Tiberian Dawn)

**Comment by jabolko909** [comment]
is that OK?

**Comment by teinarss** [comment]
Will need the content of `graphics.log`

**Comment by jabolko909** [comment]
OK!
Here:

System.InvalidProgramException: Failed to initialize low-level OpenGL bindings. GPU information is not available. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: ptr
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at OpenRA.Platforms.Default.OpenGL.Bind[T](String name)
   at OpenRA.Platforms.Default.OpenGL.Initialize(Boolean preferLegacyProfile)
   --- End of inner exception stack trace ---
   at OpenRA.Platforms.Default.OpenGL.Initialize(Boolean preferLegacyProfile)
   at OpenRA.Platforms.Default.Sdl2GraphicsContext.InitializeOpenGL()
   at OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor(Size requestEffectiveWindowSize, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile requestProfile)
   at OpenRA.Platforms.Default.DefaultPlatform.CreateWindow(Size size, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile profile)
   at OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings)
   at OpenRA.Game.Initialize(Arguments args)

BTW, I have openGL version 1.4

**Comment by abcdefg30** [comment]
> BTW, I have openGL version 1.4

Sorry, that is too low for OpenRA since we require at least version `2.0`. (Version 3.x is better.)

**Comment by jabolko909** [comment]
Oh. Any ideas where I can get OpenGL 2.0 or 3.0?

**Comment by jabolko909** [comment]
Does that mean I need a new graphics card (I currently have a built-in on an older Dell's pc) or can I just download OpenGL 2.0?

**Comment by abcdefg30** [comment]
You'll have to look online if your graphics cards supports drivers with that OpenGL version, I don't know, sorry.

**Comment by jabolko909** [comment]
I have dell optiplex 755. I looked online what graphic card it has built-in, and found out it's Sapphire Radeon HD 7750 Low Profile graphics card. then, i tried searching for it and found out it supports openGL 4.2. does that mean i can download opengl 4.2 or older? if i can, where can i?

**Comment by deleted-user-1** [comment]
The people you are asking would have to do the same research like you to answer this question. You should already have found the link to https://www.amd.com/de/support.
