### ISSUE TITLE
The Discord integration sometimes crashes when trying to update the lobby state

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#18508]
Testcase is starting a local server and joining with two other clients, then spamming the "ready" checkbox with the third client.
```
OpenRA engine version {DEV_VERSION}
Tiberian Dawn mod version {DEV_VERSION}
Date: 2020-08-10 09:11:24Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `DiscordRPC.Exceptions.BadPresenceException`: Cannot set the size of the party if the party does not exist
   at DiscordRPC.DiscordRpcClient.UpdatePartySize(Int32 size, Int32 max)
   at OpenRA.Mods.Common.DiscordService.UpdatePlayers(Int32 players, Int32 slots) in \OpenRA\OpenRA.Mods.Common\DiscordService.cs:Line 193.
   at OpenRA.Mods.Common.Widgets.Logic.LobbyLogic.UpdateDiscordStatus() in \OpenRA\OpenRA.Mods.Common\Widgets\Logic\Lobby\LobbyLogic.cs:Line 788.
   at System.Action.Invoke()
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order) in \OpenRA\OpenRA.Game\Network\UnitOrders.cs:Line 277.
   at OpenRA.Network.OrderManager.TickImmediate() in \OpenRA\OpenRA.Game\Network\OrderManager.cs:Line 141.
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0() in \OpenRA\OpenRA.Game\Sync.cs:Line 166.
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in \OpenRA\OpenRA.Game\Game.cs:Line 584.
   at OpenRA.Game.LogicTick() in \OpenRA\OpenRA.Game\Game.cs:Line 631.
   at OpenRA.Game.Loop() in \OpenRA\OpenRA.Game\Game.cs:Line 798.
   at OpenRA.Game.Run() in \OpenRA\OpenRA.Game\Game.cs:Line 836.
   at OpenRA.Game.InitializeAndRun(String[] args) in \OpenRA\OpenRA.Game\Game.cs:Line 260.
   at OpenRA.Program.Main(String[] args) in \OpenRA\OpenRA.Game\Support\Program.cs:Line 33.
```

**Comment by teinarss** [comment]
Was not able to reproduce this in #18469

**Comment by teinarss** [comment]
Need more info then.
