### ISSUE TITLE
jjuice1.aud is not a valid sound file!

### ISSUE THREAD

**Issue by DrTrygga** [OpenRA/OpenRA#18506]
## System Information

- Operating System:  Windows 10 64-bit
- OpenRA Version: release-20200503
- OpenRA Mod: Red Alert
- Source: Official download package

## Exception log

```
OpenRA engine version release-20200503
Red Alert mod version release-20200503
on map 8a5fe61f5397e6de40baee529ce5556433185808 (Siberian Pass by The Echo of Damnation).
Date: 2020-08-09 20:51:28Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.InvalidDataException`: jjuice1.aud is not a valid sound file!
   at OpenRA.Sound.LoadSound[T](String filename, Func`2 loadFormat)
   at OpenRA.Exts.GetOrAdd[K,V](Dictionary`2 d, K k, Func`2 createFn)
   at OpenRA.Sound.PlayPredefined(SoundType soundType, Ruleset ruleset, Player p, Actor voicedActor, String type, String definition, String variant, Boolean relative, WPos pos, Single volumeModifier, Boolean attenuateVolume)
   at OpenRA.Mods.Common.Traits.Voiced.OpenRA.Traits.IVoiced.PlayVoice(Actor self, String phrase, String variant)
   at OpenRA.VoiceExts.PlayVoice(Actor self, String phrase)
   at OpenRA.Mods.Common.Traits.Selection.Combine(World world, IEnumerable`1 newSelection, Boolean isCombine, Boolean isClick)
   at OpenRA.Mods.Common.Widgets.WorldInteractionControllerWidget.HandleMouseInput(MouseInput mi)
   at OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
   at OpenRA.Widgets.Ui.HandleInput(MouseInput mi)
   at OpenRA.DefaultInputHandler.<>c__DisplayClass5_0.<OnMouseInput>b__0()
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn)
   at OpenRA.Platforms.Default.Sdl2Input.PumpInput(Sdl2PlatformWindow device, IInputHandler inputHandler, Nullable`1 lockedMousePosition)
   at OpenRA.Platforms.Default.Sdl2PlatformWindow.PumpInput(IInputHandler inputHandler)
   at OpenRA.Renderer.EndFrame(IInputHandler inputHandler)
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)
```

**Comment by abcdefg30** [comment]
Odd, this looks like another case of https://github.com/OpenRA/OpenRA/issues/18085#issuecomment-627187058 but you said you downloaded the content; maybe some of our content mirrors ship broken assets?
Anyway, you can try getting around this by deleting the RA mod content (see the comment linked above; "%APPDATA%/OpenRA/Content" has a RA folder you can delete) and redownloading the assets (which hopefully will not be broken this time). You can then verify this crash is gone by using Shock Troopers (which are the units that caused this crash).

**Comment by abcdefg30** [comment]
Closing due to inactivity/lack of information.
