### ISSUE TITLE
My game crashed

### ISSUE THREAD

**Issue by olliewuk** [OpenRA/OpenRA#18603]
## System Information

- Operating System:  Windows (Microsoft Windows NT 6.2.9200.0)
- OpenRA Version: OpenRA engine version release-20200503
- OpenRA Mod: Red Alert Plus (Full) mod version v.1.3.7-beta-full
- Source: Official download 

## Exception log
OpenRA engine version release-20200503
Red Alert Plus (Full) mod version v.1.3.7-beta-full
on map aaaf8b9ae948dfcea1fff4913edd8848bc44fe9d (Rapa Nui by American Blunt).
Date: 2020-09-10 19:18:25Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenRA.Mods.Common.Traits.SpawnMPUnits.SpawnUnitsForPlayer(World w, Player p, CPos sp)
   at OpenRA.Mods.Common.Traits.SpawnMPUnits.WorldLoaded(World world, WorldRenderer wr)
   at OpenRA.World.LoadComplete(WorldRenderer wr)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.TickImmediate()
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)

## Additional information
I was restarting a level

**Comment by Mailaender** [comment]
Report that to the mod author as he made a mistake when setting up https://docs.openra.net/en/latest/release/traits/#mpstartlocations

**Comment by olliewuk** [comment]
Thanks. Yep mod author has confirmed.
