### ISSUE TITLE
Crash at fresh install and startup

### ISSUE THREAD

**Issue by DiabroDT** [OpenRA/OpenRA#18616]
OpenRA engine version release-20200503
Date: 2020-09-16 14:17:54Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: OpenGL Error: See graphics.log for details.
   at OpenRA.Platforms.Default.OpenGL.DebugMessageHandler(Int32 source, Int32 type, UInt32 id, Int32 severity, Int32 length, StringBuilder message, IntPtr userparam)
   at SDL2.SDL.SDL_GL_SwapWindow(IntPtr window)
   at OpenRA.Renderer.EndFrame(IInputHandler inputHandler)
   at OpenRA.Mods.Common.LoadScreens.SheetLoadScreen.Display()
   at OpenRA.ModData..ctor(Manifest mod, InstalledMods mods, Boolean useLoadScreen)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)

High - GL Debug API Output: Error - GL_INVALID_OPERATION error generated. Function glPushAttrib is deprecated and not available in preview contexts.
   at OpenRA.Platforms.Default.OpenGL.BuildErrorText(Int32 source, Int32 type, Int32 severity, StringBuilder message)
   at OpenRA.Platforms.Default.OpenGL.DebugMessageHandler(Int32 source, Int32 type, UInt32 id, Int32 severity, Int32 length, StringBuilder message, IntPtr userparam)
   at SDL2.SDL.SDL_GL_SwapWindow(IntPtr window)
   at SDL2.SDL.SDL_GL_SwapWindow(IntPtr window)
   at OpenRA.Renderer.EndFrame(IInputHandler inputHandler)
   at OpenRA.Mods.Common.LoadScreens.SheetLoadScreen.Display()
   at OpenRA.ModData..ctor(Manifest mod, InstalledMods mods, Boolean useLoadScreen)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)
   at OpenRA.WindowsLauncher.Main(String[] args)

Not sure what exactly is going on. This is with the 20200503 download. I have tried multiple reinstalls of the application with no avail.

**Comment by pchote** [comment]
You need to disable RivaTuner, which injects invalid commands that crash any OpenGL3-based applications.

**Comment by DiabroDT** [comment]
Thank you, that fixed it. No idea Riva was the issue.
