### ISSUE TITLE
Using CargoInit instead of RuntimeCargoInit with actor values causes an ObjectDisposedException

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#18639]
Testcase: Add a `CargoInit` with an actor instead of a string, for example
```
local tanya = Actor.Create("e7", false, { Owner = player })
Actor.Create("apc", true, { Location = CPos.New(5,5), Owner = player, Cargo = { tanya } })
```

Which shouldn't work since using `RuntimeCargoInit` would be the correct way to do it. However, the crash message is not helpful at all, and we should fail sooner.

The value is parsed as string from the argument here:
https://github.com/OpenRA/OpenRA/blob/9c4fd0e3d37f64b0c426b152ab364a6baa0ca51e/OpenRA.Game/Scripting/ScriptTypes.cs#L92

The argument is then disposed here:
https://github.com/OpenRA/OpenRA/blob/9c4fd0e3d37f64b0c426b152ab364a6baa0ca51e/OpenRA.Game/Scripting/ScriptMemberWrapper.cs#L79-L82

Now when creating the actor after loading the inits the following `ObjectDisposedException` occurs:
```
Fatal Lua Error: [string "BindingSupport.lua"]:30: Uncaught CLR exception at Lua->CLR boundary: System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.ObjectDisposedException: Auf das verworfene Objekt kann nicht zugegriffen werden.
Objektname: "Eluant.LuaClrObjectReference".
   at Eluant.LuaReference.CheckDisposed()
   at Eluant.LuaClrObjectReference.get_ClrObjectValue()
   at Eluant.LuaClrObjectReference.get_ClrObject()
   at Eluant.ClrObject.TryGetClrObject(LuaValue self, Object& obj)
   at OpenRA.Scripting.LuaValueExts.WrappedClrType(LuaValue value) in \OpenRA\OpenRA.Game\Scripting\ScriptTypes.cs:Line 21.
   at OpenRA.Scripting.LuaValueExts.TryGetClrValue(LuaValue value, Type t, Object& clrObject) in \OpenRA\OpenRA.Game\Scripting\ScriptTypes.cs:Line 129.
   at OpenRA.Mods.Common.Scripting.ActorGlobal.CreateInit(String initName, LuaValue value) in \OpenRA\OpenRA.Mods.Common\Scripting\Global\ActorGlobal.cs:Line 97.
   at OpenRA.Mods.Common.Scripting.ActorGlobal.Create(String type, Boolean addToWorld, LuaTable initTable) in \OpenRA\OpenRA.Mods.Common\Scripting\Global\ActorGlobal.cs:Line 119.
   --- Ende der internen Ausnahmestapelüberwachung ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OpenRA.Scripting.ScriptMemberWrapper.Invoke(LuaVararg args) in \OpenRA\OpenRA.Game\Scripting\ScriptMemberWrapper.cs:Line 75.
   --- Ende der internen Ausnahmestapelüberwachung ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eluant.LuaRuntime.MethodWrapper.Invoke(Object[] parms)
   at Eluant.LuaRuntime.MakeManagedCall(IntPtr state, MethodWrapper wrapper)
   at OpenRA.Scripting.ScriptContext.FatalError(String message)
   at OpenRA.Mods.Common.Scripting.TriggerGlobal.<>c__DisplayClass2_0.<AfterDelay>b__0()
   at OpenRA.Effects.DelayedAction.<Tick>b__3_0(World w)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by pchote** [comment]
7575c5b3333a52b3551881eb18d845053fc71172 is the fix I had in mind but i'm not confident in its robustness.

**Comment by dnqbob** [comment]
there is another (probably many) bug for `CargoInit`, I found when transport destroyed, the `CargoInit` actor couldn't escape it when `EjectOnDeath` is true, but when you unload then load these actors it is working again.

**Comment by MustaphaTR** [comment]
> there is another (probably many) bug for CargoInit, I found when transport destroyed, the CargoInit actor couldn't escape it when EjectOnDeath is true, but when you unload then load these actors it is working again.

Probably same thing with  #17863.

**Comment by dnqbob** [comment]
> > there is another (probably many) bug for CargoInit, I found when transport destroyed, the CargoInit actor couldn't escape it when EjectOnDeath is true, but when you unload then load these actors it is working again.
> 
> Probably same thing with #17863.

I think it is exactly the same. Fail on calculating the `CurrentAdjacentCells`.
