### ISSUE TITLE
TS SupportPower Problem

### ISSUE THREAD

**Issue by geniusxddd** [OpenRA/OpenRA#18849]
```
OpenRA engine version {DEV_VERSION}
ts mod version {DEV_VERSION}
on map 1117ae5d3542b2179401e1598ac323dc6c8183d4 (Tiers of Sorrow by Westwood Studios).
Date: 2020-11-23 15:01:51Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000

Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenRA.Mods.Common.Traits.AirstrikePower.SendAirstrike(Actor self, WPos target, Nullable`1 facing)
   at OpenRA.Mods.Common.Traits.AirstrikePower.Activate(Actor self, Order order, SupportPowerManager manager)
   at OpenRA.Mods.Common.Traits.SupportPowerInstance.Activate(Order order)
   at OpenRA.Mods.Common.Traits.SupportPowerManager.ResolveOrder(Actor self, Order order)
   at OpenRA.Network.UnitOrders.ResolveOrder(Order order)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.Program.Main(String[] args)
```

i dont really know much, because iam new to this, but basically every time i try to add a support power, that isnt a clone of already existing one(such as IonCannon or Nuke), it crashes
i think iam missing something but i have no idea what it is

**This is the .yaml for the airstrike**
```
	AirstrikePower@raiders:
		UnitType: AIRSTRIKE_BOMBER
		SquadSize: 3
		SquadOffset: -1536,1536,0
		QuantizedFacings: 8
		Cordon: 5c0
		CameraActor: camera_airstrike
		CameraRemoveDelay: 150
		ChargeInterval: 7500
		Icon: airstrikeicon
		Description: Airstrike
		LongDesc: Airstrike.\nLaunches an airstrike at specified location.
		Cursor: ioncannon
		PauseOnCondition: disabled || empdisable
		SelectTargetSpeechNotification: SelectTarget
		Prerequisites: techlevel.superweapons
		DisplayBeacon: True
		BeaconPoster: idle
		OrderName: AirstrikePowerInfoOrder
		EndChargeSpeechNotification: AirstrikeReady
		ArrowSequence: arrow
		ClockSequence: clock
		CircleSequence: circles
		UseDirectionalTarget: True
		DirectionArrowAnimation: paradirection
		SupportPowerPaletteOrder: 60
```

**Comment by abcdefg30** [comment]
`AIRSTRIKE_BOMBER` is most likely the problem here. You need to use the same case the unit is defined in. (So if your yaml for the bomber starts with `airstrike_bomber:`, putting `UnitType: airstrike_bomber` hopefully fixes the problem.)

**Comment by geniusxddd** [comment]
Thanks alot, support power works as expected.
Cant belive a capslock outsmarted me

**Comment by abcdefg30** [comment]
Sadly we're a bit inconsistent with actor name cases. Glad this helped to resolve the issue though.
