### ISSUE TITLE
Playtest TD Crash (Engineer/Airstrip Bug?)

### ISSUE THREAD

**Issue by Orb370** [OpenRA/OpenRA#18970]
Replay: [Playtest Crash.zip](https://github.com/OpenRA/OpenRA/files/5743905/Playtest.Crash.zip)

[Logs.zip](https://github.com/OpenRA/OpenRA/files/5743907/Logs.zip)

![001967](https://user-images.githubusercontent.com/42915475/103161227-97b37680-47ac-11eb-8723-eb49bf24f6b5.png)

^Moments before crash

**Comment by deleted-user-1** [comment]
```
OpenRA engine version playtest-20201213
Tiberian Dawn mod version playtest-20201213
on map 8974321e8e5435597d04f76a5c2f9268e2fd3ba5 (Tiberium Rift[TDGL2+] by ZxGanon).
Date: 2020-12-26 23:16:44Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at OpenRA.Mods.Common.Traits.ProductionQueue.BuildUnit(ActorInfo unit)
   at OpenRA.Mods.Common.Traits.ProductionQueue.<>c__DisplayClass52_2.<ResolveOrder>b__5(World _)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)
```

It's crashing on https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Player/ProductionQueue.cs#L576. What is the expected outcome for TD when capturing the airfield while a unit is produced? Although I can't reproduce the crash, sometimes the old owner get their unit delivered, sometimes the unit is cancelled. There might be a race that ended in a (rare?) crash here. FYI when setting a breakpoint before or after https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Player/ProductionQueue.cs#L163 when watching the repaly (at ~10min), the airfield actor has `IsInWorld=false` but when continuing and the exception is thrown, `IsInWorld=true`.
