### ISSUE TITLE
Renderer initializer exception not flushed to graphics.log

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#19028]
Minor bug/enhancement.

OpenRA is unable to start. It refers to the graphics.log for more information about the reason. The graphics.log is empty. I suspect the graphics log is not flushed.

bleed.

--

Platform is Linux
Engine version is Unknown
Runtime: Mono 6.12.0.107 (tarball Thu Dec 10 05:26:45 UTC 2020) CLR 4.0.30319.42000
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1600x900
Using resolution: 1024x768
Using window scale 1.00
OpenGL renderer: Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2)
OpenGL version: 4.5 (Core Profile) Mesa 21.0.0-devel (git-05ad0f8 2020-12-19 focal-oibaf-ppa)
Renderer initialization failed. Check graphics.log for details.
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1600x900
Using resolution: 1024x768
Using window scale 1.00
OpenGL renderer: Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2)
OpenGL version: 4.5 (Core Profile) Mesa 21.0.0-devel (git-05ad0f8 2020-12-19 focal-oibaf-ppa)
Renderer initialization failed. Check graphics.log for details.
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x004ea] in /home/y/source/cs/OpenRA/OpenRA.Game/Game.cs:410 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00000] in /home/y/source/cs/OpenRA/OpenRA.Game/Game.cs:270 
  at OpenRA.Launcher.Program.Main (System.String[] args) [0x00044] in /home/y/source/cs/OpenRA/OpenRA.Launcher/Program.cs:30 

--

Not related to this bug. The cause turned out to be that the OpenRA launch script was started from within the wrong directory 'System.IO.DirectoryNotFoundException: Could not find a part of the path "/home/y/source/cs/glsl/combined.vert"`.

The error/exception is caught and logged to the graphics log in `Game.cs` near line 354.

**Comment by kant2002** [comment]
I would say it's not obvious that logs located in the `%APPDATA%\OpenRA\Logs`. I later found that this is documented in https://github.com/OpenRA/OpenRA/wiki/FAQ

Another note. I hit this issue after following these steps.
1. make.cmd a
2. cd bin
3. .\OpenRA.exe

Isn't this would be common mistake for newcomer developers to the project, so it would warrant special treatment? Or maybe change message from `Check graphics.log for details.` to `Check graphics.log for details. See https://github.com/OpenRA/OpenRA/wiki/FAQ for details`. Wiki very often neglected on GitHub, so I do not even look into them.

**Comment by anvilvapre** [comment]
On Windows it is the place for an application to store user data. 

What issue did you run into with your steps? I don't understand the fault?

**Comment by kant2002** [comment]
In retrospect that location make sense. But for dev build I expect something closer to sources. Anyway. 

I do following
1. Build.cmd
2. cd bin
3. openra.exe
 
App crashed and say look for graphics.log

**Comment by Mailaender** [comment]
Closing as not being reproducible (anymore?)

```
cd bin
./OpenRA
Error:
  An assembly specified in the application dependencies manifest (OpenRA.deps.json) was not found:
    package: 'OpenRA.Game', version: '1.0.0'
    path: 'OpenRA.Game.dll'
```

There is no `.exe` anymore in `bin`.

**Comment by Mailaender** [comment]
I was actually on an older branch.

**Comment by Mailaender** [comment]
Still this is my `graphics.log` when I run from `OpenRA/bin> ./OpenRA`

```
System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/matthias/Entwicklung/OpenRA/bin/glsl/combined.vert'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at OpenRA.Platforms.Default.Shader.CompileShaderObject(Int32 type, String name) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/Shader.cs:line 36
   at OpenRA.Platforms.Default.Shader..ctor(String name) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/Shader.cs:line 71
   at OpenRA.Platforms.Default.Sdl2GraphicsContext.CreateShader(String name) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/Sdl2GraphicsContext.cs:line 97
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.<>c__DisplayClass23_0.<RenderThread>b__9(Object name) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/ThreadedGraphicsContext.cs:line 95
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.Message.Execute() in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/ThreadedGraphicsContext.cs:line 222
--- End of stack trace from previous location ---
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.Message.Result() in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/ThreadedGraphicsContext.cs:line 262
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.RunMessage(Message message) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/ThreadedGraphicsContext.cs:line 292
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.Send[T](Func`2 method, Object state) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/ThreadedGraphicsContext.cs:line 323
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.CreateShader(String name) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/ThreadedGraphicsContext.cs:line 394
   at OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings) in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Renderer.cs:line 88
   at OpenRA.Game.Initialize(Arguments args) in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:line 368
System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/matthias/Entwicklung/OpenRA/bin/glsl/combined.vert'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at OpenRA.Platforms.Default.Shader.CompileShaderObject(Int32 type, String name) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/Shader.cs:line 36
   at OpenRA.Platforms.Default.Shader..ctor(String name) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/Shader.cs:line 71
   at OpenRA.Platforms.Default.Sdl2GraphicsContext.CreateShader(String name) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/Sdl2GraphicsContext.cs:line 97
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.<>c__DisplayClass23_0.<RenderThread>b__9(Object name) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/ThreadedGraphicsContext.cs:line 95
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.Message.Execute() in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/ThreadedGraphicsContext.cs:line 222
--- End of stack trace from previous location ---
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.Message.Result() in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/ThreadedGraphicsContext.cs:line 262
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.RunMessage(Message message) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/ThreadedGraphicsContext.cs:line 292
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.Send[T](Func`2 method, Object state) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/ThreadedGraphicsContext.cs:line 323
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.CreateShader(String name) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/ThreadedGraphicsContext.cs:line 394
   at OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings) in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Renderer.cs:line 88
   at OpenRA.Game.Initialize(Arguments args) in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:line 368
```
