### ISSUE TITLE
Crash when launching OpenRA via Steam Big Picture Mode

### ISSUE THREAD

**Issue by vsctmby** [OpenRA/OpenRA#19049]
## System Information

- Operating System:  Windows 10
- OpenRA Version: release-20200503
- OpenRA Mod: Red Alert
- Source: Official download package 

## Exception log

```
OpenRA engine version release-20200503
Red Alert mod version release-20200503
on map f6c528c39e04c6880343ef6be5d2a43d086980fa (Desert Shellmap by Scott_NZ).
Date: 2021-01-13 13:58:32Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: OpenGL Error: See graphics.log for details.
   at OpenRA.Platforms.Default.OpenGL.DebugMessageHandler(Int32 source, Int32 type, UInt32 id, Int32 severity, Int32 length, StringBuilder message, IntPtr userparam)
   at SDL2.SDL.SDL_GL_SwapWindow(IntPtr window)
   at OpenRA.Renderer.EndFrame(IInputHandler inputHandler)
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)
```

## Additional information
I started the game from the Big Picture Mode. It loads the game, but crashes right in the main menu. I did change the OpenGL version to Legacy in settings, but it still does the same.
[exception-2021-01-13T135832Z.txt](https://github.com/OpenRA/OpenRA/files/5809178/exception-2021-01-13T135832Z.txt)
[graphics.txt](https://github.com/OpenRA/OpenRA/files/5809182/graphics.txt)

**Comment by vsctmby** [comment]
Okay, I didn't notice the Fullscreen (Legacy) in the display mode in Settings. Choosing that solved the issue.
