### ISSUE TITLE
Crash related to pathfinding

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#19063]
## System Information

- Operating System:  Win10
- OpenRA Version: rv-engine bd535ad
- OpenRA Mod: SP

**We haven't touched pathfinding on engine modifying**

## Exception log

```
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given keyword is not in the dictionary
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenRA.Mods.Common.Pathfinder.PathGraph.set_Item(CPos pos, CellInfo value) ~\OpenRA.Mods.Common\Pathfinder\PathGraph.cs: 226
   at OpenRA.Mods.Common.Pathfinder.PathSearch.AddInitialCell(CPos location) ~\OpenRA.Mods.Common\Pathfinder\PathSearch.cs: 94
   at OpenRA.Mods.Common.Pathfinder.PathSearch.FromPoints(World world, Locomotor locomotor, Actor self, IEnumerable`1 froms, CPos target, BlockedByActor check) ~\OpenRA.Mods.Common\Pathfinder\PathSearch.cs: 83
   at OpenRA.Mods.Common.Traits.PathFinder.FindUnitPath(CPos source, CPos target, Actor self, Actor ignoreActor, BlockedByActor check) ~\OpenRA.Mods.Common\Traits\World\PathFinder.cs: 89
   at OpenRA.Mods.Common.Pathfinder.PathFinderUnitPathCacheDecorator.FindUnitPath(CPos source, CPos target, Actor self, Actor ignoreActor, BlockedByActor check) ~\OpenRA.Mods.Common\Pathfinder\PathFinderUnitPathCacheDecorator.cs: 48
   at OpenRA.Mods.Common.Activities.Move.<>c__DisplayClass13_0.<.ctor>b__0(BlockedByActor check) ~\OpenRA.Mods.Common\Activities\Move\Move.cs: 84
   at OpenRA.Mods.Common.Activities.Move.EvalPath(BlockedByActor check) ~\OpenRA.Mods.Common\Activities\Move\Move.cs: 152
   at OpenRA.Mods.Common.Activities.Move.OnFirstRun(Actor self) ~\OpenRA.Mods.Common\Activities\Move\Move.cs: 166
```

<img width="523" alt="1" src="https://user-images.githubusercontent.com/13763394/104845542-f635c580-5910-11eb-8059-d1d8553f012e.PNG">

## Replay
Nah for now, the only replay lasts for >30 mins.

## Additional information
We didn't even touch pathfinding on engine modifying and here it comes. Hard to reproduce.

But from the limited information I gathered, it happens when actor pathfinding module meets a "layer !=0" cell in map, may be from flying units or underground units.

Launching a debug version on replay, if it is smoothly I can get which actor and locomotor and cell information on pathfinding.

Upgrade:
Looks like it is only a normal ground unit (the 106, -31 is the cell index of pathfinding crash point at PathGraph.cs: 226)
<img width="144" alt="bug" src="https://user-images.githubusercontent.com/13763394/104845847-87596c00-5912-11eb-98b7-88ce4498f2f4.PNG">
(it triggers multiple times for dead loop causing by my debug exception throwing, unrelated to this crash bug) 

map position 
<img width="309" alt="1" src="https://user-images.githubusercontent.com/13763394/104846049-81b05600-5913-11eb-9ee3-abb714eff839.PNG">

**Comment by dnqbob** [comment]
visc_lrg is a actor belonging to creep that spawned by  "SpawnActorOnDeath", use Vehicle as locomotor. It moves with the Wanders trait. 

In this case, I believe you can use TS, which have terrain layer, to reproduce this bug on frequently trying.

**Comment by dnqbob** [comment]
The newst commit for Pathfinder folder:
![Screenshot](https://user-images.githubusercontent.com/13763394/104859233-bb5a7e80-595e-11eb-86c9-dbe9e663731e.jpg)

**Comment by anvilvapre** [comment]
In `PathGraph.this[CPos].set` `customLayerInfo[pos.Layer].get` seems to fail(?). The custom layer info missing the layer `pos.Layer`?

**Comment by dnqbob** [comment]
> In `PathGraph.this[CPos].set` `customLayerInfo[pos.Layer].get` seems to fail(?). The custom layer info missing the layer `pos.Layer`?

Yes.  In addition, the layer on the crash position in game is also incorrect (IMO). in Map editor the 106, -31 has z-index 5 (layer 5 ?)  but when the Pathfinder crash, it is trying to get PFgraph information on 106, -31 has layer 2. If the z-index in Map editor is the layer, then we can confirm that OpenRA is trying to access a undefined cell (wrong layer) during pathfinding.

**Comment by dnqbob** [comment]
```
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key '2' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenRA.Mods.Common.Pathfinder.PathGraph.set_Item(CPos pos, CellInfo value) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\PathGraph.cs:line 226
   at OpenRA.Mods.Common.Pathfinder.PathSearch.AddInitialCell(CPos location) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 95
   at OpenRA.Mods.Common.Pathfinder.PathSearch.FromPoints(World world, Locomotor locomotor, Actor self, IEnumerable`1 froms, CPos target, BlockedByActor check) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 82
   at OpenRA.Mods.Common.Traits.PathFinder.FindUnitPath(CPos source, CPos target, Actor self, Actor ignoreActor, BlockedByActor check) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Traits\World\PathFinder.cs:line 92
   at OpenRA.Mods.Common.Pathfinder.PathFinderUnitPathCacheDecorator.FindUnitPath(CPos source, CPos target, Actor self, Actor ignoreActor, BlockedByActor check) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\PathFinderUnitPathCacheDecorator.cs:line 55
   at OpenRA.Mods.Common.Activities.Move.<>c__DisplayClass13_0.<.ctor>b__0(BlockedByActor check) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\Move.cs:line 81
   at OpenRA.Mods.Common.Activities.Move.EvalPath(BlockedByActor check) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\Move.cs:line 154
   at OpenRA.Mods.Common.Activities.Move.OnFirstRun(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\Move.cs:line 166
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 37
   at OpenRA.Actor.Tick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Actor.cs:line 266
   at OpenRA.World.Tick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\World.cs:line 422
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 646
   at OpenRA.Game.LogicTick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 661
   at OpenRA.Game.Loop() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 823
   at OpenRA.Game.Run() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 864
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 274
   at OpenRA.Launcher.Program.Main(String[] args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Launcher\Program.cs:line 30
```

Today I get another.

**Comment by anvilvapre** [comment]
Having read the path finding code recently...

`AddInitialCell` checks to see if a coordinate is inside the width and height of the map. So it must be the layer.

The source of the bug may not be in the path finding, but in the mod, starting a Move activity passing an invalid value for start/from points. `AddInitialCell` is before a path search really starts.

The problem originates from the `Move` activity being called with the third constructor that takes an `ignoreActor` argument. Only here `getPath` is set here to use `FindUnitPath`. It means that either `mobile.ToCell` has an invalid layer or `Move.destination.value` has. You can be certain which one if you check line 82 in `PathSearch`.

So likely something is moving an actor to an invalid `destination`.

You could temporarily add a check in the constructor and throw a stack trace if  the layer is invalid. Should tell you rom where the 'invalid' Move activity is created and problem originates. Probably one of the 'custom' move's used by the mod. Since otherwise the bug should show up more often in default mod's as well.

**Comment by pchote** [comment]
>  So it must be the layer.

The fact that the key is `2` rather than a cell also confirms this. Specifically the subterranean layer.

**Comment by dnqbob** [comment]
> Probably one of the 'custom' move's used by the mod. Since otherwise the bug should show up more often in default mod's as well.


This bug is a rare bug.  I got two in 3 months at the same map with hundred of hours of testing. So I suspect it will also happen in TS but not yet found. 

From the first bug, locomotive vehicle which is a common used locomotive which is also apply in TS. If it is the move cause the bug we should also check on trait `Wanders`.

**Comment by dnqbob** [comment]
Launching the replay with the debug version.

>You can be certain which one if you check line 82 in PathSearch.

I used it above on the first debug.

**Comment by dnqbob** [comment]
<img width="242" alt="bug-report" src="https://user-images.githubusercontent.com/13763394/114129680-a1af4e80-9931-11eb-94ca-5ef939d61886.PNG">

Bug report

In short, actor wants to move from its cell `(121, -26, 0)` to `(121, -26, 0)` (the arg `CPos target` in `FromPoints`, PathSearch) and receive error in `(121, -26, 2)`.

`(121, -26)` On map: 
<img width="333" alt="bug location" src="https://user-images.githubusercontent.com/13763394/114130374-04551a00-9933-11eb-9a2f-14848f20a184.png">

and its layer  = 4 actually.

**Comment by dnqbob** [comment]
My thought:
1. "visc_lrg" and "berserker" are all death spawn creep actor by killing a vehicle by using some kind of weapon. So the problem may related to `SpawnActorOnDeath` trait.
2. The two game all include Nod, who use subterranean unit.

So I guess the problem happens like: a killed subterranean actor spawn a actor under correct layer (when  subterranean actor hasn't get the condition of being invisible), the game try to find a path for this new actor to reach correct layer but find there is no valid underground layer, so the game crashes.

**Comment by dnqbob** [comment]
To solve this crash we may need to add a 'forceGrounded' option in `SpawnActorOnDeath` and check valid ground if actor spawn in this option.

**Comment by reaperrr** [comment]
Subterranean units simply shouldn't be able to die while submerged, then the problem shouldn't occur.
Of course, disabling (via conditions) `SpawnActorOnDeath` while submerged to be safe wouldn't hurt, either.

**Comment by dnqbob** [comment]
It seems that subterranean condition must be granted under layer < ground layer - 2

**Comment by dnqbob** [comment]
which means under this layer we can make this unit unseen/invisible by using condition.
