### ISSUE TITLE
Crash on Allies05a (bleed)

### ISSUE THREAD

**Issue by Smittytron** [OpenRA/OpenRA#19060]
At the end of the truck steal sequence, the spy gets out of the truck and the truck detonates on the barrels. The game crashes at this point. The function for this event is on line 310 in `allies05a.lua`. The crash is in bleed and not in the 20201213 playtest.

```
Fatal Lua Error: [string "BindingSupport.lua"]:30: Unable to convert parameter 0 to Object
   at OpenRA.Scripting.ScriptContext.FatalError(String message)
   at OpenRA.Mods.Common.Scripting.ScriptTriggers.OpenRA.Mods.Common.Traits.INotifyKilled.Killed(Actor self, AttackInfo e)
   at OpenRA.Mods.Common.Traits.Health.InflictDamage(Actor self, Actor attacker, Damage damage, Boolean ignoreModifiers)
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, WarheadArgs args)
   at OpenRA.Mods.Common.Warheads.DamageWarhead.DoImpact(Target& target, WarheadArgs args)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.Launcher.Program.Main(String[] args)
```

**Comment by reaperrr** [comment]
Certainly a regression from #19056, the question is why.

**Comment by pchote** [comment]
Did that remove `ScriptTriggers` from barrels too? They are likely to have triggers attached.

**Comment by anvilvapre** [comment]
`ScriptTriggers.cs:142`

```
 using (var b = e.Attacker.ToLuaValue(f.Context))
                                                f.Function.Call(f.Self, b).Dispose();
```

**Comment by reaperrr** [comment]
> Did that remove ScriptTriggers from barrels too? They are likely to have triggers attached.

No, at least I don't see how. Barrels don't inherit any of the places I removed it from.

**Comment by Smittytron** [comment]
This crash made it into playtest 20210131, so that should narrow it down.

**Comment by pchote** [comment]
😢 

Must be #19038 then?
