### ISSUE TITLE
Attempted to calculate the square root of a negative integer on Desert-Oil-War-Map

### ISSUE THREAD

**Issue by Leo512bit** [OpenRA/OpenRA#19261]
## System Information

- Operating System:  Windows 10 20H2
- OpenRA Version: 20200503

- OpenRA Mod: RA
- Source: Official download package

## Exception log
OpenRA engine version release-20200503
Red Alert mod version release-20200503
on map 01c663fa2969b1dc2c511739fda86df63f60be40 (Desert Oil War *incomplete* R47.3 Hotfix by LeonardMT).
Date: 2021-03-20 15:36:20Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Attempted to calculate the square root of a negative integer: -1345641671
   at OpenRA.Exts.ISqrt(Int32 number, ISqrtRoundMode round)
   at OpenRA.Mods.Common.HitShapes.PolygonShape.DistanceFromEdge(WVec v)
   at OpenRA.Mods.Common.HitShapes.PolygonShape.DistanceFromEdge(WPos pos, WPos origin, WRot orientation)
   at OpenRA.Mods.Common.Traits.HitShape.DistanceFromEdge(Actor self, WPos pos)
   at OpenRA.Mods.Common.Warheads.TargetDamageWarhead.<>c__DisplayClass1_1.<DoImpact>b__0(HitShape s)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at OpenRA.Exts.CompareBy[T,U](IEnumerable`1 ts, Func`2 selector, Int32 modifier, Boolean throws)
   at OpenRA.Mods.Common.Warheads.TargetDamageWarhead.DoImpact(WPos pos, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.Mods.Common.Warheads.DamageWarhead.DoImpact(Target target, WarheadArgs args)
   at OpenRA.GameRules.WeaponInfo.Impact(Target target, WarheadArgs args)
   at OpenRA.GameRules.WeaponInfo.Impact(Target target, Actor firedBy)
   at OpenRA.Mods.Common.Traits.ExplodeCrateAction.Activate(Actor collector)
   at OpenRA.Mods.Common.Traits.Crate.OnCrushInner(Actor crusher)
   at OpenRA.Mods.Common.Traits.Crate.OpenRA.Mods.Common.Traits.INotifyCrushed.OnCrush(Actor self, Actor crusher, BitSet`1 crushClasses)
   at OpenRA.Mods.Common.Traits.Mobile.FinishedMoving(Actor self)
   at OpenRA.Mods.Common.Traits.Mobile.SetPosition(Actor self, CPos cell, SubCell subCell)
   at OpenRA.Mods.Common.Activities.Move.MoveSecondHalf.OnComplete(Actor self, Mobile mobile, Move parent)
   at OpenRA.Mods.Common.Activities.Move.MovePart.Tick(Actor self)
   at OpenRA.Activities.Activity.TickOuter(Actor self)
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act)
   at OpenRA.Activities.Activity.TickChild(Actor self)
   at OpenRA.Activities.Activity.TickOuter(Actor self)
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act)
   at OpenRA.Actor.Tick()
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)

## Replay
[OpenRA-2020-12-14T232528Z.zip](https://github.com/OpenRA/OpenRA/files/6175884/OpenRA-2020-12-14T232528Z.zip)

## Additional information

Not sure if its a bug with my map or openra.

**Comment by anvilvapre** [comment]
- The last line of function `DistanceFromEdge` results in a negative value `min2 + z * z` in `return new WDist(Exts.ISqrt(min2 + z * z));`
- `z` is the absolute value of `v.Z` therefore always positive or zero.
- `DistanceSquaredFromLineSegment` only returns `LengthSquared` therefore also only positive values.
- Which suggest a possible overflow error at the end of `DistanceSquaredFromLineSegment` when `WVec.LengthSquared` `long` is being cast to an `int`?

**Comment by KOYK** [comment]
@Leo512bit is your map modded in any way? other than using the map editor?

**Comment by Leo512bit** [comment]
@KOYK Yes its probably one of the most highly modded maps in openra https://github.com/Leo512bit/Desert-Oil-War-Map But I don't know why it would crash

Btw I'm still trying to update it for the current version of openra it would be nice to have some help.

**Comment by anvilvapre** [comment]
Is there a definition of a weapon that has a very wide range. Where it could attack something on the other side of the map. If so try reducing the range. Perhaps the impact range of a nuke?
