### ISSUE TITLE
Crashed when open map-editor

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#19270]
Exception of type `System.InvalidCastException`: Unable to cast object of type 'OpenRA.Mods.Common.Widgets.SpriteWidget' to type 'OpenRA.Mods.Common.Widgets.ResourcePreviewWidget'.

**Comment by pchote** [comment]
Can you please provide more information?

I am unable to reproduce this on bleed.

**Comment by dnqbob** [comment]
In mod SP. but I find there is no change in widget in that resource layer PR

```
Exception of type `System.Reflection.TargetInvocationException`: Exception has been thrown by the target of an invocation.
Inner
  Exception of type `System.Reflection.TargetInvocationException`: Exception has been thrown by the target of an invocation.
  Inner
    Exception of type `System.InvalidCastException`: Unable to cast object of type 'OpenRA.Mods.Common.Widgets.SpriteWidget' to type 'OpenRA.Mods.Common.Widgets.ResourcePreviewWidget'.
       at OpenRA.Widgets.Widget.GetOrNull[T](String id) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Widgets\Widget.cs:line 551
   at OpenRA.Widgets.Widget.Get[T](String id) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Widgets\Widget.cs:line 558
   at OpenRA.Mods.Common.Widgets.Logic.LayerSelectorLogic.IntializeLayerPreview(Widget widget) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Widgets\Logic\Editor\LayerSelectorLogic.cs:line 56
   at OpenRA.Mods.Common.Widgets.Logic.LayerSelectorLogic..ctor(Widget widget, WorldRenderer worldRenderer) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Widgets\Logic\Editor\LayerSelectorLogic.cs:line 39
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
```

**Comment by MustaphaTR** [comment]
SP has a custom editor.yaml and looks like i missed this change while updating the mod. Not related to OpenRA itself.
