### ISSUE TITLE
Game crashes every time I open up my map on Map editor

### ISSUE THREAD

**Issue by TheIrishEmpire** [OpenRA/OpenRA#19329]
## System Information

- Operating System:  Window 10
- OpenRA Version: release-20210321
- OpenRA Mod: Dune 2000

## Exception log

```
OpenRA engine version release-20210321
Dune 2000 mod version release-20210321
on map f9d5c15bf21cf3c6f1f8be06ea3f7264caa60e61 (Europa by TheIrishEmpire).
Date: 2021-04-09 07:31:08Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IndexOutOfRangeException`: Index was outside the bounds of the array.
   at OpenRA.Mods.D2k.Traits.D2kResourceRenderer.UpdateRenderedSprite(CPos cell, RendererCellContents content)
   at OpenRA.Mods.Common.Traits.ResourceRenderer.OpenRA.Traits.IWorldLoaded.WorldLoaded(World w, WorldRenderer wr)
   at OpenRA.World.LoadComplete(WorldRenderer wr)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Mods.Common.Widgets.Logic.MainMenuLogic.<>c__DisplayClass15_0.<LoadMapIntoEditor>b__0()
   at System.Action`1.Invoke(T obj)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)
```

**Comment by abcdefg30** [comment]
Can you share the map (or a link to your map on the resource site), please?

**Comment by TheIrishEmpire** [comment]
I start a new map and deleted the old one so I shouldve closed this one down XD
