### ISSUE TITLE
Game crashes on attempting to load - too many units saved?

### ISSUE THREAD

**Issue by MikeCaputo** [OpenRA/OpenRA#19368]
Longtime player here; I love this game! I couldn't find an issue like this, so I hope this isn't a duplicate.

I recently had the game crash when I attempted to load a saved game. I was playing the new "Europe" map; it was a _big_ game and a lot of the AI bots had accumulated a large number of troops when I saved it. So, based on that information and the line `The length of the string (297892) is longer than the maximum allowed (131072).` in the error log, it sounds like there may be a limit to how many units (?) the game can save?

I took a look at the file itself - the size is `31.8MB`. 

If there is a known limit, maybe an error message can be thrown when attempting to save.

Here is the crash log:
```
OpenRA engine version release-20210321
Red Alert mod version release-20210321
on map b15ed0de59c498fe9a3e20cfde1d90f0117aa739 (Desert Shellmap by Scott_NZ).
Date: 2021-04-23 22:34:03Z
Operating System: Linux (Unix 4.15.0.140)
Runtime Version: Mono 6.4.0.198 (tarball Tue Sep 24 01:20:30 UTC 2019) CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: The length of the string (297892) is longer than the maximum allowed (131072).
  at OpenRA.StreamExts.ReadString (System.IO.Stream s, System.Text.Encoding encoding, System.Int32 maxLength) [0x0002d] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.Network.GameSave..ctor (System.String filepath) [0x001fd] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.Mods.Common.Widgets.Logic.GameSaveBrowserLogic.Load () [0x00009] in <5ef18333659f4b3884b32134748e7e88>:0 
  at OpenRA.Mods.Common.Widgets.Logic.GameSaveBrowserLogic+<>c__DisplayClass11_0.<.ctor>b__14 () [0x00000] in <5ef18333659f4b3884b32134748e7e88>:0 
  at OpenRA.Mods.Common.Widgets.ButtonWidget.<.ctor>b__42_5 (OpenRA.MouseInput _) [0x00000] in <5ef18333659f4b3884b32134748e7e88>:0 
  at OpenRA.Mods.Common.Widgets.ButtonWidget.HandleMouseInput (OpenRA.MouseInput mi) [0x00076] in <5ef18333659f4b3884b32134748e7e88>:0 
  at OpenRA.Widgets.Widget.HandleMouseInputOuter (OpenRA.MouseInput mi) [0x00097] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.Widgets.Ui.HandleInput (OpenRA.MouseInput mi) [0x0001e] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.DefaultInputHandler+<>c__DisplayClass5_0.<OnMouseInput>b__0 () [0x00000] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.Sync.RunUnsynced[T] (System.Boolean checkSyncHash, OpenRA.World world, System.Func`1[TResult] fn) [0x00023] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.DefaultInputHandler.OnMouseInput (OpenRA.MouseInput input) [0x0000d] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.Platforms.Default.Sdl2Input.PumpInput (OpenRA.Platforms.Default.Sdl2PlatformWindow device, OpenRA.IInputHandler inputHandler, System.Nullable`1[T] lockedMousePosition) [0x00238] in <f59f7e47a16a41b3bfb9da0ae260cbf2>:0 
  at OpenRA.Platforms.Default.Sdl2PlatformWindow.PumpInput (OpenRA.IInputHandler inputHandler) [0x00006] in <f59f7e47a16a41b3bfb9da0ae260cbf2>:0 
  at OpenRA.Renderer.EndFrame (OpenRA.IInputHandler inputHandler) [0x0009f] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.Game.RenderTick () [0x001ba] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.Game.Loop () [0x0015a] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.Game.Run () [0x0003c] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00010] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.Launcher.Program.Main (System.String[] args) [0x00044] in <654d601744ea40a08007c756fb7dd724>:0 
```

**Comment by pchote** [comment]
Can you please upload the replay? If you compress it in a zip you should be able to attach it directly in a comment.

**Comment by MikeCaputo** [comment]
Good idea, thanks. I tried to upload the file but I hadn't thought to zip it up :smile: 

Here it is:
[Europe - massiva 2v8.orasav.zip](https://github.com/OpenRA/OpenRA/files/6368445/Europe.-.massiva.2v8.orasav.zip)

**Comment by bugdebugger** [comment]
The hard limit (`131072`) is defined [here](https://github.com/OpenRA/OpenRA/blob/fe129956bb1b3f7e3231c11f306f7387d36f0630/OpenRA.Game/Server/Connection.cs#L21) and was introduced on this commit 57a27eb9487a which actually reverted a much lower limit set by this PR GH-3535 .

Interestingly there is a currently open PR GH-19019 which seems to change some things related to this limit, GameSave  etc but to me it's unclear if this would help with the problem

**Comment by anvilvapre** [comment]
The pull request only renames the variable. Since a frame can have multiple orders.

Interesting that the limit was not enforced while saving, but only while reading (sending/receiving).

I assume the limit is against abuse. The MiniYaml parser has to parse the order (which is not very efficient in splitting up order lines).

**Comment by segatrade** [comment]
Also sometimes to load savegame takes more than 11 minutes

**Comment by skinkie** [comment]
This is still an issue.

```
Platform is Linux (X64)
Engine version is release-20230225
Runtime: .NET CLR 6.0.16
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1920x1200
No custom resolution provided, using desktop resolution
Using resolution: 1920x1200
Using window scale 1.00
OpenGL renderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
OpenGL version: 3.2.0 NVIDIA 535.54.03
Using default sound device
Internal mods:
	cnc: Tiberian Dawn (release-20230225)
	ra: Red Alert (release-20230225)
	d2k: Dune 2000 (release-20230225)
	modcontent: Mod Content Manager (release-20230225)
External mods:
	cnc-release-20210321: Tiberian Dawn (release-20210321)
	cnc-release-20230225: Tiberian Dawn (release-20230225)
Loading mod: cnc
Exception of type `System.InvalidOperationException`: The length of the string (567723) is longer than the maximum allowed (131072).
   at OpenRA.StreamExts.ReadString(Stream s, Encoding encoding, Int32 maxLength) in /build/openra/src/OpenRA/OpenRA.Game/StreamExts.cs:line 218
   at OpenRA.Network.GameSave..ctor(String filepath) in /build/openra/src/OpenRA/OpenRA.Game/Network/GameSave.cs:line 144
   at OpenRA.Mods.Common.Widgets.Logic.GameSaveBrowserLogic.Load() in /build/openra/src/OpenRA/OpenRA.Mods.Common/Widgets/Logic/GameSaveBrowserLogic.cs:line 331
   at OpenRA.Mods.Common.Widgets.Logic.GameSaveBrowserLogic.<>c__DisplayClass24_0.<.ctor>b__15() in /build/openra/src/OpenRA/OpenRA.Mods.Common/Widgets/Logic/GameSaveBrowserLogic.cs:line 130
   at OpenRA.Mods.Common.Widgets.ButtonWidget.<.ctor>b__41_5(MouseInput _) in /build/openra/src/OpenRA/OpenRA.Mods.Common/Widgets/ButtonWidget.cs:line 82
   at OpenRA.Mods.Common.Widgets.ButtonWidget.HandleMouseInput(MouseInput mi) in /build/openra/src/OpenRA/OpenRA.Mods.Common/Widgets/ButtonWidget.cs:line 201
   at OpenRA.Widgets.Ui.HandleInput(MouseInput mi) in /build/openra/src/OpenRA/OpenRA.Game/Widgets/Widget.cs:line 100
   at OpenRA.DefaultInputHandler.<>c__DisplayClass5_0.<OnMouseInput>b__0() in /build/openra/src/OpenRA/OpenRA.Game/Input/InputHandler.cs:line 50
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) in /build/openra/src/OpenRA/OpenRA.Game/Sync.cs:line 205
   at OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input) in /build/openra/src/OpenRA/OpenRA.Game/Input/InputHandler.cs:line 51
   at OpenRA.Platforms.Default.Sdl2Input.PumpInput(Sdl2PlatformWindow device, IInputHandler inputHandler, Nullable`1 lockedMousePosition) in /build/openra/src/OpenRA/OpenRA.Platforms.Default/Sdl2Input.cs:line 149
   at OpenRA.Platforms.Default.Sdl2PlatformWindow.PumpInput(IInputHandler inputHandler) in /build/openra/src/OpenRA/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 496
   at OpenRA.Renderer.EndFrame(IInputHandler inputHandler) in /build/openra/src/OpenRA/OpenRA.Game/Renderer.cs:line 311
   at OpenRA.Game.RenderTick() in /build/openra/src/OpenRA/OpenRA.Game/Game.cs:line 736
   at OpenRA.Game.Loop() in /build/openra/src/OpenRA/OpenRA.Game/Game.cs:line 844
   at OpenRA.Game.Run() in /build/openra/src/OpenRA/OpenRA.Game/Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in /build/openra/src/OpenRA/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /build/openra/src/OpenRA/OpenRA.Launcher/Program.cs:line 32
```
