### ISSUE TITLE
Game crashed : No rules definition for unit 1tnk.husk

### ISSUE THREAD

**Issue by Youlixx** [OpenRA/OpenRA#19381]
We we're playing an online game when the game crashed for everyone.
It's hard to know what exactly caused the crash since there were a lot of units when it happened.

Here is the log
```
OpenRA engine version release-20210321
Red Alert mod version release-20210321
on map 08017a2d5f9417f7e0b4680f0c6b14e9a7db7fab (Chernobyl 3 vs 3[LP] by Lad).
Date: 2021-04-30 13:30:47Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.NotImplementedException`: No rules definition for unit 1tnk.husk
   at OpenRA.Actor..ctor(World world, String name, TypeDictionary initDict)
   at OpenRA.Mods.Common.Traits.SpawnActorOnDeath.<>c__DisplayClass5_0.<OpenRA.Traits.INotifyRemovedFromWorld.RemovedFromWorld>b__4(World w)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)
```

[replay.zip](https://github.com/OpenRA/OpenRA/files/6405697/replay.zip)

**Comment by pchote** [comment]
This happens because the map "Chernobyl 3 vs 3[LP]" is not compatible with the latest release. You should delete the map and search for the latest version on the resource center.

The next OpenRA release will add extra checks to block you from playing on incompatible maps like this.
