### ISSUE TITLE
Crash related with missile climbs higher terrain

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#19390]
## System Information

- Operating System:  widows 10 
- MissileTA.cs modified from Missile.cs from release version last year, but crash related place was not modified since then.

## Exception log

```
OpenRA engine version 05312d7
Tiberian Aurora mod version {DEV_VERSION}
on map 97ab1d41cd0e37f1024ce8cfb7da174daf0b27fd (Chaos Valley by 零现在是小猫咪).
Date: 2021-05-04 05:03:46Z
Operating System: Windows (Microsoft Windows NT 10.0.18363.0)
Runtime Version: .NET CLR 5.0.4
Exception of type `System.InvalidOperationException`: Attempted to calculate the square root of a negative integer: -1799301
   at OpenRA.Exts.ISqrt(Int32 number, ISqrtRoundMode round) in D:\TA-Main\TiberianAurora\engine\OpenRA.Game\Exts.cs:line 281
   at OpenRA.Mods.Common.Projectiles.MissileTA.HomingInnerTick(Int32 predClfDist, Int32 diffClfMslHgt, Int32 relTarHorDist, Int32 lastHtChg, Int32 lastHt, Int32 nxtRelTarHorDist, Int32 relTarHgt, Int32 vFacing, Boolean targetPassedBy) in D:\TA-Main\TiberianAurora\OpenRA.Mods.TA\Projectiles\MissileTA.cs:line 689
   at OpenRA.Mods.Common.Projectiles.MissileTA.HomingTick(World world, WVec tarDistVec, Int32 relTarHorDist) in D:\TA-Main\TiberianAurora\OpenRA.Mods.TA\Projectiles\MissileTA.cs:line 824
   at OpenRA.Mods.Common.Projectiles.MissileTA.Tick(World world) in D:\TA-Main\TiberianAurora\OpenRA.Mods.TA\Projectiles\MissileTA.cs:line 923
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text) in D:\TA-Main\TiberianAurora\engine\OpenRA.Game\WorldUtils.cs:line 78
   at OpenRA.World.Tick() in D:\TA-Main\TiberianAurora\engine\OpenRA.Game\World.cs:line 441
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\TA-Main\TiberianAurora\engine\OpenRA.Game\Game.cs:line 646
   at OpenRA.Game.LogicTick() in D:\TA-Main\TiberianAurora\engine\OpenRA.Game\Game.cs:line 661
   at OpenRA.Game.Loop() in D:\TA-Main\TiberianAurora\engine\OpenRA.Game\Game.cs:line 823
   at OpenRA.Game.Run() in D:\TA-Main\TiberianAurora\engine\OpenRA.Game\Game.cs:line 864
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\TA-Main\TiberianAurora\engine\OpenRA.Game\Game.cs:line 274
   at OpenRA.Launcher.Program.Main(String[] args) in D:\TA-Main\TiberianAurora\engine\OpenRA.Launcher\Program.cs:line 30
```

## Additional information

The crash is due to `2 * loopRadius - h1` < 0, as you can see at picture below. 
![3](https://user-images.githubusercontent.com/13763394/116982775-cfeb3880-acfb-11eb-88e0-c127961a5785.PNG)

I try get var data by using:
![2](https://user-images.githubusercontent.com/13763394/116982867-f01af780-acfb-11eb-9b25-b7c22ed6d8ca.PNG)

When crash happens, the var data here is:
![1](https://user-images.githubusercontent.com/13763394/116982785-d4175600-acfb-11eb-8616-3f289a1ab779.PNG)

Note:
As for somewhere in "MissileTA" may affect calculation, I allow this missile will not explode when its `DistanceAboveTerrain` < 0. Don't know if this will affect the height calculation. If this affects little, the crash will affects TS style map. 
![4](https://user-images.githubusercontent.com/13763394/116984586-fe6a1300-acfd-11eb-8fb6-6a92d327c14a.PNG)

**Comment by abcdefg30** [comment]
Looks like an overflow issue, which means we probably need to use `long`s there?

**Comment by dnqbob** [comment]
I guess not? When crash happens h1=1823, loopRadius=418, and 

2 * loopRadius - h1 = -987

h1 *  (-987) = -1,799,301

it is not an overflow.

(and Int32min should be  -2147483648, which is much larger in abs)

**Comment by abcdefg30** [comment]
Then never mind me I guess. Can you propose a fix? The comment says the height needs to be found once the missile is one loop radius away, which means we probably shouldn't even use this code path when it's more than twice the radius away in distance?

**Comment by dnqbob** [comment]
For fix, I can only put a Math.abs here but I don't know if it is correct. 

>which means we probably shouldn't even use this code path when it's more than twice the radius away in distance?

Yep, but I cannot find better idea on that.

**Comment by pchote** [comment]
Can you please provide a minimal repro case for this in TS?

**Comment by dnqbob** [comment]
I am unable to reproduce this bug for I don't even know which missile trigger this crash in map and the gameplay lasts one hour, which is a shame.

**Comment by dnqbob** [comment]
I can only find out the cause and use exception to get var value in this case
