### ISSUE TITLE
Attempted to process orders from client X for frame 1 on frame X

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#19415]
```
OpenRA engine version 98caae106faa6f3ea73c448324ae450c54a7f1fe
OpenHV mod version 20210516
on map 7e57b2ac7bd6332a058bfbcf6b5129da2bf3541f (Beyond Destruction by Dzierzan).
Date: 2021-05-16 18:54:51Z
Operating System: Linux (Unix 5.3.18.152)
Runtime Version: .NET CLR 5.0.6
Exception of type `System.IO.InvalidDataException`: Attempted to process orders from client 2 for frame 1 on frame 4
   at OpenRA.Network.OrderManager.Tick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Network/OrderManager.cs:line 215
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 640
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 655
   at OpenRA.Game.Loop() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 822
   at OpenRA.Game.Run() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 875
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 276
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Launcher/Program.cs:line 32
```

```
OpenRA engine version 98caae106faa6f3ea73c448324ae450c54a7f1fe
OpenHV mod version 20210516
on map bc4432b69c5eaad95069b94b11d24c2fdc6fc7aa (Doubles by Dzierzan).
Date: 2021-05-16 19:12:04Z
Operating System: Windows (Microsoft Windows NT 10.0.19042.0)
Runtime Version: .NET CLR 5.0.6
Exception of type `System.IO.InvalidDataException`: Attempted to process orders from client 9 for frame 1 on frame 4
   at OpenRA.Network.OrderManager.Tick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Network/OrderManager.cs:line 215
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 640
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 655
   at OpenRA.Game.Loop() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 822
   at OpenRA.Game.Run() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 875
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 276
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.WindowsLauncher/Program.cs:line 71
```

**Comment by pchote** [comment]
This appears to be caused by a race between the processing of the "StartGame" immediate order and another client's non-immediate orders.

Repro case to force the issue:
```diff
diff --git a/OpenRA.Game/Network/UnitOrders.cs b/OpenRA.Game/Network/UnitOrders.cs
index 6345721f43..c1abd554c2 100644
--- a/OpenRA.Game/Network/UnitOrders.cs
+++ b/OpenRA.Game/Network/UnitOrders.cs
@@ -9,6 +9,7 @@
  */
 #endregion
 
+using System;
 using System.Collections.Generic;
 using System.Linq;
 using OpenRA.Server;
@@ -135,7 +136,12 @@ internal static void ProcessOrder(OrderManager orderManager, World world, int cl
                                                else
                                                        Game.AddSystemLine("The game has started.");
 
-                                               Game.StartGame(orderManager.LobbyInfo.GlobalSettings.Map, WorldType.Regular);
+                                               Action foo = () => Game.StartGame(orderManager.LobbyInfo.GlobalSettings.Map, WorldType.Regular);
+
+                                               if (orderManager.LocalClient.IsAdmin)
+                                                       foo();
+                                               else
+                                                       Game.RunAfterDelay(200, foo);
                                                break;
                                        }
```

**Comment by pchote** [comment]
Possibly also related to #19297 moving the `OrderManager.FramesAhead` assignment to `Game.StartGame`.
