### ISSUE TITLE
Needs help on TA capture crash

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#19482]
## mod information:
mod: TA (we don't change capture related trait)

## Exception log
```
OpenRA engine version e04eb7c
Tiberian Aurora mod version {DEV_VERSION}
on map 5abd97d54dc7b8e3b439a7dca5e5e44165004f56 (Simple Temple by Bob).
Date: 2021-07-03 10:26:53Z
Operating System: Windows (Microsoft Windows NT 10.0.19041.0)
Runtime Version: .NET CLR 5.0.7
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Mods.Common.Traits.CaptureManager.CancelCapture(Actor self, Actor target, CaptureManager targetManager) in D:\work\Projects\Git\TiberianAurora\engine\OpenRA.Mods.Common\Traits\CaptureManager.cs:line 254
   at OpenRA.Mods.Common.Activities.CaptureActor.CancelCapture(Actor self) in D:\work\Projects\Git\TiberianAurora\engine\OpenRA.Mods.Common\Activities\CaptureActor.cs:line 155
   at OpenRA.Mods.Common.Activities.CaptureActor.Cancel(Actor self, Boolean keepQueue) in D:\work\Projects\Git\TiberianAurora\engine\OpenRA.Mods.Common\Activities\CaptureActor.cs:line 149
   at OpenRA.Mods.Common.Activities.Enter.Tick(Actor self) in D:\work\Projects\Git\TiberianAurora\engine\OpenRA.Mods.Common\Activities\Enter.cs:line 141
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Git\TiberianAurora\engine\OpenRA.Game\Activities\Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Git\TiberianAurora\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 36
   at OpenRA.Actor.Tick() in D:\work\Projects\Git\TiberianAurora\engine\OpenRA.Game\Actor.cs:line 267
   at OpenRA.World.Tick() in D:\work\Projects\Git\TiberianAurora\engine\OpenRA.Game\World.cs:line 437
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\work\Projects\Git\TiberianAurora\engine\OpenRA.Game\Game.cs:line 646
   at OpenRA.Game.LogicTick() in D:\work\Projects\Git\TiberianAurora\engine\OpenRA.Game\Game.cs:line 661
   at OpenRA.Game.Loop() in D:\work\Projects\Git\TiberianAurora\engine\OpenRA.Game\Game.cs:line 823
   at OpenRA.Game.Run() in D:\work\Projects\Git\TiberianAurora\engine\OpenRA.Game\Game.cs:line 864
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\work\Projects\Git\TiberianAurora\engine\OpenRA.Game\Game.cs:line 274
   at OpenRA.Launcher.Program.Main(String[] args) in D:\work\Projects\Git\TiberianAurora\engine\OpenRA.Launcher\Program.cs:line 30
```

## Reproduce
It is very easy to reproduce: let AI engineer capture the Conyard, undeploy conyard before capture finish.

It is very strange and confuse us for a long time, since default mods and other mods don't have this problem. However we cannot figure out the problem result in this crash

**Comment by dnqbob** [comment]
## For conyard

	CaptureManager:
	Capturable:
		Types: building
	CapturableProgressBar:
	CapturableProgressBlink:

## For engineer

	Captures@Building:
		CaptureTypes: building
		CaptureDelay: 175
	CaptureManager:

**Comment by dnqbob** [comment]
https://gitee.com/CastleJing/TiberianAurora

our repo. There are not too many units in TA so it won't be too complicated.

**Comment by pchote** [comment]
This appears to be a real engine bug.

When the conyard deploys back into the MCV `CaptureActor.TickInner` runs and takes the `enterActor != target.Actor` branch. This sets `enterActor` to the mcv and `enterCaptureManager` to null because the mcv does not have a `CaptureManager` trait.

The check below explicitly handles `enterCaptureManager` being null, but this then calls through to `CaptureManager.CancelCapture` which *doesn't* explicitly handle `targetManager` being null.

This doesn't crash in RA because all vehicles there do have the `CaptureManager` trait to support hijacking. Adding this to your `mcv` definition works around the crash, but we should fix this properly in the code.

**Comment by pchote** [comment]
RA also disables the capture trait while undeploying and disables undeploy while being captured, adding an additional level of protection against the crash.

**Comment by dnqbob** [comment]
Thanks!

**Comment by dnqbob** [comment]
I think @MustaphaTR fixed this in rv-engine branch, during my test the engineer will abort capturing if undeploy the conyard but I cannot find where is the fix on this crash.

So I guess I will just add manager to TA mcv, since Milk may take ra1 style of capturing of conyard.
