### ISSUE TITLE
A Crash related to harvester pathfinder

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#19579]
Post Updated to OpenRA/Bleed- f4a5878a532a5cd86ca4b611b416387d6917f444

## Log
```
OpenRA engine version {DEV_VERSION}
Tiberian Sun mod version {DEV_VERSION}
on map e462e9e7af638481849b51fcd9f6f8dc925f73f8 (Name your map here by Your name here).
Date: 2021-08-02 23:21:49Z
Operating System: Windows (Microsoft Windows NT 10.0.19043.0)
Runtime Version: .NET CLR 5.0.7
Exception of type `System.IndexOutOfRangeException`: Index was outside the bounds of the array.
   at OpenRA.Mods.Common.Pathfinder.PathGraph.GetConnections(CPos position) in D:\work\Projects\Github\OpenRA\OpenRA.Mods.Common\Pathfinder\PathGraph.cs:line 136
   at OpenRA.Mods.Common.Pathfinder.PathSearch.Expand() in D:\work\Projects\Github\OpenRA\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 150
   at OpenRA.Mods.Common.Traits.PathFinder.FindPath(IPathSearch search) in D:\work\Projects\Github\OpenRA\OpenRA.Mods.Common\Traits\World\PathFinder.cs:line 139
   at OpenRA.Mods.Common.Pathfinder.PathFinderUnitPathCacheDecorator.FindPath(IPathSearch search) in D:\work\Projects\Github\OpenRA\OpenRA.Mods.Common\Pathfinder\PathFinderUnitPathCacheDecorator.cs:line 82
   at OpenRA.Mods.Common.Activities.FindAndDeliverResources.ClosestHarvestablePos(Actor self) in D:\work\Projects\Github\OpenRA\OpenRA.Mods.Common\Activities\FindAndDeliverResources.cs:line 219
   at OpenRA.Mods.Common.Activities.FindAndDeliverResources.Tick(Actor self) in D:\work\Projects\Github\OpenRA\OpenRA.Mods.Common\Activities\FindAndDeliverResources.cs:line 115
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\OpenRA\OpenRA.Game\Activities\Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\OpenRA\OpenRA.Game\Traits\ActivityUtils.cs:line 30
   at OpenRA.Actor.Tick() in D:\work\Projects\Github\OpenRA\OpenRA.Game\Actor.cs:line 271
   at OpenRA.World.Tick() in D:\work\Projects\Github\OpenRA\OpenRA.Game\World.cs:line 433
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\work\Projects\Github\OpenRA\OpenRA.Game\Game.cs:line 624
   at OpenRA.Game.LogicTick() in D:\work\Projects\Github\OpenRA\OpenRA.Game\Game.cs:line 639
   at OpenRA.Game.Loop() in D:\work\Projects\Github\OpenRA\OpenRA.Game\Game.cs:line 806
   at OpenRA.Game.Run() in D:\work\Projects\Github\OpenRA\OpenRA.Game\Game.cs:line 859
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\work\Projects\Github\OpenRA\OpenRA.Game\Game.cs:line 277
   at OpenRA.Launcher.Program.Main(String[] args) in D:\work\Projects\Github\OpenRA\OpenRA.Launcher\Program.cs:line 32
```
## Related map
map:
[testcrash2.zip](https://github.com/OpenRA/OpenRA/files/6920439/testcrash2.zip)

## Reproduce:
1. use a map (like in this post) 
 - of 128*64 
 - without resource layer 
 - in OpenRA-TS
 - made by OpenRA Map Editor
2. build a refinery 
3. Oops

**Comment by dnqbob** [comment]
128*64 map generation may be the crash spot

Update:
It can 100% reproduce in TS in my test

**Comment by dnqbob** [comment]
OK, I confirmed that OpenRA TS also has this crash bug

**Comment by dnqbob** [comment]
Is there any idea on how to avoid this crash? I guess SP will have a release version soon.

**Comment by pchote** [comment]
This is going to be a regression from #19524. Someone needs to study that in detail with your stack trace in mind and work out what is going wrong.

**Comment by pchote** [comment]
> OK, I confirmed that OpenRA TS also has this crash bug

Can you please upload the replay and mention which bleed commit it is based on?

**Comment by dnqbob** [comment]
Ummm wait for 1 hour, I will directly change this post to OpenRA version I tested.

**Comment by dnqbob** [comment]
@pchote  done

**Comment by anvilvapre** [comment]
Line 136: 	`		var posLayer = position.Layer;`

That doesn't seem to make sense?

**Comment by pchote** [comment]
Running the testcase in a debugger shows that it actually crashes on the new `if (info[neighbor].Status == CellStatus.Closed)` line. `neighbour` needs to be validated as a valid cell first!

**Comment by anvilvapre** [comment]
It happens when the neighbour position falls outside map bounds?

**Comment by anvilvapre** [comment]
Yeah, Locomotor does this check (ofcourse):
`                      if (!world.Map.Contains(destNode))                      
                                return short.MaxValue;                          
                                                  `

**Comment by anvilvapre** [comment]
The/a solution would be combine the two `if`'s and to only check the status when neighbour is not max int.

**Comment by pchote** [comment]
That sounds reasonable. Do you want to file a PR with that fix?
