### ISSUE TITLE
A crash related to revoking condition in GrantConditionOnDamageState

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#19619]
Our engine based on 2d0e704

log:
```
OpenRA engine version 13bc7dc
Shattered Paradise mod version {DEV_VERSION}
on map 76424132e5b28f98c4b38918144ebc3e8828c2a7 (Way to Uganda by Morton).
Date: 2021-08-20 09:53:51Z
Operating System: Windows (Microsoft Windows NT 10.0.19043.0)
Runtime Version: .NET CLR 5.0.7
Exception of type `System.InvalidOperationException`: Attempting to revoke condition with invalid token 1 for sonic 1031.
   at OpenRA.Actor.RevokeCondition(Int32 token) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Actor.cs:line 595
   at OpenRA.Mods.Common.Traits.GrantConditionOnDamageState.OpenRA.Mods.Common.Traits.INotifyDamageStateChanged.DamageStateChanged(Actor self, AttackInfo e) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionOnDamageState.cs:line 83
   at OpenRA.Mods.Common.Traits.Health.InflictDamage(Actor self, Actor attacker, Damage damage, Boolean ignoreModifiers) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Traits\Health.cs:line 208
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, WarheadArgs args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Warheads\SpreadDamageWarhead.cs:line 107
   at OpenRA.Mods.Common.Warheads.DamageWarhead.DoImpact(Target& target, WarheadArgs args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Warheads\DamageWarhead.cs:line 64
   at OpenRA.GameRules.WeaponInfo.Impact(Target& target, WarheadArgs args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\GameRules\WeaponInfo.cs:line 241
   at OpenRA.Mods.AS.Projectiles.BulletAS.Explode(World world) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.AS\Duplicates\Projectiles\BulletAS.cs:line 332
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\WorldUtils.cs:line 75
   at OpenRA.World.Tick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\World.cs:line 437
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 624
   at OpenRA.Game.LogicTick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 639
   at OpenRA.Game.Loop() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 806
   at OpenRA.Game.Run() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 859
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 277
   at OpenRA.Launcher.Program.Main(String[] args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Launcher\Program.cs:line 32
```

I am sure that we don't change any on this trait, and in YAML we won't use 1 as condition string.

**Comment by pchote** [comment]
Can you please provide the replay that triggers this?

**Comment by dnqbob** [comment]
dude I have replay but it is based on SP, b4a9519

**Comment by dnqbob** [comment]
Is it sufficient?

**Comment by dnqbob** [comment]
[sp-2021-04-14T045955Z.zip](https://github.com/OpenRA/OpenRA/files/7021610/sp-2021-04-14T045955Z.zip)
Sorry here is the file.
@pchote 

Update:
This version: [b4a9519](https://github.com/ABrandau/Shattered-Paradise-SDK/commit/b4a9519d26d55299468cee3a2cb5288c38964b46)

**Comment by dnqbob** [comment]
Here is some guessing on reproducing on OpenRA itself:
Add multiple GrantConditionOnDamageState trait that : trigger on FullHealth, HeavyDamaged&Critical, Critical, Critical

**Comment by pchote** [comment]
The replay desyncs on the first tick when played back on SP commit b4a9519. Are you sure this is the correct version?

**Comment by dnqbob** [comment]
We are really running out of idea on this

**Comment by dnqbob** [comment]
> The replay desyncs on the first tick when played back on SP commit b4a9519. Are you sure this is the correct version?

Wait, let me check it out

**Comment by dnqbob** [comment]
OK I just get another reproducing:
Version (newest):
[Version](https://github.com/ABrandau/Shattered-Paradise-SDK/commit/1690dc2f095da1ef6aed4bbdf2f620fdc559e0b1)
Replay: 
[sp-2021-08-20T130732Z.zip](https://github.com/OpenRA/OpenRA/files/7021674/sp-2021-08-20T130732Z.zip)
Log:
[Logs.zip](https://github.com/OpenRA/OpenRA/files/7021683/Logs.zip)


@pchote
