### ISSUE TITLE
Loading maps in the editor crashes

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#19652]
## System Information

- Operating System:  Linux
- OpenRA Version: e0e219793ff7b39bdec98b45fe9f0785d0612956
- OpenRA Mod: ra
- Source: self-compiled
- Mono version: 6.8.0.105

## Exception log
```
Exception of type `System.IO.InvalidDataException`: Received packet from disconnected client '0'
   at OpenRA.Network.OrderManager.ReceiveOrders(Int32 clientId, ValueTuple`2 orders) in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Network/OrderManager.cs:line 162
   at OpenRA.Network.NetworkConnection.OpenRA.Network.IConnection.Receive(OrderManager orderManager) in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Network/Connection.cs:line 315
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0() in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Sync.cs:line 166
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Sync.cs:line 190
   at OpenRA.Sync.RunUnsynced(Boolean checkSyncHash, World world, Action fn) in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Sync.cs:line 167
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:line 628
   at OpenRA.Game.LogicTick() in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:line 643
   at OpenRA.Game.Loop() in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:line 810
   at OpenRA.Game.Run() in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:line 863
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:line 281
   at OpenRA.Launcher.Program.Main(String[] args) in /home/matthias/Entwicklung/OpenRA/OpenRA.Launcher/Program.cs:line 32
```

**Comment by pchote** [comment]
Regression was introduced by 6421c1751546ad275e4e00546a78046761c45ce2, but its not yet clear to me exactly how.

**Comment by abcdefg30** [comment]
That comment changes the debug statement to throw. We don't have any client in `pendingOrders` because there are no clients in the lobby for the map editor.

**Comment by abcdefg30** [comment]
The actual change "causing" this seems to be https://github.com/OpenRA/OpenRA/commit/d10c59298787f925ebf7cec6804d210084172e81.
