### ISSUE TITLE
A crash related to TSResourceLayer.IsValidResourceNeighbour

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#19788]
```
OpenRA engine version d21cdf66d3062e4b270e7af8e9d71b702ab9c03f
末世天堂(SP Simplified Chinese) mod version spsc-20211023
on map f2eabb8aeb42503523b775118cebf8e68184489d (Metropolis by Humble - J MegaTank.edit.).
Date: 2021-10-31 12:52:49Z
Operating System: Windows (Microsoft Windows NT 10.0.19043.0)
Runtime Version: .NET CLR 5.0.11
Exception of type `System.IndexOutOfRangeException`: Index was outside the bounds of the array.
   at OpenRA.Mods.Cnc.Traits.TSResourceLayer.IsValidResourceNeighbour(CPos cell, CPos neighbour)
   at OpenRA.Mods.Cnc.Traits.TSResourceLayer.<>c__DisplayClass9_0.<AllowResourceAt>b__0(CPos c)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at OpenRA.Mods.Cnc.Traits.TSResourceLayer.AllowResourceAt(String resourceType, CPos cell)
   at OpenRA.Mods.Common.Traits.ResourceLayer.CanAddResource(String resourceType, CPos cell, Int32 amount)
   at OpenRA.Mods.Common.Traits.ResourceLayer.OpenRA.Mods.Common.Traits.IResourceLayer.CanAddResource(String resourceType, CPos cell, Int32 amount)
   at OpenRA.Mods.Common.Traits.SeedsResource.Seed(Actor self)
   at OpenRA.Mods.Common.Traits.SeedsResource.OpenRA.Traits.ITick.Tick(Actor self)
   at OpenRA.TraitDictionary.TraitContainer`1.ApplyToAllTimed(Action`2 action, String text)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)
```
![bug](https://user-images.githubusercontent.com/13763394/139586114-37af0c20-d742-4966-9381-90dea97f4cf4.PNG)

**Comment by dnqbob** [comment]
I guess it maybe a map edge check?

**Comment by abcdefg30** [comment]
Filed #19789.
