### ISSUE TITLE
NullReferenceException in OpenRA.Sound.PlayPredefined

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#19837]
Happened on https://github.com/OpenRA/OpenRA/commit/3bde4ebbaf9801e58c3f62a516670db015950bca after some play time where I annoyed the AI and it started to hunt my units down.

```
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Sound.PlayPredefined(SoundType soundType, Ruleset ruleset, Player p, Actor voicedActor, String type, String definition, String variant, Boolean relative, WPos pos, Single volumeModifier, Boolean attenuateVolume) in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Game/Sound/Sound.cs:line 344
   at OpenRA.Sound.PlayNotification(Ruleset rules, Player player, String type, String notification, String variant) in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Game/Sound/Sound.cs:line 426
   at OpenRA.Mods.Common.Traits.Sound.ActorLostNotification.OpenRA.Mods.Common.Traits.INotifyKilled.Killed(Actor self, AttackInfo e) in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Mods.Common/Traits/Sound/ActorLostNotification.cs:line 38
   at OpenRA.Mods.Common.Traits.Health.InflictDamage(Actor self, Actor attacker, Damage damage, Boolean ignoreModifiers) in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Mods.Common/Traits/Health.cs:line 221
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, WarheadArgs args) in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Mods.Common/Warheads/SpreadDamageWarhead.cs:line 106
   at OpenRA.GameRules.WeaponInfo.Impact(Target& target, WarheadArgs args) in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Game/GameRules/WeaponInfo.cs:line 235
   at OpenRA.Mods.Common.Projectiles.Bullet.Explode(World world) in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Mods.Common/Projectiles/Bullet.cs:line 324
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text) in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Game/WorldUtils.cs:line 75
   at OpenRA.World.Tick() in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Game/World.cs:line 430
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Game/Game.cs:line 623
   at OpenRA.Game.LogicTick() in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Game/Game.cs:line 638
   at OpenRA.Game.Loop() in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Game/Game.cs:line 803
   at OpenRA.Game.Run() in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Game/Game.cs:line 856
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Game/Game.cs:line 294
   at OpenRA.Launcher.Program.Main(String[] args) in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Launcher/Program.cs:line 32
```

**Comment by Dzierzan** [comment]
Been testing OpenHV with the latest bleed changes. It crashes for me as well.

[exception-2021-12-05T160628Z.log](https://github.com/OpenRA/OpenRA/files/7656324/exception-2021-12-05T160628Z.log)
[exception-2021-12-05T160019Z.log](https://github.com/OpenRA/OpenRA/files/7656325/exception-2021-12-05T160019Z.log)
