### ISSUE TITLE
NullReferenceException in LobbyCommands.MissionBriefingOrDefault

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#19861]
## System Information
- Operating System: Linux
- OpenRA Version: 5fcc0490401036139f181cdeac479dfeb1d451a0
- OpenRA Mod: hv
- Source: AppImage

## Exception log
```
[2021-12-27T17:52:49] Felix has disconnected.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenRA.Mods.Common.Server.LobbyCommands.MissionBriefingOrDefault(Server server) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/ServerTraits/LobbyCommands.cs:line 1097
   at OpenRA.Mods.Common.Server.LobbyCommands.ClientJoined(Server server, Connection conn) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/ServerTraits/LobbyCommands.cs:line 1117
   at OpenRA.Server.Server.<>c__DisplayClass37_0.<ValidateClient>b__0() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Server/Server.cs:line 489
   at OpenRA.Server.Server.<>c__DisplayClass37_1.<ValidateClient>b__5() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Server/Server.cs:line 596
   at OpenRA.Server.Server.CallbackEvent.OpenRA.Server.Server.IServerEvent.Invoke(Server server) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Server/Server.cs:line 1407
   at OpenRA.Server.Server.<>c__DisplayClass30_0.<.ctor>b__2(Object _) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Server/Server.cs:line 288
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Aborted
```

## Additional information
The part of the code in question is unmodified
https://github.com/OpenRA/OpenRA/blob/9eab92e90aff1b86bd2aff78fcc09c315f223729/OpenRA.Mods.Common/ServerTraits/LobbyCommands.cs#L1097

**Comment by anvilvapre** [comment]
Does your mod rules define a 'world' actor? This is required if have a rules yaml. In bleed, MapPreview.cs line 140. It will not use the default - if any rules definitions are present.

Otherwise I assume that `Map` (MapPreview) is `null`.

**Comment by Mailaender** [comment]
Yes https://github.com/OpenHV/OpenHV/blob/master/mods/hv/rules/world.yaml#L262
