### ISSUE TITLE
Restarting a map after changing the Lua script crashes with a map not found exception

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#20012]
```
Exception of type `System.InvalidOperationException`: Map 016ee2032e81e5d7bbda6d1ea0bbb0509b1bfab7 not found
   at OpenRA.Mods.Common.Server.LobbyCommands.ServerStarted(Server server) in \OpenRA\OpenRA.Mods.Common\ServerTraits\LobbyCommands.cs:line 1134
   at OpenRA.Server.Server.<>c__DisplayClass52_0.<.ctor>b__2(Object _) in \OpenRA\OpenRA.Game\Server\Server.cs:line 346
   at System.Threading.Thread.StartCallback()
```
Easiest testcase is starting a mission, editing the Lua script and then restarting. Might also crash when yaml changes are applied.

**Comment by pchote** [comment]
IMO this is a major use case for the map reindexing feature, so the map cache really should be able to remap from the old UID to the new one so the restart feature can behave as you'd expect.
