### ISSUE TITLE
NullReferenceException @ hash_ChangesHealth

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#20061]
by @MustaphaTR via Discord

```
OpenRA engine version faa3be3
Shattered Paradise mod version release-20220529
on map 9100d05cb6e324aa32f515ea6d10fc7ed905b0ed (Atacama by StolenTech).
Date: 2022-06-06 06:53:32Z
Operating System: Windows (Microsoft Windows NT 10.0.19043.0)
Runtime Version: .NET CLR 6.0.5
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at hash_ChangesHealth(Object )
   at OpenRA.World.SyncHash()
   at OpenRA.Network.OrderManager.ProcessOrders()
   at OpenRA.Network.OrderManager.TryTick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)
```

**Comment by anvilvapre** [comment]
can be closed?

**Comment by anvilvapre** [comment]
ping
