### ISSUE TITLE
File not found: shadow.des or shroud.tem

### ISSUE THREAD

**Issue by geersch** [OpenRA/OpenRA#20094]
Hi, was able to compile the game locally and run D2K, but after installing the assets for the RA, CNC and TS mods the game crashes.

## System Information

- Operating System:  Apple M1 Pro - macOS Monterey 12.4
- OpenRA Version:  {DEV_VERSION}, cloned from `bleed`
- OpenRA Mod: RA, CNC and TS
- Source: self-compiled
- For self-compiled or third-party packages:  Followed instructions in `install.md` and had to install some dependencies manually as described in this issue (https://github.com/OpenRA/OpenRA/issues/19805).

```bash
brew install sdl2
brew install openal-soft
brew install freetype
brew install lua51
```

```bash
ln -s /opt/homebrew/Cellar/sdl2/2.0.16/lib/libSDL2.dylib            libSDL2.dylib       
ln -s /opt/homebrew/Cellar/freetype/2.11.0/lib/libfreetype.6.dylib  libfreetype6.dylib  
ln -s /opt/homebrew/Cellar/lua@5.1/5.1.5_8/lib/liblua.5.1.5.dylib   liblua51.dylib      
ln -s /opt/homebrew/opt/openal-soft/lib/libopenal.dylib             libsoft_oal.dylib
```

After following these steps I was able to build OpenRA (`make`) and run it (`e.g. ./launch-game.sh Game.Mod=ra`). The d2k mod works without an issue. For `ra`, `cnc` and `ts` I can download the assets via quick install, but after the installation it crashes. It complains about a missing file. For `ra` and `cnc` it cannot find `shadow.des` and for `ts` it cannot find `shroud.tem`. 

## Exception log

```
OpenRA engine version {DEV_VERSION}
Tiberian Sun mod version {DEV_VERSION}
Date: 2022-06-27 20:21:39Z
Operating System: OSX (Unix 12.4.0)
Runtime Version: .NET CLR 6.0.6
Exception of type `System.IO.FileNotFoundException`: File not found: shroud.tem
   at OpenRA.Mods.Common.Graphics.FileNotFoundSequence.OpenRA.Graphics.ISpriteSequence.GetSprite(Int32 frame) in /OpenRA/OpenRA.Mods.Common/Graphics/DefaultSpriteSequence.cs:line 119
   at OpenRA.Mods.Common.Traits.ShroudRenderer..ctor(World world, ShroudRendererInfo info) in /OpenRA/OpenRA.Mods.Common/Traits/World/ShroudRenderer.cs:line 150
   at OpenRA.Mods.Common.Traits.ShroudRendererInfo.Create(ActorInitializer init) in /OpenRA/OpenRA.Mods.Common/Traits/World/ShroudRenderer.cs:line 58
   at OpenRA.Actor..ctor(World world, String name, TypeDictionary initDict) in /OpenRA/OpenRA.Game/Actor.cs:line 161
   at OpenRA.World..ctor(ModData modData, Map map, OrderManager orderManager, WorldType type) in /OpenRA/OpenRA.Game/World.cs:line 214
   at OpenRA.Game.StartGame(String mapUID, WorldType type) in /OpenRA/OpenRA.Game/Game.cs:line 190
   at OpenRA.Game.LoadShellMap() in /OpenRA/OpenRA.Game/Game.cs:line 504
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args) in /OpenRA/OpenRA.Mods.Common/LoadScreens/BlankLoadScreen.cs:line 101
   at OpenRA.Game.InitializeMod(String mod, Arguments args) in /OpenRA/OpenRA.Game/Game.cs:line 490
   at OpenRA.Mods.Common.LoadScreens.ModContentLoadScreen.<>c__DisplayClass6_0.<StartGame>b__1() in /OpenRA/OpenRA.Mods.Common/LoadScreens/ModContentLoadScreen.cs:line 63
   at OpenRA.Primitives.ActionQueue.PerformActions(Int64 currentTime) in /OpenRA/OpenRA.Game/Primitives/ActionQueue.cs:line 53
   at OpenRA.Game.LogicTick() in /OpenRA/OpenRA.Game/Game.cs:line 637
   at OpenRA.Game.Loop() in /OpenRA/OpenRA.Game/Game.cs:line 800
   at OpenRA.Game.Run() in /OpenRA/OpenRA.Game/Game.cs:line 850
   at OpenRA.Game.InitializeAndRun(String[] args) in /OpenRA/OpenRA.Game/Game.cs:line 293
   at OpenRA.Launcher.Program.Main(String[] args) in /OpenRA/OpenRA.Launcher/Program.cs:line 32
```

**Comment by abcdefg30** [comment]
Thanks for the report! This is the same issue as #20093 and will be fixed by https://github.com/OpenRA/OpenRA/pull/20087.

**Comment by geersch** [comment]
Thanks, missed that issue. I checked out the PR and tested locally. Can start up the CNC, RA and TS mods now. Will close this issue.
