### ISSUE TITLE
Exception of type `System.IO.InvalidDataException`: nuyell5.aud is not a valid sound file!

### ISSUE THREAD

**Issue by sambonz** [OpenRA/OpenRA#20128]
Hi!
Playing Mission 2 of Tiberian Dawn and it crashes around 5 sec into the map.
All other missions load and play just fine.
Have re-copied all assets into C:\Users\User\AppData\Roaming\OpenRA\Content\cnc multiple times.

Crash Log:

OpenRA engine version release-20210321
Tiberian Dawn mod version release-20210321
on map bf0436c15eb322aa2eca14d3084f040108218c30 (02:   Knock out the Refinery by Westwood Studios).
Date: 2022-07-15 16:45:21Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.InvalidDataException`: nuyell5.aud is not a valid sound file!
   at OpenRA.Sound.LoadSound[T](String filename, Func`2 loadFormat)
   at OpenRA.Exts.GetOrAdd[K,V](Dictionary`2 d, K k, Func`2 createFn)
   at OpenRA.Sound.PlayPredefined(SoundType soundType, Ruleset ruleset, Player p, Actor voicedActor, String type, String definition, String variant, Boolean relative, WPos pos, Single volumeModifier, Boolean attenuateVolume)
   at OpenRA.Mods.Common.Traits.Voiced.OpenRA.Traits.IVoiced.PlayVoiceLocal(Actor self, String phrase, String variant, Single volume)
   at OpenRA.VoiceExts.PlayVoiceLocal(Actor self, String phrase, Single volume)
   at OpenRA.Mods.Common.Traits.Sound.DeathSounds.OpenRA.Mods.Common.Traits.INotifyKilled.Killed(Actor self, AttackInfo e)
   at OpenRA.Mods.Common.Traits.Health.InflictDamage(Actor self, Actor attacker, Damage damage, Boolean ignoreModifiers)
   at OpenRA.Mods.Common.Warheads.DamageWarhead.InflictDamage(Actor victim, Actor firedBy, HitShape shape, WarheadArgs args)
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, WarheadArgs args)
   at OpenRA.Mods.Common.Warheads.DamageWarhead.DoImpact(Target& target, WarheadArgs args)
   at OpenRA.GameRules.WeaponInfo.Impact(Target& target, WarheadArgs args)
   at OpenRA.Mods.Common.Projectiles.Bullet.Explode(World world)
   at OpenRA.Mods.Common.Projectiles.Bullet.Tick(World world)
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)

**Comment by sambonz** [comment]
Found the resolution courtesy of this comment:
[https://gist.github.com/abcdefg30/a4fe1110c2727c3960e340ae2ce45bc0?permalink_comment_id=3541919#gistcomment-3541919](https://gist.github.com/abcdefg30/a4fe1110c2727c3960e340ae2ce45bc0?permalink_comment_id=3541919#gistcomment-3541919)

**Comment by Mailaender** [comment]
Duplicate of https://github.com/OpenRA/OpenRA/issues/11735
