### ISSUE TITLE
Improve translation linting

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#20247]
Taken [from Discord](https://discord.com/channels/153649279762694144/388282819371204608/1013774462602203136), by @abcdefg30:

> we should implement a setup similar to what we did for sequence references for translations
```cs
        [TranslationReference("team")]
        static readonly string Team = "team-no-team";
```
> hardcodes the "team" and leads to errors like #20229 since "team" has to be used in code
so ideally this would also be some sort of
```cs
        [TranslationReference(<second tuple value>)]
        static readonly string Team = new TranslationTuple("team-no-team", "team");
```
> (pseudocode-ish)
and then use `Team.Key` and `Team.Parameter` in the code instead of a hardcoded string for the parameter

I think this should be addressed before we do an official release of the new translation system to mitigate issues modders and translators might run into.

**Comment by penev92** [comment]
#20262 made me think the approach we've taken is way too fragile. Potentially even expanding on the above suggestion, turning the current simple string fields that just hold the id of the translatable string into something more complicated like a struct that holds the key and also does the call to Translation.GetString() internally might give us something much more robust.

To be fair this last part would likely (mostly) be relevant only until the initial implementation of translations everywhere is done, with very limited risk of breakage later, but is still worth considering.

**Comment by dragunoff** [comment]
We'd need to also add support for linting translations with attributes if we want to implement https://github.com/OpenRA/OpenRA/pull/20207#issuecomment-1239542263

**Comment by penev92** [comment]
Attributes sound great.
Another thing that just came to mind - linting isn't going to work great with #20265 and its follow-ups, is it? We can lint translations in the C# code, but not in Lua. Would be nice if anyone has an idea how to improve on that as well.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/20393 added a regression:
> OpenRA.Utility(1,1): Warning: Unused key `slowest` in common|languages/en.ftl.
> OpenRA.Utility(1,1): Warning: Unused key `slower` in common|languages/en.ftl.
> OpenRA.Utility(1,1): Warning: Unused key `normal` in common|languages/en.ftl.
> OpenRA.Utility(1,1): Warning: Unused key `fast` in common|languages/en.ftl.
> OpenRA.Utility(1,1): Warning: Unused key `faster` in common|languages/en.ftl.
> OpenRA.Utility(1,1): Warning: Unused key `fastest` in common|languages/en.ftl.

because `GameSpeed` is not lintable as adding `[TranslationReference]` fails:

```
Error: OpenRA.Mods.Common.Lint.CheckTranslationReference failed with exception: System.ArgumentException: Field 'Name' defined on type 'OpenRA.GameSpeed' is not a field on the target object which is of type 'System.String'.
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at OpenRA.Mods.Common.Lint.CheckTranslationReference.Run(Action`1 emitError, Action`1 emitWarning, ModData modData) in /home/matthias/Entwicklung/OpenRA/OpenHV/engine/OpenRA.Mods.Common/Lint/CheckTranslationReference.cs:line 42
   at OpenRA.Mods.Common.UtilityCommands.CheckYaml.OpenRA.IUtilityCommand.Run(Utility utility, String[] args) in /home/matthias/Entwicklung/OpenRA/OpenHV/engine/OpenRA.Mods.Common/UtilityCommands/CheckYaml.cs:line 72
```

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/20400 fixes it.
