### ISSUE TITLE
Pathfinding Crash: abstract graph should consider reachable

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#20255]
## System Information & mod
System: Win10 x64
Mod: SP, Enigne is [rv-engine](https://github.com/MustaphaTR/OpenRA/commits/rv-engine) at 57e78d6, mod is [here](https://github.com/ABrandau/Shattered-Paradise-SDK).

Map is "Way to Uganda", and  replay: 
[sp-2022-09-04T070323Z.zip](https://github.com/OpenRA/OpenRA/files/9484242/sp-2022-09-04T070323Z.zip)

## Log
```
Exception of type `System.Exception`: The abstract path should never be searched for an unreachable point. This is a bug. Failed lookup for an abstract cell.
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.<>c__DisplayClass39_0.<Heuristic>b__0(CPos cell) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\HierarchicalPathFinder.cs:line 0
   at OpenRA.Mods.Common.Pathfinder.PathSearch.Expand() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 237
   at OpenRA.Mods.Common.Pathfinder.PathSearch.FindPath() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 286
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.FindPath(Actor self, IReadOnlyCollection`1 sources, CPos target, BlockedByActor check, Int32 heuristicWeightPercentage, Func`2 customCost, Actor ignoreActor, Boolean laneBias, PathFinderOverlay pathFinderOverlay) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\HierarchicalPathFinder.cs:line 748
   at OpenRA.Mods.Common.Traits.PathFinder.FindPathToTargetCell(Actor self, IEnumerable`1 sources, CPos target, BlockedByActor check, Func`2 customCost, Actor ignoreActor, Boolean laneBias) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Traits\World\PathFinder.cs:line 89
   at OpenRA.Mods.Common.Activities.MoveAdjacentTo.CalculatePathToTarget(Actor self, BlockedByActor check) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\MoveAdjacentTo.cs:line 131
   at OpenRA.Mods.Common.Activities.Move.EvalPath(BlockedByActor check) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\Move.cs:line 114
   at OpenRA.Mods.Common.Activities.Move.OnFirstRun(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\Move.cs:line 129
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 147
   at OpenRA.Mods.Common.Activities.MoveAdjacentTo.Tick(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\MoveAdjacentTo.cs:line 103
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 147
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Actor.Tick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Actor.cs:line 262
   at OpenRA.World.Tick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\World.cs:line 441
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 636
   at OpenRA.Game.LogicTick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 651
   at OpenRA.Game.Loop() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 816
   at OpenRA.Game.Run() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 869
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Launcher\Program.cs:line 32
```

**Comment by dnqbob** [comment]
I am testing if [2a681d3](https://github.com/OpenRA/OpenRA/commit/2a681d37916515fc4ddc8806c054154a13fc232a) fix it

Update:
Nope, guess need a fix

**Comment by RoosterDragon** [comment]
Thanks for the replay - it would've be hard to diagnose without one! Very much appreciated.

I have updated #20212 to cover this. The failure to update aircraft correctly is the trigger for the crash here. By fixing that we also fix this.

**Comment by dnqbob** [comment]
Thanks for the quick fix!

**Comment by henryliang21** [comment]
Hi, not sure if this is fixed, but I am on MacOS and my code is at commit ee0d958cd107cb1e3f3332c2f21d4c7a0a1653ba, and I am still experiencing the crash.

This is the console output.
```
Platform is OSX
Engine version is {DEV_VERSION}
Runtime: .NET CLR 6.0.8
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1.00
OpenGL renderer: Intel(R) Iris(TM) Plus Graphics OpenGL Engine
OpenGL version: 4.1 INTEL-18.8.4
Using default sound device
AL lib: (WW) GetProcPath: Failed to readlink /proc/self/file: No such file or directory
AL lib: (WW) alc_initconfig: Failed to initialize backend "jack"
Internal mods:
	cnc: Tiberian Dawn ({DEV_VERSION})
	d2k: Dune 2000 ({DEV_VERSION})
	all: All mods ({DEV_VERSION})
	ra: Red Alert ({DEV_VERSION})
	modcontent: Mod Content Manager ({DEV_VERSION})
	ts: Tiberian Sun ({DEV_VERSION})
External mods:
	ra-{DEV_VERSION}: Red Alert ({DEV_VERSION})
	ra2-{DEV_VERSION}: Red Alert 2 ({DEV_VERSION})
	cnc-{DEV_VERSION}: Tiberian Dawn ({DEV_VERSION})
Loading mod: ra
[2022-09-08T23:59:42] Game started
[2022-09-08T23:59:55] Game started
[2022-09-09T00:00:07] Game started
Exception of type `System.Exception`: The abstract path should never be searched for an unreachable point. This is a bug. Failed lookup for an abstract cell.
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.<>c__DisplayClass40_0.<Heuristic>b__0(CPos cell)
   at OpenRA.Mods.Common.Pathfinder.PathSearch.Expand() in /Users/henryliang/source/OpenRA/OpenRA.Mods.Common/Pathfinder/PathSearch.cs:line 237
   at OpenRA.Mods.Common.Pathfinder.PathSearch.FindBidiPath(PathSearch first, PathSearch second) in /Users/henryliang/source/OpenRA/OpenRA.Mods.Common/Pathfinder/PathSearch.cs:line 320
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.FindPath(Actor self, CPos source, CPos target, BlockedByActor check, Int32 heuristicWeightPercentage, Func`2 customCost, Actor ignoreActor, Boolean laneBias, PathFinderOverlay pathFinderOverlay) in /Users/henryliang/source/OpenRA/OpenRA.Mods.Common/Pathfinder/HierarchicalPathFinder.cs:line 865
   at OpenRA.Mods.Common.Traits.PathFinder.FindPathToTargetCell(Actor self, IEnumerable`1 sources, CPos target, BlockedByActor check, Func`2 customCost, Actor ignoreActor, Boolean laneBias) in /Users/henryliang/source/OpenRA/OpenRA.Mods.Common/Traits/World/PathFinder.cs:line 89
   at OpenRA.Mods.Common.Activities.Move.<>c__DisplayClass15_0.<.ctor>b__0(BlockedByActor check) in /Users/henryliang/source/OpenRA/OpenRA.Mods.Common/Activities/Move/Move.cs:line 78
   at OpenRA.Mods.Common.Activities.Move.EvalPath(BlockedByActor check) in /Users/henryliang/source/OpenRA/OpenRA.Mods.Common/Activities/Move/Move.cs:line 108
   at OpenRA.Mods.Common.Activities.Move.OnFirstRun(Actor self) in /Users/henryliang/source/OpenRA/OpenRA.Mods.Common/Activities/Move/Move.cs:line 123
   at OpenRA.Activities.Activity.TickOuter(Actor self) in /Users/henryliang/source/OpenRA/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in /Users/henryliang/source/OpenRA/OpenRA.Game/Traits/ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in /Users/henryliang/source/OpenRA/OpenRA.Game/Activities/Activity.cs:line 144
   at OpenRA.Mods.Common.Activities.AttackMoveActivity.Tick(Actor self) in /Users/henryliang/source/OpenRA/OpenRA.Mods.Common/Activities/Move/AttackMoveActivity.cs:line 80
   at OpenRA.Activities.Activity.TickOuter(Actor self) in /Users/henryliang/source/OpenRA/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in /Users/henryliang/source/OpenRA/OpenRA.Game/Traits/ActivityUtils.cs:line 31
   at OpenRA.Actor.Tick() in /Users/henryliang/source/OpenRA/OpenRA.Game/Actor.cs:line 262
   at OpenRA.World.Tick() in /Users/henryliang/source/OpenRA/OpenRA.Game/World.cs:line 441
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /Users/henryliang/source/OpenRA/OpenRA.Game/Game.cs:line 636
   at OpenRA.Game.LogicTick() in /Users/henryliang/source/OpenRA/OpenRA.Game/Game.cs:line 651
   at OpenRA.Game.Loop() in /Users/henryliang/source/OpenRA/OpenRA.Game/Game.cs:line 820
   at OpenRA.Game.Run() in /Users/henryliang/source/OpenRA/OpenRA.Game/Game.cs:line 873
   at OpenRA.Game.InitializeAndRun(String[] args) in /Users/henryliang/source/OpenRA/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /Users/henryliang/source/OpenRA/OpenRA.Launcher/Program.cs:line 32

OpenRA has encountered a fatal error.
Please refer to the crash logs and FAQ for more information.
```

**Comment by dnqbob** [comment]
This fix is not yet merged, you can see https://github.com/OpenRA/OpenRA/pull/20212

**Comment by RoosterDragon** [comment]
@dnqbob if you get a crash on a version that uses the changes in #20212 for either the "The abstract path should never be searched for an unreachable point." or the "Cannot AddInfluence until previous influence is removed with RemoveInfluence" exceptions I would be happy to take a look at the replay.

**Comment by dnqbob** [comment]
Sure. Actually I am looking into add a setting to avoid adding influence in Aircraft to fix related bug.
