### ISSUE TITLE
Crash related to add/remove influence on carryall

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#20402]
This bug can reproduce in bleed easily

## System Information

- Operating System:  Win10
- OpenRA Version: OpenRA https://github.com/OpenRA/OpenRA/commit/425c678cd91455b6aa92e59bbacf73c6e1be9d56
- OpenRA Mod: TS

## Exception log
```
OpenRA engine version {DEV_VERSION}
Tiberian Sun mod version {DEV_VERSION}
on map e48e630c007119d652b84488e135b99175164440 (Way to Uganda by Morton).
Date: 2022-10-26 08:06:43Z
Operating System: Windows (Microsoft Windows NT 10.0.19043.0)
Runtime Version: .NET CLR 6.0.10
Exception of type `System.InvalidOperationException`: Cannot AddInfluence until previous influence is removed with RemoveInfluence
   at OpenRA.Mods.Common.Traits.Aircraft.AddInfluence(IEnumerable`1 landingCells) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Traits\Air\Aircraft.cs:line 860
   at OpenRA.Mods.Common.Traits.Aircraft.AddInfluence(CPos landingCell) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Traits\Air\Aircraft.cs:line 870
   at OpenRA.Mods.Common.Activities.Land.Tick(Actor self) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Activities\Air\Land.cs:line 232
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Activities\Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Actor.Tick() in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Actor.cs:line 262
   at OpenRA.World.Tick() in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\World.cs:line 441
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Game.cs:line 639
   at OpenRA.Game.LogicTick() in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Game.cs:line 654
   at OpenRA.Game.Loop() in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Game.cs:line 823
   at OpenRA.Game.Run() in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Launcher\Program.cs:line 32
```

## Replay & Reproduce
[Replay.zip](https://github.com/OpenRA/OpenRA/files/9867492/Replay.zip)
Reproduce:
1. build a carryall (refered as A) and a carryable (refered as B)
2. order A to carry B, but when A is landing and almost get B, order A to go away
3. order A land or try to carry B again
4. crash

![carryallbug-showcase](https://user-images.githubusercontent.com/13763394/197983563-867e119c-9ad4-42e4-81a2-051a3e3c4763.gif)

**Comment by dnqbob** [comment]
@RoosterDragon @PunkPun 
You can have a test to see if #20313 and #20401 can fix it, otherwise we have to deal with it in another fix

**Comment by ThomasChr** [comment]
Can't recreate on bleed on 425c678cd91455b6aa92e59bbacf73c6e1be9d56 - either I'm too stuipd or it has already been fixed?
As soon as the Carryall is near my buggy I can't give him any new orders. So there's no "let him drive away"...

**Comment by dnqbob** [comment]
>  So there's no "let him drive away"...

Order the carryall to go away, not the buggy

You can also try the replay to see if it will result in crash

**Comment by ThomasChr** [comment]
So it was my fault. Yes, I can reproduce it now without any problems.

**Comment by PunkPun** [comment]
That's weird, I swear I tried this in #20212 and it didn't crash back then. This needs some investigation

**Comment by PunkPun** [comment]
Oh it appears carryall doesn't use takeoff activity when cancelling the pickup activity, what means it never removes influence. Instead it just uses fly

**Comment by PunkPun** [comment]
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Activities/PickupUnit.cs#L71-L77 gets called, but https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Activities/Air/Land.cs#L79-L104 doesn't
