### ISSUE TITLE
Failed mapserver response parsing leads to future connection drops on the server

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#20442]
@SeanScherer set the map of a dedicated server to https://resource.openra.net/maps/40312/ which caused

```
[2022-11-07T10:58:40] Failed parsing mapserver response: System.ArgumentNullException: Value cannot be null. (Parameter 's')
   at System.Convert.FromBase64String(String s)
   at OpenRA.MapPreview.UpdateRemoteSearch(MapStatus status, MiniYaml yaml, Action`1 parseMetadata) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Map/MapPreview.cs:line 445
[2022-11-07T10:58:40] Remote map query failed with error: System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenRA.Mods.Common.Server.LobbyCommands.LoadMapSettings(Server server, Global gs, MapPreview map) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/ServerTraits/LobbyCommands.cs:line 1196
   at OpenRA.Mods.Common.Server.LobbyCommands.<>c__DisplayClass56_1.<Map>b__0(MapPreview map) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/ServerTraits/LobbyCommands.cs:line 582
   at OpenRA.MapPreview.UpdateRemoteSearch(MapStatus status, MiniYaml yaml, Action`1 parseMetadata) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Map/MapPreview.cs:line 462
   at OpenRA.MapCache.<>c__DisplayClass30_0.<<QueryRemoteMapDetails>b__4>d.MoveNext() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Map/MapCache.cs:line 250
[2022-11-07T10:58:40] URL was: https://resource.openra.net/map/hash/5476952d21e66312b1033439af32bf25d0aeb483/yaml
```

and then crashes every time a user tries to join:

```
[2022-11-08T16:00:04] Dropping connection XXX.XX.XXX.XXX:35650 because an error occurred:
[2022-11-08T16:00:04] System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenRA.Mods.Common.Server.LobbyCommands.MissionBriefingOrDefault(Server server) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/ServerTraits/LobbyCommands.cs:line 1251
   at OpenRA.Mods.Common.Server.LobbyCommands.ClientJoined(Server server, Connection conn) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/ServerTraits/LobbyCommands.cs:line 1271
   at OpenRA.Server.Server.<>c__DisplayClass61_0.<ValidateClient>b__0() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Server/Server.cs:line 573
   at OpenRA.Server.Server.ValidateClient(Connection newConn, String data) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Server/Server.cs:line 690
```

**Comment by anvilvapre** [comment]
In bleed, this is the base64 decoding of the preview image. 


```
var r = FieldLoader.Load<RemoteMapData>(yaml)
...
try                                     
{                                       
        newData.Preview = new Png(new MemoryStream(Convert.FromBase64String(r.minimap)));
}                                       
catch (Exception e)                     
{                                       
        Log.Write("debug", "Failed parsing mapserver minimap response: {0}", e);
        newData.Preview = null;         
} 
``` 

When requesting https://resource.openra.net/map/hash/5476952d21e66312b1033439af32bf25d0aeb483 

minimap value in yaml is set to:
```
"minimap": "iVBORw0KGgoAAAANSUhEUgAAADwAAAA8CAYAAAA6/NlyAAADN0lEQVR4nNTaS24TQRAG4JFYcxiugOR7cQRWrFkiIZFNeOQlyC4sUBAK2ygnQNwAaEtt2TP1+P+q6sFZlCIbPNNfv6a7pqerLz//rB3vTm8OPl+/ekuFdE30t9MquOs7Fcxiy8EPD78XkcHOW3P+XRZaArY+R7H9M9ud0fvRYKs154WMtixTULaCQ2BzHBZ2Y6+g0SG0OliDMeAoFoUfgD9efA+BtfGJXgPBvnj5eheZypiQQlnfe1C2l0hAK6xrbDYbH6xFFLr/m/OrH6VYtgJ2YLRLotCnz57sYn6NMwedwSLoiW0pCyeFVHEfzm+HQBH0lMFGwB198v7rMKwJzmCj4I6OgKfnbxZRDvZQI8ASzIqjBp+efXPHbxasoac5aCRYm+X/K1gqcFXrWhNkFk116RFgb9yiaLQC4Oew120j3VrDIo/ACBjFLiYtpPDsbIy2brSLM9gFGJnAJDRyo+gCx0MzWBE8IrLL13340YMrsJXooWAJ2/ao0j6VQZdNWlXAyH55rVY+AFflo9lg81oZNJTEOzZwR2uPqRRYS+xZIb292L9+RS56GDgyDr3ekgV7CxEIrMUcbI1zdOy3XpMFW6suy2KCWxqmgy0gO8m1a158vlPB2cyHds8DsJWezU5oUoVoQ6UizaNh3S6deTx5v7WSAJnNv4WFwBbGivb/kFVVVaYDrdgtWJs4LHCk1ef56AwUxcJgCxUBz2/urZbQYLBbsPZ4GAFufy//zc5Sy0ZQLFYFe2M30p17Adrfin2thtTOkITBmQKNBs+/k3ouDK46zVMNZg7LiGANh4CR98sdXIVmz46EwdJjjDkJUIVmz45M0pceWHtuR8AZdOSwzCTtUh4DOJpCgsDW5p0B7xcSATNLxjKwh+1r5XZ2Azkj0j8/SjCSoZT+3dswWNhewf16ny65FJS4W0LAzKkfDaphGYCU9y4BMznn6Evv6MKjvIWZNfSa2DJwJtbEDgEzr06Q1mVnY/Z+IXDkOavdfBQ20roi2FtYtLi//wXX9DG17gKsvRHQ4EhXHwHOvJlc5LS8YG/ggdfEbsEM9ljAUWwIzMIrwdnWHQ5GHklrYlv8FUCAAQBqY7GKWfqdkQAAAABJRU5ErkJggg==",
```

Which i can decode and seems to result in a valid png.

So unless the API was unstable, unlikely as it would have failed earlier, the issue seems to orignate from MapCache.

MapCache calls MapPreview.UpdateRemoteSearch with status DownloadAvailable in one location, line 250. 

Does `var result = await httpResponseMessage.Content.ReadAsStreamAsync();` read the JSON response in full also when the server replies in http chunks?

**Comment by anvilvapre** [comment]
debug log should contain the URL
```
                                              Log.Write("debug", "Remote map query failed with error: {0}", e);
                                              Log.Write("debug", "URL was: {0}", url);

```

Map cache seems to download map info for multiple (up to 50 in a single request) maps. Likely one of the 50 RemoteMapData json entries lacks a minimap yaml field value - causing the error.

Having the URL would help.

**Comment by Mailaender** [comment]
> [2022-11-07T10:58:40] URL was: https://resource.openra.net/map/hash/5476952d21e66312b1033439af32bf25d0aeb483/yaml

**Comment by anvilvapre** [comment]
I see. Then only map info for the map with that has was being requested. Then it might be a multi threading issue.
