### ISSUE TITLE
Pathfinding crash on abstract cell

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#20443]
## System Information

- Operating System:  Win10
- OpenRA Version: [OpenMeow a67643e](https://github.com/EoralMilk/OpenMeow), but we don't change the pathfinding part
- OpenRA Mod: TS

## Exception log

```
OpenRA engine version {DEV_VERSION}
OpenRA Language: en
Tiberian Sun mod version ${DEV_VERSION}
on map 7fa8133194727bb88fc7c304bd3f9e4ef2db5d0e (Oasis Trouble by BornL33T).
Date: 2022-11-09 09:37:30Z
Operating System: Windows (Microsoft Windows NT 10.0.19045.0)
Runtime Version: .NET CLR 6.0.11
Installed Language: zh (Installed) zh (Current) zh (Current UI)
Exception of type `System.Exception`: The abstract path should never be searched for an unreachable point. This is a bug. Failed lookup for an abstract cell.
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.<>c__DisplayClass40_0.<Heuristic>b__0(CPos cell) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Pathfinder\HierarchicalPathFinder.cs:line 0
   at OpenRA.Mods.Common.Pathfinder.PathSearch.Expand() in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 241
   at OpenRA.Mods.Common.Pathfinder.PathSearch.FindPath() in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 290
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.FindPath(Actor self, IReadOnlyCollection`1 sources, CPos target, BlockedByActor check, Int32 heuristicWeightPercentage, Func`2 customCost, Actor ignoreActor, Boolean laneBias, PathFinderOverlay pathFinderOverlay) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Pathfinder\HierarchicalPathFinder.cs:line 755
   at OpenRA.Mods.Common.Traits.PathFinder.FindPathToTargetCell(Actor self, IEnumerable`1 sources, CPos target, BlockedByActor check, Func`2 customCost, Actor ignoreActor, Boolean laneBias) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Traits\World\PathFinder.cs:line 89
   at OpenRA.Mods.Common.Activities.MoveAdjacentTo.CalculatePathToTarget(Actor self, BlockedByActor check) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Activities\Move\MoveAdjacentTo.cs:line 131
   at OpenRA.Mods.Common.Activities.Move.EvalPath(BlockedByActor check) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Activities\Move\Move.cs:line 115
   at OpenRA.Mods.Common.Activities.Move.OnFirstRun(Actor self) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Activities\Move\Move.cs:line 130
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Activities\Activity.cs:line 147
   at OpenRA.Mods.Common.Activities.MoveAdjacentTo.Tick(Actor self) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Activities\Move\MoveAdjacentTo.cs:line 103
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Activities\Activity.cs:line 147
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Actor.Tick() in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Actor.cs:line 300
   at OpenRA.World.Tick() in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\World.cs:line 454
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Game.cs:line 649
   at OpenRA.Game.LogicTick() in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Game.cs:line 664
   at OpenRA.Game.Loop() in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Game.cs:line 840
   at OpenRA.Game.Run() in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Game.cs:line 893
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Game.cs:line 317
   at OpenRA.Launcher.Program.Main(String[] args) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Launcher\Program.cs:line 32
```

## Replay
[replay.zip](https://github.com/OpenRA/OpenRA/files/9970620/replay.zip)

## Additional information
In my debugging, 
![bug](https://user-images.githubusercontent.com/13763394/200821151-8ae0262e-0d0c-4662-98c9-b6f89a69b3ec.png)
![bug2](https://user-images.githubusercontent.com/13763394/200821165-326809d8-1f1b-481f-9ba9-de9b618938ac.png)

It seems it is not related with subterrain unit this time

**Comment by PunkPun** [comment]
I'm unable to run that branch. 

[graphics.log](https://github.com/OpenRA/OpenRA/files/9971346/graphics.log)

**Comment by dnqbob** [comment]
1. Did you run it in window mode or full screen mode? Our changed render layer doesn't support full screen mode for now
2. You may need to upgrade your graphic driver? Our changed render layer requires at least Opengl 3.0

**Comment by PunkPun** [comment]
Apple has deprecated OpenGL a long time ago, so it may be an issue related to that.

When launching

> Platform is OSX
Engine version is {DEV_VERSION}
Runtime: .NET CLR 6.0.1
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1680x1050
Using resolution: 1024x768
Using window scale 2.00
OpenGL renderer: AMD Radeon Pro 450 OpenGL Engine
OpenGL version: 4.1 ATI-4.8.101
Renderer initialization failed. Check graphics.log for details.

./launch-game.sh Game.Mod=ts Graphics.Mode=Windowed

didn't help

**Comment by dnqbob** [comment]
So maybe @RoosterDragon can run it?

**Comment by PunkPun** [comment]
According to [link](https://support.apple.com/en-us/HT202823) my pc should support OpenGL 4.1

these are the warnings I get when compiling [warnings.log](https://github.com/OpenRA/OpenRA/files/9971938/warnings.log)

**Comment by dnqbob** [comment]
The warnings are normal, we don't obey the code style temporarily for there are some functions and lines need test until we decide to use them to replace original function, and only 2 of our members are working on it for developing TS functions and support a proper 3d render to OpenRA

**Comment by dnqbob** [comment]
> Platform is OSX
Engine version is {DEV_VERSION}
Runtime: .NET CLR 6.0.1
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1680x1050
Using resolution: 1024x768
Using window scale 2.00
OpenGL renderer: AMD Radeon Pro 450 OpenGL Engine
OpenGL version: 4.1 ATI-4.8.101
Renderer initialization failed. Check graphics.log for details.

This is mine:
```
Platform is Windows
Engine version is {DEV_VERSION}
Runtime: .NET CLR 6.0.11
Using SDL 2 with OpenGL (ANGLE) renderer
Desktop resolution: 1600x900
Using resolution: 1572x806
Using window scale 1.00
OpenGL renderer: ANGLE (Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0)
OpenGL version: OpenGL ES 3.0.0 (ANGLE 2.1.0.ea8043b73f93)
Using default sound device
```

You can switch to OpenGL (ANGLE) renderer to try again

**Comment by PunkPun** [comment]
Angle is used to translate OpenGL (or WebGL) to DirectX or Vulcan. It doesn't seem like it translates OpenGL ES 3 into Metal though, besides, on bleed it doesn't look like we even use Angle for mac

**Comment by dnqbob** [comment]
> It doesn't seem like it translates OpenGL ES 3 into Metal

umm this is a trouble on our new render, will tell milk

Can mac use Vulcan instead?

**Comment by PunkPun** [comment]
From what I gather, not really. MoltenVK (VK standing for Vulcan) tries to translate Vulcan To Metal, but from some quick googling it looks pretty poor and it would be incredibly bad for performance to do OpenGL -> ANGLE -> Vulcan -> MoltenVK -> Metal

**Comment by dnqbob** [comment]
>  OpenGL -> ANGLE -> Vulcan -> Metal

God. We need a better idea on mac, this chain is indeed too long

**Comment by PunkPun** [comment]
The proper way is to use the modern OpenGL profile. See the first comment in https://stackoverflow.com/questions/41120025/isnt-it-possible-to-run-opengl-3-0-on-macbok-pro-2015-mid-with-glfw3

**Comment by dnqbob** [comment]
>  OpenGL -> ANGLE -> Vulcan -> Metal

God, we need a better idea on mac, this chain is indeed too long

**Comment by RoosterDragon** [comment]
I was able to replicate and diagnose the issue successfully, thank you very much for the report and the replay!

**Comment by dnqbob** [comment]
also hope you have fun if you play it!
