### ISSUE TITLE
bleed, ExceptionHandler, npe

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#20461]
bleed, Ubuntu,

At start up. Due to a write permission issue an exception is correctly raised. However the handling of the exception causes below stack trace - and does not show the actual exception.

```
 ./launch-game.sh Game.Mod=ra
Platform is Linux
Engine version is {DEV_VERSION}
Runtime: .NET CLR 6.0.10
Exception of type `System.ArgumentNullException`: Value cannot be null. (Parameter 'format')
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.Text.StringBuilder.AppendFormat(String format, Object[] args)
   at OpenRA.ExceptionHandler.AppendIndentedFormatLine(StringBuilder sb, Int32 indent, String format, Object[] args) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 61
   at OpenRA.ExceptionHandler.BuildExceptionReport(Exception ex, StringBuilder sb, Int32 indent) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 102
   at OpenRA.ExceptionHandler.BuildExceptionReport(Exception ex, StringBuilder sb, Int32 indent) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 99
   at OpenRA.ExceptionHandler.BuildExceptionReport(Exception ex) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 56
   at OpenRA.ExceptionHandler.HandleFatalError(Exception ex) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 49
   at OpenRA.Launcher.Program.Main(String[] args) in /home/user/source/cs/OpenRA/OpenRA.Launcher/Program.cs:line 36

Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'format')
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.Text.StringBuilder.AppendFormat(String format, Object[] args)
   at OpenRA.ExceptionHandler.AppendIndentedFormatLine(StringBuilder sb, Int32 indent, String format, Object[] args) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 61
   at OpenRA.ExceptionHandler.BuildExceptionReport(Exception ex, StringBuilder sb, Int32 indent) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 102
   at OpenRA.ExceptionHandler.BuildExceptionReport(Exception ex, StringBuilder sb, Int32 indent) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 99
   at OpenRA.ExceptionHandler.BuildExceptionReport(Exception ex) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 56
   at OpenRA.ExceptionHandler.HandleFatalError(Exception ex) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 49
   at OpenRA.Launcher.Program.Main(String[] args) in /home/user/source/cs/OpenRA/OpenRA.Launcher/Program.cs:line 36
Aborted (core dumped)
OpenRA has encountered a fatal error.
Please refer to the crash logs and FAQ for more information.

Log files are located in /home/user/.openra/Logs
The FAQ is available at http://wiki.openra.net/FAQ
````

After adding some logging before calling ExceptionHandler:

```
--------------begin of System.Console.WriteLine(e)
--------- System.UnauthorizedAccessException: Access to the path '/home/user/.openra/Logs/perf.log' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.CreateText(String path)
   at OpenRA.Log.AddChannel(String channelName, String baseFilename, Boolean isTimestamped) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/Log.cs:line 148
   at OpenRA.Game.Initialize(Arguments args) in /home/user/source/cs/OpenRA/OpenRA.Game/Game.cs:line 348
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/user/source/cs/OpenRA/OpenRA.Game/Game.cs:line 304
   at OpenRA.Launcher.Program.Main(String[] args) in /home/user/source/cs/OpenRA/OpenRA.Launcher/Program.cs:line 32
Exception of type `System.ArgumentNullException`: Value cannot be null. (Parameter 'format')
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.Text.StringBuilder.AppendFormat(String format, Object[] args)
   at OpenRA.ExceptionHandler.AppendIndentedFormatLine(StringBuilder sb, Int32 indent, String format, Object[] args) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 61
   at OpenRA.ExceptionHandler.BuildExceptionReport(Exception ex, StringBuilder sb, Int32 indent) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 102
   at OpenRA.ExceptionHandler.BuildExceptionReport(Exception ex, StringBuilder sb, Int32 indent) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 99
   at OpenRA.ExceptionHandler.BuildExceptionReport(Exception ex) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 56
   at OpenRA.ExceptionHandler.HandleFatalError(Exception ex) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 49
   at OpenRA.Launcher.Program.Main(String[] args) in /home/user/source/cs/OpenRA/OpenRA.Launcher/Program.cs:line 37
--------------end of System.Console.WriteLine(e)

Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'format')
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.Text.StringBuilder.AppendFormat(String format, Object[] args)
   at OpenRA.ExceptionHandler.AppendIndentedFormatLine(StringBuilder sb, Int32 indent, String format, Object[] args) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 61
   at OpenRA.ExceptionHandler.BuildExceptionReport(Exception ex, StringBuilder sb, Int32 indent) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 102
   at OpenRA.ExceptionHandler.BuildExceptionReport(Exception ex, StringBuilder sb, Int32 indent) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 99
   at OpenRA.ExceptionHandler.BuildExceptionReport(Exception ex) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 56
   at OpenRA.ExceptionHandler.HandleFatalError(Exception ex) in /home/user/source/cs/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 49
   at OpenRA.Launcher.Program.Main(String[] args) in /home/user/source/cs/OpenRA/OpenRA.Launcher/Program.cs:line 37
Aborted (core dumped)
```

**Comment by anvilvapre** [comment]
Cause is a stack trace (string) being passed as format parameter to a StringBuilder. Possible dangerous from a security point of view. 

Likely the result of replacing old format arguments with formatted strings.

**Comment by Mailaender** [comment]
Can't reproduce

```
./launch-game.sh 
Platform is Linux
Engine version is {DEV_VERSION}
Runtime: .NET CLR 6.0.11
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/home/matthias/Entwicklung/OpenRA/OpenRA/Support/Logs' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at OpenRA.Log.FilenamesForChannel(String baseFilename)+MoveNext()
   at OpenRA.Log.AddChannel(String channelName, String baseFilename, Boolean isTimestamped) in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Game/Support/Log.cs:line 148
   at OpenRA.ExceptionHandler.HandleFatalError(Exception ex) in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Game/Support/ExceptionHandler.cs:line 24
   at OpenRA.Launcher.Program.Main(String[] args) in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Launcher/Program.cs:line 36
Aborted
```

**Comment by anvilvapre** [comment]
i could, when fixing a few days later. but it happens only when ex.StackTrace is null. which is a bit odd because in my example i can log a stack trace.

the access persmission issue was caused by a different user owning the files. perhaps that makes the difference.
