### ISSUE TITLE
Add influence about land, again.

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#20468]
## Version
Mod: d2k, 
at https://github.com/OpenRA/OpenRA/commit/621c85059ec92f550ad25044063f73ed326ae8fa, with some changes to yaml, see Replay below.

## Log
```
OpenRA engine version {DEV_VERSION}
OpenRA Language: en
Dune 2000 mod version ${DEV_VERSION}
on map 594ed72bbd471e3c61ed1a68c60e3fab74d10141 (Desert Twister by Psydev).
Date: 2022-11-20 09:24:22Z
Operating System: Windows (Microsoft Windows NT 10.0.19045.0)
Runtime Version: .NET CLR 6.0.11
Installed Language: zh (Installed) zh (Current) zh (Current UI)
Exception of type `System.InvalidOperationException`: Cannot AddInfluence until previous influence is removed with RemoveInfluence
   at OpenRA.Mods.Common.Traits.Aircraft.AddInfluence(ValueTuple`2[] landingCells) in D:\work\Projects\Github\OpenRA\OpenRA.Mods.Common\Traits\Air\Aircraft.cs:line 871
   at OpenRA.Mods.Common.Traits.Aircraft.AddInfluence(CPos landingCell) in D:\work\Projects\Github\OpenRA\OpenRA.Mods.Common\Traits\Air\Aircraft.cs:line 882
   at OpenRA.Mods.Common.Activities.Land.Tick(Actor self) in D:\work\Projects\Github\OpenRA\OpenRA.Mods.Common\Activities\Air\Land.cs:line 232
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\OpenRA\OpenRA.Game\Activities\Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\OpenRA\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in D:\work\Projects\Github\OpenRA\OpenRA.Game\Activities\Activity.cs:line 144
   at OpenRA.Mods.Common.Activities.PickupUnit.Tick(Actor self) in D:\work\Projects\Github\OpenRA\OpenRA.Mods.Common\Activities\PickupUnit.cs:line 129
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\OpenRA\OpenRA.Game\Activities\Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\OpenRA\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in D:\work\Projects\Github\OpenRA\OpenRA.Game\Activities\Activity.cs:line 144
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\OpenRA\OpenRA.Game\Activities\Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\OpenRA\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Actor.Tick() in D:\work\Projects\Github\OpenRA\OpenRA.Game\Actor.cs:line 262
   at OpenRA.World.Tick() in D:\work\Projects\Github\OpenRA\OpenRA.Game\World.cs:line 441
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\work\Projects\Github\OpenRA\OpenRA.Game\Game.cs:line 639
   at OpenRA.Game.LogicTick() in D:\work\Projects\Github\OpenRA\OpenRA.Game\Game.cs:line 654
   at OpenRA.Game.Loop() in D:\work\Projects\Github\OpenRA\OpenRA.Game\Game.cs:line 823
   at OpenRA.Game.Run() in D:\work\Projects\Github\OpenRA\OpenRA.Game\Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\work\Projects\Github\OpenRA\OpenRA.Game\Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in D:\work\Projects\Github\OpenRA\OpenRA.Launcher\Program.cs:line 32
```

## Replay:
[replay.zip](https://github.com/OpenRA/OpenRA/files/10049319/replay.zip)
You need to copy the yamls under 'denpendency' to cover the original one. Those changes just affect AI and give 4 carryall when game starts.

**Comment by Mailaender** [comment]
Confirmed, happens on a game with AI when they build Carryalls:

```
Exception of type `System.InvalidOperationException`: Cannot AddInfluence until previous influence is removed with RemoveInfluence
   at OpenRA.Mods.Common.Traits.Aircraft.AddInfluence(IEnumerable`1 landingCells) in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/Air/Aircraft.cs:line 873
   at OpenRA.Mods.Common.Traits.Aircraft.AddInfluence(CPos landingCell) in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/Air/Aircraft.cs:line 884
   at OpenRA.Mods.Common.Activities.Land.Tick(Actor self) in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Mods.Common/Activities/Air/Land.cs:line 232
   at OpenRA.Activities.Activity.TickOuter(Actor self) in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Game/Traits/ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Game/Activities/Activity.cs:line 144
   at OpenRA.Mods.Common.Activities.PickupUnit.Tick(Actor self) in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Mods.Common/Activities/PickupUnit.cs:line 116
   at OpenRA.Activities.Activity.TickOuter(Actor self) in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Game/Traits/ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Game/Activities/Activity.cs:line 144
   at OpenRA.Activities.Activity.TickOuter(Actor self) in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Game/Traits/ActivityUtils.cs:line 31
   at OpenRA.Actor.Tick() in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Game/Actor.cs:line 262
   at OpenRA.World.Tick() in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Game/World.cs:line 441
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 636
   at OpenRA.Game.LogicTick() in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 651
   at OpenRA.Game.Loop() in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 820
   at OpenRA.Game.Run() in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 873
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /home/matthias/Entwicklung/OpenRA/OpenRA/OpenRA.Launcher/Program.cs:line 32
```

**Comment by abcdefg30** [comment]
#20489 was merged just into prep, so on bleed this will still happen.
