### ISSUE TITLE
Crash related to abstract cell again

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#20475]
## System Information
- OpenRA Mod: SP on https://github.com/ABrandau/Shattered-Paradise-SDK/tree/sync-test

## Exception log
```
OpenRA engine version f60bfb9
OpenRA Language: en
Shattered Paradise mod version ${DEV_VERSION}
on map 12b35c47aae1b7bdd48cbe3ee831dc5b1132738d (Borrowed Time by StolenTech).
Date: 2022-11-21 07:05:21Z
Operating System: Windows (Microsoft Windows NT 10.0.19045.0)
Runtime Version: .NET CLR 6.0.11
Installed Language: zh (Installed) zh (Current) zh (Current UI)
Exception of type `System.Exception`: The abstract path should never be searched for an unreachable point. This is a bug. Failed to route to abstract cell.
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.<>c__DisplayClass40_0.<Heuristic>b__0(CPos cell) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\HierarchicalPathFinder.cs:line 1146
   at OpenRA.Mods.Common.Pathfinder.PathSearch.Expand() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 247
   at OpenRA.Mods.Common.Pathfinder.PathSearch.FindPath() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 296
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.FindPath(Actor self, IReadOnlyCollection`1 sources, CPos target, BlockedByActor check, Int32 heuristicWeightPercentage, Func`2 customCost, Actor ignoreActor, Boolean laneBias, PathFinderOverlay pathFinderOverlay) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\HierarchicalPathFinder.cs:line 783
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.FindPath(Actor self, CPos source, CPos target, BlockedByActor check, Int32 heuristicWeightPercentage, Func`2 customCost, Actor ignoreActor, Boolean laneBias, PathFinderOverlay pathFinderOverlay) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\HierarchicalPathFinder.cs:line 899
   at OpenRA.Mods.Common.Traits.PathFinder.FindPathToTargetCell(Actor self, IEnumerable`1 sources, CPos target, BlockedByActor check, Func`2 customCost, Actor ignoreActor, Boolean laneBias) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Traits\World\PathFinder.cs:line 89
   at OpenRA.Mods.Common.Activities.Move.<>c__DisplayClass16_0.<.ctor>b__0(BlockedByActor check) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\Move.cs:line 83
   at OpenRA.Mods.Common.Activities.Move.EvalPath(BlockedByActor check) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\Move.cs:line 115
   at OpenRA.Mods.Common.Activities.Move.PopPath(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\Move.cs:line 0
   at OpenRA.Mods.Common.Activities.Move.MoveFirstHalf.OnComplete(Actor self, Mobile mobile, Move parent) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\Move.cs:line 528
   at OpenRA.Mods.Common.Activities.Move.MovePart.Tick(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\Move.cs:line 484
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 147
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 147
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 147
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Actor.Tick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Actor.cs:line 262
   at OpenRA.World.Tick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\World.cs:line 441
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 639
   at OpenRA.Game.LogicTick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 654
   at OpenRA.Game.Loop() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 823
   at OpenRA.Game.Run() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Launcher\Program.cs:line 32
```

## Replay
[replay-pathfind.zip](https://github.com/OpenRA/OpenRA/files/10054154/replay-pathfind.zip)

**Comment by dnqbob** [comment]
The engine we use is https://github.com/MustaphaTR/OpenRA/commit/f60bfb9921b0dca50d10cf2db95bc72b702e2db3, which is up to https://github.com/OpenRA/OpenRA/commit/b8a71215eb93e57eb22e1147fbed1f5bf07639d7 on the upstream

**Comment by anvilvapre** [comment]
@RoosterDragon

**Comment by anvilvapre** [comment]
Wanted to take a look. But `OpenRA.Mods.Common//Traits/World/PathFinder.cs` line 89 in the stack trace does not seem to match with https://github.com/OpenRA/OpenRA/commit/b8a71215eb93e57eb22e1147fbed1f5bf07639d7. 

So the `PathFinder.cs` in https://github.com/MustaphaTR/OpenRA/commit/f60bfb9921b0dca50d10cf2db95bc72b702e2db3 differs from the one in https://github.com/OpenRA/OpenRA/commit/b8a71215eb93e57eb22e1147fbed1f5bf07639d7 also to the commit before 7005da35920bdb4dc6b362ecefe6947e1ae60d7c?

**Comment by dnqbob** [comment]
No, `PathFinder.cs` in https://github.com/MustaphaTR/OpenRA/commit/f60bfb9921b0dca50d10cf2db95bc72b702e2db3 and https://github.com/OpenRA/OpenRA/commit/b8a71215eb93e57eb22e1147fbed1f5bf07639d7 is the same.

I also do a double check on simply copy the `OpenRA.Mods.Common/Traits/World/PathFinder.cs` from bleed (at https://github.com/OpenRA/OpenRA/commit/ac921628251a2c7fb9f8ecb058d9760196cdc84e) to the https://github.com/MustaphaTR/OpenRA/commit/f60bfb9921b0dca50d10cf2db95bc72b702e2db3, there is no difference.

**Comment by anvilvapre** [comment]
In the stack trace there is the line
``` 
at OpenRA.Mods.Common.Traits.PathFinder.FindPathToTargetCell(Actor self, IEnumerable`1 sources, CPos target, BlockedByActor check, Func`2 customCost, Actor ignoreActor, Boolean laneBias) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Traits\World\PathFinder.cs:line 89
```

This would map to this line in the code. However on this line `FindPath` is not called on the HPF? (The ToList is a standard .net function - so no chance it triggers the path find, even if, it would be in the stack frame?)

(https://github.com/OpenRA/OpenRA/blob/b8a71215eb93e57eb22e1147fbed1f5bf07639d7/OpenRA.Mods.Common/Traits/World/PathFinder.cs#L89) 

Not sure what I am overlooking. Or does the stack frame line number at times only mark the start line of a function?

**Comment by dnqbob** [comment]
> Not sure what I am overlooking. Or does the stack frame line number at times only mark the start line of a function?

Sometimes it is on the stack trace, at this situation I recommend to write a try catch on the lines where really has problem.

**Comment by RoosterDragon** [comment]
The crash is reproducible from the replay - so if the stack trace has some unreliable line numbers that doesn't seem to matter too much.

My inital investigation suggests this is a bug somewhere in HPF itself, rather than in other areas such as Locomotor. It needs more investigation. Given the recent change to handle searching from multiple source cells it seems likely it may be related to that.
