### ISSUE TITLE
Crash playtest ffa

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#20507]
```
OpenRA engine version playtest-20221203
OpenRA Language: en
Red Alert mod version $playtest-20221203
on map ed1276677d2039166fe03d8de6d2213757987caf (Europe by Trump).
Date: 2022-12-04 17:11:09Z
Operating System: Linux (Unix 5.15.0.53)
Runtime Version: .NET CLR 6.0.11
Installed Language: nb (Installed) nb (Current) nb (Current UI)
Exception of type `System.Exception`: The abstract path should never be searched for an unreachable point. Abstract cell 166,20 failed to route to abstract cell.
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.<>c__DisplayClass40_0.<Heuristic>b__0(CPos cell) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Pathfinder/HierarchicalPathFinder.cs:line 1146
   at OpenRA.Mods.Common.Pathfinder.PathSearch.Expand() in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Pathfinder/PathSearch.cs:line 247
   at OpenRA.Mods.Common.Pathfinder.PathSearch.FindPath() in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Pathfinder/PathSearch.cs:line 296
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.FindPath(Actor self, IReadOnlyCollection`1 sources, CPos target, BlockedByActor check, Int32 heuristicWeightPercentage, Func`2 customCost, Actor ignoreActor, Boolean laneBias, PathFinderOverlay pathFinderOverlay) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Pathfinder/HierarchicalPathFinder.cs:line 783
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.FindPath(Actor self, CPos source, CPos target, BlockedByActor check, Int32 heuristicWeightPercentage, Func`2 customCost, Actor ignoreActor, Boolean laneBias, PathFinderOverlay pathFinderOverlay) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Pathfinder/HierarchicalPathFinder.cs:line 899
   at OpenRA.Mods.Common.Traits.PathFinder.FindPathToTargetCell(Actor self, IEnumerable`1 sources, CPos target, BlockedByActor check, Func`2 customCost, Actor ignoreActor, Boolean laneBias) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/World/PathFinder.cs:line 89
   at OpenRA.Mods.Common.Activities.Move.<>c__DisplayClass15_0.<.ctor>b__0(BlockedByActor check) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Activities/Move/Move.cs:line 78
   at OpenRA.Mods.Common.Activities.Move.EvalPath(BlockedByActor check) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Activities/Move/Move.cs:line 108
   at OpenRA.Mods.Common.Activities.Move.OnFirstRun(Actor self) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Activities/Move/Move.cs:line 123
   at OpenRA.Activities.Activity.TickOuter(Actor self) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Traits/ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Activities/Activity.cs:line 144
   at OpenRA.Mods.Common.Activities.AttackMoveActivity.Tick(Actor self) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Activities/Move/AttackMoveActivity.cs:line 80
   at OpenRA.Activities.Activity.TickOuter(Actor self) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Traits/ActivityUtils.cs:line 31
   at OpenRA.Actor.Tick() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Actor.cs:line 262
   at OpenRA.World.Tick() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/World.cs:line 441
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 639
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 654
   at OpenRA.Game.Loop() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 823
   at OpenRA.Game.Run() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenRA/OpenRA/OpenRA.Launcher/Program.cs:line 32


```

## Replay
can give if needed

**Comment by abcdefg30** [comment]
Ping @RoosterDragon

**Comment by PunkPun** [comment]
Was it the same game that SirCake and Zypres reported? Because if it was then #20498 fixes it

**Comment by PunkPun** [comment]
Oh yes, it crashed from the same cell, same map, so it's very likely from the same game

**Comment by RoosterDragon** [comment]
Can confirm the replay from https://discord.com/channels/153649279762694144/279290580201373696/1049013821437644800 appears to match and cherry-picking #20498 to the prep branch fixes the crash.
