### ISSUE TITLE
Crash related to sound files

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#20510]
```
OpenRA engine version playtest-20221203
OpenRA Language: en
Red Alert mod version $playtest-20221203
on map c9c3012fe6b7dc9c01b3c26464ac6cd901574bbd (1000x1000 by PacmanGraphics).
Date: 2022-12-05 12:08:25Z
Operating System: Windows (Microsoft Windows NT 10.0.19045.0)
Runtime Version: .NET CLR 6.0.11
Installed Language: zh (Installed) zh (Current) zh (Current UI)
Exception of type `System.IO.InvalidDataException`: jyes1.aud is not a valid sound file!
   at OpenRA.Sound.LoadSound[T](String filename, Func`2 loadFormat)
   at OpenRA.Sound.<PlayPredefined>g__PlaySound|80_0(<>c__DisplayClass80_0& )
   at OpenRA.Sound.PlayPredefined(SoundType soundType, Ruleset ruleset, Player p, Actor voicedActor, String type, String definition, String variant, Boolean relative, WPos pos, Single volumeModifier, Boolean attenuateVolume)
   at OpenRA.Mods.Common.Traits.Voiced.OpenRA.Traits.IVoiced.PlayVoice(Actor self, String phrase, String variant)
   at OpenRA.VoiceExts.PlayVoice(Actor self, String phrase)
   at OpenRA.Mods.Common.Traits.Selection.Combine(World world, IEnumerable`1 newSelection, Boolean isCombine, Boolean isClick)
   at OpenRA.Mods.Common.Widgets.WorldInteractionControllerWidget.HandleMouseInput(MouseInput mi)
   at OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
   at OpenRA.Widgets.Ui.HandleInput(MouseInput mi)
   at OpenRA.DefaultInputHandler.<>c__DisplayClass5_0.<OnMouseInput>b__0()
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn)
   at OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input)
   at OpenRA.Platforms.Default.Sdl2Input.PumpInput(Sdl2PlatformWindow device, IInputHandler inputHandler, Nullable`1 lockedMousePosition)
   at OpenRA.Platforms.Default.Sdl2PlatformWindow.PumpInput(IInputHandler inputHandler)
   at OpenRA.Renderer.EndFrame(IInputHandler inputHandler)
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)
```

**Comment by PunkPun** [comment]
> jyes1.aud is not a valid sound file

This will need more context

**Comment by abcdefg30** [comment]
This is probably #18882/#18828.

**Comment by Leo512bit** [comment]
> This is probably #18882/#18828.

Considering that these are both mechanic voice lines I think you're right.

**Comment by pchote** [comment]
Closing as duplicate.
