### ISSUE TITLE
Another abstract path searched for an unreachable point 

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#20528]
## System Information
- Operating System:  Win10

- OpenRA Version: https://github.com/EoralMilk/OpenMeow/commit/bbe56f721986b8a619bdbe6a2f1409cd1aa61083
Note: I have already used https://github.com/OpenRA/OpenRA/pull/20498/commits/1d77ef43e9285c1d2cafe418a03f0228fd4758be in #20498 in https://github.com/EoralMilk/OpenMeow/commit/bbe56f721986b8a619bdbe6a2f1409cd1aa61083 to test if issue is fixed, but it seems not working here.

- OpenRA Mod: TS(meow-TS)

PS: Please ignore the warnings when compiling, that is normal -- we are test changing render layer for better 3d support as well as some other functions of CNC3, too many things to do.

## Exception log

```
Exception of type `System.Exception`: The abstract path should never be searched for an unreachable point. Cell 39,-28 failed lookup for an abstract cell.
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.<>c__DisplayClass40_0.<Heuristic>b__0(CPos cell) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Pathfinder\HierarchicalPathFinder.cs:line 1157
   at OpenRA.Mods.Common.Pathfinder.PathSearch.Expand() in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 247
   at OpenRA.Mods.Common.Pathfinder.PathSearch.FindPath() in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 296
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.FindPath(Actor self, IReadOnlyCollection`1 sources, CPos target, BlockedByActor check, Int32 heuristicWeightPercentage, Func`2 customCost, Actor ignoreActor, Boolean laneBias, PathFinderOverlay pathFinderOverlay) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Pathfinder\HierarchicalPathFinder.cs:line 784
   at OpenRA.Mods.Common.Traits.PathFinder.FindPathToTargetCell(Actor self, IEnumerable`1 sources, CPos target, BlockedByActor check, Func`2 customCost, Actor ignoreActor, Boolean laneBias) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Traits\World\PathFinder.cs:line 89
   at OpenRA.Mods.Common.Activities.MoveAdjacentTo.CalculatePathToTarget(Actor self, BlockedByActor check) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Activities\Move\MoveAdjacentTo.cs:line 131
   at OpenRA.Mods.Common.Activities.Move.EvalPath(BlockedByActor check) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Activities\Move\Move.cs:line 115
   at OpenRA.Mods.Common.Activities.Move.OnFirstRun(Actor self) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Activities\Move\Move.cs:line 130
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Activities\Activity.cs:line 147
   at OpenRA.Mods.Common.Activities.MoveAdjacentTo.Tick(Actor self) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Activities\Move\MoveAdjacentTo.cs:line 103
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Activities\Activity.cs:line 147
   at OpenRA.Mods.Common.Activities.Enter.Tick(Actor self) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Mods.Common\Activities\Enter.cs:line 141
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Actor.Tick() in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Actor.cs:line 300
   at OpenRA.World.Tick() in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\World.cs:line 454
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Game.cs:line 649
   at OpenRA.Game.LogicTick() in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Game.cs:line 664
   at OpenRA.Game.Loop() in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Game.cs:line 840
   at OpenRA.Game.Run() in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Game.cs:line 893
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Game\Game.cs:line 317
   at OpenRA.Launcher.Program.Main(String[] args) in D:\work\Projects\Git\open-ra-3-d\OpenRA.Launcher\Program.cs:line 32
```

## Replay
[ts-2022-12-07T102553Z.zip](https://github.com/OpenRA/OpenRA/files/10175849/ts-2022-12-07T102553Z.zip)
Upon test, put it under "replays/ts/{DEV_VERSION}"

**Comment by PunkPun** [comment]
Could it be this https://github.com/OpenRA/OpenRA/pull/20498#issuecomment-1338042001 ?

**Comment by dnqbob** [comment]
idk, maybe?

**Comment by dnqbob** [comment]
Nope, not the same

**Comment by RoosterDragon** [comment]
Added an additional commit to PR #20498 to also resolve this issue.

In the replay, when the power plant is placed on the map edge it flattens some of the land. This brings a cell that was previously outside the map to inside the map as it's height lowered slighty. HPF wasn't prepared for this situation, and crashed. With the fix applied it will handle changes in map height going forward.
