### ISSUE TITLE
NullReferenceException when attacking bridge in OpenRA "Production Disruption" mission

### ISSUE THREAD

**Issue by colin-nolan** [OpenRA/OpenRA#20600]
## System Information

- Operating System:  macOS Ventura Version 13.1
- OpenRA Version: playtest-20221224
- OpenRA Mod: Red Alert
- Source: Official download package 

## Exception log

```
OpenRA engine version playtest-20221224
OpenRA Language: en
Red Alert mod version playtest-20221224
on map 7a21012e87007e2be021c96653131f1713775002 (Production Disruption by Westwood Studios).
Date: 2023-01-04 22:12:22Z
Operating System: OSX (X64, Unix 13.1.0)
Runtime Version: .NET CLR 6.0.12
Installed Language: en (Installed) en (Current) en (Current UI)
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Mods.Common.Traits.Bridge.UpdateState() in /Users/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/Buildings/Bridge.cs:line 322
   at OpenRA.Mods.Common.Traits.Bridge.<>c.<OpenRA.Mods.Common.Traits.INotifyDamageStateChanged.DamageStateChanged>b__41_0(Bridge b, Int32 d) in /Users/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/Buildings/Bridge.cs:line 364
   at OpenRA.Mods.Common.Traits.Bridge.Do(Action`2 action) in /Users/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/Buildings/Bridge.cs:line 141
   at OpenRA.Mods.Common.Traits.Bridge.OpenRA.Mods.Common.Traits.INotifyDamageStateChanged.DamageStateChanged(Actor self, AttackInfo e) in /Users/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/Buildings/Bridge.cs:line 364
   at OpenRA.Mods.Common.Traits.Health.InflictDamage(Actor self, Actor attacker, Damage damage, Boolean ignoreModifiers) in /Users/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/Health.cs:line 208
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, WarheadArgs args) in /Users/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Warheads/SpreadDamageWarhead.cs:line 123
   at OpenRA.GameRules.WeaponInfo.Impact(Target& target, WarheadArgs args)
   at OpenRA.Mods.Common.Projectiles.Missile.Explode(World world) in /Users/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Projectiles/Missile.cs:line 915
   at OpenRA.Mods.Common.Projectiles.Missile.Tick(World world)
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.Launcher.Program.Main(String[] args) in /Users/runner/work/OpenRA/OpenRA/OpenRA.Launcher/Program.cs:line 32
```

## Replay

Replay file: [ra-2023-01-04T221304Z.orarep.gz](https://github.com/OpenRA/OpenRA/files/10347929/ra-2023-01-04T221304Z.orarep.gz)

Save file (if it's useful): [Production Disruption.orasav.gz](https://github.com/OpenRA/OpenRA/files/10347962/Production.Disruption.orasav.gz)

## Additional information

Single player OpenRA mission: Aftermath Allied Missions -> Production Disruption. Crash occurs repeatably when attacking the (repaired) first bridge (after the radar dome) following the enemy reinforcements. Units ordered to attack the bridge manually. Crash likely coincides with the time that the bridge changes into a more damaged state (not on the first damage).

**Comment by PunkPun** [comment]
On damaging the bridge it crashed on this cell
<img width="354" alt="Screenshot 2023-01-05 at 18 21 59" src="https://user-images.githubusercontent.com/37534529/210829433-c4abe7c9-d90a-4e18-a375-704b40273d39.png">

In the map editor this bridge doesn't have that cell,

<img width="142" alt="Screenshot 2023-01-05 at 18 26 08" src="https://user-images.githubusercontent.com/37534529/210830358-88dac43c-890d-415e-8d33-0123f4a0a7c8.png">

It seems like 2 bridges were combined into 1 and it broke

**Comment by PunkPun** [comment]
Most likely regression from https://github.com/OpenRA/OpenRA/commit/7f94d67d39d35ef030ccf9ba532b77c6824473f1 #19572

`GetTerrainType()` was replaced by `GetTerrainInfo().TerrainType`. And on that tile `GetTerrainInfo` returns a null

**Comment by PunkPun** [comment]
The error happens because the 2 tiles are considered a separate bridge, and when that part gets destroyed it wants to switch to the destroyed state but that state doesn't have the needed tiles.

The winter tileset doesn't have this issue

<img width="152" alt="Screenshot_2023-01-06_at_15 01 57" src="https://user-images.githubusercontent.com/37534529/211024708-2024fb7a-7ece-459f-813e-2f1a9679bfac.png">

**Comment by PunkPun** [comment]
the extra 2 tiles should be using tiles from this template

<img width="140" alt="Screenshot_2023-01-06_at_15 03 50" src="https://user-images.githubusercontent.com/37534529/211025972-99d7fd4c-55c2-4f60-92fc-29de045d5925.png">

**Comment by pchote** [comment]
The best fix would be to remove those extra two tiles from the 378 template definition - the three maps using those tiles will have them replaced by the default clear tile at runtime, and be flagged by the linter and can be manually fixed.

**Comment by colin-nolan** [comment]
I'm happy to confirm that the fix worked and I was able to destroy the bridge without issue in another playthrough (using dev build).

Many thanks for your work!
