### ISSUE TITLE
Attempted to get trait from destroyed player actor in GrantConditionOnPrerequisite on ChangeOwnerSync

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#20603]
## System Information
- Operating System:  win10
- OpenRA Version: [MustaphaTR-OpenRA](https://github.com/MustaphaTR/OpenRA/commit/727c61fa699fb9dd2fbf4e6044abfd8f6ec57637)
- OpenRA Mod: [SP](https://github.com/ABrandau/Shattered-Paradise-SDK/commit/dfd8db96b068e1609ba19b5bb35c49eac0b4a01f) 

## Exception log
```
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (player 2 (not in world))
   at OpenRA.TraitDictionary.CheckDestroyed(Actor actor) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\TraitDictionary.cs:line 84
   at OpenRA.Mods.Common.Traits.GrantConditionOnPrerequisite.OpenRA.Traits.INotifyOwnerChanged.OnOwnerChanged(Actor self, Player oldOwner, Player newOwner) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionOnPrerequisite.cs:line 65
   at OpenRA.Actor.ChangeOwnerSync(Player newOwner) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Actor.cs:line 459
   at OpenRA.World.Dispose() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\World.cs:line 603
   at OpenRA.Graphics.WorldRenderer.Dispose() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Graphics\WorldRenderer.cs:line 423
   at OpenRA.Game.StartGame(String mapUID, WorldType type) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 185
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Network\UnitOrders.cs:line 155
   at OpenRA.Network.OrderManager.ReceiveImmediateOrders(Int32 clientId, OrderPacket orders) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Network\OrderManager.cs:line 168
   at OpenRA.Network.NetworkConnection.OpenRA.Network.IConnection.Receive(OrderManager orderManager) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Network\Connection.cs:line 347
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Sync.cs:line 167
   at OpenRA.Sync.RunUnsynced(World world, Action fn) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Sync.cs:line 168
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 639
   at OpenRA.Game.LogicTick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 654
   at OpenRA.Game.Loop() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 823
   at OpenRA.Game.Run() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 311
   at OpenRA.Launcher.Program.Main(String[] args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Launcher\Program.cs:line 32

AL lib: (EE) alc_cleanup: 1 device not closed
```

## Replay
[sp-2023-01-06T032248Z.zip](https://github.com/OpenRA/OpenRA/files/10357378/sp-2023-01-06T032248Z.zip)

**Comment by PunkPun** [comment]
The issue is explained in #19226

**Comment by PunkPun** [comment]
WIthout running the replay, my guess is that actor owner changing is handled incorrectly in Shattered Paradise, where it is queued in INotifyRemovedFromWorld callback or in other way died to unit disposal
