### ISSUE TITLE
LUA crash when engineer is trying to capture Actor with disabled Capturable triat

### ISSUE THREAD

**Issue by Porenutak** [OpenRA/OpenRA#20616]
Using  **actor.Capture(Actor target)**  will crash if targets _Capturable_ triat is disabled by condition.
example:
![Screenshot (168)](https://user-images.githubusercontent.com/100044015/212867063-75314fd4-dc50-40cd-91c5-9d032bb9fd7c.png)
crash log:

```
Fatal Lua Error: [string "-- Make copies of global functions to preve..."]:30: Uncaught CLR exception at Lua->CLR boundary: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> **Eluant.LuaException: Actor 'engineer 4164' cannot capture actor 'construction_yard 4409'!**
   at OpenRA.Mods.Common.Scripting.CaptureProperties.Capture(Actor target)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OpenRA.Scripting.ScriptMemberWrapper.Invoke(LuaVararg args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eluant.LuaRuntime.MethodWrapper.Invoke(Object[] parms)
   at Eluant.LuaRuntime.MakeManagedCall(IntPtr state, MethodWrapper wrapper)
   at OpenRA.Scripting.ScriptContext.FatalError(String message)
   at OpenRA.Mods.Common.Scripting.TriggerGlobal.<>c__DisplayClass2_0.<AfterDelay>b__0()
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.Main(String[] args)
```

Engineer script:
[engineer.txt](https://github.com/OpenRA/OpenRA/files/10433700/engineer.txt)
Conyard Capturable triat:
```
Capturable:
		RequiresCondition: !build-incomplete
```
There is no way how to check if actor Capturable trait is enabled or disabled via LUA (Or I dont know any)

Propoused Solution:

add LUA  ability to check actor's non-external conditions.

**Comment by PunkPun** [comment]
Related #20276
