### ISSUE TITLE
LUA: Media.PlayMovieInRadar crashes game [cnc: crash, ra: no function]

### ISSUE THREAD

**Issue by EricDamonStahl** [OpenRA/OpenRA#20622]
- Operating System:  Windows 10+11
- OpenRA Version: playtest-20230110 + release-20210321
- OpenRA Mod: cnc

lua.log:
```
A ScriptLobbyDropdown with ID `difficulty` was not found.
Fatal Lua Error: [string "-- Make copies of global functions to preve..."]:30: Uncaught CLR exception at Lua->CLR boundary: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   at OpenRA.Mods.Common.Scripting.MediaGlobal.AsyncLoader.BeginInvoke(Stream s, AsyncCallback callback, Object object)
   at OpenRA.Mods.Common.Scripting.MediaGlobal.PlayMovieInRadar(String movie, LuaFunction playComplete) in C:\Users\unXpected\Downloads\OpenRA-playtest-20230110\OpenRA-playtest-20230110\OpenRA.Mods.Common\Scripting\Global\MediaGlobal.cs:line 179
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OpenRA.Scripting.ScriptMemberWrapper.Invoke(LuaVararg args) in C:\Users\unXpected\Downloads\OpenRA-playtest-20230110\OpenRA-playtest-20230110\OpenRA.Game\Scripting\ScriptMemberWrapper.cs:line 76
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eluant.LuaRuntime.MethodWrapper.Invoke(Object[] parms)
   at Eluant.LuaRuntime.MakeManagedCall(IntPtr state, MethodWrapper wrapper)
   at OpenRA.Scripting.ScriptContext.FatalError(String message)
   at OpenRA.Mods.Common.Scripting.TriggerGlobal.<>c__DisplayClass2_0.<AfterDelay>b__0()
   at OpenRA.Effects.DelayedAction.<Tick>b__3_0(World w)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.Launcher.Program.Main(String[] args)

```

I put the following in the map .lua:

Movie = function()
	Media.PlayMovieInRadar("gdi12.vqa")
end

and (in WorldLoaded)
Trigger.AfterDelay(DateTime.Seconds(3), function() Movie() end)

This immediately crashes the game every time. Tested with the playtest and release versions, cnc mod.
Media.PlayMovieFullscreen("gdi12.vqa") works without any issues.

In ra mod nothing happens, neither PlayMovieFullscreen nor PlayMovieInRadar do anything (also no errors and no entries in lua.log).

**Comment by penev92** [comment]
From what I see there is some pretty weird asynchronous shenanigans from 8 years ago - #7156 (the original implementation) going on with the video loading that obscures the issue greatly, resulting in `Operation is not supported on this platform.`
Digging a bit, the problem seems to be https://devblogs.microsoft.com/dotnet/migrating-delegate-begininvoke-calls-for-net-core/

I tried to update `PlayMovieInRadar()` to 
```diff
-var l = new AsyncLoader(Media.LoadVideo);
-var ar = l.BeginInvoke(s, null, null);
-Action onLoadComplete = () =>
-{
-	Media.StopFMVInRadar();
-	world.AddFrameEndTask(_ => Media.PlayFMVInRadar(l.EndInvoke(ar), onCompleteRadar));
-};
-
-world.AddFrameEndTask(w => w.Add(new AsyncAction(ar, onLoadComplete)));
+Task.Run(() =>
+{
+	var video = Media.LoadVideo(s);
+	world.AddFrameEndTask(_ =>
+	{
+		Media.StopFMVInRadar();
+		Media.PlayFMVInRadar(video, onCompleteRadar);
+	});
+});
```
but I ended up with 
```
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=OpenRA.Platforms.Default
  StackTrace:
   at OpenRA.Platforms.Default.Texture.SetData(Byte[] colors, Int32 width, Int32 height) in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Platforms.Default\Texture.cs:line 89
   at OpenRA.Platforms.Default.ThreadedTexture.<>c__DisplayClass12_0.<.ctor>b__5(Object tuple) in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Platforms.Default\ThreadedGraphicsContext.cs:line 590
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.Message.Execute() in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Platforms.Default\ThreadedGraphicsContext.cs:line 210
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.QueueMessage(Message message) in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Platforms.Default\ThreadedGraphicsContext.cs:line 279
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.Post(Action`1 method, Object state) in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Platforms.Default\ThreadedGraphicsContext.cs:line 357
   at OpenRA.Platforms.Default.ThreadedShader.SetTexture(String param, ITexture texture) in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Platforms.Default\ThreadedGraphicsContext.cs:line 704
   at OpenRA.Graphics.SpriteRenderer.Flush() in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Game\Graphics\SpriteRenderer.cs:line 46
   at OpenRA.Renderer.set_CurrentBatchRenderer(IBatchRenderer value) in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Game\Renderer.cs:line 373
   at OpenRA.Renderer.Flush() in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Game\Renderer.cs:line 353
   at OpenRA.Renderer.DisableAntialiasingFilter() in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Game\Renderer.cs:line 472
   at OpenRA.Mods.Common.Widgets.ProductionPaletteWidget.Draw() in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Mods.Common\Widgets\ProductionPaletteWidget.cs:line 549
   at OpenRA.Widgets.Widget.DrawOuter() in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Game\Widgets\Widget.cs:line 481
   at OpenRA.Widgets.Widget.DrawOuter() in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Game\Widgets\Widget.cs:line 483
   at OpenRA.Widgets.Widget.DrawOuter() in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Game\Widgets\Widget.cs:line 483
   at OpenRA.Widgets.Widget.DrawOuter() in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Game\Widgets\Widget.cs:line 483
   at OpenRA.Widgets.Widget.DrawOuter() in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Game\Widgets\Widget.cs:line 483
   at OpenRA.Widgets.Widget.DrawOuter() in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Game\Widgets\Widget.cs:line 483
   at OpenRA.Widgets.Widget.DrawOuter() in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Game\Widgets\Widget.cs:line 483
   at OpenRA.Widgets.Ui.Draw() in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Game\Widgets\Widget.cs:line 96
   at OpenRA.Game.RenderTick() in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Game\Game.cs:line 706
   at OpenRA.Game.Loop() in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Game\Game.cs:line 844
   at OpenRA.Game.Run() in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Game\Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Game\Game.cs:line 311
   at OpenRA.Launcher.Program.Main(String[] args) in D:\Work.Personal\OpenRA\OpenRA\OpenRA.Launcher\Program.cs:line 26

  This exception was originally thrown at this call stack:
    OpenRA.Platforms.Default.Texture.SetData(byte[], int, int) in Texture.cs
    OpenRA.Platforms.Default.ThreadedTexture..ctor.AnonymousMethod__5(object) in ThreadedGraphicsContext.cs
    OpenRA.Platforms.Default.ThreadedGraphicsContext.Message.Execute() in ThreadedGraphicsContext.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    OpenRA.Platforms.Default.ThreadedGraphicsContext.QueueMessage(OpenRA.Platforms.Default.ThreadedGraphicsContext.Message) in ThreadedGraphicsContext.cs
    OpenRA.Platforms.Default.ThreadedGraphicsContext.Post(System.Action<object>, object) in ThreadedGraphicsContext.cs
    OpenRA.Platforms.Default.ThreadedShader.SetTexture(string, OpenRA.ITexture) in ThreadedGraphicsContext.cs
    OpenRA.Graphics.SpriteRenderer.Flush() in SpriteRenderer.cs
    OpenRA.Renderer.CurrentBatchRenderer.set(OpenRA.Renderer.IBatchRenderer) in Renderer.cs
    OpenRA.Renderer.Flush() in Renderer.cs
    ...
    [Call Stack Truncated]
```
or similar(!) - basically whoever tries to render something first after the video has started makes the renderer throw, and I don't know what's going on here.
