### ISSUE TITLE
Manual linking required on M2 with .NET

### ISSUE THREAD

**Issue by taoeffect** [OpenRA/OpenRA#20641]
## Issue Summary

The manual linking as described here still seems to be required: https://github.com/OpenRA/OpenRA/issues/19805 , at least when using .NET.

A PR was submitted that supposedly fixed the issue: https://github.com/OpenRA/OpenRA/pull/19887

However that doesn't seem to have fixed it? Either that or the build instructions need to be updated.

Even on `bleed` at commit e1b78c482119e961cb9352802bafc2a73f14233f `./launch-game.sh` fails, requiring the manual linking described in #19805:

```
-> % ./launch-game.sh Game.Mod=ts
Platform is OSX (Arm64)
Engine version is {DEV_VERSION}
Runtime: .NET CLR 6.0.13
Renderer initialization failed. Check graphics.log for details.
Renderer initialization failed. Check graphics.log for details.
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
   at OpenRA.Game.Initialize(Arguments args) in /Users/user/Games/C&C Red Alert/ra2/engine/OpenRA.Game/Game.cs:line 364
   at OpenRA.Game.InitializeAndRun(String[] args) in /Users/user/Games/C&C Red Alert/ra2/engine/OpenRA.Game/Game.cs:line 307
   at OpenRA.Launcher.Program.Main(String[] args) in /Users/user/Games/C&C Red Alert/ra2/engine/OpenRA.Launcher/Program.cs:line 32

OpenRA has encountered a fatal error.
Please refer to the crash logs and FAQ for more information.

Log files are located in /Users/user/Library/Application Support/OpenRA/Logs/
The FAQ is available at http://wiki.openra.net/FAQ
```

With the following in `graphics.log`:

```
System.DllNotFoundException: Unable to load shared library 'SDL2' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libSDL2, 0x0001): tried: 'libSDL2' (no such file), '/usr/local/lib/libSDL2' (no such file), '/usr/lib/libSDL2' (no such file), '/Users/user/Games/C&C Red Alert/ra2/engine/libSDL2' (no such file)
   at SDL2.SDL.SDL_Init(UInt32 flags)
   at OpenRA.Platforms.Default.Sdl2PlatformWindow.CanCreateGLWindow(GLProfile profile, List`1 errorLog) in /Users/user/Games/C&C Red Alert/ra2/engine/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 548
   at OpenRA.Platforms.Default.Sdl2PlatformWindow.<>c__DisplayClass49_0.<.ctor>b__0(GLProfile profile) in /Users/user/Games/C&C Red Alert/ra2/engine/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 156
   at System.Linq.Enumerable.WhereListIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor(Size requestEffectiveWindowSize, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile requestProfile, Boolean enableLegacyGL) in /Users/user/Games/C&C Red Alert/ra2/engine/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 155
   at OpenRA.Platforms.Default.DefaultPlatform.CreateWindow(Size size, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile profile, Boolean enableLegacyGL) in /Users/user/Games/C&C Red Alert/ra2/engine/OpenRA.Platforms.Default/DefaultPlatform.cs:line 21
   at OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings) in /Users/user/Games/C&C Red Alert/ra2/engine/OpenRA.Game/Renderer.cs:line 79
   at OpenRA.Game.Initialize(Arguments args) in /Users/user/Games/C&C Red Alert/ra2/engine/OpenRA.Game/Game.cs:line 382
```

Curiously, this isn't needed when building the project with mono. But my understanding is that .NET is better than mono...? And ra2 mod ~~requires .NET to build...~~ (EDIT: [it doesn't](https://github.com/OpenRA/ra2/issues/804#issuecomment-1405775023)!) so it would be great if the linking issue with homebrew and .NET was addressed.

## Reproduction

Err, see here: https://github.com/OpenRA/ra2/issues/804#issuecomment-1405694114

## Expected behavior

For no manual linking of homebrew library dependencies needed.

**Comment by taoeffect** [comment]
One possible cause, on [this line](https://github.com/OpenRA/OpenRA/blob/bleed/Makefile#L61) `DOTNET_RID` is: `osx.12-arm64`, causing `TARGETPLATFORM` to be `osx-x64` instead of `osx-arm64`.

I've confirmed that making this modification to the ifeq on [line 71](https://github.com/OpenRA/OpenRA/blob/bleed/Makefile#L71) seems to fix the problem. The program runs without manual linking needed.

EDIT: recommend doing a grep for `arm64` or something instead of an ifeq

**Comment by penev92** [comment]
I don't know if there is a simple way of doing this (or even if I didn't make any syntax errors since I can't run it), but this is what I came up with:
```diff
--- a/Makefile
+++ b/Makefile

# Only for use in target version:
VERSION := $(shell git name-rev --name-only --tags --no-undefined HEAD 2>/dev/null || (c=$$(git rev-parse --short HEAD 2>/dev/null) && echo git-$$c))

+dotnet_rid_regex_macos = ^net[0-9]-osx[\.0-9]*-arm64$
+
# Detect target platform for dependencies if not given by the user
ifndef TARGETPLATFORM
UNAME_S := $(shell uname -s)
UNAME_M := $(shell uname -m)
ifeq ($(UNAME_S),Darwin)
-ifeq ($(RUNTIME)-$(DOTNET_RID),net6-osx-arm64)
-TARGETPLATFORM = osx-arm64
-else
+ifeq ($(shell echo ${RUNTIME}-${DOTNET_RID} | egrep "${dotnet_rid_regex_macos}"),)
TARGETPLATFORM = osx-x64
+else
+TARGETPLATFORM = osx-arm64
endif
else
```

**Comment by taoeffect** [comment]
@penev92 I can test that later today, but I would recommend just grepping for `arm` or `arm64` and ignoring everything else. You already know it's a mac because of `ifeq ($(UNAME_S),Darwin)`

**Comment by penev92** [comment]
Hopefully @pchote will take care of this soonish.

**Comment by taoeffect** [comment]
@penev92 fyi yeah your patch works. If they change the format of the string some more it might break again though so that's why I would just grep for `arm`. Good luck to @pchote!

**Comment by PunkPun** [comment]
@taoeffect please try this solution out

```diff
--- a/Makefile
+++ b/Makefile
RUNTIME ?= net6
CONFIGURATION ?= Release
DOTNET_RID = $(shell ${DOTNET} --info | grep RID: | cut -w -f3)
+ARCH_ARM = $(shell echo ${DOTNET_RID} | grep arm64)

# Only for use in target version:
VERSION := $(shell git name-rev --name-only --tags --no-undefined HEAD 2>/dev/null || (c=$$(git rev-parse --short HEAD 2>/dev/null) && echo git-$$c))

# Detect target platform for dependencies if not given by the user
ifndef TARGETPLATFORM
UNAME_S := $(shell uname -s)
UNAME_M := $(shell uname -m)
ifeq ($(UNAME_S),Darwin)
-ifeq ($(RUNTIME)-$(DOTNET_RID),net6-osx-arm64)
+ifeq ($(DOTNET_RID),$(ARCH_ARM))
TARGETPLATFORM = osx-arm64
else
TARGETPLATFORM = osx-x64
```

**Comment by taoeffect** [comment]
@PunkPun Yes, that works too, and looks clean to me 👍
