### ISSUE TITLE
Freeze during playback of the ts mod

### ISSUE THREAD

**Issue by stefan1983** [OpenRA/OpenRA#20750]
## Issue Summary
Played the ts mod and had a freeze out of nowhere.

## Reproduction
Not sure if I am able to reproduce, I'll see.

The log output upon the freeze:

Platform is OSX (Arm64)
Engine version is {DEV_VERSION}
Runtime: .NET CLR 6.0.14
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1512x982
No custom resolution provided, using desktop resolution
Using resolution: 1512x982
Using new resolution: 1512x945
Using window scale 2,00
OpenGL renderer: Apple M1 Pro
OpenGL version: 4.1 Metal - 76.3
Using default sound device
Internal mods:
	cnc: Tiberian Dawn ({DEV_VERSION})
	d2k: Dune 2000 ({DEV_VERSION})
	all: All mods ({DEV_VERSION})
	ra: Red Alert ({DEV_VERSION})
	modcontent: Mod Content Manager ({DEV_VERSION})
	ts: Tiberian Sun ({DEV_VERSION})
External mods:
	ra-playtest-20230110: Red Alert (playtest-20230110)
	cnc-release-20230225: Tiberian Dawn (release-20230225)
	cnc-playtest-20230110: Tiberian Dawn (playtest-20230110)
	ts-{DEV_VERSION}: Tiberian Sun ({DEV_VERSION})
Loading mod: ts
Loading mod: modcontent
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 1 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
Loading mod: ts

**Comment by penev92** [comment]
Please let us know if this was a one-time thing or you can reproduce. Also whether it happens when you start the mod or while playing.

**Comment by stefan1983** [comment]
> Please let us know if this was a one-time thing or you can reproduce. Also whether it happens when you start the mod or while playing.

It was while playing, but so far it didn't happen again. I look further into it and close the ticket otherwise.

**Comment by dictvm** [comment]
This is happening again after pulling from the latest bleed branch:

```
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 0 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
[2025-04-05T12:26:42] Game started.
Exception of type `System.DivideByZeroException`: Attempted to divide by zero.
   at OpenRA.Mods.Common.Traits.BodyOrientation.QuantizeFacing(WAngle facing) in /Users/user/Documents/Source/personal/OpenRA/OpenRA.Mods.Common/Traits/BodyOrientation.cs:line 111
   at OpenRA.Mods.Common.Traits.Render.WithIdleOverlay.<>c__DisplayClass1_1.<.ctor>b__6() in /Users/user/Documents/Source/personal/OpenRA/OpenRA.Mods.Common/Traits/Render/WithIdleOverlay.cs:line 99
   at OpenRA.Graphics.Animation.Render(WPos pos, WVec& offset, Int32 zOffset, PaletteReference palette) in /Users/user/Documents/Source/personal/OpenRA/OpenRA.Game/Graphics/Animation.cs:line 60
   at OpenRA.Graphics.AnimationWithOffset.Render(Actor self, PaletteReference pal) in /Users/user/Documents/Source/personal/OpenRA/OpenRA.Game/Graphics/AnimationWithOffset.cs:line 44
   at OpenRA.Mods.Common.Traits.Render.RenderSprites.Render(Actor self, WorldRenderer wr)+MoveNext() in /Users/user/Documents/Source/personal/OpenRA/OpenRA.Mods.Common/Traits/Render/RenderSprites.cs:line 186
   at OpenRA.Actor.Renderables(WorldRenderer wr)+MoveNext() in /Users/user/Documents/Source/personal/OpenRA/OpenRA.Game/Actor.cs:line 307
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at OpenRA.Mods.Common.Traits.Render.WithShadow.OpenRA.Traits.IRenderModifier.ModifyRender(Actor self, WorldRenderer wr, IEnumerable`1 r) in /Users/user/Documents/Source/personal/OpenRA/OpenRA.Mods.Common/Traits/Render/WithShadow.cs:line 54
   at OpenRA.Graphics.WorldRenderer.GenerateRenderables() in /Users/user/Documents/Source/personal/OpenRA/OpenRA.Game/Graphics/WorldRenderer.cs:line 141
   at OpenRA.Game.RenderTick() in /Users/user/Documents/Source/personal/OpenRA/OpenRA.Game/Game.cs:line 704
   at OpenRA.Game.Loop() in /Users/user/Documents/Source/personal/OpenRA/OpenRA.Game/Game.cs:line 867
   at OpenRA.Game.Run() in /Users/user/Documents/Source/personal/OpenRA/OpenRA.Game/Game.cs:line 899
   at OpenRA.Game.InitializeAndRun(String[] args) in /Users/user/Documents/Source/personal/OpenRA/OpenRA.Game/Game.cs:line 325
   at OpenRA.Launcher.Program.Main(String[] args) in /Users/user/Documents/Source/personal/OpenRA/OpenRA.Launcher/Program.cs:line 46

OpenRA has encountered a fatal error.
Please refer to the crash logs and FAQ for more information.
```
