### ISSUE TITLE
Asset of EA version not found 

### ISSUE THREAD

**Issue by fdev3000** [OpenRA/OpenRA#20763]
Hi,

it seems EA replaced Origin by the EA App on Windows. The registry keys in [mod.yaml](https://github.com/OpenRA/TiberianDawnHD/blob/master/mods/cnc/mod.yaml#L23) are still present and valid. Unfortunately it only shows the "Install Content" dialog box.

CNCDATA Folder is (now) contained in a DATA folder of the installation. I don't know if that was the case before. Might be helpful for a fix.

Best regards

**Comment by dukedagmor** [comment]
I'm having the same issue, upvoted

my error in install.log:

```
Using installer `ra-origin: C&C The Ultimate Collection (Origin version, English)` of type `RegistryDirectory`:
System.ArgumentNullException: Path cannot be null. (Parameter 'path')
   at System.IO.Strategies.FileStreamHelpers.ValidateArguments(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at OpenRA.Mods.Cnc.Installer.ExtractMixSourceAction.RunActionOnSource(MiniYaml actionYaml, String path, ModData modData, List`1 extracted, Action`1 updateMessage)
   at OpenRA.Mods.Common.Widgets.Logic.InstallFromSourceLogic.<>c__DisplayClass44_0.<InstallFromSource>g__RunSourceActions|2(MiniYamlNode contentPackageYaml, <>c__DisplayClass44_1& )
   at OpenRA.Mods.Common.Widgets.Logic.InstallFromSourceLogic.<>c__DisplayClass44_0.<InstallFromSource>b__1()

```

**Comment by dukedagmor** [comment]
my issue seems to be that main.mix is split and openRA doesnt account for that

![Image](https://github.com/user-attachments/assets/e3d1f8a8-4b53-479e-9d9e-36cc0bb772c5)

![Image](https://github.com/user-attachments/assets/536c3d74-06e1-4120-a2f8-06d0b2ea708f)
