### ISSUE TITLE
Unable to load shared library 'soft_oal' or one of its dependencies.

### ISSUE THREAD

**Issue by stefan1983** [OpenRA/OpenRA#20766]
```
Stefan@imac OpenRA-bleed % ./launch-game.sh Game.Mod=cnc
Platform is OSX (X64)
Engine version is {DEV_VERSION}
Runtime: .NET CLR 6.0.14
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 2560x1440
No custom resolution provided, using desktop resolution
Using resolution: 2560x1440
Using window scale 1,00
OpenGL renderer: NVIDIA GeForce GT 755M OpenGL Engine
OpenGL version: 4.1 NVIDIA-14.0.32 355.11.11.10.10.143
Using default sound device
Renderer initialization failed. Check graphics.log for details.
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 2560x1440
No custom resolution provided, using desktop resolution
Using resolution: 2560x1440
Using window scale 1,00
OpenGL renderer: NVIDIA GeForce GT 755M OpenGL Engine
OpenGL version: 4.1 NVIDIA-14.0.32 355.11.11.10.10.143
Using default sound device
Renderer initialization failed. Check graphics.log for details.
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
   at OpenRA.Game.Initialize(Arguments args) in /Users/Stefan/Downloads/OpenRA-bleed/OpenRA.Game/Game.cs:line 358
   at OpenRA.Game.InitializeAndRun(String[] args) in /Users/Stefan/Downloads/OpenRA-bleed/OpenRA.Game/Game.cs:line 301
   at OpenRA.Launcher.Program.Main(String[] args) in /Users/Stefan/Downloads/OpenRA-bleed/OpenRA.Launcher/Program.cs:line 32

OpenRA has encountered a fatal error.
Please refer to the crash logs and FAQ for more information.

Log files are located in /Users/Stefan/Library/Application Support/OpenRA/Logs/
The FAQ is available at http://wiki.openra.net/FAQ
```
```
Stefan@imac OpenRA-bleed % cat /Users/Stefan/Library/Application\ Support/OpenRA/Logs/graphics.log 
System.DllNotFoundException: Unable to load shared library 'soft_oal' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libsoft_oal, 1): image not found
   at OpenAL.ALC10.alcOpenDevice(String devicename)
   at OpenRA.Platforms.Default.OpenAlSoundEngine..ctor(String deviceName) in /Users/Stefan/Downloads/OpenRA-bleed/OpenRA.Platforms.Default/OpenAlSoundEngine.cs:line 124
   at OpenRA.Platforms.Default.DefaultPlatform.CreateSound(String device) in /Users/Stefan/Downloads/OpenRA-bleed/OpenRA.Platforms.Default/DefaultPlatform.cs:line 28
   at OpenRA.Sound..ctor(IPlatform platform, SoundSettings soundSettings) in /Users/Stefan/Downloads/OpenRA-bleed/OpenRA.Game/Sound/Sound.cs:line 52
   at OpenRA.Game.Initialize(Arguments args) in /Users/Stefan/Downloads/OpenRA-bleed/OpenRA.Game/Game.cs:line 380
System.DllNotFoundException: Unable to load shared library 'soft_oal' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libsoft_oal, 1): image not found
   at OpenAL.ALC10.alcOpenDevice(String devicename)
   at OpenRA.Platforms.Default.OpenAlSoundEngine..ctor(String deviceName) in /Users/Stefan/Downloads/OpenRA-bleed/OpenRA.Platforms.Default/OpenAlSoundEngine.cs:line 124
   at OpenRA.Platforms.Default.DefaultPlatform.CreateSound(String device) in /Users/Stefan/Downloads/OpenRA-bleed/OpenRA.Platforms.Default/DefaultPlatform.cs:line 28
   at OpenRA.Sound..ctor(IPlatform platform, SoundSettings soundSettings) in /Users/Stefan/Downloads/OpenRA-bleed/OpenRA.Game/Sound/Sound.cs:line 52
   at OpenRA.Game.Initialize(Arguments args) in /Users/Stefan/Downloads/OpenRA-bleed/OpenRA.Game/Game.cs:line 380
```

Any ideas?

Thanks

**Comment by stefan1983** [comment]
I just tried to compile with mono instead of dotnet@6 - same result

**Comment by penev92** [comment]
Are you missing a system dependency like OpenAL? Either that or something like #19750, which should be fixed already 🤔

**Comment by Mailaender** [comment]
Try deleting all `.dylib` in `bin/` and then run `./configure-system-libraries.sh` again. Paste the output of the script here.

**Comment by stefan1983** [comment]
@Mailaender I did as proposed, then i got:

> Stefan@iMac OpenRA-bleed % ./configure-system-libraries.sh
> Searching for Lua 5.1... FAILED
> OpenRA expects to find a file matching "liblua5.1.dylib" in one of the following locations:
> /usr/local/lib /usr/local/opt/openal-soft/lib

After looking into /usr/local/lib for liblua* I found:

> Stefan@iMac lib % ls liblua*
> liblua.5.4.4.dylib	liblua.5.4.dylib	liblua.a		liblua.dylib		liblua5.4.dylib
> 

It seems OpenRA does only look for a specific version of libua > 5.1.*
So I installed the specific version via brew:

> Stefan@iMac lib % brew install lua@5.1                                                            
> 
> Warning: lua@5.1 has been deprecated because it is deprecated upstream!
> ==> Fetching lua@5.1

After doing that, I now can start the game via the launch script.

Is there something specific in Lua 5.1* that OpenRA needs? 
I was thinking, a newer version should be sufficient as well...

**Comment by Mailaender** [comment]
The API is incompatible.

**Comment by anvilvapre** [comment]
Can be closed?
