### ISSUE TITLE
Crash when overriding binds in certain situations

### ISSUE THREAD

**Issue by JovialFeline** [OpenRA/OpenRA#20770]
## System Information

- Operating System:  64-bit Windows 10 Pro (Version 22H2, OS build 19045.2604)
- OpenRA Version: `release-20230225`
- OpenRA Mod:  `ra`, though `d2k` and `cnc` also show the issue.
- Source: Official download for `release-20230225`

## Exception log

```
OpenRA engine version release-20230225
OpenRA Language: en
Red Alert mod version release-20230225
on map b884e9d4e8e59f89b0f338e32fdc52a0a51b6ae4 (Desert Shellmap by Scott_NZ).
Date: 2023-03-27 22:57:59Z
Operating System: Windows (X64, Microsoft Windows NT 10.0.19045.0)
Runtime Version: .NET CLR 6.0.14
Installed Language: en (Installed) en (Current) en (Current UI)
Exception of type `System.InvalidOperationException`: Widget HOTKEY_LIST has no child ToLastEvent of type ContainerWidget
   at OpenRA.Widgets.Widget.Get[T](String id)
   at OpenRA.Mods.Common.Widgets.Logic.HotkeysSettingsLogic.OverrideHotkey()
   at OpenRA.Mods.Common.Widgets.ButtonWidget.<.ctor>b__41_5(MouseInput _)
   at OpenRA.Mods.Common.Widgets.ButtonWidget.HandleMouseInput(MouseInput mi)
   at OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
   at OpenRA.Widgets.Ui.HandleInput(MouseInput mi)
   at OpenRA.DefaultInputHandler.<>c__DisplayClass5_0.<OnMouseInput>b__0()
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn)
   at OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input)
   at OpenRA.Platforms.Default.Sdl2Input.PumpInput(Sdl2PlatformWindow device, IInputHandler inputHandler, Nullable`1 lockedMousePosition)
   at OpenRA.Platforms.Default.Sdl2PlatformWindow.PumpInput(IInputHandler inputHandler)
   at OpenRA.Renderer.EndFrame(IInputHandler inputHandler)
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)
```

## Replay

I can't offer a replay, but I did make a short video recording (for the log above): https://user-images.githubusercontent.com/4985264/228085571-4c496ffd-f1cd-40f6-a721-7c5bf80d9b3c.mov

## Additional information

Steps to reproduce (on my machine):

- Enter the Hotkeys menu.
- Use the search bar to look for something to change, like Scatter.
- Select a key that's already bound.
- When warned that the key is in use, override to cause a crash.

**OR**

- Enter the Hotkeys menu.
- Select a context that hides the UI bit displaying a certain bound key. Attempt to rebind that key.
  - For example, change the context to Spectator, then try to bind a key that's already bound to Stop or Scatter from the Player context.
- When warned that the key is in use, override to cause a crash.

Scrolling through and overriding without a search or narrowed context shows no issues. I apologize if this report is a duplicate or otherwise done incorrectly.

**Comment by ThomasChr** [comment]
Easily reproducible!
```
Exception of type `System.InvalidOperationException`: Widget HOTKEY_LIST has no child SelectUnitsByType of type ContainerWidget
   at OpenRA.Widgets.Widget.Get[T](String id) in C:\Users\tchristlieb\RiderProjects\OpenRA\OpenRA.Game\Widgets\Widget.cs:line 592
   at OpenRA.Mods.Common.Widgets.Logic.HotkeysSettingsLogic.OverrideHotkey() in C:\Users\tchristlieb\RiderProjects\OpenRA\OpenRA.Mods.Common\Widgets\Logic\Settings\HotkeysSettingsLogic.cs:line 305
   at OpenRA.Mods.Common.Widgets.ButtonWidget.<.ctor>b__41_5(MouseInput _) in C:\Users\tchristlieb\RiderProjects\OpenRA\OpenRA.Mods.Common\Widgets\ButtonWidget.cs:line 82
   at OpenRA.Mods.Common.Widgets.ButtonWidget.HandleMouseInput(MouseInput mi) in C:\Users\tchristlieb\RiderProjects\OpenRA\OpenRA.Mods.Common\Widgets\ButtonWidget.cs:line 178
   at OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) in C:\Users\tchristlieb\RiderProjects\OpenRA\OpenRA.Game\Widgets\Widget.cs:line 422
   at OpenRA.Widgets.Ui.HandleInput(MouseInput mi) in C:\Users\tchristlieb\RiderProjects\OpenRA\OpenRA.Game\Widgets\Widget.cs:line 106
   at OpenRA.DefaultInputHandler.<>c__DisplayClass5_0.<OnMouseInput>b__0() in C:\Users\tchristlieb\RiderProjects\OpenRA\OpenRA.Game\Input\InputHandler.cs:line 50
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) in C:\Users\tchristlieb\RiderProjects\OpenRA\OpenRA.Game\Sync.cs:line 194
   at OpenRA.Sync.RunUnsynced[T](World world, Func`1 fn) in C:\Users\tchristlieb\RiderProjects\OpenRA\OpenRA.Game\Sync.cs:line 179
   at OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input) in C:\Users\tchristlieb\RiderProjects\OpenRA\OpenRA.Game\Input\InputHandler.cs:line 50
   at OpenRA.Platforms.Default.Sdl2Input.PumpInput(Sdl2PlatformWindow device, IInputHandler inputHandler, Nullable`1 lockedMousePosition) in C:\Users\tchristlieb\RiderProjects\OpenRA\OpenRA.Platforms.Default\Sdl2Input.cs:line 149
   at OpenRA.Platforms.Default.Sdl2PlatformWindow.PumpInput(IInputHandler inputHandler) in C:\Users\tchristlieb\RiderProjects\OpenRA\OpenRA.Platforms.Default\Sdl2PlatformWindow.cs:line 492
   at OpenRA.Renderer.EndFrame(IInputHandler inputHandler) in C:\Users\tchristlieb\RiderProjects\OpenRA\OpenRA.Game\Renderer.cs:line 323
   at OpenRA.Game.RenderTick() in C:\Users\tchristlieb\RiderProjects\OpenRA\OpenRA.Game\Game.cs:line 712
   at OpenRA.Game.Loop() in C:\Users\tchristlieb\RiderProjects\OpenRA\OpenRA.Game\Game.cs:line 835
   at OpenRA.Game.Run() in C:\Users\tchristlieb\RiderProjects\OpenRA\OpenRA.Game\Game.cs:line 867
   at OpenRA.Game.InitializeAndRun(String[] args) in C:\Users\tchristlieb\RiderProjects\OpenRA\OpenRA.Game\Game.cs:line 305
   at OpenRA.Launcher.Program.Main(String[] args) in C:\Users\tchristlieb\RiderProjects\OpenRA\OpenRA.Launcher\Program.cs:line 32
```

**Comment by ThomasChr** [comment]
It also crashes when resetting the hotkeys while they are filtered.
