### ISSUE TITLE
My game crashed due to error

### ISSUE THREAD

**Issue by GhostSlayer305** [OpenRA/OpenRA#20831]
## System Information

- Operating System:  Windows 10
- OpenRA Version: 20230225
- OpenRA Mod: Shattered Paradise
- Source: (https://www.moddb.com/mods/shattered-paradise)
- For self-compiled or third-party packages: Mono version

## Exception log

```
OpenRA engine version 7f3a922
OpenRA Language: en
Shattered Paradise mod version playest-20230211
on map 85a17a45dce3d0f9d4ce901fe96caa1a4a9a54ea (Assimilate the Alien Artifact by Nolt, jrb0001).
Date: 2023-04-29 16:28:23Z
Operating System: Windows (X64, Microsoft Windows NT 10.0.19045.0)
Runtime Version: .NET CLR 6.0.13
Installed Language: en (Installed) en (Current) en (Current UI)
Exception of type `System.NotImplementedException`: No rules definition for unit cabgrinder
   at OpenRA.Actor..ctor(World world, String name, TypeDictionary initDict)
   at OpenRA.Mods.Common.Traits.SpawnMapActors.WorldLoaded(World world, WorldRenderer wr)
   at OpenRA.World.LoadComplete(WorldRenderer wr)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.ReceiveImmediateOrders(Int32 clientId, OrderPacket orders)
   at OpenRA.Network.NetworkConnection.OpenRA.Network.IConnection.Receive(OrderManager orderManager)
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0()
   at OpenRA.Sync.RunUnsynced(World world, Action fn)
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)


```

## Additional information

The game launches fine its just when I try to play a match its crashes. I have tried 4 or 5 times now and its always the same error

**Comment by PunkPun** [comment]
This should be directed at the shattered paradise team. See https://github.com/ABrandau/Shattered-Paradise-SDK

**Comment by GhostSlayer305** [comment]
> This should be directed at the shattered paradise team. See https://github.com/ABrandau/Shattered-Paradise-SDK

Thanks I'll do that now.
