### ISSUE TITLE
Crash when using building variant

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#20888]
```
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Mods.Common.Orders.PlaceBuildingOrderGenerator.InnerOrder(World world, CPos cell, MouseInput mi)+MoveNext() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Orders\PlaceBuildingOrderGenerator.cs:line 172
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at OpenRA.Mods.Common.Orders.PlaceBuildingOrderGenerator.Order(World world, CPos cell, int2 worldPixel, MouseInput mi) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Orders\PlaceBuildingOrderGenerator.cs:line 137
   at OpenRA.Mods.Common.Widgets.WorldInteractionControllerWidget.ApplyOrders(World world, MouseInput mi) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Widgets\WorldInteractionControllerWidget.cs:line 186
   at OpenRA.Mods.Common.Widgets.WorldInteractionControllerWidget.HandleMouseInput(MouseInput mi) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Widgets\WorldInteractionControllerWidget.cs:line 177
   at OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Widgets\Widget.cs:line 422
   at OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Widgets\Widget.cs:line 413
   at OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Widgets\Widget.cs:line 413
   at OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Widgets\Widget.cs:line 413
   at OpenRA.Widgets.Ui.HandleInput(MouseInput mi) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Widgets\Widget.cs:line 100
   at OpenRA.DefaultInputHandler.<>c__DisplayClass5_0.<OnMouseInput>b__0() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Input\InputHandler.cs:line 50
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Sync.cs:line 205
   at OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Input\InputHandler.cs:line 51
   at OpenRA.Platforms.Default.Sdl2Input.PumpInput(Sdl2PlatformWindow device, IInputHandler inputHandler, Nullable`1 lockedMousePosition) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Platforms.Default\Sdl2Input.cs:line 128
   at OpenRA.Platforms.Default.Sdl2PlatformWindow.PumpInput(IInputHandler inputHandler) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Platforms.Default\Sdl2PlatformWindow.cs:line 495
   at OpenRA.Renderer.EndFrame(IInputHandler inputHandler) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Renderer.cs:line 310
   at OpenRA.Game.RenderTick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 727
   at OpenRA.Game.Loop() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 835
   at OpenRA.Game.Run() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 867
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 305
   at OpenRA.Launcher.Program.Main(String[] args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Launcher\Program.cs:line 32
```

Cannot reproduce.

Crash happens when I am trying to place a refinary and the game is just beginning. May relate to my mistake input on keyboard but I cannot reproduce another.

**Comment by anvilvapre** [comment]
Suggests that either `Queue` is `null` or otherwise `placeBuidlingInfo`. 

Could there have been a player actor that has no `PlaceBuildingInfo` trait? If not - then likely `ProductionPaletteWidget.currentQueue` can be `null`.

So this check may be missing.

**Comment by dnqbob** [comment]
It seems that some changes in bleed make we have to add buildable to variant actor
