### ISSUE TITLE
Crashed after changing the display scale

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenRA/OpenRA#20951]
## System Information

- Operating System:  ArchLinux with kernel 6.4.1-arch2-1
- OpenRA Version: fa65e7fd3f4ac8309ccbc27673d24fbec8d48764
- OpenRA Mod: @OpenHV
- Source: Official download package

## Exception log

```
OpenRA engine version fa65e7fd3f4ac8309ccbc27673d24fbec8d48764
OpenRA Language: en
OpenHV mod version 20230618
on map 01809567ec3853b9bb40c60cf556821992282dad (Shellmap by Matt, Dzierzan, SiegeSpud).
Date: 2023-07-06 19:07:00Z
Operating System: Linux (X64, Unix 6.4.1.2)
Runtime Version: .NET CLR 6.0.16
Installed Language: en (Installed) en (Current) en (Current UI)
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Mods.Common.Widgets.Logic.DisplaySettingsLogic.RecalculateWidgetLayout(Widget w, Boolean insideScrollPanel) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Widgets/Logic/Settings/DisplaySettingsLogic.cs:line 513
   at OpenRA.Mods.Common.Widgets.Logic.DisplaySettingsLogic.<>c__DisplayClass42_1.<ShowUIScaleDropdown>b__5() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Widgets/Logic/Settings/DisplaySettingsLogic.cs:line 546
   at OpenRA.Primitives.ActionQueue.PerformActions(Int64 currentTime) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Primitives/ActionQueue.cs:line 53
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 645
   at OpenRA.Game.Loop() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 814
   at OpenRA.Game.Run() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 867
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 305
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Launcher/Program.cs:line 32

```

## Replay

No replay was recorded.

## Additional information

I ran the game, went on the Settings, then decided to change the UI Scale to 125%, and then it crashed. I didn't play any match.

I just installed the most recent version of OpenHV from the official site.

**Comment by dnqbob** [comment]
Hi, you could post it to https://github.com/OpenHV/OpenHV, not here.

Although I can help you @Mailaender

**Comment by dnqbob** [comment]
Hi, you could post it to https://github.com/OpenHV/OpenHV, not here.

Although I can help you @Mailaender

**Comment by PunkPun** [comment]
This looks like the type of problem which might be caused by OpenRA engine

**Comment by Mailaender** [comment]
You tried to change the display scale?

**Comment by Mailaender** [comment]
We have not forked `DisplaySettingsLogic`.

**Comment by Mailaender** [comment]
Which window manager do you use?

**Comment by WilliamWeberBerrutti** [comment]
> Which window manager do you use?

I'm using KWin. Version details:

KWin version: 5.27.6
Qt Version: 5.15.10
Qt compile version: 5.15.10
XCB compile version: 1.15

Operation Mode: X11 only
