### ISSUE TITLE
I have recieved several "Attempted to get trait from destroyed object" crashes during the singleplayer missions of Combined Arms

### ISSUE THREAD

**Issue by SmashinAshe** [OpenRA/OpenRA#20952]
## System Information

- Operating System:  Windows (X64, Microsoft Windows NT 10.0.19045.0)
- OpenRA Version: OpenRA engine version ca
- OpenRA Mod: Combined Arms mod version 0.91
- Source: Official download package (I think)

## Exception log

```
OpenRA engine version ca
OpenRA Language: en
Combined Arms mod version 0.91
on map b5265beed1366bbf0214446d877936968ea2e930 (05: Machinations by Darkademic).
Date: 2023-07-07 06:14:40Z
Operating System: Windows (X64, Microsoft Windows NT 10.0.19045.0)
Runtime Version: .NET CLR 6.0.18
Installed Language: en (Installed) en (Current) en (Current UI)
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (ctnk 1111 (not in world))
   at OpenRA.TraitDictionary.CheckDestroyed(Actor actor)
   at OpenRA.Mods.CA.Traits.PortableChronoOrderGenerator.<>c.<.ctor>b__4_1(Actor a)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at OpenRA.Mods.CA.Traits.PortableChronoOrderGenerator.RenderAnnotations(WorldRenderer wr, World world)+MoveNext()
   at OpenRA.Graphics.WorldRenderer.GenerateAnnotationRenderables()
   at OpenRA.Graphics.WorldRenderer.PrepareRenderables()
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)


```

## Additional information

I had three other near identical crashes, with the exceptions
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (ctnk 2724 (not in world))
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (ctnk 1983 (not in world))
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (ctnk 768 (not in world))
At a glance they are all otherwise identical. Most of them occurred during Allied mission 5, 'ctnk 1983' occurred during mission 3.

**Comment by PunkPun** [comment]
@darkademic

**Comment by PunkPun** [comment]
This is an issue with Combined Arms, please report it to their repository https://github.com/Inq8/CAmod/issues
