### ISSUE TITLE
crash, seg fault even

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#21009]
release-20230225

Likely the map: UF_Fast_WW3_PMG-1.oramap 

multi player game, near the end.

```
.openra/maps/ra/release-20230225/UF_Fast_WW3_PMG-1.oramap was updated
Exception of type `System.IndexOutOfRangeException`: Index was outside the bounds of the array.
   at OpenRA.Mods.Common.Graphics.DefaultSpriteSequence.GetSprite(Int32 start, Int32 frame, WAngle facing) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Graphics/DefaultSpriteSequence.cs:line 564
   at OpenRA.Mods.Common.Graphics.DefaultSpriteSequence.GetSprite(Int32 frame, WAngle facing) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Graphics/DefaultSpriteSequence.cs:line 543
   at OpenRA.Mods.Common.Effects.SpriteEffect.Tick(World world) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Effects/SpriteEffect.cs:line 76
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/WorldUtils.cs:line 75
   at OpenRA.World.Tick() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/World.cs:line 448
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 639
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 654
   at OpenRA.Game.Loop() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 823
   at OpenRA.Game.Run() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenRA/OpenRA/OpenRA.Launcher/Program.cs:line 32

Segmentation fault (core dumped)

```

**Comment by PunkPun** [comment]
bleed uses a completely different way of loading sequences, so I'm not sure how useful this is

**Comment by anvilvapre** [comment]
the segfault is interesting, would have expected dotnet to avoid that.

**Comment by abcdefg30** [comment]
Is this reproducible? (On bleed as well?)

**Comment by anvilvapre** [comment]
Reproducible using replay in release. Haven't tried bleed.

```
Exception of type `System.IndexOutOfRangeException`: Index was outside the bounds of the array.
   at OpenRA.Mods.Common.Graphics.DefaultSpriteSequence.GetSprite(Int32 start, Int32 frame, WAngle facing) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Graphics/DefaultSpriteSequence.cs:line 564
   at OpenRA.Mods.Common.Graphics.DefaultSpriteSequence.GetSprite(Int32 frame, WAngle facing) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Graphics/DefaultSpriteSequence.cs:line 543
   at OpenRA.Mods.Common.Effects.SpriteEffect.Tick(World world) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Effects/SpriteEffect.cs:line 76
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/WorldUtils.cs:line 75
   at OpenRA.World.Tick() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/World.cs:line 448
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 639
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 654
   at OpenRA.Game.Loop() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 823
   at OpenRA.Game.Run() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenRA/OpenRA/OpenRA.Launcher/Program.cs:line 32

```
See replay attached. 18:45 is end of game.

**Comment by anvilvapre** [comment]
[ra-2023-08-20T194000Z.zip](https://github.com/OpenRA/OpenRA/files/12446349/ra-2023-08-20T194000Z.zip)

**Comment by PunkPun** [comment]
Looks like an issue with the map. I suspect this is outdated
