### ISSUE TITLE
`lua51.dll` crashes the game on 32-bit Windows

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#21033]
This was recently [reported on Discord](https://discord.com/channels/153649279762694144/279290580201373696/1145749330377056367):
```
OpenRA engine version playtest-20230808
OpenRA Language: en
Red Alert mod version playtest-20230808
on map 5f4f8d88b90f2a7ef776e75b183c1d14ac2d2c3f (Desert Shellmap by Scott_NZ).
Date: 2023-08-28 15:56:21Z
Operating System: Windows (X86, Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 6.0.20
Installed Language: hu (Installed) hu (Current) hu (Current UI)
Exception of type `System.DllNotFoundException`: Unable to load DLL 'lua51' or one of its dependencies: A megadott modul nem található. (0x8007007E)
TypeName=``
   at Eluant.LuaApi.lua_newstate(LuaAllocator f, IntPtr ud)
   at Eluant.LuaRuntime..ctor()
   at Eluant.MemoryConstrainedLuaRuntime..ctor()
   at OpenRA.Scripting.ScriptContext..ctor(World world, WorldRenderer worldRenderer, IEnumerable`1 scripts)
   at OpenRA.Mods.Common.Scripting.LuaScript.OpenRA.Traits.IWorldLoaded.WorldLoaded(World world, WorldRenderer worldRenderer)
   at OpenRA.World.LoadComplete(WorldRenderer wr)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Game.LoadShellMap()
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Mods.Common.LoadScreens.ModContentLoadScreen.<>c__DisplayClass6_0.<StartGame>b__1()
   at OpenRA.Primitives.ActionQueue.PerformActions(Int64 currentTime)
   at OpenRA.Game.PerformDelayedActions()
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)
```

Investigation showed that the "new" Lua libraries produced by  https://github.com/OpenRA/Eluant/releases/tag/1.0.21  do not work on 32-bit Windows.
The simple fix turned out to be compiling them on Ubuntu-20.04 instead of Ubuntu-22.04, but that is not a great solution. The ideal fix would be to figure out what is different between the two versions and what we need to change to the workflow so it also produces working binaries when compiling on the newer Ubuntu.

**Comment by Mailaender** [comment]
I assume https://github.com/OpenRA/Eluant/commit/e886e636ff1c38281f7892046da8f19ce2c21ab0 which does not bear any description is related.

**Comment by Mailaender** [comment]
Why does reverting to Ubuntu-20.04 simply fix it?

**Comment by penev92** [comment]
I wish I knew. I was messing with the workflow until it worked, and for some reason that was the thing that fixed it.
My guess is some extra/missing/different packages are present in the two versions that affect the compilation.

**Comment by Mailaender** [comment]
https://luabinaries.sourceforge.net/download.html still has 32-bit DLLs we could use.

**Comment by penev92** [comment]
I think https://github.com/OpenRA/Eluant/pull/7 is a better temporary solution.
