### ISSUE TITLE
Saving a map copies over hidden files which can crash the process

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#21057]
Affects prep and bleed

In my case a .vscode file prevented me from saving with a null exception

```
Object reference not set to an instance of an object.
   at OpenRA.StreamExts.ReadAllBytes(Stream s) in OpenRA/OpenRA.Game/StreamExts.cs:line 128
   at OpenRA.Map.Save(IReadWritePackage toPackage) in OpenRA/OpenRA.Game/Map/Map.cs:line 650
   at OpenRA.Mods.Common.Widgets.Logic.SaveMapLogic.SaveMapInner(Map map, IReadWritePackage package, World world, ModData modData) in OpenRA/OpenRA.Mods.Common/Widgets/Logic/Editor/SaveMapLogic.cs:line 313```

**Comment by SBSixteen** [comment]
![Fsissue](https://github.com/OpenRA/OpenRA/assets/77447920/92d78251-e79b-4d7c-8978-496a6aaa7d57)

Hopefully this rectifies the issue by eliminating the hidden files in IReadWritePackage.Contents

**Comment by PunkPun** [comment]
I was more thinking of adding a null check as it does crash with null. But something like this could work in addition to that

**Comment by anvilvapre** [comment]
what happens in this case? you select the .vscode file and try to overwrite that? Package.Contents returns null?

`IPackage` is a `Folder` in this case. Where does it return `null`?
