### ISSUE TITLE
Unable to load shared library 'SDL2' or one of its dependencies on EOL Ubuntu 16.04

### ISSUE THREAD

**Issue by gimpox** [OpenRA/OpenRA#21112]
## Issue Summary
If I start OpenRA from console or from a desktop launcher, the game won't start but appears a little error window.
Usually all the Appimages I downloaded in the past was working flawless at the first shot on my Ubunt0 16.04.

DESCRIPTION

The graphics.log contains the following error:

```
System.DllNotFoundException: Unable to load shared library 'SDL2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSDL2: cannot open shared object file: No such file or directory
   at SDL2.SDL.SDL_Init(UInt32 flags)
   at OpenRA.Platforms.Default.Sdl2PlatformWindow.CanCreateGLWindow(GLProfile profile, List`1 errorLog) in /home/runner/work/OpenRA/OpenRA/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 552
   at OpenRA.Platforms.Default.Sdl2PlatformWindow.<>c__DisplayClass49_0.<.ctor>b__0(GLProfile profile) in /home/runner/work/OpenRA/OpenRA/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 155
   at System.Linq.Enumerable.WhereListIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor(Size requestEffectiveWindowSize, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile requestProfile, Boolean enableLegacyGL) in /home/runner/work/OpenRA/OpenRA/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 154
   at OpenRA.Platforms.Default.DefaultPlatform.CreateWindow(Size size, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile profile, Boolean enableLegacyGL) in /home/runner/work/OpenRA/OpenRA/OpenRA.Platforms.Default/DefaultPlatform.cs:line 21
   at OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Renderer.cs:line 78
   at OpenRA.Game.Initialize(Arguments args) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 380
```

STEPS TO REPRODUCE THE ISSUE

1. cd (your appimage folder)
2. type "./(how-you-named-your-appimage)"

EXPECTED BEHAVIOR

Game starts.

REAL BEHAVIOUR

`./OpenRA-Red-Alert-x86_64-20231010.AppImage 
Platform is Linux (X64)
Engine version is release-20231010
Runtime: .NET CLR 6.0.22
Renderer initialization failed. Check graphics.log for details.
Renderer initialization failed. Check graphics.log for details.
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
   at OpenRA.Game.Initialize(Arguments args) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 359
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 302
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenRA/OpenRA/OpenRA.Launcher/Program.cs:line 32
`

**Comment by gimpox** [comment]
FYI: the result of (successfully) launching the previous version on my Ubuntu 16.04:

```
./OpenRA-Red-Alert-x86_64_05.03.2023.AppImage 
Platform is Linux (X64)
Engine version is release-20230225
Runtime: .NET CLR 6.0.14
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1920x1080
Using resolution: 1800x1000
Using window scale 1.00
OpenGL renderer: GeForce GTX 750 Ti/PCIe/SSE2
OpenGL version: 3.2.0 NVIDIA 384.130
Using sound device `Built-in Audio Analog Stereo`
Internal mods:
	modcontent: Mod Content Manager (release-20230225)
	ra: Red Alert (release-20230225)
External mods:
	ra-release-20200503: Red Alert (release-20200503)
	cnc-release-20200503: Tiberian Dawn (release-20200503)
	ra-release-20210321: Red Alert (release-20210321)
	ra-release-20230225: Red Alert (release-20230225)
	d2k-release-20200503: Dune 2000 (release-20200503)
Loading mod: ra
```

**Comment by abcdefg30** [comment]
Is updating your OS an option? Ubuntu 16.04 seems to have an older glibc version than what we compile our native binaries with.

**Comment by gimpox** [comment]
I'm using a CAD/CAM software for my work that works miraculously with my current configuration. I would like to not touch anything for the next 2-3 years.
I'm planning to buy a second PC, but not in the immediate future.
Any other option?

**Comment by abcdefg30** [comment]
The other option would be compiling https://github.com/OpenRA/SDL2-CS with an OS that supports Ubuntu 16.04 (or ubuntu itself). I don't know which works myself though. (For reference, https://github.com/OpenRA/SDL2-CS/commit/24d14a75815c92cb547b9a7261f541ac2b538dc3 is probably the breaking change.)

**Comment by Mailaender** [comment]
Try to use https://flathub.org/apps/net.openra.OpenRA where SDL2 is part of the runtime.

**Comment by gimpox** [comment]
I will try it tomorrow. Thanks.

**Comment by gimpox** [comment]
The version on https://flathub.org/apps/net.openra.OpenRA does not work either:

```
>flatpak run net.openra.OpenRA
Ubuntu 16.04 'xenial' reached end-of-life for general support in April 2021.

The packages in the Flatpak PPAs for Ubuntu 16.04 will not necessarily
be updated, even if there are security vulnerabilities. Please upgrade
to a newer LTS branch of Ubuntu.

Platform is Linux (X64)
Engine version is release-20231010
Runtime: .NET CLR 6.0.22
/app/bin/openra-ra.real: line 20:    23 Segmentation fault      (core dumped) ./OpenRA Game.Mod=ra Engine.LaunchPath="/app/bin/openra-ra" "${JOIN_SERVER}" "$@"

```

**Comment by Mailaender** [comment]
Try https://snapcraft.io/install/openra/ubuntu instead. Also you should really update to a supported version.
