### ISSUE TITLE
A list of TS maps that fail to import

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#21126]
[Failed.zip](https://github.com/OpenRA/OpenRA/files/12925155/Failed.zip)

These 5 maps crash for various reasons, the most common crash log it seems is
```
Unhandled exception. System.OverflowException: Arithmetic operation resulted in an overflow.
   at OpenRA.Map.SavePreview() in /OpenRA/OpenRA.Game/Map/Map.cs:line 809
   at OpenRA.Map.Save(IReadWritePackage toPackage) in OpenRA/OpenRA.Game/Map/Map.cs:line 655
   at OpenRA.Mods.Cnc.UtilityCommands.ImportGen2MapCommand.Run(Utility utility, String[] args) in OpenRA/OpenRA.Mods.Cnc/UtilityCommands/ImportGen2MapCommand.cs:line 101
   at OpenRA.Mods.Cnc.UtilityCommands.ImportTiberianSunMapCommand.OpenRA.IUtilityCommand.Run(Utility utility, String[] args) in OpenRA/OpenRA.Mods.Cnc/UtilityCommands/ImportTiberianSunMapCommand.cs:line 27```

**Comment by PunkPun** [comment]
Maps are from this map pack https://ppmforums.com/topic-4391/open-map-competition-map-1-2-3-pack/

**Comment by tinix0** [comment]
Two of the maps fail on INI parsing, there is a multiline comment at the start of those where some of the comment lines do not start with ; and it looks like vanilla TS just skips those.

The arithemetic operation issue is with maps where there are cliffs near the bottom of the map. The inversecell coordinate mapping seems to be buggy and unable to handle cliffs near edges. That causes preview rendering to be unable to determine where the corner is and end up with IntMax in height.
