### ISSUE TITLE
My game crashed

### ISSUE THREAD

**Issue by basilin642** [OpenRA/OpenRA#21230]
## System Information

- Operating System:  Arch Linux
- OpenRA Version: 
Engine version is release-20231010
Runtime: .NET CLR 6.0.25

- OpenRA Mod: openra-ra
- Source: openra 20231010-2 from https://archlinux.org/packages/extra/any/openra/
- For self-compiled or third-party packages: Mono version

## Exception log

```
$ openra-ra
Platform is Linux (X64)
Engine version is release-20231010
Runtime: .NET CLR 6.0.25
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1.00
OpenGL renderer: NVIDIA GeForce GTX 1650 Ti/PCIe/SSE2
OpenGL version: 3.2.0 NVIDIA 545.29.06
Using default sound device
Internal mods:
	cnc: Tiberian Dawn (release-20231010)
	d2k: Dune 2000 (release-20231010)
	modcontent: Mod Content Manager (release-20231010)
	ra: Red Alert (release-20231010)
External mods:
	ra-{DEV_VERSION}: Red Alert ({DEV_VERSION})
	d2k-release-20210321: Dune 2000 (release-20210321)
	cnc-release-20230225: Tiberian Dawn (release-20230225)
	cnc-release-20210321: Tiberian Dawn (release-20210321)
	cnc-release-20231010: Tiberian Dawn (release-20231010)
	ra-release-20210321: Red Alert (release-20210321)
	ra-release-20231010: Red Alert (release-20231010)
	cnc-{DEV_VERSION}: Tiberian Dawn ({DEV_VERSION})
Loading mod: ra
[2023-11-25T14:14:48] Game started
[2023-11-25T14:35:46] Game started
Exception of type `System.IO.InvalidDataException`: mhowdy1.aud is not a valid sound file!
   at OpenRA.Sound.LoadSound[T](String filename, Func`2 loadFormat) in /build/openra/src/OpenRA/OpenRA.Game/Sound/Sound.cs:line 81
   at OpenRA.Sound.<PlayPredefined>g__PlaySound|83_0(<>c__DisplayClass83_0& ) in /build/openra/src/OpenRA/OpenRA.Game/Sound/Sound.cs:line 416
   at OpenRA.Sound.PlayPredefined(SoundType soundType, Ruleset ruleset, Player player, Actor voicedActor, String type, String definition, String variant, Boolean relative, WPos pos, Single volumeModifier, Boolean attenuateVolume)
   at OpenRA.Mods.Common.Traits.Voiced.OpenRA.Traits.IVoiced.PlayVoice(Actor self, String phrase, String variant) in /build/openra/src/OpenRA/OpenRA.Mods.Common/Traits/Voiced.cs:line 50
   at OpenRA.VoiceExts.PlayVoice(Actor self, String phrase) in /build/openra/src/OpenRA/OpenRA.Game/VoiceExts.cs:line 26
   at OpenRA.Mods.Common.Traits.Selection.Combine(World world, IEnumerable`1 newSelection, Boolean isCombine, Boolean isClick) in /build/openra/src/OpenRA/OpenRA.Mods.Common/Traits/World/Selection.cs:line 140
   at OpenRA.Mods.Common.Widgets.WorldInteractionControllerWidget.HandleMouseInput(MouseInput mi) in /build/openra/src/OpenRA/OpenRA.Mods.Common/Widgets/WorldInteractionControllerWidget.cs:line 177
   at OpenRA.Widgets.Ui.HandleInput(MouseInput mi) in /build/openra/src/OpenRA/OpenRA.Game/Widgets/Widget.cs:line 101
   at OpenRA.DefaultInputHandler.<>c__DisplayClass5_0.<OnMouseInput>b__0() in /build/openra/src/OpenRA/OpenRA.Game/Input/InputHandler.cs:line 50
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) in /build/openra/src/OpenRA/OpenRA.Game/Sync.cs:line 205
   at OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input) in /build/openra/src/OpenRA/OpenRA.Game/Input/InputHandler.cs:line 51
   at OpenRA.Platforms.Default.Sdl2Input.PumpInput(Sdl2PlatformWindow device, IInputHandler inputHandler, Nullable`1 lockedMousePosition) in /build/openra/src/OpenRA/OpenRA.Platforms.Default/Sdl2Input.cs:line 144
   at OpenRA.Platforms.Default.Sdl2PlatformWindow.PumpInput(IInputHandler inputHandler) in /build/openra/src/OpenRA/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 500
   at OpenRA.Renderer.EndFrame(IInputHandler inputHandler) in /build/openra/src/OpenRA/OpenRA.Game/Renderer.cs:line 310
   at OpenRA.Game.RenderTick() in /build/openra/src/OpenRA/OpenRA.Game/Game.cs:line 728
   at OpenRA.Game.Loop() in /build/openra/src/OpenRA/OpenRA.Game/Game.cs:line 836
   at OpenRA.Game.Run() in /build/openra/src/OpenRA/OpenRA.Game/Game.cs:line 868
   at OpenRA.Game.InitializeAndRun(String[] args) in /build/openra/src/OpenRA/OpenRA.Game/Game.cs:line 306
   at OpenRA.Launcher.Program.Main(String[] args) in /build/openra/src/OpenRA/OpenRA.Launcher/Program.cs:line 32
```
[exception-2023-11-25T084439Z.log](https://github.com/OpenRA/OpenRA/files/13463443/exception-2023-11-25T084439Z.log)

## Replay

[ra-2023-11-25T073547Z.orarep.zip](https://github.com/OpenRA/OpenRA/files/13463439/ra-2023-11-25T073547Z.orarep.zip)

**Comment by basilin642** [comment]
Oh almost forgotten troublemaker-file
$ shasum ./.config/openra/Content/ra/v2/expand/mhowdy1.aud
ef105b95a0209eb03716fca4cb42ac6fb9fc6602  ./.config/openra/Content/ra/v2/expand/mhowdy1.aud
[mhowdy1.aud.zip](https://github.com/OpenRA/OpenRA/files/13463459/mhowdy1.aud.zip)

**Comment by basilin642** [comment]
Lol I check out log files red alert is buugy stuff:
```
$ grep -rn 'aud' ~/.config/openra/Logs
/home/basil/.config/openra/Logs/exception-2022-06-18T093208Z.log:7:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-05-21T024806Z.log:7:Exception of type `System.IO.InvalidDataException`: mhowdy1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2023-11-17T122116Z.log:9:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2023-01-20T164149Z.log:9:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-05-29T135926Z.log:7:Exception of type `System.IO.InvalidDataException`: madchrg2.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-06-18T042627Z.log:7:Exception of type `System.IO.InvalidDataException`: mhowdy1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-05-08T091455Z.log:7:Exception of type `System.IO.InvalidDataException`: jjuice1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2023-11-25T084439Z.log:9:Exception of type `System.IO.InvalidDataException`: mhowdy1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-05-11T133843Z.log:7:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-05-03T130934Z.log:7:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-05-04T153540Z.log:7:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-05-08T134841Z.log:7:Exception of type `System.IO.InvalidDataException`: mhuh1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2023-01-22T125311Z.log:9:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-05-13T143711Z.log:7:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2023-01-22T053643Z.log:9:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-05-10T034349Z.log:7:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2023-11-24T113955Z.log:9:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2023-01-22T125810Z.log:9:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-06-19T050549Z.log:7:Exception of type `System.IO.InvalidDataException`: mlaff1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2023-01-21T150133Z.log:9:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-05-03T132601Z.log:7:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-05-21T062816Z.log:7:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-05-04T124341Z.log:7:Exception of type `System.IO.InvalidDataException`: jjump1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-05-13T124943Z.log:7:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2021-04-21T181640Z.log:7:Exception of type `System.IO.InvalidDataException`: jjuice1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2023-01-21T150546Z.log:9:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-05-08T015942Z.log:7:Exception of type `System.IO.InvalidDataException`: jyes1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-06-05T132817Z.log:7:Exception of type `System.IO.InvalidDataException`: jjump1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-06-19T124325Z.log:7:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-06-19T051236Z.log:7:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-05-08T063500Z.log:7:Exception of type `System.IO.InvalidDataException`: jjuice1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2023-11-15T143453Z.log:9:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-06-04T140906Z.log:7:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2023-01-21T110730Z.log:9:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-06-19T061407Z.log:7:Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-05-09T041607Z.log:7:Exception of type `System.IO.InvalidDataException`: madchrg2.aud is not a valid sound file!
/home/basil/.config/openra/Logs/exception-2022-05-22T101507Z.log:7:Exception of type `System.IO.InvalidDataException`: jyes1.aud is not a valid sound file!
```

**Comment by basilin642** [comment]
Is this problem only for arch-users?

**Comment by abcdefg30** [comment]
Where did you install your content from? It looks like that audio file is corrupted.

**Comment by basilin642** [comment]
got some iso file with cnc95
I've deleted it long time ago
where can I get right one?
except torrents
Are there sources available?

**Comment by basilin642** [comment]
Could I have checksum of right file?
and Could you give me a clue how to reproduce crash?
I suppose it is necessary to check your idea)

**Comment by abcdefg30** [comment]
Sorry for the late delay. From the crash message the culprit are the sounds of the expansion, so units like Shok Troopers and Mechanics should produce the crash when selected/ordered. (The exception message points to mechanics.)
Sha1 checksum:
> %AppData%\OpenRA\Content\ra\v2\expand> sha1sum.exe .\mhowdy1.aud
\863df676ca7fdcb359250f0e5d7f56847c78e3b6 *.\\mhowdy1.aud

**Comment by abcdefg30** [comment]
You can delete the content and re-download it by starting the game and using our base download. We don't offer the music and videos though, so I'd recommend backing up the `expand` folder, and then just deleting that folder. After the download you can re-add the files that weren't downloaded (should be one .mix file for the music).

**Comment by Mailaender** [comment]
My checksum is different

```
$ shasum ./.config/openra/Content/ra/v2/expand/mhowdy1.aud
863df676ca7fdcb359250f0e5d7f56847c78e3b6  ./.config/openra/Content/ra/v2/expand/mhowdy1.aud
```

so this is likely corrupted data on your side.
