### ISSUE TITLE
Unable to install Red Alert from The First Decade DVD

### ISSUE THREAD

**Issue by kelvSYC** [OpenRA/OpenRA#21289]
## Issue Summary
I encountered an issue when trying to install the Red Alert using The First Decade DVD.

Though most of the assets I obtained were from the Remastered Collection, The First Decade was needed for the original Soviet cutscenes. Because of this, I pulled out my copy of The First Decade DVD. Though OpenRA was able to detect the DVD, it was unable to install the cutscenes.

Inspecting the `install.log` file suggests that I was missing a file at `~/Library/Application Support/OpenRA/Content/ra/v2/main.mix`.

This persists even if I removed all of the Red Alert assets obtained from the Remastered Collection and attempted to obtain all assets from The First Decade.

## Reproduction
From the Red Alert OpenRA app, launch, then follow instructions while The First Decade DVD was in an external drive.

## Expected behavior
Expecting the installation of assets to proceed normally.

## Workaround
The installation was able to proceed by copying a `main.mix` from an existing Red Alert installation, and copying it to the indicated path. It does not appear that `main.mix` is otherwise needed, but my install has retained it just in case.

**Comment by ImTheEscapePlan** [comment]
same issue but on windows, thanks for the workaround!

**Comment by vbartels** [comment]
Hi, I have the same problem on linux. I compiled release 20231010 from source. 
C&C The First Decade (English) DVD is detected but copying fails.
This is from the install.log:

```
Using installer `tfd: C&C The First Decade (English)\` of type `Disc`:
System.IO.FileNotFoundException: Could not find file '/home/veit/.config/openra/Content/ra/v2/main.mix'.
File name: '/home/veit/.config/openra/Content/ra/v2/main.mix'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at OpenRA.Mods.Cnc.Installer.ExtractMixSourceAction.RunActionOnSource(MiniYaml actionYaml, String path, ModData modData, List`1 extracted, Action`1 updateMessage) in /home/veit/Downloads/openra/OpenRA.Mods.Cnc/Installer/ExtractMixSourceAction.cs:line 30
   at OpenRA.Mods.Common.Widgets.Logic.InstallFromSourceLogic.<>c__DisplayClass44_0.<InstallFromSource>g__RunSourceActions|2(MiniYamlNode contentPackageYaml, <>c__DisplayClass44_1& ) in /home/veit/Downloads/openra/OpenRA.Mods.Common/Widgets/Logic/Installation/InstallFromSourceLogic.cs:line 256
   at OpenRA.Mods.Common.Widgets.Logic.InstallFromSourceLogic.<>c__DisplayClass44_0.<InstallFromSource>b__1() in /home/veit/Downloads/openra/OpenRA.Mods.Common/Widgets/Logic/Installation/InstallFromSourceLogic.cs:line 268
```
Edit:
I copied just main.mix over from a windows install and then the copy through the gui was possible.
