### ISSUE TITLE
Cannot AddInfluence until previous influence is removed with RemoveInfluence

### ISSUE THREAD

**Issue by HakkaTjakka** [OpenRA/OpenRA#21302]
```
OpenRA engine version release-20231010
OpenRA Language: en
Red Alert mod version release-20231010
on map 90cf7e868507cd3d76403b788a329025326d61b3 (WW3 Dry Europe v3.0.7 by H + Waggy).
Date: 2024-01-15 00:19:47Z
Operating System: Linux (X64, Unix 6.5.0.14)
Runtime Version: .NET CLR 6.0.22
Installed Language: en (Installed) en (Current) en (Current UI)
Exception of type `System.InvalidOperationException`: Cannot AddInfluence until previous influence is removed with RemoveInfluence
   at OpenRA.Mods.Common.Traits.Aircraft.AddInfluence(ValueTuple`2[] landingCells) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/Air/Aircraft.cs:line 870
   at OpenRA.Mods.Common.Traits.Aircraft.AddInfluence(CPos landingCell) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/Air/Aircraft.cs:line 881
   at OpenRA.Mods.Common.Activities.Land.Tick(Actor self) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Activities/Air/Land.cs:line 232
   at OpenRA.Activities.Activity.TickOuter(Actor self) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Traits/ActivityUtils.cs:line 29
   at OpenRA.Activities.Activity.TickChild(Actor self) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Activities/Activity.cs:line 144
   at OpenRA.Activities.Activity.TickOuter(Actor self) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Traits/ActivityUtils.cs:line 29
   at OpenRA.Actor.Tick() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Actor.cs:line 262
   at OpenRA.World.Tick() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/World.cs:line 446
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 631
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 646
   at OpenRA.Game.Loop() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 815
   at OpenRA.Game.Run() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 868
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 306
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenRA/OpenRA/OpenRA.Launcher/Program.cs:line 32
```

**Comment by ThomasChr** [comment]
Hi @HakkaTjakka 
any infos about how I can reproduce the crash?

**Comment by penev92** [comment]
@ThomasChr please refer to [this comment](https://discord.com/channels/153649279762694144/279290580201373696/1193882924567773224) on Discord and my investigation that it comes from, which is about the same crash on the same map.
![image](https://github.com/OpenRA/OpenRA/assets/7137365/eef41db4-3ce9-4499-ac9e-634e0abf5f28)

**Comment by darkademic** [comment]
I think I can replicate this reliably.

Force land two aircraft adjacent to each other, then force move one of them onto the other one.

(It also works if you do the same with an aircraft force moving onto a unit that won't be nudged for some reason, which seems to be the case for a harvester that is looking for resources but can't find any (so it's not idle, but not moving).

**Comment by LipkeGu** [comment]
I tried to update the map to bleed but: ICSharpCode.SharpZipLib.SharpZipBaseException: broken uncompressed block
