### ISSUE TITLE
Support packing maps to .oramap using third-party software

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#21323]
## System Information

- Operating System:  Windows 11 Pro (x64)
- OpenRA Version: DEV-VERSION (bleed)
- OpenRA Mod: ra
- Source: Official download package OR self-compiled OR third-party package
- For self-compiled or third-party packages: Mono version

## Exception log

```
RemoveValidRelationsFromCapturable: Remove ValidRelations property from Capturable.
   Updating map... FAILED

   The automated changes for this rule were not applied because of an error.
   After the issue reported below is resolved you should run the updater
   with SOURCE set to RemoveValidRelationsFromCapturable to retry these changes

   The exception reported was:
     ICSharpCode.SharpZipLib.Zip.ZipException: Failed to copy bytes expected 108 read 0
        at ICSharpCode.SharpZipLib.Zip.ZipFile.CopyEntryDataDirect(ZipUpdate update, Stream stream, Boolean updateCrc, Int64& destinationPosition, Int64& sourcePosition)
        at ICSharpCode.SharpZipLib.Zip.ZipFile.CopyEntryDirect(ZipFile workFile, ZipUpdate update, Int64& destinationPosition)
        at ICSharpCode.SharpZipLib.Zip.ZipFile.RunUpdates()
        at ICSharpCode.SharpZipLib.Zip.ZipFile.CommitUpdate()
        at OpenRA.FileSystem.ZipFileLoader.ReadWriteZipFile.Update(String filename, Byte[] contents) in D:\Project\OpenRA\OpenRA.Game\FileSystem\ZipFile.cs:line 128
        at OpenRA.Mods.Common.UpdateRules.UpdateExtensions.Save(List`1 files) in D:\Project\OpenRA\OpenRA.Mods.Common\UpdateRules\UpdateUtils.cs:line 349
        at OpenRA.Mods.Common.UtilityCommands.UpdateMapCommand.ApplyRules(ModData modData, IReadWritePackage mapPackage, IEnumerable`1 rules) in D:\Project\OpenRA\OpenRA.Mods.Common\UtilityCommands\UpdateMapCommand.cs:line 112
ExtractResourceStorageFromHarvester: Renames StoresResources to StoresPlayerResources and extracts StoresResources from Harvester.
   Updating map... FAILED

   The automated changes for this rule were not applied because of an error.
   After the issue reported below is resolved you should run the updater
   with SOURCE set to ExtractResourceStorageFromHarvester to retry these changes

   The exception reported was:
     System.ObjectDisposedException: Cannot access a disposed object.
     Object name: 'ZipFile'.
        at ICSharpCode.SharpZipLib.Zip.ZipFile.GetEntry(String name)
        at OpenRA.FileSystem.ZipFileLoader.ReadOnlyZipFile.GetStream(String filename) in D:\Project\OpenRA\OpenRA.Game\FileSystem\ZipFile.cs:line 40
        at OpenRA.Mods.Common.UpdateRules.UpdateUtils.UpdateMap(ModData modData, IReadWritePackage mapPackage, UpdateRule rule, List`1& files, HashSet`1 externalFilenames) in D:\Project\OpenRA\OpenRA.Mods.Common\UpdateRules\UpdateUtils.cs:line 88
        at OpenRA.Mods.Common.UtilityCommands.UpdateMapCommand.ApplyRules(ModData modData, IReadWritePackage mapPackage, IEnumerable`1 rules) in D:\Project\OpenRA\OpenRA.Mods.Common\UtilityCommands\UpdateMapCommand.cs:line 109
ReplacePaletteModifiers: Replace palette modifiers with post-processing shaders.
   Updating map... FAILED
```

## Replay
try to update the map https://resource.openra.net/maps/55706/

**Comment by LipkeGu** [comment]
It seems to happen when a map is repacked with winrar

**Comment by PunkPun** [comment]
related #8999

it has been true for a while that a lot of zippers aren't compatible with our zip library.

The usual recommendation we give is to use map editor to compress. Though alternatives have beed found, f.e. the python zip library produces compatible maps

**Comment by anvilvapre** [comment]
Perhaps clarify the exception message so that in future people understand the cause and can find the solution themselves. i.e. refer them to comp zip application.

**Comment by Mailaender** [comment]
It works just fine with https://apps.kde.org/ark/

**Comment by Mailaender** [comment]
Actually I can also create incompatible ZIP with Ark. This is essentially an upstream problem

https://github.com/icsharpcode/SharpZipLib/blob/ff2d7c30bdb2474d507f001bc555405e9f02a0bb/src/ICSharpCode.SharpZipLib/Zip/ZipConstants.cs#L45-L68

due to some compression types not being supported.

**Comment by Mailaender** [comment]
https://resource.openra.net/maps/55706/ is standard Deflate compressed though.

**Comment by Mailaender** [comment]
Comparing the broken file with a recompressed, known working version using `zipinfo -v` I see additional fields
```
  MS-DOS file attributes (20 hex):                arc

  The central-directory extra field contains:
  - A subfield with ID 0x000a (PKWARE Win32) and 32 data bytes.  The first
    20 are:   00 00 00 00 01 00 18 00 6e c2 17 75 15 0f da 01 3e 24 9c 3b.

  There is no file comment.
```

which is an NTFS extra field https://github.com/icsharpcode/SharpZipLib/blob/ff2d7c30bdb2474d507f001bc555405e9f02a0bb/docs/specification/appnote.txt#L1137
