### ISSUE TITLE
OpenSA crashed shortly after start 

### ISSUE THREAD

**Issue by Kurominos** [OpenRA/OpenRA#21349]
- Operating System:  Windows 11
- OpenRA Version: 386f691c2e1f469596ef6f58e258a10a176bdc3d
- OpenRA Mod: Swarm assault
- Source: Official download package OR self-compiled OR third-party package
- For self-compiled or third-party packages: Mono version

## Exception log

```
PASTE LOG HERE
```
Exception of type `System.IO.InvalidDataException`: Non-power-of-two array 768x768
   at OpenRA.Platforms.Default.Texture.SetData(Byte[] colors, Int32 width, Int32 height)
   at OpenRA.Platforms.Default.ThreadedTexture.<>c__DisplayClass11_0.<.ctor>b__5(Object tuple)
   at OpenRA.Platforms.Default.ThreadedTexture.<>c__DisplayClass11_0.<.ctor>b__6(Object tuple)
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.Message.Execute()
--- End of stack trace from previous location ---
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.Message.Result()
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.RunMessage(Message message)
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.Send[T](Func`2 method, Object state)
   at OpenRA.Platforms.Default.ThreadedTexture.SetData(Byte[] colors, Int32 width, Int32 height)
   at OpenRA.Graphics.Sheet.GetTexture()
   at OpenRA.Graphics.Sheet.ReleaseBuffer()
   at OpenRA.Graphics.Sheet..ctor(SheetType type, Stream stream)
   at OpenRA.Graphics.ChromeProvider.SheetForCollection(Collection c)
   at OpenRA.Graphics.ChromeProvider.TryGetImage(String collectionName, String imageName)
   at OpenRA.Mods.Common.Widgets.WidgetUtils.<>c__DisplayClass1_0.<GetCachedStatefulImage>b__0(ValueTuple`5 args)
   at OpenRA.Mods.Common.Widgets.CachedTransform`2.Update(T input)
   at OpenRA.Mods.Common.Widgets.DropDownButtonWidget.Draw()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Mods.Common.Widgets.ScrollPanelWidget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)

## Additional information

The Game starts ..loads ..then the music starts playing for a split second then it crashes

**Comment by abcdefg30** [comment]
Seems like this would be better reported at https://github.com/Dzierzan/OpenSA/issues for @Dzierzan to see.
