### ISSUE TITLE
Crashed on renderer thread for InvalidDataException: Non-power-of-two array 1025x1024

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#21377]
Crash on start.

Shattered Paradise engine version [233aa77405c91a10751a25b58b834ae1f4283d62](https://github.com/MustaphaTR/OpenRA/commit/233aa77405c91a10751a25b58b834ae1f4283d62)

Based on OpenRA engine 63247d2d11f19be56e145a673c472c15419e02a9

We didn't change any render thread code.

OpenRA Language: en
Shattered Paradise mod version playtest-20240315
Operating System: Windows (X64, Microsoft Windows NT 10.0.22631.0)
Runtime Version: .NET CLR 6.0.27
Installed Language: de (Installed) de (Current) de (Current UI)

There is the log

```
OpenRA engine version 233aa77405c91a10751a25b58b834ae1f4283d62
OpenRA Language: en
Shattered Paradise mod version playtest-20240315
on map 7794df3defa538d607a7bd7ab389eaa0e8d1bf2e (Enter the Hivemind by Westwood Studios).
Date: 2024-03-28 22:13:33Z
Operating System: Windows (X64, Microsoft Windows NT 10.0.22631.0)
Runtime Version: .NET CLR 6.0.27
Installed Language: de (Installed) de (Current) de (Current UI)
Exception of type System.IO.InvalidDataException: Non-power-of-two array 1025x1024
at OpenRA.Platforms.Default.Texture.SetData(Byte[] colors, Int32 width, Int32 height)
at OpenRA.Platforms.Default.ThreadedTexture.<>c__DisplayClass12_0.<.ctor>b__5(Object tuple)
at OpenRA.Platforms.Default.ThreadedTexture.<>c__DisplayClass12_0.<.ctor>b__6(Object tuple)
at OpenRA.Platforms.Default.ThreadedGraphicsContext.Message.Execute()
--- End of stack trace from previous location ---
at OpenRA.Platforms.Default.ThreadedGraphicsContext.Message.Result()
at OpenRA.Platforms.Default.ThreadedGraphicsContext.RunMessage(Message message)
at OpenRA.Platforms.Default.ThreadedGraphicsContext.Send[T](Func2 method, Object state) at OpenRA.Platforms.Default.ThreadedTexture.SetData(Byte[] colors, Int32 width, Int32 height) at OpenRA.Graphics.Sheet.GetTexture() at OpenRA.Graphics.Sheet.ReleaseBuffer() at OpenRA.Graphics.Sheet..ctor(SheetType type, Stream stream) at OpenRA.Graphics.ChromeProvider.SheetForCollection(Collection c) at OpenRA.Graphics.ChromeProvider.TryGetImage(String collectionName, String imageName) at OpenRA.Mods.Common.Widgets.WidgetUtils.<>c__DisplayClass1_0.<GetCachedStatefulImage>b__0(ValueTuple5 args)
at OpenRA.Mods.Common.Widgets.CachedTransform`2.Update(T input)
at OpenRA.Mods.Common.Widgets.DropDownButtonWidget.Draw()
at OpenRA.Widgets.Widget.DrawOuter()
at OpenRA.Widgets.Widget.DrawOuter()
at OpenRA.Widgets.Widget.DrawOuter()
at OpenRA.Widgets.Widget.DrawOuter()
at OpenRA.Widgets.Ui.Draw()
at OpenRA.Game.RenderTick()
at OpenRA.Game.Loop()
at OpenRA.Game.Run()
at OpenRA.Game.InitializeAndRun(String[] args)
at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)
```

**Comment by dnqbob** [comment]
https://github.com/ABrandau/Shattered-Paradise-SDK/issues/60

**Comment by RoosterDragon** [comment]
The texture dimensions need to be powers of 2, so crashing for a width of 1025 is expected.

Looks like you fixed it via https://github.com/ABrandau/Shattered-Paradise-SDK/commit/e970d7f14f3411bf833ee86efe2df1eb40eca5a1? If so there's nothing to do in OpenRA here. We're crashing due to bad input, and you've fixed the bad input.
