### ISSUE TITLE
Fractured Realm Fatal Error

### ISSUE THREAD

**Issue by freak1q** [OpenRA/OpenRA#21394]
When I try to enter the game.. getting fatal error. 

Here is the logs.

```

OpenRA engine version 7f3a922
OpenRA Language: en
Fractured Realms mod version v1.2 (Release 2023.07.23)
on map 6e2fdbf953d6348c456c555a13515bba19c65147 (Shellmap2 by Divadawm).
Date: 2024-04-09 09:30:40Z
Operating System: Windows (X64, Microsoft Windows NT 10.0.22631.0)
Runtime Version: .NET CLR 6.0.2

Installed Language: tr (Installed) tr (Current) tr (Current UI)
Exception of type `Eluant.LuaException`: [string "--[[..."]:15: module 'sandbox' not found:
	no field package.preload['sandbox']
	no file 'C:\Users\palad\OneDrive\Masaüstü\FR\/lua/sandbox.lua'
	no file '.\sandbox.dll'
	no file 'C:\Users\palad\OneDrive\Masa st \FR\sandbox.dll'
	no file 'C:\Users\palad\OneDrive\Masa st \FR\loadall.dll'
	no file 'C:\Users\palad\OneDrive\Masa st \FR\clibs\sandbox.dll'
	no file 'C:\Users\palad\OneDrive\Masa st \FR\clibs\loadall.dll'
	no file '.\sandbox51.dll'
	no file 'C:\Users\palad\OneDrive\Masa st \FR\sandbox51.dll'
	no file 'C:\Users\palad\OneDrive\Masa st \FR\clibs\sandbox51.dll'
   at Eluant.LuaRuntime.Call(IList`1 args)
   at Eluant.LuaRuntime.DoBuffer(String str, String name)
   at OpenRA.Scripting.ScriptContext..ctor(World world, WorldRenderer worldRenderer, IEnumerable`1 scripts)
   at OpenRA.Mods.Common.Scripting.LuaScript.OpenRA.Traits.IWorldLoaded.WorldLoaded(World world, WorldRenderer worldRenderer)
   at OpenRA.World.LoadComplete(WorldRenderer wr)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Game.LoadShellMap()
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)


```

**Comment by PunkPun** [comment]
OpenRA is not responsible for fractured realms. Refer this error to its devs.

I have no idea what they have done to the engine, but it seems something's very wrong with the lua integration
