### ISSUE TITLE
ServerListLogic, Only send beaconlib probes during LAN games.

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#21417]
Request to only run a BeaconLib probe when the use chooses to start or join a LAN game. Not by default when joining an online Internet game.

https://github.com/OpenRA/OpenRA/blob/d91d1f5466e65be370bdfe3f0755ecdca3c21e20/OpenRA.Mods.Common/Widgets/Logic/ServerListLogic.cs#L404-L414

Results in the following journal entries. Messages seem to be repeated each 2 seconds.

```
OpenRA[24061]: System.Net.Sockets.SocketException (13): Permission denied
                                      at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketE
rror error, String callerName)
                                      at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, Socke
tFlags socketFlags, EndPoint remoteEP)
                                      at System.Net.Sockets.UdpClient.Send(Byte[] dgram, Int32 bytes, IPEndPoint endPoin
t)
                                      at BeaconLib.Probe.BroadcastProbe()
                                      at BeaconLib.Probe.BackgroundLoop()

```

Goal: do not run unneeded additional network services, do not generate any unnessecary network traffic.

People who play at work will be thankfull ; )

**Comment by anvilvapre** [comment]
https://github.com/rix0rrr/beacon/blob/eeb5e3b6dccfba57b1a21ce29ce85ef1378b817f/BeaconLib/Probe.cs#L103-L107
