### ISSUE TITLE
XCC mixer TD SHP: Reference doesn't point to image data

### ISSUE THREAD

**Issue by Typhoon-95** [OpenRA/OpenRA#21422]
## System Information

- Operating System:  Windows 10 x64 22H2
- OpenRA Version: release-20231010
- OpenRA Mod: openra-cnc
- Source: Official download from the website
- For self-compiled or third-party packages: Mono version

## Exception log

```
OpenRA engine version release-20231010
OpenRA Language: en
Tiberian Dawn mod version release-20231010
Date: 2024-05-10 15:33:57Z
Operating System: Windows (X64, Microsoft Windows NT 10.0.19045.0)
Runtime Version: .NET CLR 6.0.22
Installed Language: es (Installed) es (Current) es (Current UI)
Exception of type `System.IO.InvalidDataException`: Reference doesn't point to image data 70788->4633
   at OpenRA.Mods.Cnc.SpriteLoaders.ShpTDSprite..ctor(Stream stream)
   at OpenRA.Mods.Cnc.SpriteLoaders.ShpTDLoader.TryParseSprite(Stream s, String filename, ISpriteFrame[]& frames, TypeDictionary& metadata)
   at OpenRA.Graphics.SpriteCache.GetFrames(IReadOnlyFileSystem fileSystem, String filename, ISpriteLoader[] loaders, TypeDictionary& metadata)
   at OpenRA.Graphics.SpriteCache.LoadReservations(ModData modData)
   at OpenRA.Graphics.SequenceSet.LoadSprites()
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.World..ctor(String mapUID, ModData modData, OrderManager orderManager, WorldType type)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Game.LoadShellMap()
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)
```

## Additional information

I've been trying to add a new unit based on the Mammoth Mark 2, with both idle and move sequences included in my shp file. I modded the defaults.yaml and each of the vehicles yaml files located in rules and sequences respectively to get this working. The games starts and crashes after some seconds, giving me this error as a result.

**Comment by Mailaender** [comment]
How did you create the `.shp` file?

**Comment by Typhoon-95** [comment]
First, I converted all the frames from Blender into TD's temperat palette using the ImageShaper tool, giving me a TS shp file with TD colors. Then, I separated all the frames into png files using XCC Mixer and finally, I turned all the images into an actual TD shp file with the same tool

**Comment by anvilvapre** [comment]
OpenRA.Mods.Cnc/SpriteLoaders/ShpTDLoader.cs
```
else if (h.Format == Format.XORLCW && !offsets.TryGetValue(h.RefOffset, out h.RefImage))
                                        throw new InvalidDataException($"Reference doesn't point to image data {h.FileOffset}->{h.RefOffset}");                                                                                                 
                        }            
```

**Comment by abcdefg30** [comment]
Can you try using the shp (TS) format instead of the TD one?

**Comment by Typhoon-95** [comment]
Hi, I'm very sorry for the late response. My E-Mail never notified me of your post. I was able to get my animation working by separating my model into two TD shp files. The first one for the main body and another one for the legs containing the walking animation
