### ISSUE TITLE
Attempted to get trait from destroyed object in SquadManagerBotModule.FindEnemies

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#21438]
commit 8c174551f575097f42bf747f0e78447a19a4027c

```
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (scout2 3103 (not in world))
   at OpenRA.TraitDictionary.CheckDestroyed(Actor actor) in OpenRA.Game/TraitDictionary.cs:line 84
   at OpenRA.Mods.Common.Traits.SquadManagerBotModule.FindEnemies(IEnumerable`1 actors, Actor sourceActor)
   at OpenRA.Mods.Common.Traits.BotModules.Squads.Squad.IsTargetValid(Actor squadUnit) in OpenRA.Mods.Common/Traits/BotModules/Squads/Squad.cs:line 118
   at OpenRA.Mods.Common.Traits.SquadManagerBotModule.ProtectOwn(IBot bot, Actor attacker) in OpenRA.Mods.Common/Traits/BotModules/SquadManagerBotModule.cs:line 484
   at OpenRA.Mods.Common.Traits.ModularBot.<>c__DisplayClass15_0.<OpenRA.Mods.Common.Traits.INotifyDamage.Damaged>b__0() in OpenRA.Mods.Common/Traits/Player/ModularBot.cs:line 115
   at OpenRA.Sync.<>c__DisplayClass14_0.<RunUnsynced>b__0() in OpenRA.Game/Sync.cs:line 172
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) in OpenRA.Game/Sync.cs:line 203
   at OpenRA.Sync.RunUnsynced(Boolean checkSyncHash, World world, Action fn) in OpenRA.Game/Sync.cs:line 173
   at OpenRA.Mods.Common.Traits.ModularBot.OpenRA.Mods.Common.Traits.INotifyDamage.Damaged(Actor self, AttackInfo e) in OpenRA.Mods.Common/Traits/Player/ModularBot.cs:line 118
   at OpenRA.Mods.Common.Traits.Health.InflictDamage(Actor self, Actor attacker, Damage damage, Boolean ignoreModifiers) in OpenRA.Mods.Common/Traits/Health.cs:line 204
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, WarheadArgs args) in OpenRA.Mods.Common/Warheads/SpreadDamageWarhead.cs:line 123
   at OpenRA.GameRules.WeaponInfo.Impact(Target& target, WarheadArgs args) in OpenRA.Game/GameRules/WeaponInfo.cs:line 246
   at OpenRA.Mods.HV.Projectiles.EnergyBolt..ctor(ProjectileArgs args, EnergyBoltInfo info) in $HOME/Git Projects/OpenHV/OpenRA.Mods.HV/Projectiles/EnergyBolt.cs:line 147
   at OpenRA.Mods.HV.Projectiles.EnergyBoltInfo.Create(ProjectileArgs args) in $HOME/Git Projects/OpenHV/OpenRA.Mods.HV/Projectiles/EnergyBolt.cs:line 56
   at OpenRA.Mods.Common.Traits.Armament.<>c__DisplayClass36_0.<FireBarrel>b__2(Int32 burst) in OpenRA.Mods.Common/Traits/Armament.cs:line 346
   at OpenRA.Mods.Common.Traits.Armament.FireBarrel(Actor self, IFacing facing, Target& target, Barrel barrel) in OpenRA.Mods.Common/Traits/Armament.cs:line 342
   at OpenRA.Mods.Common.Traits.Armament.CheckFire(Actor self, IFacing facing, Target& target) in OpenRA.Mods.Common/Traits/Armament.cs:line 287
   at OpenRA.Mods.Common.Activities.Attack.DoAttack(Actor self, AttackFrontal attack, IEnumerable`1 armaments) in OpenRA.Mods.Common/Activities/Attack.cs:line 258
   at OpenRA.Mods.Common.Activities.Attack.TickAttack(Actor self, AttackFrontal attack) in OpenRA.Mods.Common/Activities/Attack.cs:line 251
   at OpenRA.Mods.Common.Activities.Attack.Tick(Actor self) in OpenRA.Mods.Common/Activities/Attack.cs:line 147
   at OpenRA.Activities.Activity.TickOuter(Actor self) in OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in OpenRA.Game/Traits/ActivityUtils.cs:line 29
   at OpenRA.Activities.Activity.TickChild(Actor self) in OpenRA.Game/Activities/Activity.cs:line 144
   at OpenRA.Mods.Common.Activities.AttackMoveActivity.Tick(Actor self) in OpenRA.Mods.Common/Activities/Move/AttackMoveActivity.cs:line 80
   at OpenRA.Activities.Activity.TickOuter(Actor self) in OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in OpenRA.Game/Traits/ActivityUtils.cs:line 29
   at OpenRA.Actor.Tick() in OpenRA.Game/Actor.cs:line 270
   at OpenRA.World.Tick() in OpenRA.Game/World.cs:line 456
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in OpenRA.Game/Game.cs:line 651
   at OpenRA.Game.LogicTick() in OpenRA.Game/Game.cs:line 666
   at OpenRA.Game.Loop() in OpenRA.Game/Game.cs:line 835
   at OpenRA.Game.Run() in OpenRA.Game/Game.cs:line 888
   at OpenRA.Game.InitializeAndRun(String[] args) in OpenRA.Game/Game.cs:line 313
   at OpenRA.Launcher.Program.Main(String[] args) in OpenRA.Launcher/Program.cs:line 32
```

**Comment by Mailaender** [comment]
Not yet fixed https://github.com/OpenHV/OpenHV/issues/1076.

**Comment by Mailaender** [comment]
```
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (mbt 1984 (not in world))
   at OpenRA.TraitDictionary.CheckDestroyed(Actor actor) in OpenRA.Game/TraitDictionary.cs:line 84
   at OpenRA.Mods.Common.Traits.SquadManagerBotModule.FindEnemies(IEnumerable`1 actors, Actor sourceActor)
   at OpenRA.Mods.Common.Traits.BotModules.Squads.Squad.IsTargetValid(Actor squadUnit) in OpenRA.Mods.Common/Traits/BotModules/Squads/Squad.cs:line 119
   at OpenRA.Mods.Common.Traits.SquadManagerBotModule.ProtectOwn(IBot bot, Actor attacker) in OpenRA.Mods.Common/Traits/BotModules/SquadManagerBotModule.cs:line 494
   at OpenRA.Mods.Common.Traits.ModularBot.<>c__DisplayClass15_0.<OpenRA.Mods.Common.Traits.INotifyDamage.Damaged>b__0() in OpenRA.Mods.Common/Traits/Player/ModularBot.cs:line 115
   at OpenRA.Sync.<>c__DisplayClass14_0.<RunUnsynced>b__0() in OpenRA.Game/Sync.cs:line 172
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) in OpenRA.Game/Sync.cs:line 203
   at OpenRA.Sync.RunUnsynced(Boolean checkSyncHash, World world, Action fn) in OpenRA.Game/Sync.cs:line 173
   at OpenRA.Mods.Common.Traits.ModularBot.OpenRA.Mods.Common.Traits.INotifyDamage.Damaged(Actor self, AttackInfo e) in OpenRA.Mods.Common/Traits/Player/ModularBot.cs:line 118
   at OpenRA.Mods.Common.Traits.Health.InflictDamage(Actor self, Actor attacker, Damage damage, Boolean ignoreModifiers) in OpenRA.Mods.Common/Traits/Health.cs:line 204
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, WarheadArgs args) in OpenRA.Mods.Common/Warheads/SpreadDamageWarhead.cs:line 123
   at OpenRA.GameRules.WeaponInfo.Impact(Target& target, WarheadArgs args) in OpenRA.Game/GameRules/WeaponInfo.cs:line 246
   at OpenRA.Mods.HV.Projectiles.EnergyBolt..ctor(ProjectileArgs args, EnergyBoltInfo info) in /home/rampoina/sources/OpenHV/OpenRA.Mods.HV/Projectiles/EnergyBolt.cs:line 147
   at OpenRA.Mods.HV.Projectiles.EnergyBoltInfo.Create(ProjectileArgs args) in /home/rampoina/sources/OpenHV/OpenRA.Mods.HV/Projectiles/EnergyBolt.cs:line 56
   at OpenRA.Mods.Common.Traits.Armament.<>c__DisplayClass36_0.<FireBarrel>b__2(Int32 burst) in OpenRA.Mods.Common/Traits/Armament.cs:line 346
   at OpenRA.Mods.Common.Traits.Armament.FireBarrel(Actor self, IFacing facing, Target& target, Barrel barrel) in OpenRA.Mods.Common/Traits/Armament.cs:line 342
   at OpenRA.Mods.Common.Traits.Armament.CheckFire(Actor self, IFacing facing, Target& target) in OpenRA.Mods.Common/Traits/Armament.cs:line 287
   at OpenRA.Mods.Common.Activities.Attack.DoAttack(Actor self, AttackFrontal attack, IEnumerable`1 armaments) in OpenRA.Mods.Common/Activities/Attack.cs:line 257
   at OpenRA.Mods.Common.Activities.Attack.TickAttack(Actor self, AttackFrontal attack) in OpenRA.Mods.Common/Activities/Attack.cs:line 250
   at OpenRA.Mods.Common.Activities.Attack.Tick(Actor self) in OpenRA.Mods.Common/Activities/Attack.cs:line 147
   at OpenRA.Activities.Activity.TickOuter(Actor self) in OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in OpenRA.Game/Traits/ActivityUtils.cs:line 29
   at OpenRA.Actor.Tick() in OpenRA.Game/Actor.cs:line 270
   at OpenRA.World.Tick() in OpenRA.Game/World.cs:line 456
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in OpenRA.Game/Game.cs:line 651
   at OpenRA.Game.LogicTick() in OpenRA.Game/Game.cs:line 666
   at OpenRA.Game.Loop() in OpenRA.Game/Game.cs:line 835
   at OpenRA.Game.Run() in OpenRA.Game/Game.cs:line 888
   at OpenRA.Game.InitializeAndRun(String[] args) in OpenRA.Game/Game.cs:line 313
   at OpenRA.Launcher.Program.Main(String[] args) in OpenRA.Launcher/Program.cs:line 32
```
```

**Comment by Mailaender** [comment]
Still crashes on 48a5b5b9bcbe770be08fc42b5d389d962d93e0f4.

**Comment by PunkPun** [comment]
Likelly regression from #22036
