### ISSUE TITLE
Game crash due to pathfinding bug in Cameo mod

### ISSUE THREAD

**Issue by AedisToru** [OpenRA/OpenRA#21459]
System: Win 11 64bit
Mod: https://github.com/Zeruel87/Cameo-mod on [commit](https://github.com/Zeruel87/Cameo-mod/commit/d510b65bd4f1eede6b285d6f506b43e6577603cf)
Log:

```
Platform is Windows (X64)
Engine version is db67e6d
Runtime: .NET CLR 6.0.31
Using SDL 2 with OpenGL (ANGLE) renderer
Desktop resolution: 2560x1440
No custom resolution provided, using desktop resolution
Using resolution: 2560x1440
Using window scale 1,00
OpenGL renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 4060 Direct3D11 vs_5_0 ps_5_0, D3D11-31.0.15.5244)
OpenGL version: OpenGL ES 3.0.0 (ANGLE 2.1.20989 git hash: 5c0b4251bd2c)
Using default sound device
Exception of type `System.Exception`: The abstract path should never be searched for an unreachable point. Abstract cell 28,36 failed to route to abstract cell.
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.<>c__DisplayClass41_0.<Heuristic>b__0(CPos cell, Boolean knownAccessible) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Mods.Common\Pathfinder\HierarchicalPathFinder.cs:line 1209
   at OpenRA.Mods.Common.Pathfinder.PathSearch.AddInitialCell(CPos location, Func`2 customCost) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 216
   at OpenRA.Mods.Common.Pathfinder.PathSearch.AddInitialCells(World world, Locomotor locomotor, Actor self, IEnumerable`1 froms, BlockedByActor check, Func`2 customCost, Actor ignoreActor, Boolean inReverse, PathSearch search) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 109
   at OpenRA.Mods.Common.Pathfinder.PathSearch.ToTargetCell(World world, Locomotor locomotor, Actor self, IEnumerable`1 froms, CPos target, BlockedByActor check, Int32 heuristicWeightPercentage, Func`2 customCost, Actor ignoreActor, Boolean laneBias, Boolean inReverse, Func`3 heuristic, Nullable`1 grid, IRecorder recorder) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 76
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.FindPath(Actor self, IReadOnlyCollection`1 sources, CPos target, BlockedByActor check, Int32 heuristicWeightPercentage, Func`2 customCost, Actor ignoreActor, Boolean laneBias, PathFinderOverlay pathFinderOverlay) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Mods.Common\Pathfinder\HierarchicalPathFinder.cs:line 816
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.FindPath(Actor self, CPos source, CPos target, BlockedByActor check, Int32 heuristicWeightPercentage, Func`2 customCost, Actor ignoreActor, Boolean laneBias, PathFinderOverlay pathFinderOverlay) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Mods.Common\Pathfinder\HierarchicalPathFinder.cs:line 949
   at OpenRA.Mods.Common.Traits.PathFinder.FindPathToTarget(Actor self, List`1 sources, CPos target, BlockedByActor check, Func`2 customCost, Actor ignoreActor, Boolean laneBias) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Mods.Common\Traits\World\PathFinder.cs:line 176
   at OpenRA.Mods.Common.Traits.PathFinder.FindPathToTargetCell(Actor self, IEnumerable`1 sources, CPos target, BlockedByActor check, Func`2 customCost, Actor ignoreActor, Boolean laneBias) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Mods.Common\Traits\World\PathFinder.cs:line 97
   at OpenRA.Mods.Common.Activities.Move.<>c__DisplayClass19_0.<.ctor>b__0(BlockedByActor check) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Mods.Common\Activities\Move\Move.cs:line 83
   at OpenRA.Mods.Common.Activities.Move.EvalPath(BlockedByActor check) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Mods.Common\Activities\Move\Move.cs:line 115
   at OpenRA.Mods.Common.Activities.Move.OnFirstRun(Actor self) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Mods.Common\Activities\Move\Move.cs:line 130
   at OpenRA.Activities.Activity.TickOuter(Actor self) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 29
   at OpenRA.Activities.Activity.TickChild(Actor self) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Game\Activities\Activity.cs:line 147
   at OpenRA.Activities.Activity.TickOuter(Actor self) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 29
   at OpenRA.Activities.Activity.TickChild(Actor self) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Game\Activities\Activity.cs:line 147
   at OpenRA.Activities.Activity.TickOuter(Actor self) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 29
   at OpenRA.Actor.Tick() in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Game\Actor.cs:line 270
   at OpenRA.World.Tick() in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Game\World.cs:line 456
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Game\Game.cs:line 651
   at OpenRA.Game.LogicTick() in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Game\Game.cs:line 666
   at OpenRA.Game.Loop() in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Game\Game.cs:line 835
   at OpenRA.Game.Run() in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Game\Game.cs:line 888
   at OpenRA.Game.InitializeAndRun(String[] args) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Game\Game.cs:line 313
   at OpenRA.Launcher.Program.Main(String[] args) in C:\Users\manue\Documents\GitHub\Cameo-mod\engine\OpenRA.Launcher\Program.cs:line 32
```

## Replay
[cameo-2024-06-21T111015Z.zip](https://github.com/user-attachments/files/15927936/cameo-2024-06-21T111015Z.zip)

**Comment by RoosterDragon** [comment]
I notice this mod is using a customised engine that has made changes in `Locomotor` and `HierarchicalPathFinder`.
https://github.com/tjk-ws/OpenRA/commit/a8e6690e562582a4b0eb1d0d6612fe6e9850260f
https://github.com/tjk-ws/OpenRA/commit/cde14257ab463ab8e10f2974d8dae3c0ca9ca14c

`HierarchicalPathFinder` is extremely sensitive to bugs where it and the outside world disagree on which cells are reachable. When HPF doesn't agree with the reality this error is often triggered.

`Locomotor.IsBlockedBy` is the "raw" function that determines if an actor can enter a cell. `Locomotor.UpdateCellBlocking` updates a cache within locomotor which can be used for fast checks.
`Locomotor.CanMoveFreelyInto` calls into the cache for an answer to blocking rules when possible, and falls back to `Locomotor.IsBlockedBy` for anything the cache can't answer.

`HierarchicalPathFinder.ActorIsBlocking` and `HierarchicalPathFinder.ActorCellIsBlocking` then replicate these blocking rules for a subset of Immovable actors.

All of these functions must agree on their definition of what actors are considered blocking. Inconsistencies will result in the state in HPF becoming out of sync with the rest of the game. When you try and find a path and HPF realizes it has an out of sync viewpoint of affairs, it crashes because it's got little other choice. The unit is trying to move along accessible cells on the map, but the HPF doesn't think those cells are accessible.

Anyway, I can see that I can see `Locomotor.UpdateCellBlocking` has been updated to account for this change, however `Locomotor.IsBlockedBy` has not been updated. This means Locomotor will return inconsistent results depending on when it is able to consult the cache or when is has to work out the result from scratch. If Locomotor can't even keep a consistent view internally, there's no way HPF can be aligned either - there isn't a consistent viewpoint for it to align with! Eventually this inconsistency will manifest as a crash.

The custom engine needs to fix this bug by ensuring all these methods are made consistent, that will resolve the crash. However this can be difficult to achieve. By the time HPF crashes to alert you it thinks a cell in unreachable that is nonetheless actually reachable, it's far too late. The bogus logic may have been executed many ticks ago in a far flung part of the codebase, e.g. locomotor deciding whether a cell was reachable or not and then caching an incorrect result which wasn't used for some time. An alternative approach I would suggest is to revert any customisations made to Locomotor/HPF. Whilst you'll lose that functionality, you'll also save yourself from terrible amount of pain debugging crashes in the pathfinder.

**Comment by Mailaender** [comment]
Closing here.
