### ISSUE TITLE
My game crashed

### ISSUE THREAD

**Issue by sebastianpetri** [OpenRA/OpenRA#21562]
## System Information

- Operating System:  WINDOWS
- OpenRA Version: release-20231010
- OpenRA Mod: None
- Source: Official download package 
- For self-compiled or third-party packages: Mono version

## Exception log
Exception of type `System.NotImplementedException`: No rules definition for unit sniper
   at OpenRA.Actor..ctor(World world, String name, TypeDictionary initDict)
   at OpenRA.Mods.Common.Traits.SpawnMapActors.WorldLoaded(World world, WorldRenderer wr)
   at OpenRA.World.LoadComplete(WorldRenderer wr)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.ReceiveImmediateOrders(Int32 clientId, OrderPacket orders)
   at OpenRA.Network.NetworkConnection.OpenRA.Network.IConnection.Receive(OrderManager orderManager)
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0()
   at OpenRA.Sync.RunUnsynced(World world, Action fn)
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)

```
OpenRA engine version release-20231010
OpenRA Language: en
Red Alert mod version release-20231010
on map ad21fb775e8cb65ba14b219621bcad71ec04cdfd (Kampf durch den Freind by Joker).
Date: 2024-08-27 19:11:21Z
Operating System: Windows (X64, Microsoft Windows NT 10.0.19045.0)
Runtime Version: .NET CLR 6.0.22
Installed Language: de (Installed) de (Current) de (Current UI)
Exception of type `System.NotImplementedException`: No rules definition for unit sniper
   at OpenRA.Actor..ctor(World world, String name, TypeDictionary initDict)
   at OpenRA.Mods.Common.Traits.SpawnMapActors.WorldLoaded(World world, WorldRenderer wr)
   at OpenRA.World.LoadComplete(WorldRenderer wr)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.ReceiveImmediateOrders(Int32 clientId, OrderPacket orders)
   at OpenRA.Network.NetworkConnection.OpenRA.Network.IConnection.Receive(OrderManager orderManager)
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0()
   at OpenRA.Sync.RunUnsynced(World world, Action fn)
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)
```

## Replay
Loding Map Issue
[all_in3.zip](https://github.com/user-attachments/files/16767907/all_in3.zip)

## Additional information
I have just updated from release-20210321 to release-20231010. Now I can no longer load my maps with the Sniper unit. Neither as skirmish nor in the editor.

**Comment by PunkPun** [comment]
You need to remove the sniper unit from the map manually or add definitions and sniper to your maps. #20509

**Comment by sebastianpetri** [comment]
Thanks, the solution is simple for my case.
Thought more of stabilizing the application by ignoring a missing unit and not stopping the application with an error message
