### ISSUE TITLE
Unable to add add content for Red Alert using a First Decade disk. File not found "main.mix".

### ISSUE THREAD

**Issue by Ktufuathama** [OpenRA/OpenRA#21591]
## Issue Summary
When trying to add the content from my "C&C The First Decade (English)" disk, it is failing with a file not found exception. This is for all three options (Base music, Soviet and Allies movies). I can install the game from the disk so I believe it is not an issue with the disk. Error type is FileNotFoundException. Path is OpenRA\Content\ra\v2\main.mix.

## Reproduction
Issue occurs every attempt. This includes after computer restarts, appdata directory clean, and clean install of OpenRA. 

## Expected behavior
Music and movie content will be added from the disk to OpenRA.

### Error message from .\install.log ->
Using installer `tfd: C&C The First Decade (English)` of type `Disc`:
System.IO.FileNotFoundException: Could not find file 'C:\Users\User\AppData\Roaming\OpenRA\Content\ra\v2\main.mix'.
File name: 'C:\Users\User\AppData\Roaming\OpenRA\Content\ra\v2\main.mix'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at OpenRA.Mods.Cnc.Installer.ExtractMixSourceAction.RunActionOnSource(MiniYaml actionYaml, String path, ModData modData, List`1 extracted, Action`1 updateMessage)
   at OpenRA.Mods.Common.Widgets.Logic.InstallFromSourceLogic.<>c__DisplayClass44_0.<InstallFromSource>g__RunSourceActions|2(MiniYamlNode contentPackageYaml, <>c__DisplayClass44_1& )
   at OpenRA.Mods.Common.Widgets.Logic.InstallFromSourceLogic.<>c__DisplayClass44_0.<InstallFromSource>b__1()

### Example of directory after trying to add content which shows the file missing. ->
Directory of C:\Users\User\AppData\Roaming\OpenRA\Content\ra\v2
d----- cnc
d----- expand
-a----  311.7K  allies.mix
-a----   2.09M  conquer.mix
-a----   5.55M  hires.mix
-a---- 243.64K  interior.mix
-a----   3.65M  local.mix
-a---- 737.11K  lores.mix
-a---- 268.29K  russian.mix
-a----1011.44K  snow.mix
-a----   1.32M  sounds.mix
-a----   1.91M  speech.mix
-a----1019.21K  temperat.mix

### Snip of contents of CD, incase that would be useful.
![CNCTFD_contents](https://github.com/user-attachments/assets/d8832b04-41d4-44bb-9e9c-0659c8fc7ceb)

**Comment by pchote** [comment]
This has been fixed by #21520.
