### ISSUE TITLE
MasterServerPinger pings in Skirmish games

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#21597]
bleed,

`MasterServerPinger` takes up 10% of CPU during Skirmisch game where POST to master servers keep failing.

This because `isinitialPing` is always true.

Most time is spend in the yaml serialization under `gs.toPostData()`.

https://github.com/OpenRA/OpenRA/blob/b4882a8b03d8dbe99469b278f3633d9678231506/OpenRA.Mods.Common/ServerTraits/MasterServerPinger.cs#L93

server.log:
```
[2024-09-28T18:57:59] Initial mod: ra
[2024-09-28T18:57:59] Initial map: 9600f96879f53ddc27514bf05a8dcc7dce1ee1ba
[2024-09-28T18:58:00] Client 0: Accepted connection from 127.0.0.1:54710.
[2024-09-28T18:58:00] acll (127.0.0.1:54710) has joined the game.
[2024-09-28T18:58:00] Player @127.0.0.1:54710 is NotReady
[2024-09-28T18:58:19] Failed to set socket option on 127.0.0.1:0: Protocol not available
```

Possible solution: set `isInitialPing` to false on fatal error. And/or cache post data.

Occurs in Lobby and during game play.

**Comment by pchote** [comment]
Skirmish games shouldn't be pinging the master server at all?!

**Comment by anvilvapre** [comment]
In my case the cause was that outcoming http(s) traffic was blocked by default.

**Comment by anvilvapre** [comment]
Additionally `journalctl` also lists many of below entries. These entries are there even without starting a server or skirmisch game - possible caused by the shell map starting a server?

```
OpenRA[9595]: System.Net.Sockets.SocketException (13): Permission denied
                                     at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
                                     at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
                                     at System.Net.Sockets.UdpClient.Send(Byte[] dgram, Int32 bytes, IPEndPoint endPoint)
                                     at BeaconLib.Probe.BroadcastProbe()
                                     at BeaconLib.Probe.BackgroundLoop()
```
