### ISSUE TITLE
UPnP feature does not work with Mikrotik routers on Linux

### ISSUE THREAD

**Issue by MasterMind2k** [OpenRA/OpenRA#21610]
## Issue Summary
Creating multiplayer game with Mikrotik router fails with exception in logs

DESCRIPTION
Creating a multiplayer game with UPnP enabled on Mikrotik router fails. OpenRA UPnP status defines active.

Error reported in nat.log:
```
Device found: 192.168.1.1:2828
Type: Upnp
   at Mono.Nat.Upnp.ResponseMessage.Decode(UpnpNatDevice device, String message)
   at Mono.Nat.Upnp.UpnpNatDevice.DecodeMessageFromResponse(Stream s, Int32 length)
   at Mono.Nat.Upnp.UpnpNatDevice.SendMessageAsync(RequestMessage message)
   at Mono.Nat.Upnp.UpnpNatDevice.CreatePortMapAsync(Mapping mapping)
   at Mono.Nat.NatDeviceExtensions.CreatePortMap(INatDevice device, Mapping mapping)
   at OpenRA.Network.Nat.TryForwardPort(Int32 listen, Int32 external) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Network/Nat.cs:line 70
   at Mono.Nat.Upnp.ResponseMessage.Decode(UpnpNatDevice device, String message)
   at Mono.Nat.Upnp.UpnpNatDevice.DecodeMessageFromResponse(Stream s, Int32 length)
   at Mono.Nat.Upnp.UpnpNatDevice.SendMessageAsync(RequestMessage message)
   at Mono.Nat.Upnp.UpnpNatDevice.DeletePortMapAsync(Mapping mapping)
   at Mono.Nat.NatDeviceExtensions.DeletePortMap(INatDevice device, Mapping mapping)
   at OpenRA.Network.Nat.TryRemovePortForward() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Network/Nat.cs:line 89
```

Forward rule is removed after closing the game.

## Reproduction
STEPS TO REPRODUCE THE ISSUE
1. Start an advertised multiplayer game

## Expected behavior

EXPECTED BEHAVIOR

Game should be accessible from master server.

## Work-around

With looking at console output, I found out the problem is with unallowed temporary mappings. By configuring `Server.NatPortMappingLifetime` to 0, problem is resolved.

**Comment by MasterMind2k** [comment]
Diging a little bit deeper (locally compiled the game and executed in terminal) I got an error on stdout: `Port forwarding failed: Error 725: OnlyPermanentLeasesSupported`

**Comment by RoosterDragon** [comment]
Perhaps we can detect when the router responds with a `OnlyPermanentLeasesSupported` error code and write out a prescriptive log message, e.g.: "Router responsed with OnlyPermanentLeasesSupported. You must set Server.NatPortMappingLifetime to 0 to use NAT port mapping with this router."

**Comment by pchote** [comment]
IMO it would be better to either do that automatically or to report UPnP as not available.

**Comment by MasterMind2k** [comment]
For end-user, the best would be to automatically disable expiry setting. But without letting the user know, user may end up with rules being filled up.

On the other hand, if we report UPnP as unavailable, user may end up troubleshoot-ing in completely wrong direction.

Exposing the lifetime setting, it would bring more clutter to configuration.

I think the best way could be to, in case of `OnlyPermanentLeasesSupported` error code, to retry with 0 expiry and log a warning "Port mapping may not be removed in case of unclean shutdown", or something similar. Maybe also print it into game lobby message (with a description on how to disable the warning)?

**Comment by sgmustafi** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
