### ISSUE TITLE
My game crashed while playing ts

### ISSUE THREAD

**Issue by aceArt-GmbH** [OpenRA/OpenRA#21641]
## System Information

- Operating System:  Linux (X64) but also macOS and windows
- OpenRA Version: git-2c68964566
- OpenRA Mod: tiberian sun
- Source: self-compiled
- For self-compiled or third-party packages: Mono version

## Exception log

```
Platform is Linux (X64)
Engine version is git-2c68964566
Runtime: .NET CLR 6.0.33
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 2560x1440
No custom resolution provided, using desktop resolution
Using resolution: 2560x1440
Using window scale 1.00
OpenGL renderer: AMD Radeon Graphics (radeonsi, renoir, LLVM 18.1.8, DRM 3.54, 6.6.54-2-MANJARO)
OpenGL version: 4.6 (Core Profile) Mesa 24.2.4-arch1.0.1
Using default sound device
Internal mods:
	all (git-2c68964566)
	cnc-content (git-2c68964566)
	ra (git-2c68964566)
	ra-content (git-2c68964566)
	cnc (git-2c68964566)
	d2k-content (git-2c68964566)
	ts (git-2c68964566)
	d2k (git-2c68964566)
	ts-content (git-2c68964566)
External mods:
	ra-release-20230225 (release-20230225)
	ra-release-20231010 (release-20231010)
	ra-release-20210321 (release-20210321)
	d2k-release-20200503 (release-20200503)
	ts-git-2c68964 (git-2c68964)
	ts-git-2c68964566 (git-2c68964566)
Loading mod: ts
Exception of type `System.DivideByZeroException`: Attempted to divide by zero.
   at OpenRA.Mods.Common.Traits.BodyOrientationInfo.QuantizeFacing(WAngle facing, Int32 facings) in /home/tux/Downloads/OpenRA/OpenRA.Mods.Common/Traits/BodyOrientation.cs:line 55
   at OpenRA.Mods.Common.Traits.BodyOrientation.QuantizeFacing(WAngle facing) in /home/tux/Downloads/OpenRA/OpenRA.Mods.Common/Traits/BodyOrientation.cs:line 111
   at OpenRA.Mods.Common.Traits.Render.WithIdleOverlay.<>c__DisplayClass1_1.<.ctor>b__6() in /home/tux/Downloads/OpenRA/OpenRA.Mods.Common/Traits/Render/WithIdleOverlay.cs:line 99
   at OpenRA.Graphics.Animation.Render(WPos pos, WVec& offset, Int32 zOffset, PaletteReference palette) in /home/tux/Downloads/OpenRA/OpenRA.Game/Graphics/Animation.cs:line 75
   at OpenRA.Graphics.AnimationWithOffset.Render(Actor self, PaletteReference pal) in /home/tux/Downloads/OpenRA/OpenRA.Game/Graphics/AnimationWithOffset.cs:line 44
   at OpenRA.Mods.Common.Traits.Render.RenderSprites.Render(Actor self, WorldRenderer wr)+MoveNext() in /home/tux/Downloads/OpenRA/OpenRA.Mods.Common/Traits/Render/RenderSprites.cs:line 192
   at OpenRA.Actor.Renderables(WorldRenderer wr)+MoveNext() in /home/tux/Downloads/OpenRA/OpenRA.Game/Actor.cs:line 307
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at OpenRA.Mods.Common.Traits.Render.WithShadow.OpenRA.Traits.IRenderModifier.ModifyRender(Actor self, WorldRenderer wr, IEnumerable`1 r) in /home/tux/Downloads/OpenRA/OpenRA.Mods.Common/Traits/Render/WithShadow.cs:line 54
   at OpenRA.Actor.Render(WorldRenderer wr) in /home/tux/Downloads/OpenRA/OpenRA.Game/Actor.cs:line 293
   at OpenRA.Graphics.WorldRenderer.GenerateRenderables() in /home/tux/Downloads/OpenRA/OpenRA.Game/Graphics/WorldRenderer.cs:line 141
   at OpenRA.Graphics.WorldRenderer.PrepareRenderables() in /home/tux/Downloads/OpenRA/OpenRA.Game/Graphics/WorldRenderer.cs:line 264
   at OpenRA.Game.RenderTick() in /home/tux/Downloads/OpenRA/OpenRA.Game/Game.cs:line 748
   at OpenRA.Game.Loop() in /home/tux/Downloads/OpenRA/OpenRA.Game/Game.cs:line 856
   at OpenRA.Game.Run() in /home/tux/Downloads/OpenRA/OpenRA.Game/Game.cs:line 888
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/tux/Downloads/OpenRA/OpenRA.Game/Game.cs:line 313
   at OpenRA.Launcher.Program.Main(String[] args) in /home/tux/Downloads/OpenRA/OpenRA.Launcher/Program.cs:line 46

```

## Replay

[git-2c68964566.zip](https://github.com/user-attachments/files/17664333/git-2c68964566.zip)

## Additional information

All players received the same crash, but at different times.
It was some 8 player map.

**Comment by jeremiahlangner** [comment]
You can prevent the crash by adding the following at line 104 of OpenRA.Mods.Common/Util.cs. You may witness some render bugs.

```CSharp
if (facings == 0)
    return new WAngle(IndexFacing(facing, 1) * (1024 / 1));
```

**Comment by PunkPun** [comment]
Closes as duplicated of #21668
