### ISSUE TITLE
Server.ReceiveOrders Connection NullReferenceException

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#21654]
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenRA.Server.Server.ReceiveOrders(Connection conn, Int32 frame, Byte[] data) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Server/Server.cs:line 910
   at OpenRA.Server.Server.ConnectionPacketEvent.OpenRA.Server.Server.IServerEvent.Invoke(Server server) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Server/Server.cs:line 1507
   at OpenRA.Server.Server.<.ctor>b_58_2(Object ) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Server/Server.cs:line 361
   at System.Threading.Thread.StartCallback()
```

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenRA.Server.Server.ReceiveOrders(Connection conn, Int32 frame, Byte[] data) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Server/Server.cs:line 921
   at OpenRA.Server.Server.<.ctor>b_58_2(Object ) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Server/Server.cs:line 361
```

**Comment by anvilvapre** [comment]
Bit odd that we see this only now after years.

**Comment by Mailaender** [comment]
I guess most people just restart their servers and don't care. This also doesn't happen frequently.

**Comment by Mailaender** [comment]
I am closing this as not reproducible as I collected these from dedicated servers with a very long uptime.
