### ISSUE TITLE
Exception of type `System.InvalidOperationException`: TypeDictionary contains multiple instances of type `OpenRA.Mods.Common.Traits.ProductionInfo`

### ISSUE THREAD

**Issue by sreschke80** [OpenRA/OpenRA#21663]
## System Information
- Operating System:  Linux (X64, Unix 6.8.0.48)
- OpenRA Version: playtest-20241116
- OpenRA Mod: d2k mod version playtest-20241116
- Source: https://github.com/OpenRA/OpenRA/releases/download/playtest-20241116/OpenRA-Dune-2000-playtest-x86_64.AppImage
- For self-compiled or third-party packages: Mono version

## Exception log

```
OpenRA engine version playtest-20241116
d2k mod version playtest-20241116
on map bdcff34983b28f36e047f234d4e7acc923159187 (Venac ditch by CombineCnR).
Date: 2024-12-02 19:22:22Z
Operating System: Linux (X64, Unix 6.8.0.48)
Runtime Version: .NET CLR 6.0.36
Installed Language: en (Installed) en (Current) en (Current UI)
Exception of type `System.InvalidOperationException`: TypeDictionary contains multiple instances of type `OpenRA.Mods.Common.Traits.ProductionInfo`
   at OpenRA.Primitives.TypeDictionary.Get[T](Boolean throwsIfMissing) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Primitives/TypeDictionary.cs:line 67
   at OpenRA.Mods.Common.Traits.BaseBuilderBotModule.LocomotorsForProducibles(Actor producer)
   at OpenRA.Mods.Common.Traits.BaseBuilderBotModule.ChooseRallyLocationNear(Actor producer) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs:line 341
   at OpenRA.Mods.Common.Traits.BaseBuilderBotModule.SetRallyPoint(IBot bot, TraitPair`1 rp) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs:line 310
   at OpenRA.Mods.Common.Traits.BaseBuilderBotModule.OpenRA.Mods.Common.Traits.IBotTick.BotTick(IBot bot) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs:line 244
   at OpenRA.Mods.Common.Traits.ModularBot.<OpenRA.Traits.ITick.Tick>b__14_0() in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/Player/ModularBot.cs:line 97
   at OpenRA.Sync.<>c__DisplayClass14_0.<RunUnsynced>b__0() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Sync.cs:line 172
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Sync.cs:line 203
   at OpenRA.Sync.RunUnsynced(Boolean checkSyncHash, World world, Action fn) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Sync.cs:line 173
   at OpenRA.Mods.Common.Traits.ModularBot.OpenRA.Traits.ITick.Tick(Actor self) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/Player/ModularBot.cs:line 93
   at OpenRA.TraitDictionary.TraitContainer`1.ApplyToAllTimed(Action`2 action, String text) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/TraitDictionary.cs:line 312
   at OpenRA.World.Tick() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/World.cs:line 458
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 651
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 666
   at OpenRA.Game.Loop() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 835
   at OpenRA.Game.Run() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 888
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 313
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenRA/OpenRA/OpenRA.Launcher/Program.cs:line 46
```

**Comment by sreschke80** [comment]
The crash occurs another time, when I moved the mouse of the tank in the production menu.

**Comment by PunkPun** [comment]
This crash looks like an error with the map. It seems multiple production traints on an actor are not allowed.

I can't find the map itself on resource centre, are you running a local version?

**Comment by sreschke80** [comment]
> This crash looks like an error with the map. It seems multiple production traints on an actor are not allowed.
> 
> I can't find the map itself on resource centre, are you running a local version?

The map is named `Vanec ditch` and it is one of the default maps for a Skirmish Game.
