### ISSUE TITLE
TS - EMPing Voxel Vehicles crash the game due to division by 0.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#21668]
Regression from #21412 , which i seem to have had fixed in RV by setting `QuantizedFacings` to 1024, but i had to reinvestiage this because that revealed its own problems (QuantizedFacings not being 0 break ramp tilting for the voxels). I tested the problem with bleed TS as well, and was able to produce both issues there, so i guess the crash needs to be fixed properly in the C# code.

```OpenRA engine version {DEV_VERSION}
ts mod version {DEV_VERSION}
on map 1db71585838de78fba3963674177ff2746827766 (Hot Springs by Westwood Studios).
Date: 2024-12-08 11:45:47Z
Operating System: Windows (X64, Microsoft Windows NT 10.0.22631.0)
Runtime Version: .NET CLR 6.0.21
Installed Language: tr (Installed) tr (Current) tr (Current UI)
Exception of type `System.DivideByZeroException`: Attempted to divide by zero.
   at OpenRA.Mods.Common.Traits.BodyOrientationInfo.QuantizeFacing(WAngle facing, Int32 facings) in C:\OpenRA\Basegame\OpenRA-bleed\OpenRA.Mods.Common\Traits\BodyOrientation.cs:line 55
   at OpenRA.Mods.Common.Traits.BodyOrientation.QuantizeFacing(WAngle facing) in C:\OpenRA\Basegame\OpenRA-bleed\OpenRA.Mods.Common\Traits\BodyOrientation.cs:line 111
   at OpenRA.Mods.Common.Traits.Render.WithIdleOverlay.<>c__DisplayClass1_1.<.ctor>b__6() in C:\OpenRA\Basegame\OpenRA-bleed\OpenRA.Mods.Common\Traits\Render\WithIdleOverlay.cs:line 99
   at OpenRA.Graphics.Animation.Render(WPos pos, WVec& offset, Int32 zOffset, PaletteReference palette) in C:\OpenRA\Basegame\OpenRA-bleed\OpenRA.Game\Graphics\Animation.cs:line 79
   at OpenRA.Graphics.AnimationWithOffset.Render(Actor self, PaletteReference pal) in C:\OpenRA\Basegame\OpenRA-bleed\OpenRA.Game\Graphics\AnimationWithOffset.cs:line 44
   at OpenRA.Mods.Common.Traits.Render.RenderSprites.Render(Actor self, WorldRenderer wr)+MoveNext() in C:\OpenRA\Basegame\OpenRA-bleed\OpenRA.Mods.Common\Traits\Render\RenderSprites.cs:line 192
   at OpenRA.Actor.Renderables(WorldRenderer wr)+MoveNext() in C:\OpenRA\Basegame\OpenRA-bleed\OpenRA.Game\Actor.cs:line 307
   at OpenRA.Mods.Common.Traits.WithColoredOverlay.ModifiedRender(IEnumerable`1 r)+MoveNext() in C:\OpenRA\Basegame\OpenRA-bleed\OpenRA.Mods.Common\Traits\Modifiers\WithColoredOverlay.cs:line 50
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at OpenRA.Graphics.WorldRenderer.GenerateRenderables() in C:\OpenRA\Basegame\OpenRA-bleed\OpenRA.Game\Graphics\WorldRenderer.cs:line 141
   at OpenRA.Graphics.WorldRenderer.PrepareRenderables() in C:\OpenRA\Basegame\OpenRA-bleed\OpenRA.Game\Graphics\WorldRenderer.cs:line 263
   at OpenRA.Game.RenderTick() in C:\OpenRA\Basegame\OpenRA-bleed\OpenRA.Game\Game.cs:line 748
   at OpenRA.Game.Loop() in C:\OpenRA\Basegame\OpenRA-bleed\OpenRA.Game\Game.cs:line 856
   at OpenRA.Game.Run() in C:\OpenRA\Basegame\OpenRA-bleed\OpenRA.Game\Game.cs:line 888
   at OpenRA.Game.InitializeAndRun(String[] args) in C:\OpenRA\Basegame\OpenRA-bleed\OpenRA.Game\Game.cs:line 313
   at OpenRA.Launcher.Program.Main(String[] args) in C:\OpenRA\Basegame\OpenRA-bleed\OpenRA.Launcher\Program.cs:line 46
```

**Comment by MSCMDD** [comment]
Maybe you can test this https://github.com/OpenRA/OpenRA/pull/21666

**Comment by HakunaMatata47** [comment]
Same here  with TS  on playtest 2024-12-28:

Exception of type `System.DivideByZeroException`: Attempted to divide by zero.
   at OpenRA.Mods.Common.Traits.BodyOrientationInfo.QuantizeFacing(WAngle facing, Int32 facings) in /home/user/OpenRA/OpenRA-241228/OpenRA.Mods.Common/Traits/BodyOrientation.cs:line 55
   at OpenRA.Mods.Common.Traits.BodyOrientation.QuantizeFacing(WAngle facing) in /home/user/OpenRA/OpenRA-241228/OpenRA.Mods.Common/Traits/BodyOrientation.cs:line 111
   at OpenRA.Mods.Common.Traits.Render.WithIdleOverlay.<>c__DisplayClass1_1.<.ctor>b__6() in /home/user/OpenRA/OpenRA-241228/OpenRA.Mods.Common/Traits/Render/WithIdleOverlay.cs:line 99
   at OpenRA.Graphics.Animation.Render(WPos pos, WVec& offset, Int32 zOffset, PaletteReference palette) in /home/user/OpenRA/OpenRA-241228/OpenRA.Game/Graphics/Animation.cs:line 79
   at OpenRA.Graphics.AnimationWithOffset.Render(Actor self, PaletteReference pal) in /home/user/OpenRA/OpenRA-241228/OpenRA.Game/Graphics/AnimationWithOffset.cs:line 44
   at OpenRA.Mods.Common.Traits.Render.RenderSprites.Render(Actor self, WorldRenderer wr)+MoveNext() in /home/user/OpenRA/OpenRA-241228/OpenRA.Mods.Common/Traits/Render/RenderSprites.cs:line 192
   at OpenRA.Actor.Renderables(WorldRenderer wr)+MoveNext() in /home/user/OpenRA/OpenRA-241228/OpenRA.Game/Actor.cs:line 307
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at OpenRA.Mods.Common.Traits.Render.WithShadow.OpenRA.Traits.IRenderModifier.ModifyRender(Actor self, WorldRenderer wr, IEnumerable`1 r) in /home/user/OpenRA/OpenRA-241228/OpenRA.Mods.Common/Traits/Render/WithShadow.cs:line 63
   at OpenRA.Actor.Render(WorldRenderer wr) in /home/user/OpenRA/OpenRA-241228/OpenRA.Game/Actor.cs:line 293
   at OpenRA.Graphics.WorldRenderer.GenerateRenderables() in /home/user/OpenRA/OpenRA-241228/OpenRA.Game/Graphics/WorldRenderer.cs:line 141
   at OpenRA.Graphics.WorldRenderer.PrepareRenderables() in /home/user/OpenRA/OpenRA-241228/OpenRA.Game/Graphics/WorldRenderer.cs:line 264
   at OpenRA.Game.RenderTick() in /home/user/OpenRA/OpenRA-241228/OpenRA.Game/Game.cs:line 748
   at OpenRA.Game.Loop() in /home/user/OpenRA/OpenRA-241228/OpenRA.Game/Game.cs:line 856
   at OpenRA.Game.Run() in /home/user/OpenRA/OpenRA-241228/OpenRA.Game/Game.cs:line 888
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/user/OpenRA/OpenRA-241228/OpenRA.Game/Game.cs:line 313
   at OpenRA.Launcher.Program.Main(String[] args) in /home/user/OpenRA/OpenRA-241228/OpenRA.Launcher/Program.cs:line 46

**Comment by HerroBert** [comment]
Got this too with release-20250303

Exception of type `System.DivideByZeroException`: Attempted to divide by zero.
   at OpenRA.Mods.Common.Traits.BodyOrientationInfo.QuantizeFacing(WAngle facing, Int32 facings) in /usr/src/OpenRA/OpenRA.Mods.Common/Traits/BodyOrientation.cs:line 55
   at OpenRA.Mods.Common.Traits.BodyOrientation.QuantizeFacing(WAngle facing) in /usr/src/OpenRA/OpenRA.Mods.Common/Traits/BodyOrientation.cs:line 111
   at OpenRA.Mods.Common.Traits.Render.WithIdleOverlay.<>c__DisplayClass1_1.<.ctor>b__6() in /usr/src/OpenRA/OpenRA.Mods.Common/Traits/Render/WithIdleOverlay.cs:line 99
   at OpenRA.Graphics.Animation.Render(WPos pos, WVec& offset, Int32 zOffset, PaletteReference palette) in /usr/src/OpenRA/OpenRA.Game/Graphics/Animation.cs:line 60
   at OpenRA.Graphics.AnimationWithOffset.Render(Actor self, PaletteReference pal) in /usr/src/OpenRA/OpenRA.Game/Graphics/AnimationWithOffset.cs:line 44
   at OpenRA.Mods.Common.Traits.Render.RenderSprites.Render(Actor self, WorldRenderer wr)+MoveNext() in /usr/src/OpenRA/OpenRA.Mods.Common/Traits/Render/RenderSprites.cs:line 186
   at OpenRA.Actor.Renderables(WorldRenderer wr)+MoveNext() in /usr/src/OpenRA/OpenRA.Game/Actor.cs:line 307
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at OpenRA.Mods.Common.Traits.Render.WithShadow.OpenRA.Traits.IRenderModifier.ModifyRender(Actor self, WorldRenderer wr, IEnumerable`1 r) in /usr/src/OpenRA/OpenRA.Mods.Common/Traits/Render/WithShadow.cs:line 54
   at OpenRA.Graphics.WorldRenderer.GenerateRenderables() in /usr/src/OpenRA/OpenRA.Game/Graphics/WorldRenderer.cs:line 141
   at OpenRA.Game.RenderTick() in /usr/src/OpenRA/OpenRA.Game/Game.cs:line 714
   at OpenRA.Game.Loop() in /usr/src/OpenRA/OpenRA.Game/Game.cs:line 877
   at OpenRA.Game.Run() in /usr/src/OpenRA/OpenRA.Game/Game.cs:line 909
   at OpenRA.Game.InitializeAndRun(String[] args) in /usr/src/OpenRA/OpenRA.Game/Game.cs:line 338
   at OpenRA.Launcher.Program.Main(String[] args) in /usr/src/OpenRA/OpenRA.Launcher/Program.cs:line 46
