### ISSUE TITLE
crashed playtest-20241116

### ISSUE THREAD

**Issue by hhsnake** [OpenRA/OpenRA#21676]
## System Information

- Operating System:  Linux Ubuntu 20.04
- OpenRA Version: playtest-20241116
- OpenRA Mod: playtest-20241116
- Source: Official download package

[exception-2024-12-20T115616Z.log](https://github.com/user-attachments/files/18210429/exception-2024-12-20T115616Z.log)
```
OpenRA engine version playtest-20241116
d2k mod version playtest-20241116
on map 791e4bf87425a986a42ea217cb16640b91c4b2ae (Halleck's Ridge by Westwood Studios).
Date: 2024-12-20 11:56:16Z
Operating System: Linux (X64, Unix 5.15.0.125)
Runtime Version: .NET CLR 6.0.36
Installed Language: ru (Installed) ru (Current) ru (Current UI)
Exception of type `System.InvalidOperationException`: TypeDictionary contains multiple instances of type `OpenRA.Mods.Common.Traits.ProductionInfo`
   at OpenRA.Primitives.TypeDictionary.Get[T](Boolean throwsIfMissing) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Primitives/TypeDictionary.cs:line 67
   at OpenRA.Mods.Common.Traits.BaseBuilderBotModule.LocomotorsForProducibles(Actor producer)
   at OpenRA.Mods.Common.Traits.BaseBuilderBotModule.ChooseRallyLocationNear(Actor producer) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs:line 341
   at OpenRA.Mods.Common.Traits.BaseBuilderBotModule.SetRallyPoint(IBot bot, TraitPair`1 rp) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs:line 310
   at OpenRA.Mods.Common.Traits.BaseBuilderBotModule.OpenRA.Mods.Common.Traits.IBotTick.BotTick(IBot bot) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs:line 244
   at OpenRA.Mods.Common.Traits.ModularBot.<OpenRA.Traits.ITick.Tick>b__14_0() in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/Player/ModularBot.cs:line 97
   at OpenRA.Sync.<>c__DisplayClass14_0.<RunUnsynced>b__0() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Sync.cs:line 172
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Sync.cs:line 203
   at OpenRA.Sync.RunUnsynced(Boolean checkSyncHash, World world, Action fn) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Sync.cs:line 173
   at OpenRA.Mods.Common.Traits.ModularBot.OpenRA.Traits.ITick.Tick(Actor self) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/Player/ModularBot.cs:line 93
   at OpenRA.TraitDictionary.TraitContainer`1.ApplyToAllTimed(Action`2 action, String text) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/TraitDictionary.cs:line 312
   at OpenRA.World.Tick() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/World.cs:line 458
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 651
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 666
   at OpenRA.Game.Loop() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 835
   at OpenRA.Game.Run() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 888
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 313
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenRA/OpenRA/OpenRA.Launcher/Program.cs:line 46
```

**Comment by penev92** [comment]
Thanks for the report!
This looks just like #21663, which was fixed by #21665, so should be OK in the next playtest.
