### ISSUE TITLE
MixFile.RaHeader, duplicate values found

### ISSUE THREAD

**Issue by dn150** [OpenRA/OpenRA#2441]
On map room-warzone with release-20121019, playing as Allies, closed as game began. exception.log contains:

```
Exception of type `System.ArgumentException`: MixFile.RaHeader, duplicate values found for the following keys: 2811818068: [(offs=1376304610, len=1436818881),(offs=1303428578, len=3844756581),(offs=3932274146, len=504285086),(offs=261406178, len=2011127635),(offs=3772169698, len=2458156051),(offs=4124556770, len=1657300316),(offs=394575330, len=2763129078),(offs=3464150498, len=1912530027),(offs=3887775202, len=1535573085),(offs=1667349986, len=1651050265)], 3255518541: [(offs=1099208783, len=3303102605),(offs=3604191311, len=3972225307),(offs=2693699663, len=316463550),(offs=2821888079, len=2932147912)], 2925018180: [(offs=118932477, len=331163447),(offs=2042545149, len=4248835109)], 3575071090: [(offs=2624743082, len=3797053306),(offs=1751213738, len=1182934561)], 1243613079: [(offs=1637127797, len=3841171263),(offs=3865482869, len=2023497237)], 3284888157: [(offs=687789427, len=358779927),(offs=3138704755, len=4230776020),(offs=1887884659, len=3736988869)], 465091051: [(offs=1882287750, len=3730501625),(offs=3090378374, len=4279611615)], 3851858380: [(offs=197200840, len=1913283067),(offs=83561416, len=2673869643)], 3683159305: [(offs=867278684, len=1087770530),(offs=2663358300, len=3130547281),(offs=1722326876, len=1312637092)], 400405198: [(offs=2385359528, len=400405198),(offs=1218818728, len=1142595513)]
   at OpenRA.Exts.ToDictionaryWithConflictLog[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, String debugName, Func`2 logKey, Func`2 logValue)
   at OpenRA.Exts.ToDictionaryWithConflictLog[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, String debugName, Func`2 logKey, Func`2 logValue)
   at OpenRA.FileFormats.MixFile..ctor(String filename, Int32 priority)
   at OpenRA.FileFormats.FileSystem.OpenPackage(String filename, Int32 order)
   at OpenRA.FileFormats.FileSystem.OpenPackage(String filename)
   at OpenRA.FileFormats.FileSystem.<Mount>c__AnonStoreyF.<>m__2E()
   at OpenRA.FileFormats.FileSystem.Mount(String name)
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, Boolean isShellmap)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.TickImmediate()
   at OpenRA.Game.<Tick>c__AnonStorey39.<>m__9E()
   at OpenRA.Sync.<CheckSyncUnchanged>c__AnonStorey30.<>m__69()
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   at OpenRA.Sync.CheckSyncUnchanged(World world, Action fn)
   at OpenRA.Game.Tick(OrderManager orderManager)
   at OpenRA.Game.Tick(OrderManager orderManager, Viewport viewPort)
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by Mailaender** [comment]
Nothing so far on release-20150424. At least I hope so.

**Comment by pchote** [comment]
It'll be reproduced in time.  I very much doubt this has been accidentally fixed between the last two releases.

**Comment by pchote** [comment]
http://logs.openra.net/?year=2015&month=06&day=09#00:13:47

**Comment by pchote** [comment]
http://pastebin.com/3sdLn4TQ

**Comment by Basti504** [comment]
When I tried to open a replay from a game I played yesterday, this error occured.
http://pastebin.com/pLRXuxAh

Second try was succesfull and the replay started just fine.
I could not reproduce the same crash.

**Comment by Basti504** [comment]
Same kind of error again. Happend the moment a multiplayer game started. In the same openra session I already played a multiplayer game successfully, before this crash.

http://pastebin.com/HRkLBuG2

**Comment by pi99y** [comment]
playtest: 20150808
Crashed in the menu after watching a RA replay
http://pastebin.com/Xb4EzCwR

**Comment by Basti504** [comment]
Got it again. release-20150614
http://pastebin.com/p8yr0zdj

Strange thing is, the crash came when I closed OpenRA from the main menu (?) after leaving a singleplayer skirmish match. Also, shellmap was disabled from settings menu.
