### ISSUE TITLE
Crash On starting game host

### ISSUE THREAD

**Issue by ryanrules247** [OpenRA/OpenRA#4465]
I try to open a game (to Host) and the game crashes.

Running on 64x Win 7.
On all Mods for OpenRA, also happens on Stable release aswell as the Playtest

Exception log:
Red Alert Mod at Version playtest-20131220
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 2.0.50727.5472
Exception of type `System.Net.Sockets.SocketException`: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at System.Net.Sockets.TcpListener.Start()
   at OpenRA.Server.Server..ctor(IPEndPoint endpoint, ServerSettings settings, ModData modData)
   at OpenRA.Game.CreateServer(ServerSettings settings)
   at OpenRA.Mods.RA.Widgets.Logic.ServerCreationLogic.CreateAndJoin()
   at OpenRA.Widgets.ButtonWidget.<ButtonWidget>m__CE(MouseInput _)
   at OpenRA.Widgets.ButtonWidget.HandleMouseInput(MouseInput mi)
   at OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
   at OpenRA.Widgets.Ui.HandleInput(MouseInput mi)
   at OpenRA.DefaultInputHandler.<OnMouseInput>c__AnonStorey24.<>m__24()
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   at OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input)
   at OpenRA.Renderer.SdlCommon.SdlInput.PumpInput(IInputHandler inputHandler)
   at OpenRA.Renderer.SdlCommon.SdlGraphics.PumpInput(IInputHandler inputHandler)
   at OpenRA.Graphics.Renderer.EndFrame(IInputHandler inputHandler)
   at OpenRA.Game.Tick(OrderManager orderManager)
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by abcdefg30** [comment]
@ryanrules247 does hosting work on our latest version?

If no please reopen this/leave a note.
(Also feel free to leave a note when it works. :p)

Otherwise closing here as this is hasn't seen any activity for a long time.
