### ISSUE TITLE
Arty to repair pad desync

### ISSUE THREAD

**Issue by VagueVigor** [OpenRA/OpenRA#4475]
This happened when i clicked arty to repair pad. (my nick is "Allies Lime Gray"). Arty had almost zero life left when i did that click. Maybe cause of that?

All logs: http://www.speedyshare.com/s4BPS/syncerror-19-01-14.7z

```
Red Alert Mod at Version release-20131223
Operating System: Windows (Microsoft Windows NT 5.1.2600 Service Pack 3)
Runtime Version: .NET CLR 2.0.50727.3082
Exception of type `System.InvalidOperationException`: Out of sync in frame 8439.
 OrderString: "Repair" 
	 Subject: "arty 696". 
	 TargetActor: "fix" 
	 TargetLocation: 0,0.
	 TargetString: "".
	 IsImmediate: False.
	 Player(PlayerName): Allies Lime Gray

 Compare syncreport.log with other players.
   at OpenRA.Network.OrderManager.OutOfSync(Int32 frame, Int32 index)
   at OpenRA.Network.OrderManager.CheckSync(Byte[] packet)
   at OpenRA.Network.OrderManager.<TickImmediate>c__AnonStorey13.<>m__4(Int32 clientId, Byte[] packet)
   at OpenRA.Network.ReplayRecorderConnection.<Receive>c__AnonStorey1B.<>m__12(Int32 client, Byte[] data)
   at OpenRA.Network.EchoConnection.Receive(Action`2 packetFn)
   at OpenRA.Network.ReplayRecorderConnection.Receive(Action`2 packetFn)
   at OpenRA.Network.OrderManager.TickImmediate()
   at OpenRA.Sync.<CheckSyncUnchanged>c__AnonStorey35.<>m__6A()
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   at OpenRA.Sync.CheckSyncUnchanged(World world, Action fn)
   at OpenRA.Game.TickInner(OrderManager orderManager)
   at OpenRA.Game.Tick(OrderManager orderManager)
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by abcdefg30** [comment]
I don't think we can do something about this without other syncreport logs.
This issue is also pretty old already (release-20131223).
