### ISSUE TITLE
Can not order Actor.Attack command

### ISSUE THREAD

**Issue by Computerfreaked** [OpenRA/OpenRA#7453]
I tried ordering an e1 actor(infantry) to attack a building. The game crashes and reports: Actor 'e1' does not define a property 'Attack'

The Lua API says void Attack(Actor target) => Fly an attack against the target actor. Requires Trait: AttackPlane.

It seems this command is for aircraft only so this means there is no command for non-aircraft actors to attack anything?!?

Full log:

Fatal Lua Error: [string "BindingSupport.lua"]:30: Uncaught CLR exception at Lua->CLR boundary: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Eluant.LuaException: [string "BindingSupport.lua"]:30: Actor 'e1' does not define a property 'Attack'
   at Eluant.LuaRuntime.Call(IList`1 args)
   at Eluant.LuaRuntime.Call(LuaFunction fn, IList`1 args)
   at OpenRA.Mods.Common.Scripting.UtilsGlobal.Do(LuaValue[] collection, LuaFunction func)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OpenRA.Scripting.ScriptMemberWrapper.Invoke(LuaVararg args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eluant.LuaRuntime.MethodWrapper.Invoke(Object[] parms)
   at Eluant.LuaRuntime.MakeManagedCall(IntPtr state, MethodWrapper wrapper)
   at OpenRA.Scripting.ScriptContext.FatalError(String message)
   at OpenRA.Mods.Common.Scripting.TriggerGlobal.<AfterDelay>c__AnonStorey78.<>m__D6()
   at OpenRA.Effects.DelayedAction.<Tick>m__20C(World w)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by Bynnar18** [comment]
Units that aren't planes don't have a straight attack function. You have to use something like AttackMove.

**Comment by chrisforbes** [comment]
You certainly can issue an 'Attack' order -- manually queueing up
activities is fraught with trouble though, since the activities used can
vary wildly based on what traits the actor has.

Perhaps what we want is a Lua hook into ResolveOrder (so you get the
correct activity dispatch in all cases, given a synthetic order)?

**Comment by Bynnar18** [comment]
I meant that there is no lua binding for a non-AttackPlane actor to attack specific target that I'm aware of. It might make a good addition though, given that the actor will continue its activities after destroying any actors at the target area or maybe after attacking once I don't know.

**Comment by Computerfreaked** [comment]
> I meant that there is no lua binding for a non-AttackPlane actor to attack specific target that I'm aware of.

This is exactly what I mean. I am currently working on the Soviet 02a map and it requires a team of 4 e4 to move to waypoint7 and from that position fire upon waypoint94. Using Hunt() in that case might cause them to attack something else.

**Comment by Bynnar18** [comment]
This is just a bit of a workaround but you could do this:

`allies.SetStance("neutral", "Enemy")`
`unit.AttackMove(waypoint94.Location)`
`Trigger.OnKilled(barrel, function() allies.SetStance("neutral","Ally") end)`

Of course you could also just make neutral an enemy from the start but that might make them hunt barrels instead of attack the player. I'd give it a try though or add the lua binding in yourself. (It isn't that hard, at least not for what I did in adding Demolish and EnterTransport)

**Comment by obrakmann** [comment]
Fixed in #8285.
