### ISSUE TITLE
Selling Barracks in Mission3a crashes game

### ISSUE THREAD

**Issue by zakocsis** [OpenRA/OpenRA#7553]
**Steps to reproduce:**

1. Play Allied Mission 3a.
2. Capture the Soviet Barracks in the first Soviet base.
3. Sell it.

**What I expected:**

The Barracks is sold and the game continues.

**What happens:**

The game crashes with a fatal map script error.

**Relevant log: lua.log**

      Fatal Lua Error: Object reference not set to an instance of an object
         at OpenRA.Scripting.ScriptContext.FatalError(System.String message)
         at OpenRA.Mods.RA.Scripting.TriggerGlobal+<OnAllRemovedFromWorld>c__AnonStorey3.<>m__0(OpenRA.Actor m)
         at OpenRA.Mods.RA.Scripting.ScriptTriggers.RemovedFromWorld(OpenRA.Actor self)
         at OpenRA.World.Remove(OpenRA.Actor a)
         at OpenRA.Actor.<Destroy>m__5(OpenRA.World w)
         at OpenRA.World.Tick()
         at OpenRA.Game.InnerLogicTick(OpenRA.Network.OrderManager orderManager)
         at OpenRA.Game.LogicTick()
         at OpenRA.Game.Loop()
         at OpenRA.Game.Run()
         at OpenRA.Program.Run(System.String[] args)
         at OpenRA.Program.Main(System.String[] args)

**Comment by abcdefg30** [comment]
Thanks for the report.
I tried to fix the bug: #7562
