### ISSUE TITLE
OpenRA.Map.OffsetOfSubCell IndexOutOfRangeException

### ISSUE THREAD

**Issue by i255** [OpenRA/OpenRA#7993]
Seems similar to: https://github.com/OpenRA/OpenRA/issues/7813

Stacktrace:
Red Alert Mod at Version playtest-20150418
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34014
Exception of type `System.IndexOutOfRangeException`: Index was outside the bounds of the array.
   at OpenRA.Map.OffsetOfSubCell(SubCell subCell)
   at OpenRA.Mods.Common.Activities.Move.MoveFirstHalf.OnComplete(Actor self, Mobile mobile, Move parent)
   at OpenRA.Mods.Common.Activities.Move.MovePart.InnerTick(Actor self, Mobile mobile)
   at OpenRA.Mods.Common.Activities.Move.MovePart.Tick(Actor self)
   at OpenRA.Traits.Util.RunActivity(Actor self, Activity act)
   at OpenRA.Mods.Common.Activities.AttackMoveActivity.Tick(Actor self)
   at OpenRA.Traits.Util.RunActivity(Actor self, Activity act)
   at OpenRA.Actor.Tick()
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by Mailaender** [comment]
> Seems similar to: #7813

Yes, next playtest/release will ship the fix.
