### ISSUE TITLE
NRE in SpriteFont.Measure, from ClientTooltipLogic

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#8016]
```
Red Alert Mod at Version release-20150424
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Graphics.SpriteFont.Measure(String text)
   at OpenRA.Mods.Common.Widgets.Logic.ClientTooltipLogic.<>c__DisplayClassb.<.ctor>b__1()
   at OpenRA.Mods.Common.Widgets.TooltipContainerWidget.Draw()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Ui.Draw()
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

Crashed, I don't know what happened. No repro steps yet.

**Comment by cjshmyr** [comment]
At least try with the issue name!

**Comment by Basti504** [comment]
Had the same crash, just moments after joining a multiplayer lobby.

```
Red Alert Mod at Version release-20150424
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34014
Exception of type `System.NullReferenceException`: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij OpenRA.Graphics.SpriteFont.Measure(String text)
   bij OpenRA.Mods.Common.Widgets.Logic.ClientTooltipLogic.<>c__DisplayClassb.<.ctor>b__1()
   bij OpenRA.Mods.Common.Widgets.TooltipContainerWidget.Draw()
   bij OpenRA.Widgets.Widget.DrawOuter()
   bij OpenRA.Widgets.Widget.DrawOuter()
   bij OpenRA.Widgets.Widget.DrawOuter()
   bij OpenRA.Widgets.Ui.Draw()
   bij OpenRA.Game.RenderTick()
   bij OpenRA.Game.Loop()
   bij OpenRA.Game.Run()
   bij OpenRA.Program.Run(String[] args)
   bij OpenRA.Program.Main(String[] args)
```
