### ISSUE TITLE
OpenRA goes out of memory

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#8073]
Sorry #7696, it's probably you.
```
Red Alert Mod at Version {DEV_VERSION}
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.OutOfMemoryException`: An exception of type 'System.OutOfMemoryException' was drawn. (Eine Ausnahme vom Typ "System.OutOfMemoryException" wurde ausgelöst.)
   at OpenRA.Graphics.Sheet.CreateBuffer() \OpenRA\OpenRA.Game\Graphics\Sheet.cs:Line 149.
   at OpenRA.Graphics.Sheet.GetData() \OpenRA\OpenRA.Game\Graphics\Sheet.cs:Line 30.
   at OpenRA.Graphics.SpriteFont.CreateGlyph(Pair`2 c) \OpenRA\OpenRA.Game\Graphics\SpriteFont.cs:Line 120.
   at OpenRA.Primitives.Cache`2.get_Item(T key) \OpenRA\OpenRA.Game\Primitives\Cache.cs:Line 39.
   at OpenRA.Graphics.SpriteFont.PrecacheColor(Color c, String name) \OpenRA\OpenRA.Game\Graphics\SpriteFont.cs:Line 54.
   at OpenRA.Graphics.SpriteFont..ctor(String name, Int32 size, SheetBuilder builder) \OpenRA\OpenRA.Game\Graphics\SpriteFont.cs:Line 46.
   at OpenRA.Graphics.Renderer.<InitializeFonts>b__1(KeyValuePair`2 x) \OpenRA\OpenRA.Game\Graphics\Renderer.cs:Line 104.
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at OpenRA.Graphics.Renderer.InitializeFonts(Manifest m) \OpenRA\OpenRA.Game\Graphics\Renderer.cs:Line 103.
   at OpenRA.Game.InitializeMod(String mod, Arguments args) \OpenRA\OpenRA.Game\Game.cs:Line 307.
   at OpenRA.Game.Initialize(Arguments args) \OpenRA\OpenRA.Game\Game.cs:Line 264.
   at OpenRA.Program.Run(String[] args) \OpenRA\OpenRA.Game\Support\Program.cs:Line 109.
   at OpenRA.Program.Main(String[] args) \OpenRA\OpenRA.Game\Support\Program.cs:Line 39.
```

**Comment by obrakmann** [comment]
```
(16:10:44) abcdefg30: well, openra out of memory again
(16:11:15) penev: sinfonia was complaining of the same thing
(16:11:37) antares79: abcdefg30: can you checkout dacf094956fc8204cfba32bd089fe24325678bb6 and see if it happens there, too?
(16:13:52) abcdefg30: moment
(16:14:05) abcdefg30: gone
(16:14:43) antares79: abcdefg30: how about 732001f3f32e7eac844a4f3cafe312072cd9f711?
(16:15:28) abcdefg30: problem there again
(16:15:45) antares79: we have a winner then: #7696
```

**Comment by Robmaister** [comment]
I can't reproduce it on Windows 8.1 (6.3.9600), but I have a suspicion this is because the version of SharpFont isn't getting updated. I changed the way fixed-point decimals were being returned from a raw `int` to `Fixed26Dot6` and `Fixed16Dot16` structs.

For ease of use, I included implicit casts to `float`, `double`, and `decimal` and an explicit cast to `int`. I didn't realize that on older versions of SharpFont, the `int` cast would effectively do nothing where there used to be a `value >> 6`.

If you have an older version of SharpFont, every glyph that you build will be 64x it's actual size, which could probably make you run out of memory very quickly.

**Comment by Phrohdoh** [comment]
I cannot play OpenRA anymore under OS X 10.10.3.

```
Platform is OSX
Using SDL 2 with OpenGL renderer
Desktop resolution: 1440x900
Using resolution: 1024x768
Detected OpenGL version: 2.1
Using OpenAL sound engine
Using default device
Available mods:
	cnc: Tiberian Dawn ({DEV_VERSION})
	d2k: Dune 2000 ({DEV_VERSION})
	modchooser: Mod Chooser ({DEV_VERSION})
	ra: Red Alert ({DEV_VERSION})
	ts: Tiberian Sun ({DEV_VERSION})
Loading mod: cnc
Exception of type `System.OutOfMemoryException`: Out of memory
  at (wrapper managed-to-native) object:__icall_wrapper_mono_gc_alloc_vector (intptr,intptr,intptr)
  at (wrapper alloc) object:AllocVector (intptr,intptr)
  at OpenRA.Graphics.Sheet.CreateBuffer () [0x00048] in /Users/thill/projects/openra/OpenRA.Game//Graphics/Sheet.cs:149 
  at OpenRA.Graphics.Sheet.GetData () [0x00002] in /Users/thill/projects/openra/OpenRA.Game//Graphics/Sheet.cs:30 
  at OpenRA.Graphics.SpriteFont.CreateGlyph (Pair`2 c) [0x000e2] in /Users/thill/projects/openra/OpenRA.Game//Graphics/SpriteFont.cs:120 
  at OpenRA.Primitives.Cache`2[OpenRA.Primitives.Pair`2[System.Char,System.Drawing.Color],OpenRA.Graphics.GlyphInfo].get_Item (Pair`2 key) [0x00022] in /Users/thill/projects/openra/OpenRA.Game//Primitives/Cache.cs:39 
  at OpenRA.Graphics.SpriteFont.PrecacheColor (Color c, System.String name) [0x0004d] in /Users/thill/projects/openra/OpenRA.Game//Graphics/SpriteFont.cs:54 
  at OpenRA.Graphics.SpriteFont..ctor (System.String name, Int32 size, OpenRA.Graphics.SheetBuilder builder) [0x000a3] in /Users/thill/projects/openra/OpenRA.Game//Graphics/SpriteFont.cs:46 
  at OpenRA.Graphics.Renderer.<InitializeFonts>m__1 (KeyValuePair`2 x) [0x00029] in /Users/thill/projects/openra/OpenRA.Game//Graphics/Renderer.cs:104 
  at System.Linq.Enumerable.ToDictionary[KeyValuePair`2,String,SpriteFont] (IEnumerable`1 source, System.Func`2 keySelector, System.Func`2 elementSelector, IEqualityComparer`1 comparer) [0x0002f] in /private/tmp/source-mono-mac-3.12.0-branch-32/bockbuild-mono-3.12.0-branch/profiles/mono-mac-xamarin/build-root/mono-3.12.0/mcs/class/System.Core/System.Linq/Enumerable.cs:2928 
  at System.Linq.Enumerable.ToDictionary[KeyValuePair`2,String,SpriteFont] (IEnumerable`1 source, System.Func`2 keySelector, System.Func`2 elementSelector) [0x00000] in /private/tmp/source-mono-mac-3.12.0-branch-32/bockbuild-mono-3.12.0-branch/profiles/mono-mac-xamarin/build-root/mono-3.12.0/mcs/class/System.Core/System.Linq/Enumerable.cs:2915 
  at OpenRA.Graphics.Renderer.InitializeFonts (OpenRA.Manifest m) [0x00034] in /Users/thill/projects/openra/OpenRA.Game//Graphics/Renderer.cs:103 
  at OpenRA.Game.InitializeMod (System.String mod, OpenRA.Arguments args) [0x00184] in /Users/thill/projects/openra/OpenRA.Game//Game.cs:307 
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x002d0] in /Users/thill/projects/openra/OpenRA.Game//Game.cs:264 
  at OpenRA.Program.Run (System.String[] args) [0x00007] in /Users/thill/projects/openra/OpenRA.Game//Support/Program.cs:109 
  at OpenRA.Program.Main (System.String[] args) [0x00050] in /Users/thill/projects/openra/OpenRA.Game//Support/Program.cs:39 
```

**Comment by Mailaender** [comment]
Does fetching https://github.com/OpenRA/OpenRA/pull/7953 and `make clean && make all` fix it?

**Comment by Phrohdoh** [comment]
It does!
