### ISSUE TITLE
Cannot locate type: RocketInfo

### ISSUE THREAD

**Issue by sajwang** [OpenRA/OpenRA#8088]
Hello,

I got this error: "Failed to load rules for shellmap with error Cannot locate type: RocketInfo".

I'm not sure what causes this nor what fixes this. What is going on?

For relevant information, here is what exceptions found: 

3000 Mod at Version 1
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34014
Exception of type `System.InvalidOperationException`: Cannot locate type: RocketInfo
   at OpenRA.ObjectCreator.<.cctor>b__13(String s)
   at OpenRA.ObjectCreator.CreateObject[T](String className, Dictionary`2 args)
   at OpenRA.ObjectCreator.CreateObject[T](String className)
   at OpenRA.Game.CreateObject[T](String name)
   at OpenRA.GameRules.WeaponInfo.LoadProjectile(MiniYaml yaml)
   at OpenRA.FieldLoader.Load(Object self, MiniYaml my)
   at OpenRA.GameRules.WeaponInfo..ctor(String name, MiniYaml content)
   at OpenRA.RulesetCache.<LoadMapRules>b__1(MiniYamlNode k, Dictionary`2 _)
   at OpenRA.RulesetCache.<>c__DisplayClass15`1.<LoadYamlRules>b__10(MiniYamlNode wkv, Dictionary`2 wyy)
   at OpenRA.RulesetCache.<>c__DisplayClass15`1.<LoadYamlRules>b__14(MiniYamlNode kv)
   at OpenRA.Exts.ToDictionaryWithConflictLog[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, String debugName, Func`2 logKey, Func`2 logValue)
   at OpenRA.RulesetCache.LoadYamlRules[T](Dictionary`2 itemCache, String[] files, List`1 nodes, Func`3 f)
   at OpenRA.RulesetCache.LoadMapRules(Map map)
   at OpenRA.RulesetCache.LoadDefaultRules()
   at OpenRA.ModData.<.ctor>b__2()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at OpenRA.ModData.get_DefaultRules()
   at OpenRA.Map.<PostInit>b__16()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at OpenRA.Map.PreloadRules()
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Game.LoadShellMap()
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by sajwang** [comment]
Never mind, I fixed that part; I had typed "rocket", i meant "rockets" for one of my units.

However, I put in some custom units and found this error:
Failed to load rules for shellmap with error Cannot locate type: AtackFrontalInfo

Again, the exception log:
3000 Mod at Version 1
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34014
Exception of type `System.InvalidOperationException`: Cannot locate type: AtackFrontalInfo
   at OpenRA.ObjectCreator.<.cctor>b__13(String s)
   at OpenRA.ObjectCreator.CreateObject[T](String className, Dictionary`2 args)
   at OpenRA.ObjectCreator.CreateObject[T](String className)
   at OpenRA.Game.CreateObject[T](String name)
   at OpenRA.ActorInfo.LoadTraitInfo(String traitName, MiniYaml my)
   at OpenRA.ActorInfo..ctor(String name, MiniYaml node, Dictionary`2 allUnits)
   at OpenRA.RulesetCache.<LoadMapRules>b__0(MiniYamlNode k, Dictionary`2 y)
   at OpenRA.RulesetCache.<>c__DisplayClass15`1.<LoadYamlRules>b__10(MiniYamlNode wkv, Dictionary`2 wyy)
   at OpenRA.RulesetCache.<>c__DisplayClass15`1.<LoadYamlRules>b__14(MiniYamlNode kv)
   at OpenRA.Exts.ToDictionaryWithConflictLog[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, String debugName, Func`2 logKey, Func`2 logValue)
   at OpenRA.RulesetCache.LoadYamlRules[T](Dictionary`2 itemCache, String[] files, List`1 nodes, Func`3 f)
   at OpenRA.RulesetCache.LoadMapRules(Map map)
   at OpenRA.RulesetCache.LoadDefaultRules()
   at OpenRA.ModData.<.ctor>b__2()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at OpenRA.ModData.get_DefaultRules()
   at OpenRA.Map.<PostInit>b__16()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at OpenRA.Map.PreloadRules()
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Game.LoadShellMap()
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by penev92** [comment]
The second one is because the trait is called `AttackFrontal`, not `AtackFrontal`.

**Comment by sajwang** [comment]
Okay, thank yoh Phrphdoh, looks like another typo

**Comment by pchote** [comment]
We should wrap these calls to ObjectCreator in try/catches and throw friendlier exceptions (Projectile type "Rocket" not found. / Trait type "AtackFrontal" not found.).
