### ISSUE TITLE
gdi3lose.vqa crashes the game

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#8132]
It used to work in release-20141029

```
Exception of type `System.IO.EndOfStreamException`: Failed to read past end of stream.
  at OpenRA.StreamExts.ReadBytes (System.IO.Stream s, System.Byte[] buffer, Int32 offset, Int32 count) [0x00046] in /home/oliver/devel/openra/git/OpenRA.Game/StreamExts.cs:41 
  at OpenRA.StreamExts.ReadBytes (System.IO.Stream s, Int32 count) [0x00023] in /home/oliver/devel/openra/git/OpenRA.Game/StreamExts.cs:25 
  at OpenRA.FileFormats.VqaReader.CollectAudioData () [0x0016d] in /home/oliver/devel/openra/git/OpenRA.Game/FileFormats/VqaReader.cs:206 
  at OpenRA.FileFormats.VqaReader..ctor (System.IO.Stream stream) [0x00357] in /home/oliver/devel/openra/git/OpenRA.Game/FileFormats/VqaReader.cs:152 
  at OpenRA.Mods.Common.Widgets.VqaPlayerWidget.Load (System.String filename) [0x0001d] in /home/oliver/devel/openra/git/OpenRA.Mods.Common/Widgets/VqaPlayerWidget.cs:53
```

```
$ md5sum ~/.openra/Content/cnc/movies-gdi.mix 
259cff394b66a2bad612bd080d4f77de  /home/oliver/.openra/Content/cnc/movies-gdi.mix
```

**Comment by penev92** [comment]
Here is my exception:
```
System.OutOfMemoryException was unhandled
  HResult=-2147024882
  Message=Exception of type 'System.OutOfMemoryException' was thrown.
  Source=OpenRA.Game
  StackTrace:
       at OpenRA.StreamExts.ReadBytes(Stream s, Int32 count) in e:\Work\Programming\C#\OpenRA\OpenRA\OpenRA.Game\StreamExts.cs:line 24
       at OpenRA.FileFormats.VqaReader.CollectAudioData() in e:\Work\Programming\C#\OpenRA\OpenRA\OpenRA.Game\FileFormats\VqaReader.cs:line 206
       at OpenRA.FileFormats.VqaReader..ctor(Stream stream) in e:\Work\Programming\C#\OpenRA\OpenRA\OpenRA.Game\FileFormats\VqaReader.cs:line 152
       at OpenRA.Mods.Common.Widgets.VqaPlayerWidget.Load(String filename)
       at OpenRA.Mods.Common.Widgets.Logic.AssetBrowserLogic.LoadAsset(String filename)
       at OpenRA.Mods.Common.Widgets.Logic.AssetBrowserLogic.<>c__DisplayClass42.<AddAsset>b__3f()
```

The reason for that is `VqaReader.CollectAudioData()` reads a wrong chunk for `type` - `"D\0SN"`, the `switch` goes to the default case with `length == 1144127488` and then `StreamExts.ReadBytes()` tries to do `var buffer = new byte[1144127488];`
