### ISSUE TITLE
crash probably connected with atom bomb usage

### ISSUE THREAD

**Issue by i255** [OpenRA/OpenRA#8141]
```
Red Alert Mod at Version release-20150424
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type 'System.InvalidOperationException': Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable'1 source, Func'2 predicate)
   at OpenRA.Mods.Common.Traits.SupportPowerInstance.Activate(Order order)
   at OpenRA.Mods.Common.Traits.SupportPowerManager.ResolveOrder(Actor self, Order order)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by penev92** [comment]
What mod is this?

**Comment by i255** [comment]
from stack trace:
Red Alert Mod at Version release-20150424

**Comment by penev92** [comment]
I'm going to bet that you (or some other player?) launched an atom bomb, but your(their) power went low, or the missile silo was otherwise disabled between the launch order and the actual launch.
Can you upload a replay somewhere and give us a link?

**Comment by i255** [comment]
This is possible. There were two missile launches and I think one of the silos was destroyed just before the crash. Here is the replay: https://drive.google.com/file/d/0BzEL82gcGBSIWjJFTXNmTEJMek0/view?usp=sharing

**Comment by LipkeGu** [comment]
the first is the problem :/

**Comment by penev92** [comment]
OK I looked at the replay. Turns out I was right - the green player launches his nuke at a power plant.
Then at the exact moment it hits, orange tries to launch his nuke, but it's already low on power. Should be a very simple fix to make `SupportPowerInstance.Activate()` **not* assume that the support power is **not** disabled.

**Comment by i255** [comment]
Got the same error again today with in the new release:
Red Alert Mod at Version release-20150614
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.InvalidOperationException`: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at OpenRA.Mods.Common.Traits.SupportPowerInstance.Activate(Order order)
   at OpenRA.Mods.Common.Traits.SupportPowerManager.ResolveOrder(Actor self, Order order)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by penev92** [comment]
Wow you're *that* unlucky, eh, @i255 ? :/

**Comment by Snurre86** [comment]
Got the same error again with the new release:

Download replay here:
http://s000.tinyupload.com/?file_id=69312154643439020992

Red Alert Mod at Version release-20150614
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.17929
Exception of type `System.InvalidOperationException`: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at OpenRA.Mods.Common.Traits.SupportPowerInstance.Activate(Order order)
   at OpenRA.Mods.Common.Traits.SupportPowerManager.ResolveOrder(Actor self, Order order)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

Download replay here:
http://s000.tinyupload.com/?file_id=69312154643439020992
