### ISSUE TITLE
Certain Infantry Death Sounds Cause Crash

### ISSUE THREAD

**Issue by shatterspike1** [OpenRA/OpenRA#8173]
While playing skirmish with the *.MIX files from the DOS version of Command & Conquer, sometimes, when an infantry unit dies the game crashes.  Have reproduced once under similar conditions.

```
Tiberian Dawn Mod at Version release-20150424
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.IndexOutOfRangeException`: Index was outside the bounds of the array.
   at OpenRA.FileFormats.AudLoader.LoadSound(Stream s)
   at OpenRA.Sound.LoadSound(String filename)
   at OpenRA.Primitives.Cache`2.get_Item(T key)
   at OpenRA.Sound.PlayPredefined(Ruleset ruleset, Player p, Actor voicedUnit, String type, String definition, String variant, Boolean relative, WPos pos, Single volumeModifier, Boolean attenuateVolume)
   at OpenRA.Sound.PlayVoiceLocal(String phrase, Actor voicedUnit, String variant, WPos pos, Single volume)
   at OpenRA.Mods.Common.Traits.DeathSounds.Killed(Actor self, AttackInfo e)
   at OpenRA.Traits.Health.InflictDamage(Actor self, Actor attacker, Int32 damage, DamageWarhead warhead, Boolean ignoreModifiers)
   at OpenRA.Traits.HealthExts.InflictDamage(Actor self, Actor attacker, Int32 damage, DamageWarhead warhead)
   at OpenRA.GameRules.DamageWarhead.DoImpact(Actor victim, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.GameRules.DamageWarhead.DoImpact(Target target, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.GameRules.WeaponInfo.<>c__DisplayClassc.<Impact>b__8()
   at OpenRA.GameRules.WeaponInfo.Impact(Target target, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.Mods.Common.Effects.Bullet.Explode(World world)
   at OpenRA.Mods.Common.Effects.Bullet.Tick(World world)
   at OpenRA.World.<Tick>b__11(IEffect e)
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by pchote** [comment]
Sorry, but we don't support the DOS version assets.  Please install the C&C95 assets, or use the ingame download option.
