### ISSUE TITLE
Unbuffered sheet exception in voxel renderer

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#8197]
Reported by @GraionDilach in IRC. Pinging @RoosterDragon.

```
Attacque Superior Mod at Version {DEV_VERSION}
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.18444
Exception of type `System.InvalidOperationException`: This sheet is unbuffered. You cannot call CommitData on an unbuffered sheet. If you need to completely replace the texture data you should set data into the texture directly. If you need to make only small changes to the texture data consider creating a buffered sheet instead.
   at OpenRA.Graphics.Sheet.CommitData(Boolean releaseBuffer) in e:\OpenRA-dev\OpenRA.Game\Graphics\Sheet.cs:line 171
   at OpenRA.Graphics.Sheet.ReleaseBuffer() in e:\OpenRA-dev\OpenRA.Game\Graphics\Sheet.cs:line 163
   at OpenRA.Graphics.SheetBuilder.Allocate(Size imageSize, float2 spriteOffset) in e:\OpenRA-dev\OpenRA.Game\Graphics\SheetBuilder.cs:line 120
   at OpenRA.Graphics.VoxelRenderer.RenderAsync(WorldRenderer wr, IEnumerable`1 voxels, WRot camera, Single scale, Single[] groundNormal, WRot lightSource, Single[] lightAmbientColor, Single[] lightDiffuseColor, PaletteReference color, PaletteReference normals, PaletteReference shadowPalette) in e:\OpenRA-dev\OpenRA.Game\Graphics\VoxelRenderer.cs:line 164
   at OpenRA.Mods.Common.Graphics.VoxelRenderable.FinalizedVoxelRenderable..ctor(WorldRenderer wr, VoxelRenderable voxel)
   at OpenRA.Mods.Common.Graphics.VoxelRenderable.PrepareRender(WorldRenderer wr)
   at OpenRA.Graphics.WorldRenderer.<GenerateRenderables>b__6(IRenderable r) in e:\OpenRA-dev\OpenRA.Game\Graphics\WorldRenderer.cs:line 118
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OpenRA.Graphics.WorldRenderer.GenerateRenderables() in e:\OpenRA-dev\OpenRA.Game\Graphics\WorldRenderer.cs:line 117
   at OpenRA.Graphics.WorldRenderer.Draw() in e:\OpenRA-dev\OpenRA.Game\Graphics\WorldRenderer.cs:line 131
   at OpenRA.Game.RenderTick() in e:\OpenRA-dev\OpenRA.Game\Game.cs:line 501
   at OpenRA.Game.Loop() in e:\OpenRA-dev\OpenRA.Game\Game.cs:line 623
   at OpenRA.Game.Run() in e:\OpenRA-dev\OpenRA.Game\Game.cs:line 641
   at OpenRA.Program.Run(String[] args) in e:\OpenRA-dev\OpenRA.Game\Support\Program.cs:line 111
   at OpenRA.Program.Main(String[] args) in e:\OpenRA-dev\OpenRA.Game\Support\Program.cs:line 39
```

**Comment by GraionDilach** [comment]
This happens when one uses a voxel body with multiple sections along with a turret.

Testbed: http://yras.cncguild.net/OpenRAbugs/8197.zip but I assume any muli-sectioned voxel will do - so you can as well easily just drop the Sonic Tank turret to the Mammoth MkII in the TS mod.

**Comment by pchote** [comment]
I suspect what is actually happening is that we're overflowing on to a second voxel sheet.  Large multisectioned voxels are a good way to use a bunch of texture space.
