### ISSUE TITLE
Bot related Disguise desync on release 20150424

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#8242]
It happened as I tried to disguise as a rilfe man (owned by a bot) that shot at me.
Unfortunately the replay doesn't show anything (it stops a few seconds before the critical situation).
Here are the syncreports and the difference between them: [Gist](https://gist.github.com/abcdefg30/f3b58b10fdc141132a4a)
Exception (probably not too helpful though):
```
Red Alert Mod at Version release-20150424
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.InvalidOperationException`: Out of sync in frame 20987: Blame Tick.
 Compare syncreport.log with other players.
   at OpenRA.Network.OrderManager.OutOfSync(Int32 frame, String blame)
   at OpenRA.Network.OrderManager.CheckSync(Byte[] packet)
   at OpenRA.Network.OrderManager.<>c__DisplayClass9.<TickImmediate>b__5(Int32 clientId, Byte[] packet)
   at OpenRA.Network.ReplayRecorderConnection.<>c__DisplayClass3.<Receive>b__2(Int32 client, Byte[] data)
   at OpenRA.Network.EchoConnection.Receive(Action`2 packetFn)
   at OpenRA.Network.ReplayRecorderConnection.Receive(Action`2 packetFn)
   at OpenRA.Network.OrderManager.TickImmediate()
   at OpenRA.Sync.<>c__DisplayClass5.<CheckSyncUnchanged>b__4()
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   at OpenRA.Sync.CheckSyncUnchanged(World world, Action fn)
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by Mailaender** [comment]
Could be related to https://github.com/OpenRA/OpenRA/issues/2959.

**Comment by abcdefg30** [comment]
> 15:07:25 (pchote) I suspect that #8242 has been solved now
