### ISSUE TITLE
Fatal error in "Steal the detonator (a)(b)(c)"

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#8344]
If you go to the flare before picking up the crate this happens. Version bleed 2015-06-01.
![openra game_2015_06_01_07_00_59_765](https://cloud.githubusercontent.com/assets/7798635/7906473/3284cb12-082c-11e5-8134-db13c62ab27e.png)

Also see:
 #8343
#8346

**Comment by Snurre86** [comment]
Lua.log

Fatal Lua Error: [string "BindingSupport.lua"]:30: Unable to convert parameter 0 to Int32
   at OpenRA.Scripting.ScriptContext.FatalError(String message)
   at OpenRA.Mods.Common.Scripting.TriggerGlobal.<>c__DisplayClass14.<OnEnteredFootprint>b__13(Actor a)
   at OpenRA.Traits.ActorMap.CellTrigger.Tick(ActorMap am)
   at OpenRA.Traits.ActorMap.Tick(Actor self)
   at OpenRA.World.<Tick>b__10(TraitPair`1 x)
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
