### ISSUE TITLE
Crash in the harvester logic

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#8467]
Happened while testing soviet-05 (see also #8446).

```
Red Alert Mod at Version {DEV_VERSION}
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.ArgumentException`: An item with the same key has already been added. (Ein Element mit dem gleichen Schlüssel wurde bereits hinzugefügt.)
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at OpenRA.Mods.Common.Traits.Harvester.ClosestProc(Actor self, Actor ignore)
   at OpenRA.Mods.Common.Traits.Harvester.ChooseNewProc(Actor self, Actor ignore)
   at OpenRA.Mods.Common.Traits.Harvester.<>c__DisplayClass4.<.ctor>b__2()
   at OpenRA.Activities.CallFunc.Tick(Actor self) in \OpenRA\OpenRA.Game\Activities\CallFunc.cs:Line 29.
   at OpenRA.Traits.Util.RunActivity(Actor self, Activity act) in \OpenRA\OpenRA.Game\Traits\Util.cs:Line 83.
   at OpenRA.Actor.Tick() in \OpenRA\OpenRA.Game\Actor.cs:Line 121.
   at OpenRA.World.Tick() in \OpenRA\OpenRA.Game\World.cs:Line 302.
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in \OpenRA\OpenRA.Game\Game.cs:Line 456.
   at OpenRA.Game.LogicTick() in \OpenRA\OpenRA.Game\Game.cs:Line 480.
   at OpenRA.Game.Loop() in \OpenRA\OpenRA.Game\Game.cs:Line 596.
   at OpenRA.Game.Run() in \OpenRA\OpenRA.Game\Game.cs:Line 636.
   at OpenRA.Program.Run(String[] args) in \OpenRA\OpenRA.Game\Support\Program.cs:Line 111.
   at OpenRA.Program.Main(String[] args) in \OpenRA\OpenRA.Game\Support\Program.cs:Line 39.

```
##

**Comment by penev92** [comment]
Can you reproduce this?

**Comment by abcdefg30** [comment]
Yep. Just take a map and add something like
```yaml
	Actor41: proc
		Location: 39,29
		Owner: Multi0
		FreeActor: False
	Actor42: proc
		Location: 39,29
		Owner: Multi0
		FreeActor: False
```
to `Actors:` in `map.yaml`.
Start the game and build a harvester -> crash.

**Comment by penev92** [comment]
I mean in a ... legal way. That is obviously a YAML error (which should be dealt with by a lint check).

**Comment by abcdefg30** [comment]
> I mean in a ... legal way.

Here you go: https://github.com/OpenRA/OpenRA/compare/bleed...abcdefg30:proc_crash
(This could be defined by a custom map.)

**Comment by tovl** [comment]
A lot has changed in the harvester logic in the past years. Is this issue still relevant?

**Comment by abcdefg30** [comment]
We still index refineries by `CPos`, so yes.
