### ISSUE TITLE
RA Actor type `e2` does not define a DEFAULT death animation for weapon with damage types

### ISSUE THREAD

**Issue by GrayHatter** [OpenRA/OpenRA#8540]
```
Red Alert Mod at Version release-20150614
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.Exception`: Actor type `e2` does not define a death animation for weapon with damage types ``!
   at OpenRA.Mods.Common.Traits.WithDeathAnimation.Killed(Actor self, AttackInfo e)
   at OpenRA.Traits.Health.InflictDamage(Actor self, Actor attacker, Int32 damage, DamageWarhead warhead, Boolean ignoreModifiers) in c:\Users\grayhatter\code\OpenRA\OpenRA.Game\Traits\Health.cs:line 155
   at OpenRA.Traits.HealthExts.InflictDamage(Actor self, Actor attacker, Int32 damage, DamageWarhead warhead) in c:\Users\grayhatter\code\OpenRA\OpenRA.Game\Traits\Health.cs:line 210
   at OpenRA.GameRules.DamageWarhead.DoImpact(Actor victim, Actor firedBy, IEnumerable`1 damageModifiers) in c:\Users\grayhatter\code\OpenRA\OpenRA.Game\GameRules\DamageWarhead.cs:line 74
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.GameRules.DamageWarhead.DoImpact(Target target, Actor firedBy, IEnumerable`1 damageModifiers) in c:\Users\grayhatter\code\OpenRA\OpenRA.Game\GameRules\DamageWarhead.cs:line 66
   at OpenRA.GameRules.WeaponInfo.<>c__DisplayClassc.<Impact>b__8() in c:\Users\grayhatter\code\OpenRA\OpenRA.Game\GameRules\WeaponInfo.cs:line 163
   at OpenRA.GameRules.WeaponInfo.Impact(Target target, Actor firedBy, IEnumerable`1 damageModifiers) in c:\Users\grayhatter\code\OpenRA\OpenRA.Game\GameRules\WeaponInfo.cs:line 167
   at OpenRA.Mods.Common.Effects.Bullet.Explode(World world)
   at OpenRA.Mods.Common.Effects.Bullet.Tick(World world)
   at OpenRA.World.<Tick>b__11(IEffect e) in c:\Users\grayhatter\code\OpenRA\OpenRA.Game\World.cs:line 306
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text) in c:\Users\grayhatter\code\OpenRA\OpenRA.Game\WorldUtils.cs:line 54
   at OpenRA.World.Tick() in c:\Users\grayhatter\code\OpenRA\OpenRA.Game\World.cs:line 306
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in c:\Users\grayhatter\code\OpenRA\OpenRA.Game\Game.cs:line 456
   at OpenRA.Game.LogicTick() in c:\Users\grayhatter\code\OpenRA\OpenRA.Game\Game.cs:line 480
   at OpenRA.Game.Loop() in c:\Users\grayhatter\code\OpenRA\OpenRA.Game\Game.cs:line 596
   at OpenRA.Game.Run() in c:\Users\grayhatter\code\OpenRA\OpenRA.Game\Game.cs:line 636
   at OpenRA.Program.Run(String[] args) in c:\Users\grayhatter\code\OpenRA\OpenRA.Game\Support\Program.cs:line 111
   at OpenRA.Program.Main(String[] args) in c:\Users\grayhatter\code\OpenRA\OpenRA.Game\Support\Program.cs:line 39
```

**Comment by penev92** [comment]
Any idea who tried to kill that `e2` with an illegal weapon?
Can you give us a replay?

**Comment by obrakmann** [comment]
Closing then.
