### ISSUE TITLE
Bleed TD crashes due to the Media.PlayMusic Lua script

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#8559]
This seems to be a regression of #8529 due to PlayMusic bleeding into a skirmish game.

Practically, if one has shellmap music - map1.aud, part of transit.mix - then after starting a skirmish game, the player must skip a track manually otherwise the game crashes when map1.aud ends.

**Comment by GraionDilach** [comment]
Stacktrace:

```
Tiberian Dawn Mod at Version {DEV_VERSION}
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.18444
Exception of type `System.ObjectDisposedException`: Cannot access a disposed object.
Object name: 'Eluant.MemoryConstrainedLuaRuntime'.
   at Eluant.LuaRuntime.CheckDisposed()
   at Eluant.LuaRuntime.Call(LuaFunction fn, IList`1 args)
   at Eluant.LuaFunction.Call(LuaValue[] args)
   at OpenRA.Mods.Common.Scripting.MediaGlobal.<>c__DisplayClass6.<PlayMusic>b__2()
   at OpenRA.Sound.Tick() in e:\OpenRA-dev\OpenRA.Game\Sound\Sound.cs:line 155
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in e:\OpenRA-dev\OpenRA.Game\Game.cs:line 434
   at OpenRA.Game.LogicTick() in e:\OpenRA-dev\OpenRA.Game\Game.cs:line 480
   at OpenRA.Game.Loop() in e:\OpenRA-dev\OpenRA.Game\Game.cs:line 596
   at OpenRA.Game.Run() in e:\OpenRA-dev\OpenRA.Game\Game.cs:line 636
   at OpenRA.Program.Run(String[] args) in e:\OpenRA-dev\OpenRA.Game\Support\Program.cs:line 111
   at OpenRA.Program.Main(String[] args) in e:\OpenRA-dev\OpenRA.Game\Support\Program.cs:line 39
```

**Comment by GraionDilach** [comment]
Proposal to resolve the issue: https://gist.github.com/GraionDilach/cfd895daeb903d95b05f
