### ISSUE TITLE
Actor 'camera (dead)' does not define a property 'Destroy'

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#8571]
Probably another regression from https://github.com/OpenRA/OpenRA/pull/8226.

```
Fatal Lua Error: [string "BindingSupport.lua"]:30: Actor 'camera (dead)' does not define a property 'Destroy'
   at OpenRA.Scripting.ScriptContext.FatalError(System.String message)
   at OpenRA.Mods.Common.Scripting.TriggerGlobal+<OnAllRemovedFromWorld>c__AnonStorey3.<>m__0(OpenRA.Actor m)
   at OpenRA.Mods.Common.Scripting.ScriptTriggers.RemovedFromWorld(OpenRA.Actor self)
   at OpenRA.World.Remove(OpenRA.Actor a)
   at OpenRA.Actor.<Dispose>m__6(OpenRA.World w)
   at OpenRA.World.Dispose()
   at OpenRA.Graphics.WorldRenderer.Dispose()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(System.String[] args)
   at OpenRA.Program.Main(System.String[] args)
```

**Comment by pchote** [comment]
This looks like the normal "trying to do something with an actor after it has been removed" scripting error, unrelated to #8226.

**Comment by abcdefg30** [comment]
Are you sure that you were on latest bleed?

> 00:32 (abcdefg30) pchote: are you sure about https://github.com/OpenRA/OpenRA/issues/8571#issuecomment-116161877 as the stacktrace "talks"
about `at OpenRA.World.Dispose()` etc?
00:34 (+pchote) Antares had a pr that fixed those issues
00:34 (+pchote) So either ^ or matt was testing outdated code

**Comment by Mailaender** [comment]
I was testing pull requests which were probably not rebased onto latest bleed.
