### ISSUE TITLE
Attempting to modify an infantry sprite for RA

### ISSUE THREAD

**Issue by sajwang** [OpenRA/OpenRA#8604]
Hello,

A few days ago I asked about SHP builder.

I actually have a slightly different issue now.

So I am turning a mechanic into a multipurpose unit (i.e. giving him both the medic heal weapon and mechanic repair weapon).

To distinguish him from the mechanic I swapped two colors within the sprite from a brown and red-orange color (229 and 231 in what I believe is the pallete, specifically out of the colors I'm permitted to swap in the SHP builder) to shades of blue (197 and 199).

I get this error from exceptions.log:
"
Red Alert- Globalization Mod at Version mod 1.0
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34014
Exception of type `System.IndexOutOfRangeException`: Index was outside the bounds of the array.
   at OpenRA.FileFormats.Format80.DecodeInto(Byte[] src, Byte[] dest, Int32 srcOffset, Boolean reverse)
   at OpenRA.Mods.Common.SpriteLoaders.ShpTDSprite.Decompress(ImageHeader h)
   at OpenRA.Mods.Common.SpriteLoaders.ShpTDSprite..ctor(Stream stream)
   at OpenRA.Mods.Common.SpriteLoaders.ShpTDLoader.TryParseSprite(Stream s, ISpriteFrame[]& frames)
   at OpenRA.Graphics.SpriteLoader.GetFrames(String filename, ISpriteLoader[] loaders)
   at OpenRA.Graphics.SpriteLoader.GetSprites(String filename, ISpriteLoader[] loaders, SheetBuilder sheetBuilder)
   at OpenRA.Graphics.SpriteCache.<>c__DisplayClass2.<.ctor>b__0(String filename)
   at OpenRA.Primitives.Cache`2.get_Item(T key)
   at OpenRA.Graphics.SpriteCache.get_Item(String filename)
   at OpenRA.Mods.Common.Graphics.DefaultSpriteSequence..ctor(ModData modData, TileSet tileSet, SpriteCache cache, ISpriteSequenceLoader loader, String sequence, String animation, MiniYaml info)
   at OpenRA.Mods.Common.Graphics.TilesetSpecificSpriteSequence..ctor(ModData modData, TileSet tileSet, SpriteCache cache, ISpriteSequenceLoader loader, String sequence, String animation, MiniYaml info)
   at OpenRA.Mods.Common.Graphics.TilesetSpecificSpriteSequenceLoader.CreateSequence(ModData modData, TileSet tileSet, SpriteCache cache, String sequence, String animation, MiniYaml info)
   at OpenRA.Mods.Common.Graphics.DefaultSpriteSequenceLoader.ParseSequences(ModData modData, TileSet tileSet, SpriteCache cache, MiniYamlNode node)
   at OpenRA.Graphics.SequenceCache.<>c__DisplayClass8.<Load>b__5()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at OpenRA.Graphics.SequenceProvider.Preload()
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Game.LoadShellMap()
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
"

I brute forced it later (converted the image to a GIF, processed it in another image program, and copy pasted frames from scratch), same result.

If it helps I tend to use the temperat.pal files for RA.

Thanks again!

**Comment by reaperrr** [comment]
SHP Builder is known to have issues properly saving SHP(TD) files.

**Comment by Unit158** [comment]
check that your editor isn't removing index 0 from the palette on save. GIMP does this and it torments me to no end.

**Comment by sajwang** [comment]
Thanks both, I think it works now. 
You're right, SHP builder does seem to have some problems. However, It seemed to like an alternate color choice closer to the original color (in terms of palette number). Bizarre, really.

I was actually going to use GIMP but after hearing that I may consider photoshop.

**Comment by GraionDilach** [comment]
Still keep XCC Mixer for converting, it's better than OpenRA.Utility for now. And it can extract the palettes from an indexed image too, so that can help as well.

I'm not sure, but saving in PCX in GIMP might not mess up the palette actually, I haven't used GIMP for ages now, though, and my memory faded.
