### ISSUE TITLE
Soviet mission 05

### ISSUE THREAD

**Issue by Townes27** [OpenRA/OpenRA#8613]
Tried out the latest playtest.
There are several issues with this mission.
1. The AI is completely passive and does not even harvest on the main island despite having a harvester.
2. The AI doesn't care whether it's being attacked or not.
3. Either the mission does not want to end or I'm too impatient, but after capturing the enemy buildings, destroying all allied units and having waited for about 20 minutes for the end, I decided it's time to write this bug report.

**Comment by Townes27** [comment]
Replayed it on all difficulty levels.
Same three issues as above and also got this on Normal and Hard:

<pre><code>Fatal Lua Error: [string "BindingSupport.lua"]:30: Uncaught CLR exception at Lua->CLR boundary: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Argument cannot be null.
Parameter name: source
  at System.Linq.Check.Source (System.Object source) [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable.ToList[Actor] (IEnumerable`1 source) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Scripting.TriggerGlobal.OnAllKilled (OpenRA.Actor[] actors, Eluant.LuaFunction func) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at OpenRA.Scripting.ScriptMemberWrapper.Invoke (Eluant.LuaVararg args) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at Eluant.LuaRuntime+MethodWrapper.Invoke (System.Object[] parms) [0x00000] in <filename unknown>:0 
  at Eluant.LuaRuntime.MakeManagedCall (IntPtr state, Eluant.MethodWrapper wrapper) [0x00000] in <filename unknown>:0 
   at OpenRA.Scripting.ScriptContext.FatalError(System.String message)
   at OpenRA.Mods.Common.Scripting.TriggerGlobal+<AfterDelay>c__AnonStorey0.<>m__0()
   at OpenRA.Effects.DelayedAction.<Tick>m__0(OpenRA.World w)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OpenRA.Network.OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(System.String[] args)
   at OpenRA.Program.Main(System.String[] args)
</code></pre>

**Comment by abcdefg30** [comment]
First of all, thanks for the report. ;)
Now to the bugs:
1) See #8446 
2) I think you mean counter attacks? It should repair it's buildings though.
3) Are you sure, that you destroyed all naval units / units on the island?
The crash - I'll work on a fix today.

**Comment by Townes27** [comment]
1) Okay. I suppose a dirty fix would be to place the harvester closer to the ore patch.
2) Yea. It did repair the buildings.
3) Yes, I'm sure. I had the map littered with infantry, subs and yaks. There's no way I could have missed a camo pillbox or any unit. 
I also replayed it twice today, resulting in one finished game and one neverending story in which i quickly destroyed the Allied mcv so it couldn't even build anything on the island.

Perhaps introducing replays for missions would help.

**Comment by penev92** [comment]
The fix for the crash was merged.

**Comment by clemty** [comment]
on discovering the villages you see an area without shroud there (I assume this means there are sympathisers in the village which inform on the allies for you?) - still, the soviet forces will happily kill the civilians and destroy all the buildings - this seems counter-intuitive to me

currently, if I open soviet05b in the internal editor openra crashes for me (soviet05a opens fine) - is that just me?

Red Alert Mod at Version {DEV_VERSION}
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.ArgumentException`: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at OpenRA.Mods.Common.Traits.EditorActorLayer.Add(String id, ActorReference reference, Boolean initialSetup)
   at OpenRA.Mods.Common.Traits.EditorActorLayer.WorldLoaded(World world, WorldRenderer wr)
   at OpenRA.World.LoadComplete(WorldRenderer wr) in d:\Users\clem\Documents\Programming\OpenRA\OpenRA.Game\World.cs:line 222
   at OpenRA.Game.StartGame(String mapUID, WorldType type) in d:\Users\clem\Documents\Programming\OpenRA\OpenRA.Game\Game.cs:line 155
   at OpenRA.Game.LoadEditor(String mapUid) in d:\Users\clem\Documents\Programming\OpenRA\OpenRA.Game\Game.cs:line 369
   at OpenRA.Mods.Common.Widgets.Logic.MainMenuLogic.<>c__DisplayClass53.<LoadMapIntoEditor>b__51()
   at OpenRA.Mods.Common.Widgets.Logic.ConnectionLogic.ConnectionStateChanged(OrderManager om)
   at System.Action`1.Invoke(T obj)
   at OpenRA.Game.LogicTick() in d:\Users\clem\Documents\Programming\OpenRA\OpenRA.Game\Game.cs:line 505
   at OpenRA.Game.Loop() in d:\Users\clem\Documents\Programming\OpenRA\OpenRA.Game\Game.cs:line 632
   at OpenRA.Game.Run() in d:\Users\clem\Documents\Programming\OpenRA\OpenRA.Game\Game.cs:line 672
   at OpenRA.Program.Run(String[] args) in d:\Users\clem\Documents\Programming\OpenRA\OpenRA.Game\Support\Program.cs:line 111
   at OpenRA.Program.Main(String[] args) in d:\Users\clem\Documents\Programming\OpenRA\OpenRA.Game\Support\Program.cs:line 39

**Comment by clemty** [comment]
(sorry, just posted a reply here which belonged to the soviet04 pull request)

**Comment by clemty** [comment]
I just played the mission using current bleed

- AI harvests on the main island, does not seem passive to me
- Mission ends upon destruction of last unit
- AI keeps attacking me

**Comment by penev92** [comment]
The has been a lot of work done on harvesters lately, so that should be fixed. Nobody has been able to reproduce the other two issues as far as I'm aware.
Do we mark this as fixed and close?

**Comment by abcdefg30** [comment]
> Do we mark this as fixed and close?

I think so.
