### ISSUE TITLE
e1 TD crash playtest

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#8852]
```
Tiberian Dawn Mod at Version playtest-20150628
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.18331
Exception of type `System.Exception`: Actor type `e1` does not define a death animation for weapon with damage types ``!
   at OpenRA.Mods.Common.Traits.WithDeathAnimation.Killed(Actor self, AttackInfo e)
   at OpenRA.Traits.Health.InflictDamage(Actor self, Actor attacker, Int32 damage, DamageWarhead warhead, Boolean ignoreModifiers)
   at OpenRA.Traits.HealthExts.InflictDamage(Actor self, Actor attacker, Int32 damage, DamageWarhead warhead)
   at OpenRA.GameRules.DamageWarhead.DoImpact(Actor victim, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.GameRules.DamageWarhead.DoImpact(Target target, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.GameRules.WeaponInfo.<Impact>c__AnonStorey2.<>m__0()
   at OpenRA.GameRules.WeaponInfo.Impact(Target target, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.Mods.Common.Effects.Bullet.Explode(World world)
   at OpenRA.Mods.Common.Effects.Bullet.Tick(World world)
   at OpenRA.World.<Tick>m__4(IEffect e)
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

--------------------------------------------------

Happened when an e1 was shooting at a target and I had medium tanks moving towards the enemies base. Might have been about to crush it and it crashed the game.

**Comment by penev92** [comment]
Crushing in TD works fine for me.
Did you play on a map with custom rules?
Can you provide replay and map?

**Comment by AoAGeneral** [comment]
replay here. Playtest:

https://www.dropbox.com/s/rs7v2u8pljgv2js/OpenRA-2015-07-31T025522Z.orarep?dl=0

map here:

https://www.dropbox.com/s/e86u2lm3yt5rrar/sounds1v1-1.oramap?dl=0

-------

This infact was a custom map. I clearly forgot about that while playing it. I remembered cause we switched map to just normal maps due to voices.

**Comment by penev92** [comment]
Yup, this map needs to be updated.
The custom rules for the weapons seem to be pretty old - the Warheads need to have DamageTypes added.
