### ISSUE TITLE
FrozenActorLayer: Out of sync

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#8863]
Bleed, shroud off, crates off, debug on. Map: http://resource.openra.net/maps/1715/
````
Red Alert Mod at Version {DEV_VERSION}
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Out of sync in frame 829: Blame Tick.
 Compare syncreport.log with other players.
   at OpenRA.Network.OrderManager.OutOfSync(Int32 frame, String blame) in d:\Dev\openra_dev\OpenRA\OpenRA.Game\Network\OrderManager.cs:line 63
   at OpenRA.Network.OrderManager.CheckSync(Byte[] packet) in d:\Dev\openra_dev\OpenRA\OpenRA.Game\Network\OrderManager.cs:line 161
   at OpenRA.Network.OrderManager.<>c__DisplayClass9.<TickImmediate>b__5(Int32 clientId, Byte[] packet) in d:\Dev\openra_dev\OpenRA\OpenRA.Game\Network\OrderManager.cs:line 119
   at OpenRA.Network.ReplayRecorderConnection.<>c__DisplayClass3.<Receive>b__2(Int32 client, Byte[] data) in d:\Dev\openra_dev\OpenRA\OpenRA.Game\Network\ReplayRecorderConnection.cs:line 95
   at OpenRA.Network.EchoConnection.Receive(Action`2 packetFn) in d:\Dev\openra_dev\OpenRA\OpenRA.Game\Network\Connection.cs:line 103
   at OpenRA.Network.ReplayRecorderConnection.Receive(Action`2 packetFn) in d:\Dev\openra_dev\OpenRA\OpenRA.Game\Network\ReplayRecorderConnection.cs:line 82
   at OpenRA.Network.OrderManager.TickImmediate() in d:\Dev\openra_dev\OpenRA\OpenRA.Game\Network\OrderManager.cs:line 112
   at OpenRA.Sync.<>c__DisplayClass5.<CheckSyncUnchanged>b__4() in d:\Dev\openra_dev\OpenRA\OpenRA.Game\Sync.cs:line 168
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn) in d:\Dev\openra_dev\OpenRA\OpenRA.Game\Sync.cs:line 185
   at OpenRA.Sync.CheckSyncUnchanged(World world, Action fn) in d:\Dev\openra_dev\OpenRA\OpenRA.Game\Sync.cs:line 168
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in d:\Dev\openra_dev\OpenRA\OpenRA.Game\Game.cs:line 462
   at OpenRA.Game.LogicTick() in d:\Dev\openra_dev\OpenRA\OpenRA.Game\Game.cs:line 507
   at OpenRA.Game.Loop() in d:\Dev\openra_dev\OpenRA\OpenRA.Game\Game.cs:line 631
   at OpenRA.Game.Run() in d:\Dev\openra_dev\OpenRA\OpenRA.Game\Game.cs:line 671
   at OpenRA.Program.Run(String[] args) in d:\Dev\openra_dev\OpenRA\OpenRA.Game\Support\Program.cs:line 111
   at OpenRA.Program.Main(String[] args) in d:\Dev\openra_dev\OpenRA\OpenRA.Game\Support\Program.cs:line 39

````

**Comment by deniz1a** [comment]
Three player FFA. Player 1 discovers all buildings of other players. They are all frozen under fog. Then player 2 surrenders and game is out of sync.

**Comment by Unit158** [comment]
@deniz1a we need the sync reports. You should know this.

**Comment by deniz1a** [comment]
Sync reports:
player_1: https://gist.github.com/deniz1a/cba22a7de49aef1683f0
player_2: https://gist.github.com/deniz1a/7cbd8097e8d097466ff1
player_3: https://gist.github.com/deniz1a/34dfb354c80681454f19

**Comment by deniz1a** [comment]
I compared the sync reports and player_2 has these entries that are missing in other sync reports:
````
	 4 player player_2 FrozenActorLayer (192)
		 VisibilityHash: 2641
		 FrozenHash: 2705
````
and
````
	 64 t08 Neutral FrozenUnderFog (1)
		 VisibilityHash: 1
````

**Comment by Mailaender** [comment]
Was everyone really playing latest bleed? Try `make version` to be sure.

**Comment by deniz1a** [comment]
It was just me running multiple instances of bleed.

**Comment by Mailaender** [comment]
Disabling shroud. Desynced when one player was defeated https://gist.github.com/Mailaender/7b59965c5857fb665d6a/revisions

**Comment by Phrohdoh** [comment]
On 1eb46d49222793fa3449518ce38b8af2a937aab3:
```
Tiberian Sun Mod at Version git-1eb46d4
Operating System: OSX (Unix 14.4.0.0)
Runtime Version: Mono 4.0.0 ((detached/d136b79 Mon Apr 13 14:40:59 EDT 2015) CLR 4.0.30319.17020
Exception of type `System.InvalidOperationException`: Out of sync in frame 6248: Blame Tick.
 Compare syncreport.log with other players.
  at OpenRA.Network.OrderManager.OutOfSync (Int32 frame, System.String blame) [0x0001e] in /Users/thill/projects/openra/OpenRA.Game//Network/OrderManager.cs:63 
  at OpenRA.Network.OrderManager.CheckSync (System.Byte[] packet) [0x00074] in /Users/thill/projects/openra/OpenRA.Game//Network/OrderManager.cs:161 
  at OpenRA.Network.OrderManager+<TickImmediate>c__AnonStorey0.<>m__0 (Int32 clientId, System.Byte[] packet) [0x00050] in /Users/thill/projects/openra/OpenRA.Game//Network/OrderManager.cs:119 
  at OpenRA.Network.ReplayRecorderConnection+<Receive>c__AnonStorey0.<>m__0 (Int32 client, System.Byte[] data) [0x00094] in /Users/thill/projects/openra/OpenRA.Game//Network/ReplayRecorderConnection.cs:95 
  at OpenRA.Network.EchoConnection.Receive (System.Action`2 packetFn) [0x00055] in /Users/thill/projects/openra/OpenRA.Game//Network/Connection.cs:103 
  at OpenRA.Network.ReplayRecorderConnection.Receive (System.Action`2 packetFn) [0x00027] in /Users/thill/projects/openra/OpenRA.Game//Network/ReplayRecorderConnection.cs:82 
  at OpenRA.Network.OrderManager.TickImmediate () [0x000c0] in /Users/thill/projects/openra/OpenRA.Game//Network/OrderManager.cs:112 
  at OpenRA.Sync+<CheckSyncUnchanged>c__AnonStorey0.<>m__0 () [0x00007] in /Users/thill/projects/openra/OpenRA.Game//Sync.cs:168 
  at OpenRA.Sync.CheckSyncUnchanged[Boolean] (OpenRA.World world, System.Func`1 fn) [0x00044] in /Users/thill/projects/openra/OpenRA.Game//Sync.cs:185 
  at OpenRA.Sync.CheckSyncUnchanged (OpenRA.World world, System.Action fn) [0x0001b] in /Users/thill/projects/openra/OpenRA.Game//Sync.cs:168 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x0011c] in /Users/thill/projects/openra/OpenRA.Game//Game.cs:462 
  at OpenRA.Game.LogicTick () [0x0004e] in /Users/thill/projects/openra/OpenRA.Game//Game.cs:507 
  at OpenRA.Game.Loop () [0x000d4] in /Users/thill/projects/openra/OpenRA.Game//Game.cs:631 
  at OpenRA.Game.Run () [0x00042] in /Users/thill/projects/openra/OpenRA.Game//Game.cs:671 
  at OpenRA.Program.Run (System.String[] args) [0x00011] in /Users/thill/projects/openra/OpenRA.Game//Support/Program.cs:111 
  at OpenRA.Program.Main (System.String[] args) [0x00050] in /Users/thill/projects/openra/OpenRA.Game//Support/Program.cs:39 
```

**Comment by Mailaender** [comment]
Steps to reproduce this quickly:

* start two instances
* select no shroud, debug menu in lobby
* client joins
* host start game
* host type `/all` and `/all`
* host surrenders

Did all my test on Ice Woods as it has a lot of frozen creep buildings.

**Comment by Mailaender** [comment]
`git bisect` reveals https://github.com/OpenRA/OpenRA/commit/fc8a34a7a2684dbe317e6dc25a4b7ccde65812e1 as the first bad commit.

**Comment by Mailaender** [comment]
Identified the problem and filed a fix: https://github.com/OpenRA/OpenRA/pull/8908.
