### ISSUE TITLE
"No suitable renderers were found" on windows

### ISSUE THREAD

**Issue by jano31coa** [OpenRA/OpenRA#9066]
Hello,

I have 2 computers
On both of them, OpenRA won't launch because it doesn't detect opengl 2.0 (like in the issue #7622)

1) do you know how could I fix this ?

2) do you think implementing a OpenGL to DirectX wrapper is doable ?
https://gl2dx.codeplex.com/

A) is ASUS G1S laptop with nvidia 8600M GT
OS is windows vista sp1
installed drivers for graphic card is 307.83 from 01/2013

it is weird because I used to run OpenRA like a year ago, and condiguration has not been change since (don't know the version of openra though since files deleted..)

exception.log :
```
Operating System: Windows (Microsoft Windows NT 6.0.6001 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.235
Exception of type `System.InvalidOperationException`: No suitable renderers were found. Check graphics.log for details.
   à OpenRA.Game.Initialize(Arguments args)
   à OpenRA.Program.Run(String[] args)
   à OpenRA.Program.Main(String[] args)
```

and graphics.log
```
OpenRA requires OpenGL version 2.0 or greater and detected 0.0

OpenGL Information:
Vendor: 
Renderer: 
GL Version: 
Shader Version: 
Available extensions:

System.InvalidProgramException: OpenGL Version Error: See graphics.log for details.
   à OpenRA.Renderer.Sdl2.ErrorHandler.CheckGlVersion()
   à OpenRA.Renderer.Sdl2.Sdl2GraphicsDevice..ctor(Size windowSize, WindowMode windowMode)
   à OpenRA.Renderer.Sdl2.DeviceFactory.Create(Size size, WindowMode windowMode)
   à OpenRA.Graphics.Renderer.CreateDevice(Assembly rendererDll, Int32 width, Int32 height, WindowMode window)
   à OpenRA.Graphics.Renderer..ctor(GraphicSettings graphicSettings, ServerSettings serverSettings)
   à OpenRA.Game.Initialize(Arguments args)
OpenRA requires OpenGL version 2.0 or greater and detected 0.0

OpenGL Information:
Vendor: 
Renderer: 
GL Version: 
Shader Version: 
Available extensions:

System.InvalidProgramException: OpenGL Version Error: See graphics.log for details.
   à OpenRA.Renderer.Sdl2.ErrorHandler.CheckGlVersion()
   à OpenRA.Renderer.Sdl2.Sdl2GraphicsDevice..ctor(Size windowSize, WindowMode windowMode)
   à OpenRA.Renderer.Sdl2.DeviceFactory.Create(Size size, WindowMode windowMode)
   à OpenRA.Graphics.Renderer.CreateDevice(Assembly rendererDll, Int32 width, Int32 height, WindowMode window)
   à OpenRA.Graphics.Renderer..ctor(GraphicSettings graphicSettings, ServerSettings serverSettings)
   à OpenRA.Game.Initialize(Arguments args)
```

I tried OpenGL Extension which shows OpenGL 3.3 and previous are installed
```
v1.1 (100 % - 7/7)
v1.2 (100 % - 8/8)
v1.3 (100 % - 9/9)
v1.4 (100 % - 15/15)
v1.5 (100 % - 3/3)
v2.0 (100 % - 10/10)
v2.1 (100 % - 3/3)
v3.0 (100 % - 23/23)
v3.1 (100 % - 8/8)
v3.2 (100 % - 10/10)
v3.3 (100 % - 10/10)
v4.0 (0 % - 0/14)
v4.1 (57 % - 4/7)
v4.2 (61 % - 8/13)
v4.3 (0 % - 0/23)
v4.4 (0 % - 0/10)
v4.5 (0 % - 0/11)
```

B) is an old DELL desktop with NVIDIA RIVA TNT2
OS is windows xp xp3
installed drivers for graphic card is 66.93 from 10/2004

exceptions.log
```
Operating System: Windows (Microsoft Windows NT 5.1.2600 Service Pack 3)
Runtime Version: .NET CLR 4.0.30319.1
Exception of type `System.InvalidOperationException`: No suitable renderers were found. Check graphics.log for details.
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

graphics.log
```
OpenRA requires OpenGL version 2.0 or greater and detected 1.5

OpenGL Information:
Vendor: NVIDIA Corporation
Renderer: RIVA TNT2/PCI/SSE
GL Version: 1.5.2
Shader Version: 
Available extensions:
GL_ARB_imaging GL_ARB_multitexture GL_ARB_point_parameters GL_ARB_texture_env_add GL_ARB_texture_mirrored_repeat GL_ARB_transpose_matrix GL_ARB_vertex_buffer_object GL_ARB_window_pos GL_EXT_texture_env_add GL_EXT_abgr GL_EXT_bgra GL_EXT_compiled_vertex_array GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_stencil_wrap GL_EXT_texture_edge_clamp GL_EXT_texture_env_combine GL_EXT_texture_lod_bias GL_EXT_texture_object GL_EXT_vertex_array GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_KTX_buffer_region GL_NV_blend_square GL_NV_fog_distance GL_NV_light_max_exponent GL_NV_packed_depth_stencil GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_SGIS_multitexture GL_SUN_slice_accum GL_WIN_swap_hint WGL_EXT_swap_control 
System.InvalidProgramException: OpenGL Version Error: See graphics.log for details.
   at OpenRA.Renderer.Sdl2.ErrorHandler.CheckGlVersion()
   at OpenRA.Renderer.Sdl2.Sdl2GraphicsDevice..ctor(Size windowSize, WindowMode windowMode)
   at OpenRA.Renderer.Sdl2.DeviceFactory.Create(Size size, WindowMode windowMode)
   at OpenRA.Graphics.Renderer.CreateDevice(Assembly rendererDll, Int32 width, Int32 height, WindowMode window)
   at OpenRA.Graphics.Renderer..ctor(GraphicSettings graphicSettings, ServerSettings serverSettings)
   at OpenRA.Game.Initialize(Arguments args)
OpenRA requires OpenGL version 2.0 or greater and detected 1.5

OpenGL Information:
Vendor: NVIDIA Corporation
Renderer: RIVA TNT2/PCI/SSE
GL Version: 1.5.2
Shader Version: 
Available extensions:
GL_ARB_imaging GL_ARB_multitexture GL_ARB_point_parameters GL_ARB_texture_env_add GL_ARB_texture_mirrored_repeat GL_ARB_transpose_matrix GL_ARB_vertex_buffer_object GL_ARB_window_pos GL_EXT_texture_env_add GL_EXT_abgr GL_EXT_bgra GL_EXT_compiled_vertex_array GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_stencil_wrap GL_EXT_texture_edge_clamp GL_EXT_texture_env_combine GL_EXT_texture_lod_bias GL_EXT_texture_object GL_EXT_vertex_array GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_KTX_buffer_region GL_NV_blend_square GL_NV_fog_distance GL_NV_light_max_exponent GL_NV_packed_depth_stencil GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_SGIS_multitexture GL_SUN_slice_accum GL_WIN_swap_hint WGL_EXT_swap_control 
System.InvalidProgramException: OpenGL Version Error: See graphics.log for details.
   at OpenRA.Renderer.Sdl2.ErrorHandler.CheckGlVersion()
   at OpenRA.Renderer.Sdl2.Sdl2GraphicsDevice..ctor(Size windowSize, WindowMode windowMode)
   at OpenRA.Renderer.Sdl2.DeviceFactory.Create(Size size, WindowMode windowMode)
   at OpenRA.Graphics.Renderer.CreateDevice(Assembly rendererDll, Int32 width, Int32 height, WindowMode window)
   at OpenRA.Graphics.Renderer..ctor(GraphicSettings graphicSettings, ServerSettings serverSettings)
   at OpenRA.Game.Initialize(Arguments args)
```

Regards,

John

**Comment by jano31coa** [comment]
Regards,

John

**Comment by reaperrr** [comment]
First of all, thanks for the detailed information :)

System B)'s graphics card is simply too old and below OpenRA's minimum OpenGL requirement.

About system A), try the solution presented on the 2nd page of this thread and report back if it helped:
https://forums.geforce.com/default/topic/417427/geforce-drivers/geforce-8600gt-opengl-doesn-39-t-work-help-me-33-33-33-33-33-/2/

**Comment by Mailaender** [comment]
> 2) Do you think implementing a OpenGL to DirectX wrapper is doable?

https://github.com/OpenRA/OpenRA/pull/8632 allows you to write a DirectX renderer with @SharpDX and plug that in directly without a wrapper.

**Comment by Mailaender** [comment]
Closing as inactive and being multiple issues per issue and one of it being probably a duplicate of https://github.com/OpenRA/OpenRA/issues/7622.
