### ISSUE TITLE
Crash when switching mods for second time 

### ISSUE THREAD

**Issue by SinineSiil** [OpenRA/OpenRA#9271]
This happens in bleed build

Full exception:
```
 Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.InvalidOperationException`: Can't create OpenAL context
   at OpenRA.Platforms.Default.OpenAlSoundEngine..ctor() in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Platforms.Default\OpenAlSoundEngine.cs:line 102
   at OpenRA.Platforms.Default.DeviceFactory.CreateSound() in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Platforms.Default\DefaultPlatform.cs:line 29
   at OpenRA.Sound.CreateDevice(Assembly platformDll) in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Game\Sound\Sound.cs:line 37
   at OpenRA.Sound.Initialize(String engineName) in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Game\Sound\Sound.cs:line 72
   at OpenRA.Game.InitializeMod(String mod, Arguments args) in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Game\Game.cs:line 278
   at OpenRA.Mods.Common.Widgets.Logic.ModBrowserLogic.<>c__DisplayClass23.<LoadMod>b__22()
   at System.Action.Invoke()
   at OpenRA.Primitives.ActionQueue.PerformActions() in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Game\Primitives\ActionQueue.cs:line 43
   at OpenRA.Game.LogicTick() in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Game\Game.cs:line 487
   at OpenRA.Game.Loop() in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Game\Game.cs:line 619
   at OpenRA.Game.Run() in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Game\Game.cs:line 659
   at OpenRA.Program.Run(String[] args) in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 117
   at OpenRA.Program.Main(String[] args) in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 39
```

**Comment by pchote** [comment]
This doesn't happen on the playtest / prep branch, so it will be a regression from #8632.
I suspect that we are now trying to create a new OpenAL context each time we switch mods, orphaning the old one.

**Comment by LipkeGu** [comment]
is switched on rebased bleed many times between the mods (ts d2k, ra, td) and loading them no crashes...

can you give a reproduce instruction?

**Comment by SinineSiil** [comment]
@LipkeGu I didn't do anything special, so no idea. Pchote thinks it's related to audio drivers.
I also tried this on my old desktop and didn't get crash there.

**Comment by pchote** [comment]
```
18:05 < gwass> pchote: I kinda figured out how to prevent those crashes.
18:05 < gwass> pchote:  I disabled all sound effects in audio output properties and 
               after doing that I didn't get any crashes
```
This agrees with my suspicion above.
