### ISSUE TITLE
System.IO.EndOfStreamException at OpenRA.FileSystem.MixFile

### ISSUE THREAD

**Issue by Gormomma** [OpenRA/OpenRA#9624]
Tiberian Dawn Mod at Version release-20150919
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.EndOfStreamException`: Attempted to read past the end of the stream.
   at OpenRA.StreamExts.ReadBytes(Stream s, Byte[] buffer, Int32 offset, Int32 count)
   at OpenRA.StreamExts.ReadBytes(Stream s, Int32 count)
   at OpenRA.StreamExts.ReadUInt16(Stream s)
   at OpenRA.FileSystem.MixFile..ctor(String filename, PackageHashType type, Int32 priority)
   at OpenRA.FileSystem.GlobalFileSystem.OpenPackage(String filename, String annotation, Int32 order)
   at OpenRA.FileSystem.GlobalFileSystem.<Mount>c__AnonStorey0.<>m__0()
   at OpenRA.FileSystem.GlobalFileSystem.Mount(String name, String annotation)
   at OpenRA.FileSystem.GlobalFileSystem.LoadFromManifest(Manifest manifest)
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Game.LoadShellMap()
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by penev92** [comment]
Sounds like you have a corrupted MIX file (asset package file).
I suggest deleting your \Documents\OpenRA\Content\cnc\ folder and reinstalling the mod (either from an original CD, a TFD DVD, or by simply selecting Download in the install dialog).

**Comment by pchote** [comment]
We should wrap the asset loading with a try/catch and return to the mod chooser (with a dialog box explaining ^) if it fails.

The above stacktrace can also happen as part of the (now fixed) mix-file loading bug.

**Comment by pchote** [comment]
I suspect that this was fixed by the mix decryption rewrite that was shipped in release-20151224.  We haven't seen any new reports of this since then, so closing.
