### ISSUE TITLE
desert-shellmap (order/map) in game directory make the Game Crash

### ISSUE THREAD

**Issue by alex8811** [OpenRA/OpenRA#9790]
Debug.log5 (28.10.2015)

Found 35 domains on map Desert Shellmap.
Found 3 domains on map Desert Shellmap.
--Tick: 1 (net)
--Tick: 2 (local)
--Tick: 3 (local)
--Tick: 4 (net)
--Tick: 5 (local)
--Tick: 6 (local)
--Tick: 7 (net)
--Tick: 8 (local)
--Tick: 9 (local)
--Tick: 10 (net)
--Tick: 11 (local)
--Tick: 12 (local)
--Tick: 13 (net)
--Tick: 14 (local)
--Tick: 15 (local)
--Tick: 16 (net)
--Tick: 17 (local)
--Tick: 18 (local)
--Tick: 19 (net)
--Tick: 20 (local)
--Tick: 21 (local)
--Tick: 22 (net)
--Tick: 23 (local)
--Tick: 24 (local)
--Tick: 25 (net)

By deleting the map (i think its the map by beginning) the game dont start.

i let it in the derectionary but its crashd some games sessions again....

c2d 4T
4400HD intel
Acer e1572g

please help....

in past:

Debug log4 23.10.2015

Found 35 domains on map Desert Shellmap.
Found 3 domains on map Desert Shellmap.
--Tick: 1 (net)
--Tick: 2 (local)
--Tick: 3 (local)
--Tick: 4 (net)
--Tick: 5 (local)
--Tick: 6 (local)
--Tick: 7 (net)
--Tick: 8 (local)
--Tick: 9 (local)
--Tick: 10 (net)
--Tick: 11 (local)
--Tick: 12 (local)
--Tick: 13 (net)
--Tick: 14 (local)
--Tick: 15 (local)
--Tick: 16 (net)
--Tick: 17 (local)
--Tick: 18 (local)
--Tick: 19 (net)
--Tick: 20 (local)
--Tick: 21 (local)
--Tick: 22 (net)
--Tick: 23 (local)
--Tick: 24 (local)
--Tick: 25 (net)
--Tick: 26 (local)
--Tick: 27 (local)
--Tick: 28 (net)
--Tick: 29 (local)
--Tick: 30 (local)
MapCache.LoadAsyncInternal started

Debug log 3 23.10.2015
Found 35 domains on map Desert Shellmap.
Found 3 domains on map Desert Shellmap.
--Tick: 1 (net)
--Tick: 2 (local)
--Tick: 3 (local)
--Tick: 4 (net)
--Tick: 5 (local)
--Tick: 6 (local)
--Tick: 7 (net)
--Tick: 8 (local)
--Tick: 9 (local)
--Tick: 10 (net)
--Tick: 11 (local)
--Tick: 12 (local)
--Tick: 13 (net)
--Tick: 14 (local)
--Tick: 15 (local)
--Tick: 16 (net)
--Tick: 17 (local)
--Tick: 18 (local)
--Tick: 19 (net)
--Tick: 20 (local)
--Tick: 21 (local)
--Tick: 22 (net)
--Tick: 23 (local)
--Tick: 24 (local)
--Tick: 25 (net)
--Tick: 26 (local)
--Tick: 27 (local)
--Tick: 28 (net)
--Tick: 29 (local)
--Tick: 30 (local)
--Tick: 31 (net)
--Tick: 32 (local)
--Tick: 33 (local)
--Tick: 34 (net)
--Tick: 35 (local)
--Tick: 36 (local)
--Tick: 37 (net)
--Tick: 38 (local)
--Tick: 39 (local)
--Tick: 40 (net)
--Tick: 41 (local)
--Tick: 42 (local)
--Tick: 43 (net)
--Tick: 44 (local)
--Tick: 45 (local)
--Tick: 46 (net)
--Tick: 47 (local)
MapCache.LoadAsyncInternal s...

**Comment by penev92** [comment]
Show us the exception.log please.
Also yes, removing the shellmap will crash the game.

**Comment by alex8811** [comment]
exception.log (last) = debug 5, other a bit diffrent, the other u can see next under this...

Red Alert Mod at Version release-20150919
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.IO.EndOfStreamException`: Attempted to read past the end of the stream.
   at OpenRA.StreamExts.ReadBytes(Stream s, Byte[] buffer, Int32 offset, Int32 count)
   at OpenRA.StreamExts.ReadBytes(Stream s, Int32 count)
   at OpenRA.StreamExts.ReadUInt32(Stream s)
   at OpenRA.FileSystem.MixFile.ReadBlocks(Stream s, Int64 offset, Int32 count)
   at OpenRA.FileSystem.MixFile.DecryptHeader(Stream s, Int64 offset, Int64& headerEnd)
   at OpenRA.FileSystem.MixFile..ctor(String filename, PackageHashType type, Int32 priority)
   at OpenRA.FileSystem.GlobalFileSystem.OpenPackage(String filename, String annotation, Int32 order)
   at OpenRA.FileSystem.GlobalFileSystem.<Mount>c__AnonStorey0.<>m__0()
   at OpenRA.FileSystem.GlobalFileSystem.Mount(String name, String annotation)
   at OpenRA.FileSystem.GlobalFileSystem.LoadFromManifest(Manifest manifest)
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Game.LoadShellMap()
   at OpenRA.Mods.Common.Widgets.Logic.IngameMenuLogic.<IngameMenuLogic>c__AnonStorey0.<>m__16()
   at System.Action.Invoke()
   at OpenRA.Primitives.ActionQueue.PerformActions()
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
____________________________________
exception.log 4

Red Alert Mod at Version release-20150919
on map e359ad3b103dee63159278940e37624501fd5959 (Vegetation by hamb/Chris Forbes).
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.InvalidOperationException`: Out of sync in frame 8680.
 Compare syncreport.log with other players.
   at OpenRA.Network.OrderManager.OutOfSync(Int32 frame)
   at OpenRA.Network.OrderManager.CheckSync(Byte[] packet)
   at OpenRA.Network.OrderManager.<TickImmediate>c__AnonStorey0.<>m__0(Int32 clientId, Byte[] packet)
   at OpenRA.Network.ReplayRecorderConnection.<Receive>c__AnonStorey0.<>m__0(Int32 client, Byte[] data)
   at OpenRA.Network.EchoConnection.Receive(Action`2 packetFn)
   at OpenRA.Network.ReplayRecorderConnection.Receive(Action`2 packetFn)
   at OpenRA.Network.OrderManager.TickImmediate()
   at OpenRA.Sync.<CheckSyncUnchanged>c__AnonStorey0.<>m__0()
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   at OpenRA.Sync.CheckSyncUnchanged(World world, Action fn)
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
_______________________________________
Exception.log 3

Red Alert Mod at Version release-20150919
on map e359ad3b103dee63159278940e37624501fd5959 (Vegetation by hamb/Chris Forbes).
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.InvalidOperationException`: Out of sync in frame 333.
 Compare syncreport.log with other players.
   at OpenRA.Network.OrderManager.OutOfSync(Int32 frame)
   at OpenRA.Network.OrderManager.CheckSync(Byte[] packet)
   at OpenRA.Network.OrderManager.<TickImmediate>c__AnonStorey0.<>m__0(Int32 clientId, Byte[] packet)
   at OpenRA.Network.ReplayRecorderConnection.<Receive>c__AnonStorey0.<>m__0(Int32 client, Byte[] data)
   at OpenRA.Network.EchoConnection.Receive(Action`2 packetFn)
   at OpenRA.Network.ReplayRecorderConnection.Receive(Action`2 packetFn)
   at OpenRA.Network.OrderManager.TickImmediate()
   at OpenRA.Sync.<CheckSyncUnchanged>c__AnonStorey0.<>m__0()
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   at OpenRA.Sync.CheckSyncUnchanged(World world, Action fn)
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
_______________________________________________
exception.log 2

Red Alert Mod at Version release-20150919
on map 72479719c32a75bab31cde71d9096ad16e59515b (God's Great Divide Fixed by Vigor, God, Stex).
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.InvalidOperationException`: Out of sync in frame 16368.
 Compare syncreport.log with other players.
   at OpenRA.Network.OrderManager.OutOfSync(Int32 frame)
   at OpenRA.Network.OrderManager.CheckSync(Byte[] packet)
   at OpenRA.Network.OrderManager.<TickImmediate>c__AnonStorey0.<>m__0(Int32 clientId, Byte[] packet)
   at OpenRA.Network.ReplayRecorderConnection.<Receive>c__AnonStorey0.<>m__0(Int32 client, Byte[] data)
   at OpenRA.Network.EchoConnection.Receive(Action`2 packetFn)
   at OpenRA.Network.ReplayRecorderConnection.Receive(Action`2 packetFn)
   at OpenRA.Network.OrderManager.TickImmediate()
   at OpenRA.Sync.<CheckSyncUnchanged>c__AnonStorey0.<>m__0()
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   at OpenRA.Sync.CheckSyncUnchanged(World world, Action fn)
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by GraionDilach** [comment]
2 3 and 4 are online desyncs where all player's syncreports are needed to debug the issue. 5 is #2441 which got fixed since the release.
